import type { VaultConfig } from '../types/vault'

export const DEFAULT_VAULT_CONFIG: VaultConfig = {
  daily_note: {
    directory: 'daily',
    filename_format: '{iso}',
    title_format: '{iso}',
    template_path: null,
  },
  templates_directory: '.scriptor/templates',
  inbox: { enabled: true, period: 'all', new_note_directory: null },
  workflow: { auto_advance_inbox_after_organize: false },
  note_types: { directory: 'type' },
  export: {
    bibliography_path: 'references.bib',
    csl_style_path: 'apa-lite.csl',
    export_on_save: { enabled: false, profile_id: null },
  },
  writing_targets: { daily_words: 500, history_path: '.scriptor/stats-history.json' },
  graph_groups: [],
  extra_roots: [],
  latex: {
    enabled: false,
    tectonic_path: null,
    output_directory: '.scriptor/latex-out',
    extra_flags: [],
    compile_on_save: false,
  },
  calendar_sync: {
    enabled: false,
    google_client_id: null,
    google_calendar_id: null,
    google_task_list_id: null,
    lookahead_days: 14,
    show_events_in_tasks: true,
    push_vault_tasks: false,
    capture_note_path: 'inbox/inbox.md',
  },
  autosuggest: {
    enabled: true,
    min_chars: 2,
    max_results: 8,
    cross_document: true,
    wikilinks: true,
    tags: true,
    headings: true,
    debounce_ms: 120,
  },
  reading_list: {
    enabled: false,
    status_key: 'reading-status',
  },
  accessibility: {
    reduced_motion: false,
    high_contrast: false,
    font_scale: 1.0,
    live_regions: true,
    focus_outline: 'default',
  },
  features: {
    latex: false,
    calendar: false,
    reading_list: false,
    relationship_matrix: false,
    automation_recorder: false,
    link_decay: true,
    footnote_manager: true,
  },
}
