[package]
name = "scriptor-cli"
version = "1.0.1"
edition = "2024"
license.workspace = true

[[bin]]
name = "scriptor"
path = "src/main.rs"

[dependencies]
scriptor-daemon = { path = "../daemon" }
scriptor-ipc = { path = "../ipc" }
scriptor-system-bridge = { path = "../system-bridge" }
scriptor-export-runner = { path = "../export-runner" }
scriptor-canvas-engine = { path = "../canvas-engine" }
scriptor-indexer = { path = "../indexer" }
scriptor-native-git = { path = "../native-git" }
scriptor-publish-runner = { path = "../publish-runner" }
scriptor-vault = { path = "../vault" }
scriptor-capture = { path = "../capture" }
chrono = { workspace = true }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
crossterm = "0.29"
ratatui = "0.30.2"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unicode-segmentation = "1"
unicode-width = "0.2"
pulldown-cmark = "0.13"
