import { useEffect, useRef, useState } from 'react'
import { zoteroImportPreview } from '../../bridge/commands/research_capture'
import { referencesToBibtex } from '../../lib/referenceDesk'
import type { ZoteroReference } from '../../lib/referenceDesk'
interface Props {onSave:(path:string,content:string)=>Promise<void>;onClose:()=>void}
/** Every page fetch is a user action and requires a native Zotero read grant. */
export function ReferenceImportReview({onSave,onClose}:Props){
  const [apiKey,setApiKey]=useState('');const [items,setItems]=useState<ZoteroReference[]>([]);const [selected,setSelected]=useState<Set<string>>(new Set());const [next,setNext]=useState<number|null>(null);const [path,setPath]=useState('zotero-import.bib');const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [status,setStatus]=useState('Fetch a preview, select references, then save a new .bib file. Existing files are preserved.')
  const generation=useRef(0)
  const pending=useRef(false)
  useEffect(()=>()=>{generation.current+=1},[])
  const changeKey=(value:string)=>{generation.current+=1;setApiKey(value);setItems([]);setSelected(new Set());setNext(null);setError(null);setStatus('Account key changed. Fetch a new preview before importing.')}
  const fetchPage=async(start:number)=>{if(pending.current)return;pending.current=true;const request=++generation.current;setBusy(true);setError(null)
    try {const page=await zoteroImportPreview(apiKey.trim(),start);if(request!==generation.current)return;const nextItems=start===0?page.items:[...items,...page.items.filter(item=>!items.some(old=>old.key===item.key))];if(nextItems.length>1000)throw new Error('Preview is limited to 1000 references. Save this selection before another import.');setItems(nextItems);setSelected(new Set(start===0?page.items.map(item=>item.key):[...selected,...page.items.map(item=>item.key)]));setNext(nextItems.length>=1000?null:page.nextStart);setStatus(`Previewing ${nextItems.length} references. Select entries to import.`)}catch(failure){if(request===generation.current)setError(String(failure))}finally{pending.current=false;if(request===generation.current)setBusy(false)}}
  const save=async()=>{if(pending.current)return;pending.current=true;const request=generation.current;setBusy(true);setError(null);try {await onSave(path,referencesToBibtex(items.filter(item=>selected.has(item.key))));if(request===generation.current){setApiKey('');onClose()}}catch(failure){if(request===generation.current)setError(String(failure))}finally{pending.current=false;if(request===generation.current)setBusy(false)}}
return <section className="reference-import-review" aria-label="Review Zotero import"><form onSubmit={event=>{event.preventDefault();void fetchPage(0)}}><label>Zotero read API key<input type="password" autoComplete="off" value={apiKey} maxLength={128} disabled={busy} required onChange={event=>changeKey(event.target.value)}/></label><button type="submit" disabled={busy||!apiKey.trim()}>Fetch preview</button></form><p role="status">{status}</p>{error?<p role="alert">{error}</p>:null}{items.length?<><label>New vault bibliography path<input value={path} disabled={busy} onChange={event=>setPath(event.target.value)} placeholder="Research/zotero-import.bib"/></label><ul>{items.map(item=><li key={item.key}><label><input type="checkbox" checked={selected.has(item.key)} disabled={busy} onChange={event=>setSelected(current=>{const result=new Set(current);if(event.target.checked)result.add(item.key);else result.delete(item.key);return result})}/><span><strong>{item.title||item.key}</strong> · {item.author} {item.year}</span></label>{item.abstract?<details><summary>Abstract</summary><p>{item.abstract}</p></details>:null}</li>)}</ul>{next!==null?<button type="button" disabled={busy} onClick={()=>void fetchPage(next)}>Fetch next page</button>:null}<details><summary>BibTeX preview ({selected.size} selected)</summary><pre>{selected.size?referencesToBibtex(items.filter(item=>selected.has(item.key))):'Select references to preview.'}</pre></details><button type="button" disabled={busy||!selected.size||!path.trim()} onClick={()=>void save()}>Save selected references as a new bibliography</button></>:null}<button type="button" onClick={()=>{generation.current+=1;setApiKey('');onClose()}}>Cancel import</button></section>
}
