import { test, expect } from '@playwright/test'
import { launchApp, openCommandPalette, runCommand } from './helpers'

test('asset images and audio preview locally, revoke URLs and bind vault identity', async ({ page }) => {
  await page.addInitScript(() => {
    sessionStorage.setItem('e2e:asset-media', '1')
    const revoke = URL.revokeObjectURL.bind(URL)
    URL.revokeObjectURL = url => { sessionStorage.setItem('e2e:revoked-media', url); revoke(url) }
  })
  await launchApp(page)
  await openCommandPalette(page)
  await runCommand(page, 'Asset deck')
  const deck = page.getByRole('dialog', { name: 'Asset deck', exact: true })
  const asset = (path: string) => deck.locator('.research-asset-list > li').filter({ hasText: path })
  await asset('assets/pixel.png').getByRole('button', { name: 'Open source', exact: true }).click()
  const image = deck.getByRole('img', { name: 'Vault source: assets/pixel.png', exact: true })
  await expect(image).toBeVisible()
  await expect.poll(() => image.evaluate(node => (node as HTMLImageElement).naturalWidth)).toBe(1)
  const firstUrl = await image.getAttribute('src')
  expect(firstUrl).toMatch(/^blob:/)
  await asset('assets/tone.wav').getByRole('button', { name: 'Open source', exact: true }).click()
  const audio = deck.locator('audio')
  await expect(audio).toHaveAttribute('controls', '')
  await expect.poll(() => audio.evaluate(node => (node as HTMLAudioElement).readyState)).toBeGreaterThan(0)
  expect(await audio.evaluate(node => (node as HTMLAudioElement).paused)).toBe(true)
  expect(await page.evaluate(() => sessionStorage.getItem('e2e:revoked-media'))).toBe(firstUrl)
  await expect(asset('assets/active.svg').getByRole('button', { name: 'Open source', exact: true })).toBeDisabled()
  await asset('assets/invalid.png').getByRole('button', { name: 'Open source', exact: true }).click()
  await expect(deck.getByRole('alert')).toContainText('do not match')
  await expect(deck.getByRole('button', { name: 'Retry preview', exact: true })).toBeVisible()
  const calls = await page.evaluate(() => JSON.parse(sessionStorage.getItem('e2e:media-calls') ?? '[]') as Array<{ expectedVaultId: string }>)
  expect(calls).toHaveLength(3)
  expect(calls.every(call => call.expectedVaultId === 'screenshot-vault')).toBe(true)
  await page.setViewportSize({ width: 320, height: 740 })
  await expect.poll(() => deck.evaluate(node => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(1)
})
