import { test, expect } from '@playwright/test'
import { launchApp, openCommandPalette, runCommand } from './helpers'
test('capture stop waiting keeps submitted work visibly pending and discards late extraction', async ({ page }) => {
  await page.clock.install()
  await page.addInitScript(() => { sessionStorage.setItem('e2e:research', '1'); sessionStorage.setItem('e2e:capture-delay', '1') })
  await launchApp(page); await openCommandPalette(page); await runCommand(page, 'Capture reviewer')
  const panel = page.getByRole('dialog', { name: 'Capture reviewer', exact: true })
  await panel.getByLabel('Article URL', { exact: true }).fill('https://example.org/article')
  await panel.getByRole('button', { name: 'Extract preview', exact: true }).click()
  await panel.getByRole('button', { name: 'Stop waiting', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'Extract preview', exact: true })).toBeDisabled()
  await expect(panel.getByRole('button', { name: 'Stop waiting', exact: true })).toBeDisabled()
  await page.clock.fastForward(5100)
  await expect(panel.getByRole('button', { name: 'Extract preview', exact: true })).toBeEnabled()
  await expect(panel.getByRole('textbox', { name: 'Reviewed Markdown', exact: true })).toHaveCount(0)
  const calls = await page.evaluate(() => JSON.parse(sessionStorage.getItem('e2e:research-calls') ?? '[]') as Array<{cmd: string}>)
  expect(calls.filter(call => call.cmd === 'capture_extract_preview')).toHaveLength(1)
  expect(calls.filter(call => call.cmd === 'vault_save_asset')).toHaveLength(0)
})

test('capture original source remains accessible and keyboard focus cycles inside the dialog', async ({ page }) => {
  await page.addInitScript(() => sessionStorage.setItem('e2e:research', '1'))
  await launchApp(page); await openCommandPalette(page); await runCommand(page, 'Capture reviewer')
  const panel = page.getByRole('dialog', { name: 'Capture reviewer', exact: true })
  await panel.getByLabel('Article URL', { exact: true }).fill('https://example.org/article')
  await panel.getByRole('button', { name: 'Extract preview', exact: true }).click()
  const frame = panel.locator('iframe[title="Original source snapshot"]')
  await expect(frame).toBeVisible()
  await expect(frame).not.toHaveAttribute('inert', '')
  await panel.getByRole('button', { name: 'Save reviewed capture as a new note', exact: true }).focus()
  await page.keyboard.press('Tab')
  const focus = () => page.evaluate(() => ({ contained: !!document.activeElement?.closest('[role="dialog"][aria-label="Capture reviewer"]'), active: document.activeElement?.outerHTML.slice(0, 350), guards: [...document.querySelectorAll('[data-focus-guard]')].map(el => ({ parent: el.parentElement?.getAttribute('aria-label'), first: el.parentElement?.firstChild === el, last: el.parentElement?.lastChild === el })) }))
  await expect.poll(focus).toMatchObject({ contained: true })
  await frame.focus()
  await page.keyboard.press('Tab')
  await expect.poll(focus).toMatchObject({ contained: true })
  await page.keyboard.press('Shift+Tab')
  await expect.poll(focus).toMatchObject({ contained: true })
})
