import { expect, test } from '@playwright/test'
import { launchApp, openCommandPalette, runCommand } from './helpers'

test('Graphviz renders DOT locally and preserves invalid source with a visible failure', async ({ page }) => {
  await page.route(/graphviz\.worker.*\.js$/, async route => {
    const response = await route.fetch()
    await route.fulfill({ response, headers: { ...response.headers(), 'content-security-policy': "default-src 'none'; script-src 'self' 'wasm-unsafe-eval'; connect-src 'none'" } })
  })
  await launchApp(page)
  await openCommandPalette(page)
  await runCommand(page, 'Diagram studio')
  const panel = page.getByRole('region', { name: 'Diagram studio', exact: true })
  await panel.getByLabel('Language', { exact: true }).selectOption('dot')
  await panel.getByLabel('Diagram source', { exact: true }).fill('digraph { Evidence -> Draft -> Review }')
  await panel.getByRole('button', { name: 'Render diagram', exact: true }).click()
  const image = panel.getByRole('img', { name: 'Graphviz diagram', exact: true })
  await expect(image).toBeVisible()
  await expect.poll(() => image.evaluate((element: HTMLImageElement) => element.complete && element.naturalWidth > 0)).toBe(true)
  const svg = await image.getAttribute('src')
  expect(decodeURIComponent(svg ?? '')).toContain('Evidence')
  await panel.getByLabel('Diagram source', { exact: true }).fill('digraph { broken -> }')
  await panel.getByRole('button', { name: 'Render diagram', exact: true }).click()
  await expect(panel.getByText(/Graphviz:.*syntax error/)).toBeVisible()
  await expect(panel.getByRole('region', { name: 'Diagram viewport' })).toContainText('digraph { broken -> }')
})

test('diagram preview refreshes deliberately and supports bounded zoom and keyboard pan', async ({ page }) => {
  await launchApp(page)
  await openCommandPalette(page)
  await runCommand(page, 'Diagram studio')
  const panel = page.getByRole('region', { name: 'Diagram studio', exact: true })
  await panel.getByLabel('Diagram source', { exact: true }).fill('flowchart LR\n A[Unique diagram node] --> B[End]')
  await expect(panel.getByText('Source changed. Render to refresh the preview.')).toBeVisible()
  await panel.getByLabel('Refresh local preview as I type').check()
  await expect(panel.getByText('Source changed. Render to refresh the preview.')).toHaveCount(0)
  const viewport = panel.getByRole('region', { name: 'Diagram viewport', exact: true })
  await expect(viewport.locator('svg')).toBeVisible()
  await expect(viewport).toContainText('Unique diagram node')
  for (let index = 0; index < 8; index++) await panel.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'Zoom in', exact: true })).toBeDisabled()
  await viewport.focus()
  await page.keyboard.press('Shift+ArrowRight')
  expect(await viewport.evaluate(element => element.scrollLeft)).toBeGreaterThan(0)
  await panel.getByRole('button', { name: '300% · Reset', exact: true }).click()
  await expect(panel.getByRole('button', { name: '100% · Reset', exact: true })).toBeVisible()
  expect(await viewport.evaluate(element => element.scrollLeft)).toBe(0)
})
