import { expect, test, type Page } from '@playwright/test'
import { launchApp, openCommandPalette, runCommand, settleLayout, waitForWorkspace } from './helpers'
import { attachVisualState } from './visual-state-evidence'

type Call = { cmd: string; payload: Record<string, unknown> }
async function calls(page: Page) {
  return page.evaluate(() => JSON.parse(sessionStorage.getItem('e2e:google-ecosystem-calls') ?? '[]') as Call[])
}
async function launchGoogle(page: Page, researchFixture = true) {
  await page.addInitScript(research => {
    sessionStorage.setItem('e2e:google-ecosystem', '1')
    sessionStorage.setItem('e2e:research', research ? '1' : '0')
  }, researchFixture)
  await launchApp(page)
  await waitForWorkspace(page, { allowHiddenVaultList: true })
}
async function openDrive(page: Page) {
  await openCommandPalette(page)
  await runCommand(page, 'Drive collaboration')
  const panel = page.getByRole('region', { name: 'Drive collaboration', exact: true })
  await expect(panel).toBeVisible()
  await expect(panel.getByLabel('Shared folder ID', { exact: true })).toHaveValue('shared-folder')
  return panel
}
async function openGoogleSettings(page: Page) {
  await page.locator('header.topbar').getByRole('button', { name: 'Settings', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Settings' })
  await settings.getByRole('tab', { name: 'Integrations', exact: true }).click()
  return { settings, google: settings.locator('.google-integration-settings') }
}

test('Persian Drive resource setup uses real RTL localization at restored 200 percent zoom', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 768, height: 960 })
  await page.addInitScript(() => {
    localStorage.setItem('scriptor:locale', 'fa')
    localStorage.setItem('scriptor:ui-zoom', '2')
    localStorage.setItem('scriptor:workspace-shortcuts:v1', JSON.stringify({ version: 1, visible: true, items: [
      { id: 'open-drive-collaboration', shown: true, pinned: true, label: '', width: 0, fontSize: 12 },
    ] }))
  })
  await launchGoogle(page)
  await expect(page.locator('html')).toHaveAttribute('lang', 'fa')
  await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
  await expect.poll(() => page.evaluate(() => Number(document.body.style.zoom))).toBe(2)
  await page.locator('.workspace-activity-bar').getByRole('button', { name: 'همکاری در درایو', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Drive collaboration', exact: true })
  await expect(panel).toContainText('drive@example.com')
  await panel.getByRole('button', { name: 'مرور پوشه‌های در دسترس', exact: true }).click()
  await expect(panel.getByRole('combobox', { name: 'انتخاب پوشه درایو', exact: true }).locator('option')).toHaveCount(2)
  const controls = panel.locator('.collaboration-resources').first()
  await controls.getByLabel('نام پوشه جدید', { exact: true }).fill('پژوهش مشترک')
  await expect(controls.getByRole('button', { name: 'ایجاد پوشه درایو', exact: true })).toBeEnabled()
  await expect.poll(() => controls.evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
  await attachVisualState(page, testInfo, 'drive-persian-rtl-restored-zoom', controls, controls.getByRole('button', { name: 'ایجاد پوشه درایو', exact: true }))
  expect((await calls(page)).filter(call => call.cmd === 'collaboration_write')).toHaveLength(0)
})

test('Drive discovers and deduplicates folders, authorizes creation, and persists its transport after reopening', async ({ page }, testInfo) => {
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByRole('button', { name: 'Browse accessible folders', exact: true }).click()
  await panel.getByRole('button', { name: 'More folders', exact: true }).click()
  await expect(panel.getByRole('combobox', { name: 'Choose a Drive folder', exact: true }).locator('option')).toHaveCount(3)
  await attachVisualState(page, testInfo, 'drive-folders-discovered', panel, panel.getByRole('combobox', { name: 'Choose a Drive folder', exact: true }))
  await panel.getByLabel('New folder name').fill('Team research')
  await page.evaluate(() => sessionStorage.setItem('e2e:google-cancel-operation', 'google_drive_write'))
  await panel.getByRole('button', { name: 'Create Drive folder', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('cancelled')
  await attachVisualState(page, testInfo, 'drive-folder-approval-cancelled', panel, panel.getByRole('alert'))
  expect((await calls(page)).filter(call => call.cmd === 'collaboration_write')).toHaveLength(0)
  await page.evaluate(() => sessionStorage.removeItem('e2e:google-cancel-operation'))
  await panel.getByRole('button', { name: 'Create Drive folder', exact: true }).click()
  await expect(panel.getByLabel('Shared folder ID', { exact: true })).toHaveValue('created-folder')
  await panel.getByLabel('Revision transport', { exact: true }).selectOption('google_docs')
  await panel.getByRole('button', { name: 'Save folder and transport', exact: true }).click()
  await expect(panel.getByRole('status').filter({ hasText: 'saved for this vault' })).toContainText('saved for this vault')
  const history = await calls(page)
  expect(history).toEqual(expect.arrayContaining([expect.objectContaining({ cmd: 'authorize_sensitive_operation', payload: expect.objectContaining({ operation: 'google_drive_write', scope: expect.stringMatching(/^drive:folders:create:[a-f0-9]{64}$/) }) })]))
  const save = history.filter(call => call.cmd === 'vault_save_config_cmd').at(-1)!
  expect(save.payload.expectedVaultId).toBe('screenshot-vault')
  expect((save.payload.config as { calendar_sync: unknown }).calendar_sync).toEqual(expect.objectContaining({ google_drive_folder_id: 'created-folder', google_drive_transport: 'google_docs' }))
  await settleLayout(page)
  await attachVisualState(page, testInfo, 'drive-resource-setup', panel, panel.getByLabel('Shared folder ID', { exact: true }))
  await page.reload()
  await openCommandPalette(page)
  await runCommand(page, 'Drive collaboration')
  await expect(panel.getByLabel('Shared folder ID', { exact: true })).toHaveValue('created-folder')
  await expect(panel.getByLabel('Revision transport', { exact: true })).toHaveValue('google_docs')
  await attachVisualState(page, testInfo, 'drive-binding-reopened', panel, panel.getByLabel('Shared folder ID', { exact: true }))
})

test('Docs discovery stays in the selected folder and a conflicted preview cannot overwrite a stale note', async ({ page }, testInfo) => {
  await page.addInitScript(() => {
    const vaultId = 'screenshot-vault'; const folderId = 'shared-folder'; const path = 'Research Plan.md'
    const raw = JSON.stringify({ schema: 'scriptor.collaboration.mapping.v1', vaultId, folderId, path, peerId: 'legacy-peer', markdown: '---\nstatus: Done\npriority: High\nscore: 12\n---\n\n# Research Plan\n\nResearch [@smith2024].' })
    // Neither an unowned legacy cache nor another account's ancestor can make
    // an overlapping import appear safe to apply without resolving its conflict.
    localStorage.setItem(`scriptor:collaboration:${JSON.stringify([vaultId, folderId, path])}`, raw)
    localStorage.setItem(`scriptor:google-collaboration:v2:${JSON.stringify(['other@example.com', vaultId, folderId, path])}`, raw)
  })
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByText('Optional Google Docs text translation', { exact: true }).click()
  await panel.getByRole('button', { name: 'Browse documents in this folder', exact: true }).click()
  await panel.getByRole('combobox', { name: 'Choose a Google document', exact: true }).selectOption('shared-doc')
  await panel.getByRole('button', { name: 'Preview translated Google document', exact: true }).click()
  const preview = panel.getByRole('textbox', { name: 'Reviewed translated merge', exact: true })
  await expect(preview).toHaveValue(/Remote translated text/)
  await attachVisualState(page, testInfo, 'docs-translated-preview', panel, preview)
  await panel.getByLabel('I reviewed and accept the text conversion losses for this action').check()
  await expect(panel.getByRole('button', { name: 'Apply reviewed translated merge', exact: true })).toBeDisabled()
  await attachVisualState(page, testInfo, 'docs-overlapping-merge-blocked', panel, preview)
  await preview.fill('# Reviewed text\n\nLocal and remote edits retained.')
  await page.evaluate(() => sessionStorage.setItem('e2e:google-stale-note', '1'))
  await panel.getByRole('button', { name: 'Apply reviewed translated merge', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('content hash mismatch')
  await expect(preview).toHaveValue('# Reviewed text\n\nLocal and remote edits retained.')
  await attachVisualState(page, testInfo, 'docs-stale-content-rejected', panel, panel.getByRole('alert'))
  const history = await calls(page)
  expect(history.filter(call => call.cmd === 'collaboration_write')).toHaveLength(0)
  const importAttempt = history.filter(call => call.cmd === 'vault_save_note').at(-1)!
  expect(importAttempt.payload).toEqual(expect.objectContaining({ expectedVaultId: 'screenshot-vault', path: 'Research Plan.md', dryRun: false }))
  expect(importAttempt.payload.expectedContentHash).toBeTruthy()
  expect(history.filter(call => call.cmd === 'collaboration_read').map(call => call.payload.request)).toEqual(expect.arrayContaining([
    expect.objectContaining({ kind: 'list_docs', folder_id: 'shared-folder' }),
    expect.objectContaining({ kind: 'read_docs', folder_id: 'shared-folder', file_id: 'shared-doc' }),
  ]))
})

test('Docs export creates a new document only after accepted loss disclosure and approval', async ({ page }, testInfo) => {
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByText('Optional Google Docs text translation', { exact: true }).click()
  const create = panel.getByRole('button', { name: 'Create new Google Docs text copy', exact: true })
  await expect(create).toBeDisabled()
  await attachVisualState(page, testInfo, 'docs-loss-consent-required', panel, create)
  await panel.getByLabel('I reviewed and accept the text conversion losses for this action').check()
  await page.evaluate(() => sessionStorage.setItem('e2e:google-cancel-operation', 'google_drive_write'))
  await create.click()
  await expect(panel.getByRole('alert')).toContainText('cancelled')
  await attachVisualState(page, testInfo, 'docs-create-approval-cancelled', panel, panel.getByRole('alert'))
  expect((await calls(page)).filter(call => call.cmd === 'collaboration_write')).toHaveLength(0)
  await page.evaluate(() => sessionStorage.removeItem('e2e:google-cancel-operation'))
  await create.click()
  await expect(panel.getByRole('status').filter({ hasText: 'Created new Google document' })).toContainText('Created new Google document')
  await attachVisualState(page, testInfo, 'docs-new-copy-created', panel, panel.getByRole('status').filter({ hasText: 'Created new Google document' }))
  const write = (await calls(page)).find(call => call.cmd === 'collaboration_write')!
  expect(write.payload.request).toEqual(expect.objectContaining({ kind: 'append_docs', folder_id: 'shared-folder' }))
  expect(write.payload.request).not.toHaveProperty('file_id')
  expect((await calls(page)).filter(call => call.cmd === 'vault_save_note')).toHaveLength(0)
})

test('External Drive account changes clear discoveries and discard late Docs previews', async ({ page }, testInfo) => {
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByRole('button', { name: 'Browse accessible folders', exact: true }).click()
  await panel.getByText('Optional Google Docs text translation', { exact: true }).click()
  await panel.getByRole('button', { name: 'Browse documents in this folder', exact: true }).click()
  await panel.getByRole('combobox', { name: 'Choose a Google document', exact: true }).selectOption('shared-doc')
  await page.evaluate(() => sessionStorage.setItem('e2e:google-delay-docs', '1'))
  await panel.getByRole('button', { name: 'Preview translated Google document', exact: true }).click()
  await expect(panel.getByRole('status').filter({ hasText: 'Working' })).toContainText('Working')
  await page.evaluate(() => {
    sessionStorage.setItem('e2e:google-drive-connected', '0')
    window.dispatchEvent(new CustomEvent('scriptor:google-account-changed', { detail: { service: 'drive', origin: 'settings' } }))
  })
  await expect(panel.getByRole('status').filter({ hasText: 'account changed' })).toContainText('account changed')
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem('e2e:google-late-docs'))).toBe('1')
  await expect(panel.getByRole('textbox', { name: 'Reviewed translated merge', exact: true })).toHaveCount(0)
  await expect(panel.getByRole('combobox', { name: 'Choose a Google document', exact: true })).toHaveCount(0)
  await expect(panel.getByRole('combobox', { name: 'Choose a Drive folder', exact: true })).toHaveCount(0)
  await expect(panel.getByLabel('Google document ID', { exact: true })).toHaveValue('')
  await attachVisualState(page, testInfo, 'drive-disconnected-review-cleared', panel, panel.getByLabel('Google document ID', { exact: true }))
  expect((await calls(page)).filter(call => call.cmd === 'vault_save_note')).toHaveLength(0)
})

test('Revision pagination rejects repeated tokens without duplicating entries or blocking recovery', async ({ page }, testInfo) => {
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByRole('button', { name: 'Refresh shared revisions', exact: true }).click()
  await panel.getByRole('button', { name: 'Load next page', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'Shared revision one', exact: true })).toHaveCount(1)
  await expect(panel.getByRole('button', { name: 'Shared revision two', exact: true })).toHaveCount(1)
  await attachVisualState(page, testInfo, 'drive-revisions-paginated', panel, panel.getByRole('button', { name: 'Shared revision two', exact: true }))
  await page.evaluate(() => sessionStorage.setItem('e2e:google-revision-loop', '1'))
  await panel.getByRole('button', { name: 'Refresh shared revisions', exact: true }).click()
  await panel.getByRole('button', { name: 'Load next page', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('repeated a resource page')
  await attachVisualState(page, testInfo, 'drive-revision-cycle-rejected', panel, panel.getByRole('alert'))
  await expect(panel.getByRole('button', { name: 'Load next page', exact: true })).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Shared revision one', exact: true })).toHaveCount(1)
  await page.evaluate(() => sessionStorage.removeItem('e2e:google-revision-loop'))
  await panel.getByRole('button', { name: 'Refresh shared revisions', exact: true }).click()
  await expect(panel.getByRole('alert')).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Load next page', exact: true })).toBeEnabled()
})

test('Calendar and task-list discovery persists selections without authorizing other accounts', async ({ page }, testInfo) => {
  await launchGoogle(page)
  const { settings, google } = await openGoogleSettings(page)
  await expect(google.getByRole('combobox', { name: 'Calendar', exact: true }).locator('option', { hasText: 'Shared read-only calendar' })).toBeAttached()
  await expect(google.getByRole('combobox', { name: 'Calendar', exact: true }).locator('option', { hasText: 'Availability only' })).toHaveJSProperty('disabled', true)
  await google.getByRole('combobox', { name: 'Calendar', exact: true }).selectOption('reader@example.com')
  await google.getByRole('combobox', { name: 'Task list', exact: true }).selectOption('research-tasks')
  await settings.getByRole('button', { name: 'Save vault config', exact: true }).click()
  await expect(settings.getByRole('button', { name: 'Save vault config', exact: true })).toBeDisabled()
  await attachVisualState(page, testInfo, 'google-settings-resource-selection', google, google.getByRole('combobox', { name: 'Task list', exact: true }))
  const save = (await calls(page)).filter(call => call.cmd === 'vault_save_config_cmd').at(-1)!
  expect((save.payload.config as { calendar_sync: unknown }).calendar_sync).toEqual(expect.objectContaining({ google_calendar_id: 'reader@example.com', google_task_list_id: 'research-tasks' }))
  const calendarGroup = google.getByRole('group', { name: 'Google Calendar & Tasks', exact: true })
  await page.evaluate(() => sessionStorage.setItem('e2e:google-cancel-operation', 'google_calendar_auth'))
  await calendarGroup.getByRole('button', { name: 'Reconnect', exact: true }).click()
  await expect(calendarGroup.getByRole('alert')).toContainText('cancelled')
  await attachVisualState(page, testInfo, 'calendar-reconnect-cancelled', google, calendarGroup.getByRole('alert'))
  const history = await calls(page)
  expect(history.filter(call => /collaboration_connect|collaboration_disconnect|google_gmail_start_auth|google_gmail_disconnect/.test(call.cmd))).toHaveLength(0)
  expect(history.filter(call => call.cmd === 'google_calendar_start_auth')).toHaveLength(0)
  await page.reload()
  const reopened = await openGoogleSettings(page)
  await expect(reopened.google.getByRole('combobox', { name: 'Calendar', exact: true })).toHaveValue('reader@example.com')
  await expect(reopened.google.getByRole('combobox', { name: 'Task list', exact: true })).toHaveValue('research-tasks')
  await attachVisualState(page, testInfo, 'google-settings-restored-resources', reopened.google, reopened.google.getByRole('combobox', { name: 'Task list', exact: true }))
})

test('Google setup save failures retain the connected account and allow an explicit retry', async ({ page }, testInfo) => {
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByLabel('Shared folder ID', { exact: true }).fill('another-folder')
  await page.evaluate(() => sessionStorage.setItem('e2e:google-config-save-error', '1'))
  await panel.getByRole('button', { name: 'Save folder and transport', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('could not be persisted')
  await expect(panel).toContainText('drive@example.com')
  await attachVisualState(page, testInfo, 'drive-binding-save-error', panel, panel.getByRole('alert'))
  expect((await calls(page)).filter(call => call.cmd === 'collaboration_disconnect')).toHaveLength(0)
  await page.evaluate(() => sessionStorage.removeItem('e2e:google-config-save-error'))
  await panel.getByRole('button', { name: 'Save folder and transport', exact: true }).click()
  await expect(panel.getByRole('status').filter({ hasText: 'saved for this vault' })).toContainText('saved for this vault')
  await attachVisualState(page, testInfo, 'drive-binding-save-recovered', panel, panel.getByRole('status').filter({ hasText: 'saved for this vault' }))
})

test('A read-only selected calendar permits reviewed imports while blocking event writes', async ({ page }, testInfo) => {
  await launchGoogle(page, false)
  const { settings, google } = await openGoogleSettings(page)
  await expect(google.getByRole('combobox', { name: 'Calendar', exact: true }).locator('option', { hasText: 'Shared read-only calendar' })).toBeAttached()
  await google.getByRole('combobox', { name: 'Calendar', exact: true }).selectOption('reader@example.com')
  await settings.getByRole('button', { name: 'Save vault config', exact: true }).click()
  await page.reload()
  await openCommandPalette(page)
  await runCommand(page, 'Open tasks panel')
  const planner = page.getByRole('region', { name: 'Weekly planner', exact: true })
  await expect(planner.getByRole('button', { name: 'Review bidirectional sync', exact: true })).toBeEnabled()
  await planner.getByRole('combobox', { name: 'Vault task', exact: true }).selectOption({ label: 'Collect sources' })
  await planner.getByRole('combobox', { name: 'Google event', exact: true }).selectOption('remote-event')
  await planner.getByRole('button', { name: 'Save time block', exact: true }).click()
  await planner.getByRole('button', { name: 'Review bidirectional sync', exact: true }).click()
  const eventRow = planner.locator('.planner-review__row').filter({ has: page.locator('pre', { hasText: 'remote-event' }) })
  // The event JSON stores the local event identity; task rows have no eventId.
  await expect(eventRow).toHaveCount(1)
  await expect(eventRow.getByRole('button', { name: 'Use vault → Google', exact: true })).toBeDisabled()
  await expect(eventRow.getByRole('button', { name: 'Use Google → vault', exact: true })).toBeEnabled()
  await attachVisualState(page, testInfo, 'calendar-readonly-reviewed-change', eventRow, eventRow.getByRole('button', { name: 'Use Google → vault', exact: true }))
  await eventRow.getByRole('button', { name: 'Use Google → vault', exact: true }).click()
  await expect(planner.getByRole('status')).toContainText('Change applied')
  await attachVisualState(page, testInfo, 'calendar-reviewed-import-applied', planner, planner.getByRole('status'))
  expect((await calls(page)).filter(call => call.cmd === 'google_planner_write_event')).toHaveLength(0)
})

test('Drive resource controls stay usable at narrow width, RTL and 200% zoom', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 768, height: 960 })
  await page.addInitScript(() => localStorage.setItem('scriptor:ui-zoom', '2'))
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByRole('button', { name: 'Browse accessible folders', exact: true }).click()
  await expect.poll(() => page.evaluate(() => Number(document.body.style.zoom))).toBe(2)
  await page.locator('html').evaluate(node => { node.setAttribute('dir', 'rtl') })
  await settleLayout(page)
  await expect.poll(() => panel.evaluate(node => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(1)
  const controls = panel.locator('.collaboration-resources').first()
  await expect.poll(() => controls.evaluate(node => node.scrollWidth - node.clientWidth)).toBeLessThanOrEqual(1)
  await controls.getByLabel('New folder name', { exact: true }).focus()
  await expect(controls.getByLabel('New folder name', { exact: true })).toBeFocused()
  await controls.getByLabel('New folder name', { exact: true }).fill('RTL research')
  await page.keyboard.press('Tab')
  await expect(controls.getByRole('button', { name: 'Create Drive folder', exact: true })).toBeFocused()
  await attachVisualState(page, testInfo, 'drive-resources-rtl-200-percent', controls, controls.getByRole('button', { name: 'Create Drive folder', exact: true }))
})

test('Calendar changes in Settings invalidate an already prepared planner review in another consumer', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.addInitScript(() => localStorage.setItem('scriptor:panel-presentation', 'dock-right'))
  await launchGoogle(page)
  await openCommandPalette(page)
  await runCommand(page, 'Open tasks panel')
  const planner = page.getByRole('region', { name: 'Weekly planner', exact: true })
  await expect(planner.getByRole('button', { name: 'Review bidirectional sync', exact: true })).toBeEnabled()
  await planner.getByRole('button', { name: 'Review bidirectional sync', exact: true }).click()
  await expect(planner.locator('.planner-review')).toBeVisible()
  // Tasks owns a modal: use a non-editing control's palette route rather
  // than attempting to click chrome behind the backdrop.
  await planner.getByRole('button', { name: 'Review bidirectional sync', exact: true }).focus()
  await page.keyboard.press('Control+KeyK')
  await runCommand(page, 'Open settings')
  const settings = page.getByRole('dialog', { name: 'Settings', exact: true })
  await settings.getByRole('tab', { name: 'Integrations', exact: true }).click()
  const google = settings.locator('.google-integration-settings')
  const calendar = google.getByRole('group', { name: 'Google Calendar & Tasks', exact: true })
  await calendar.getByRole('button', { name: 'Disconnect', exact: true }).click()
  await expect(planner.locator('.planner-review')).toHaveCount(0)
  await expect(planner.getByRole('button', { name: 'Review bidirectional sync', exact: true })).toBeDisabled()
  await calendar.getByRole('button', { name: 'Connect Google', exact: true }).click()
  await expect(planner.getByRole('button', { name: 'Review bidirectional sync', exact: true })).toBeEnabled()
  await expect(planner.locator('.planner-review')).toHaveCount(0)
  const history = await calls(page)
  expect(history.filter(call => call.cmd === 'google_calendar_disconnect')).toHaveLength(1)
  expect(history.filter(call => call.cmd === 'google_calendar_start_auth')).toHaveLength(1)
  expect(history.filter(call => /google_planner_write|collaboration_disconnect|google_gmail_disconnect/.test(call.cmd))).toHaveLength(0)
})

test('Drive reconnect clears its own old-account resources and reviewed previews', async ({ page }) => {
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByRole('button', { name: 'Browse accessible folders', exact: true }).click()
  await panel.getByRole('button', { name: 'Refresh shared revisions', exact: true }).click()
  await panel.getByText('Optional Google Docs text translation', { exact: true }).click()
  await panel.getByRole('button', { name: 'Browse documents in this folder', exact: true }).click()
  await panel.getByRole('combobox', { name: 'Choose a Google document', exact: true }).selectOption('shared-doc')
  await panel.getByRole('button', { name: 'Preview translated Google document', exact: true }).click()
  await expect(panel.getByRole('textbox', { name: 'Reviewed translated merge', exact: true })).toBeVisible()
  await panel.getByRole('button', { name: 'Connect Google Drive', exact: true }).click()
  await expect(panel.getByRole('status').filter({ hasText: 'Google setup saved' })).toContainText('Google setup saved')
  await expect(panel.getByRole('textbox', { name: 'Reviewed translated merge', exact: true })).toHaveCount(0)
  await expect(panel.getByRole('combobox', { name: 'Choose a Google document', exact: true })).toHaveCount(0)
  await expect(panel.getByRole('combobox', { name: 'Choose a Drive folder', exact: true })).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Shared revision one', exact: true })).toHaveCount(0)
  await expect(panel.getByLabel('Google document ID', { exact: true })).toHaveValue('')
  expect((await calls(page)).filter(call => call.cmd === 'vault_save_note')).toHaveLength(0)
})

test('A late initial Drive credential read cannot erase a newly completed connection', async ({ page }) => {
  await page.addInitScript(() => {
    sessionStorage.setItem('e2e:google-drive-connected', '0')
    sessionStorage.setItem('e2e:google-delay-account', '1')
  })
  await launchGoogle(page)
  const panel = await openDrive(page)
  await panel.getByRole('button', { name: 'Connect Google Drive', exact: true }).click()
  await expect(panel.getByRole('status').filter({ hasText: 'Google setup saved' })).toContainText('Google setup saved')
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem('e2e:google-late-account'))).toBe('1')
  await expect(panel).toContainText('Connected: drive@example.com')
})
