import { expect, test, type Page } from '@playwright/test'
import { closeWorkspacePanel, launchApp, openCommandPalette, runCommand, settleLayout, waitForWorkspace } from './helpers'
import { attachVisualState } from './visual-state-evidence'

async function openGmail(page: Page, connected = true, theme: 'light' | 'dark' = 'light') {
  await page.addInitScript(({ connected }) => {
    sessionStorage.setItem('e2e:google-gmail', '1')
    sessionStorage.setItem('e2e:enable-gmail-plugin', '1')
    if (sessionStorage.getItem('e2e:gmail-connected') === null) sessionStorage.setItem('e2e:gmail-connected', connected ? '1' : '0')
    localStorage.setItem('scriptor:plugins:consent', JSON.stringify({ schemaVersion: 1, savedAt: '2026-10-08T00:00:00Z', data: {
      'scriptor.gmail-manager': { grantedPermissions: ['read', 'write-approved'], allowedVaultIds: ['screenshot-vault'], networkAccess: 'blocked', allowlistedHosts: [], reviewedAt: '2026-10-08T00:00:00Z' },
    } }))
  }, { connected })
  await launchApp(page, { theme })
  await waitForWorkspace(page, { allowHiddenVaultList: true })
  await openCommandPalette(page)
  await runCommand(page, 'Open Gmail Manager')
  const panel = page.locator('.gmail-manager-panel')
  await expect(panel).toBeVisible()
  return panel
}

async function calls(page: Page) {
  return page.evaluate(() => JSON.parse(sessionStorage.getItem('e2e:gmail-calls') ?? '[]') as { cmd: string; payload: Record<string, unknown> }[])
}

test('Gmail dark inbox and long compose fields retain readable boundaries', async ({ page }, testInfo) => {
  const panel = await openGmail(page, true, 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-appearance', 'dark')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await attachVisualState(page, testInfo, 'gmail-dark-inbox', panel, panel.locator('.gmail-manager-message-row').first())
  await panel.getByRole('tab', { name: 'Compose', exact: true }).click()
  await panel.getByLabel('Recipient (To)').fill('research.collaboration@example.com')
  await panel.getByLabel('Subject', { exact: true }).fill('Research collaboration: long subject with Unicode سلام and retained local draft')
  await panel.getByLabel('Message body (plain text)').fill('First paragraph of a reviewed message.\n\nSecond paragraph with a long line: ' + 'Research evidence '.repeat(20))
  await expect(panel.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled()
  await expect.poll(() => panel.evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
  await attachVisualState(page, testInfo, 'gmail-dark-long-compose', panel, panel.getByLabel('Message body (plain text)'))
  expect((await calls(page)).filter(call => call.cmd === 'google_gmail_send_message')).toHaveLength(0)
})

test('Gmail paginates, deduplicates, searches and renders provider text literally', async ({ page }, testInfo) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await attachVisualState(page, testInfo, 'gmail-inbox', panel, panel.locator('.gmail-manager-message-row').first())
  await panel.getByRole('button', { name: 'Load more messages' }).click()
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(3)
  await attachVisualState(page, testInfo, 'gmail-pages-deduplicated', panel, panel.locator('.gmail-manager-message-row').last())
  await expect(panel.getByRole('button', { name: 'Load more messages' })).toHaveCount(0)
  await panel.locator('.gmail-manager-message-row').first().click()
  await expect(panel.locator('.gmail-manager-message-body')).toContainText('<script>alert(1)</script>')
  await expect(panel.locator('.gmail-manager-message-body script, .gmail-manager-message-body img')).toHaveCount(0)
  await attachVisualState(page, testInfo, 'gmail-literal-message-detail', panel, panel.locator('.gmail-manager-message-body'))
  await panel.getByRole('button', { name: 'Import', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('Imported')
  await attachVisualState(page, testInfo, 'gmail-markdown-imported', panel, panel.getByRole('status').filter({ hasText: 'Imported' }))
  const imported = (await calls(page)).find(call => call.cmd === 'vault_save_note')
  expect(JSON.stringify(imported)).toContain('&lt;script&gt;')
  expect(JSON.stringify(imported)).toContain('gmail_id')
  await panel.getByRole('searchbox').fill('from:new@example.com')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(0)
  await expect(panel.locator('.gmail-manager-message-detail')).toHaveCount(0)
  await panel.getByRole('searchbox').press('Enter')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(1)
  await expect(panel.locator('.gmail-manager-message-row')).toContainText('New search result')
  await settleLayout(page)
  await attachVisualState(page, testInfo, 'gmail-search-populated', panel, panel.locator('.gmail-manager-message-row').first())
})

test('Gmail drops late list and detail responses after a query change', async ({ page }) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-delay-detail', '1'))
  await panel.locator('.gmail-manager-message-row').first().click()
  await expect(panel.getByText('Loading message…', { exact: true })).toBeVisible()
  await panel.getByRole('searchbox').fill('from:new@example.com')
  await panel.getByRole('searchbox').press('Enter')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(1)
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem('e2e:gmail-late-detail-completed'))).toBe('1')
  await expect(panel.locator('.gmail-manager-message-detail')).toHaveCount(0)
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-delay-list', '1'))
  await panel.getByRole('searchbox').fill('in:inbox')
  await panel.getByRole('searchbox').press('Enter')
  await expect(panel.locator('.gmail-manager-message-list')).toHaveAttribute('aria-busy', 'true')
  await panel.getByRole('searchbox').fill('is:unread')
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem('e2e:gmail-late-list-completed'))).toBe('1')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Load more messages' })).toHaveCount(0)
})

test('Gmail archive, trash and send use distinct reviewed authorization scopes', async ({ page }) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await panel.locator('.gmail-manager-message-row').first().click()
  await panel.getByRole('button', { name: 'Archive message' }).click()
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(1)
  await panel.locator('.gmail-manager-message-row').first().click()
  await panel.getByRole('button', { name: 'Move to trash' }).click()
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(0)
  await panel.getByRole('tab', { name: 'Compose', exact: true }).click()
  await panel.getByLabel('Recipient (To)').fill('person@example.com')
  await panel.getByLabel('Subject', { exact: true }).fill('Unicode سلام')
  await panel.getByLabel('Message body (plain text)').fill('Plain outgoing text')
  await panel.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('Email sent successfully')
  await expect(panel.getByLabel('Message body (plain text)')).toHaveValue('')
  const history = await calls(page)
  const approvals = history.filter(call => call.cmd === 'authorize_sensitive_operation').map(call => call.payload)
  expect(approvals).toEqual(expect.arrayContaining([
    expect.objectContaining({ operation: 'google_gmail_write', scope: 'a1' }),
    expect.objectContaining({ operation: 'google_gmail_write', scope: 'a2' }),
    expect.objectContaining({ operation: 'google_gmail_send', scope: 'gmail-send' }),
  ]))
  const sent = history.find(call => call.cmd === 'google_gmail_send_message')
  expect(sent?.payload.authorizationToken).toBe('e2e-authorization-token')
  expect(Buffer.from(String(sent?.payload.rawMessage), 'base64url').toString('utf8')).toContain('=?UTF-8?B?')
  expect(history.filter(call => /google_calendar_(start_auth|disconnect|create|update|delete)|google_task_(create|update|delete)|collaboration_(start_auth|disconnect|write)/.test(call.cmd))).toHaveLength(0)
})

test('Gmail cancelled approval does not send and failed sending preserves the draft', async ({ page }, testInfo) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await panel.getByRole('tab', { name: 'Compose', exact: true }).click()
  await panel.getByLabel('Recipient (To)').fill('person@example.com')
  await panel.getByLabel('Subject', { exact: true }).fill('Keep this draft')
  await panel.getByLabel('Message body (plain text)').fill('Draft body')
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-cancel-approval', '1'))
  await panel.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('cancelled')
  await attachVisualState(page, testInfo, 'gmail-send-cancelled-draft', panel, panel.getByRole('alert'))
  expect((await calls(page)).filter(call => call.cmd === 'google_gmail_send_message')).toHaveLength(0)
  await page.evaluate(() => { sessionStorage.removeItem('e2e:gmail-cancel-approval'); sessionStorage.setItem('e2e:gmail-send-error', '1') })
  await panel.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('Gmail send failed')
  await expect(panel.getByLabel('Subject', { exact: true })).toHaveValue('Keep this draft')
  await expect(panel.getByLabel('Message body (plain text)')).toHaveValue('Draft body')
  await attachVisualState(page, testInfo, 'gmail-send-failed-draft', panel, panel.getByRole('alert'))
})

test('Gmail reconnects, disconnects and rejects late reads after external disconnect', async ({ page }, testInfo) => {
  const panel = await openGmail(page, false)
  await expect(panel).toContainText('Gmail is not connected')
  await panel.getByRole('tab', { name: 'Account', exact: true }).click()
  await panel.getByLabel('Google OAuth client ID').fill('desktop.apps.googleusercontent.com')
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-auth-cancel', '1'))
  await panel.getByRole('button', { name: 'Connect with Google' }).click()
  await expect(panel.getByRole('alert')).toContainText('cancelled')
  await expect(panel).toContainText('Not connected to Gmail')
  await attachVisualState(page, testInfo, 'gmail-account-auth-cancelled', panel, panel.getByRole('alert'))
  await page.evaluate(() => sessionStorage.removeItem('e2e:gmail-auth-cancel'))
  await panel.getByRole('button', { name: 'Connect with Google' }).click()
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-delay-detail', '1'))
  await panel.locator('.gmail-manager-message-row').first().click()
  await expect(panel.getByText('Loading message…', { exact: true })).toBeVisible()
  await page.evaluate(() => {
    sessionStorage.setItem('e2e:gmail-connected', '0')
    window.dispatchEvent(new CustomEvent('scriptor:google-account-changed', { detail: { service: 'gmail' } }))
  })
  await expect(panel).toContainText('Gmail is not connected')
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem('e2e:gmail-late-detail-completed'))).toBe('1')
  await expect(panel.locator('.gmail-manager-message-detail')).toHaveCount(0)
  await panel.getByRole('tab', { name: 'Account', exact: true }).click()
  await panel.getByRole('button', { name: 'Connect with Google' }).click()
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await panel.getByRole('tab', { name: 'Account', exact: true }).click()
  await panel.getByRole('button', { name: 'Disconnect account' }).click()
  await expect(panel).toContainText('Disconnected from Gmail')
  await attachVisualState(page, testInfo, 'gmail-account-disconnected', panel, panel.getByRole('status').filter({ hasText: 'Disconnected from Gmail' }))
  const history = await calls(page)
  expect(history.some(call => call.cmd === 'google_gmail_disconnect')).toBe(true)
  expect(history.filter(call => /google_calendar_disconnect|collaboration_disconnect/.test(call.cmd))).toHaveLength(0)
})

test('Gmail terminates cyclic pagination and clears caches on close', async ({ page }, testInfo) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-pagination-loop', '1'))
  await panel.getByRole('button', { name: 'Search or refresh messages' }).click()
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(1)
  await panel.getByRole('button', { name: 'Load more messages' }).click()
  await expect.poll(async () => (await calls(page)).filter(call => call.cmd === 'google_gmail_list_messages_page').length).toBe(3)
  await panel.getByRole('button', { name: 'Load more messages' }).click()
  await expect(panel.getByRole('alert')).toContainText('repeated a page token')
  await attachVisualState(page, testInfo, 'gmail-page-cycle-error', panel, panel.getByRole('alert'))
  await expect(panel.getByRole('button', { name: 'Load more messages' })).toHaveCount(0)
  await closeWorkspacePanel(page, panel)
  await expect(panel).toBeHidden()
})

test('Gmail recovers from list failure and keeps an empty search authoritative', async ({ page }, testInfo) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-list-error', '1'))
  await panel.getByRole('button', { name: 'Search or refresh messages' }).click()
  await expect(panel.getByRole('alert')).toContainText('temporarily unavailable')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(0)
  await attachVisualState(page, testInfo, 'gmail-list-failure', panel, panel.getByRole('alert'))
  await page.evaluate(() => sessionStorage.removeItem('e2e:gmail-list-error'))
  await panel.getByRole('searchbox').fill('is:unread')
  await panel.getByRole('searchbox').press('Enter')
  await expect(panel).toContainText('No messages found')
  await attachVisualState(page, testInfo, 'gmail-search-empty', panel, panel.getByText('No messages found', { exact: true }))
  await expect(panel.getByRole('alert')).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Load more messages' })).toHaveCount(0)
})

test('Gmail rejects an immediate repeated token and recovers only through an explicit refresh', async ({ page }) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-immediate-pagination-loop', '1'))
  await panel.getByRole('button', { name: 'Load more messages' }).click()
  await expect(panel.getByRole('alert')).toContainText('repeated pagination token')
  await expect(panel.getByRole('button', { name: 'Load more messages' })).toHaveCount(0)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await page.evaluate(() => sessionStorage.removeItem('e2e:gmail-immediate-pagination-loop'))
  await panel.getByRole('button', { name: 'Search or refresh messages' }).click()
  await expect(panel.getByRole('alert')).toHaveCount(0)
  await panel.getByRole('button', { name: 'Load more messages' }).click()
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(3)
})

test('Closing Gmail prevents a pending old query from replacing the reopened inbox', async ({ page }) => {
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await page.evaluate(() => sessionStorage.setItem('e2e:gmail-delay-list', '1'))
  await panel.getByRole('searchbox').fill('from:new@example.com')
  await panel.getByRole('searchbox').press('Enter')
  await expect(panel.locator('.gmail-manager-message-list')).toHaveAttribute('aria-busy', 'true')
  await closeWorkspacePanel(page, panel)
  await page.evaluate(() => sessionStorage.removeItem('e2e:gmail-delay-list'))
  await openCommandPalette(page)
  await runCommand(page, 'Open Gmail Manager')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem('e2e:gmail-late-list-completed'))).toBe('1')
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await expect(panel.locator('.gmail-manager-message-list')).not.toContainText('New search result')
})

test('Gmail controls remain usable with keyboard, RTL and 200 percent app zoom', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 768, height: 960 })
  await page.addInitScript(() => localStorage.setItem('scriptor:ui-zoom', '2'))
  const panel = await openGmail(page)
  await expect(panel.locator('.gmail-manager-message-row')).toHaveCount(2)
  await expect.poll(() => page.evaluate(() => Number(document.body.style.zoom))).toBe(2)
  await page.locator('html').evaluate(element => { element.dir = 'rtl' })
  await panel.getByRole('searchbox').focus()
  await page.keyboard.press('Tab')
  await expect(panel.getByRole('button', { name: 'Search or refresh messages' })).toBeFocused()
  await panel.locator('.gmail-manager-message-row').first().click()
  await expect(panel.locator('.gmail-manager-message-body')).toContainText('Plain message text')
  const metrics = await panel.evaluate(element => {
    const box = element.getBoundingClientRect()
    return { left: box.left, right: box.right, overflow: element.scrollWidth - element.clientWidth }
  })
  expect(metrics.left).toBeGreaterThanOrEqual(0)
  expect(metrics.right).toBeLessThanOrEqual(769)
  expect(metrics.overflow).toBeLessThanOrEqual(1)
  const importButton = panel.getByRole('button', { name: 'Import', exact: true })
  await importButton.scrollIntoViewIfNeeded()
  await expect(importButton).toBeInViewport({ ratio: 1 })
  await settleLayout(page)
  await attachVisualState(page, testInfo, 'gmail-narrow-rtl-zoom-detail', panel, importButton)
  await panel.getByRole('tab', { name: 'Compose', exact: true }).click()
  await panel.getByLabel('Recipient (To)').fill('person@example.com')
  await panel.getByLabel('Subject', { exact: true }).fill('Zoom draft')
  await panel.getByLabel('Message body (plain text)').fill('Usable compose body')
  const sendButton = panel.getByRole('button', { name: 'Send message', exact: true })
  await sendButton.scrollIntoViewIfNeeded()
  await expect(sendButton).toBeInViewport({ ratio: 1 })
  await expect(sendButton).toBeEnabled()
  await attachVisualState(page, testInfo, 'gmail-narrow-rtl-zoom-compose', panel, sendButton)
})
