import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { closeWorkspacePanel, workspacePanelCloseButton, launchApp, openCommandPalette, runCommand } from './helpers'
async function openResearch(page:Page,command:string){await page.addInitScript(()=>sessionStorage.setItem('e2e:research','1'));await launchApp(page);await openCommandPalette(page);await runCommand(page,command)}
async function calls(page:Page,command:string){return page.evaluate(cmd=>(JSON.parse(sessionStorage.getItem('e2e:research-calls')??'[]') as Array<{cmd:string;payload:Record<string,unknown>}>).filter(row=>row.cmd===cmd),command)}

test('database edit preserves the displayed revision after an external source change', async ({ page }) => {
  await openResearch(page, 'Database studio')
  const panel = page.getByRole('region', { name: 'Database Studio', exact: true })
  await panel.getByRole('button', { name: 'Load notes', exact: true }).click()
  await panel.getByRole('button', { name: 'Edit Score in Research Plan.md', exact: true }).click()
  await panel.getByLabel('Score', { exact: true }).fill('24')
  await page.evaluate(() => sessionStorage.setItem('e2e:external-row-edit', 'Research Plan.md'))
  await panel.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(panel.getByRole('alert').filter({ hasText: 'Cell was not saved' })).toContainText(/changed|Stale/, { timeout: 5000 })
  expect(await calls(page, 'vault_frontmatter_set')).toHaveLength(0)
})

test('changing a Zotero key clears the previous library preview and cursor', async ({ page }) => {
  await openResearch(page, 'Browse bibliography')
  const panel = page.getByRole('dialog', { name: 'Bibliography', exact: true })
  await panel.getByRole('button', { name: 'Review Zotero import', exact: true }).click()
  const key = panel.getByLabel('Zotero read API key', { exact: true })
  await key.fill('firstAccount')
  await panel.getByRole('button', { name: 'Fetch preview', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'Fetch next page', exact: true })).toBeVisible()
  await key.fill('secondAccount')
  await expect(panel.getByRole('button', { name: 'Fetch next page', exact: true })).toHaveCount(0, { timeout: 5000 })
  await expect(panel.getByRole('button', { name: 'Save selected references as a new bibliography', exact: true })).toHaveCount(0)
})

test('stopping initial database preset loading offers a successful reload', async ({ page }) => {
  await page.addInitScript(() => sessionStorage.setItem('e2e:delay-db-preset', '1'))
  await openResearch(page, 'Database studio')
  const panel = page.getByRole('region', { name: 'Database Studio', exact: true })
  await panel.getByRole('button', { name: 'Stop waiting', exact: true }).click()
  await expect(panel.getByRole('button', { name: 'Save view', exact: true })).toBeDisabled()
  const reload = panel.getByRole('button', { name: 'Reload saved views', exact: true })
  await expect(reload).toBeVisible({ timeout: 5000 })
  await reload.click()
  await expect(panel.getByRole('button', { name: 'Save view', exact: true })).toBeEnabled()
  await expect(reload).toHaveCount(0)
})

test('database metadata filters, inline YAML edits and vault saved views work together',async({page})=>{
  await openResearch(page,'Database studio')
  const panel=page.getByRole('region',{name:'Database Studio',exact:true})
  await panel.getByRole('button',{name:'Add filter',exact:true}).click()
  await panel.getByRole('combobox',{name:'Filter field',exact:true}).selectOption('metadata')
  await panel.getByLabel('YAML field',{exact:true}).fill('status')
  await panel.getByLabel('Equals',{exact:true}).fill('Done')
  await panel.getByRole('button',{name:'Load notes',exact:true}).click()
  await expect(panel.locator('tbody tr')).toHaveCount(1)
  await panel.getByRole('button',{name:'Edit Score in Research Plan.md',exact:true}).click()
  await panel.getByLabel('Score',{exact:true}).fill('24')
  await panel.getByRole('button',{name:'Save',exact:true}).click()
  await expect(panel.getByRole('button',{name:'Edit Score in Research Plan.md',exact:true})).toHaveText('24')
  const mutations=await calls(page,'vault_frontmatter_set')
  expect(mutations).toHaveLength(1);expect(mutations[0].payload.expectedVaultId).toBe('screenshot-vault')
  await panel.getByRole('button',{name:'Save view',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('Saved view in this vault.')
  const saves=await calls(page,'vault_save_asset');expect(saves).toHaveLength(1);expect(saves[0].payload.requireMissing).toBe(true)
  await closeWorkspacePanel(page, panel)
  await openCommandPalette(page);await runCommand(page,'Database studio')
  await expect(page.getByRole('combobox',{name:'Saved view',exact:true}).locator('option')).toHaveCount(2)
})

test('malformed database presets block save and remain intact',async({page})=>{
  await page.addInitScript(()=>sessionStorage.setItem('e2e:corrupt-db-preset','1'))
  await openResearch(page,'Database studio')
  const panel=page.getByRole('region',{name:'Database Studio',exact:true})
  await expect(panel.getByRole('alert')).toContainText('Saving is blocked')
  await expect(panel.getByRole('button',{name:'Save view',exact:true})).toBeDisabled()
  await panel.getByRole('button',{name:'Reload saved views',exact:true}).click()
  await expect(panel.getByRole('button',{name:'Save view',exact:true})).toBeDisabled()
  expect(await calls(page,'vault_save_asset')).toHaveLength(0)
})

test('database layouts preserve calculated values and scoped aggregate evidence',async({page})=>{
  await openResearch(page,'Database studio')
  const panel=page.getByRole('region',{name:'Database Studio',exact:true})
  await panel.getByRole('button',{name:'Add column',exact:true}).click()
  const column=panel.locator('.database-builder-row').last()
  await column.getByRole('textbox',{name:'Field',exact:true}).fill('double_score')
  await column.getByRole('textbox',{name:'Heading',exact:true}).fill('Double score')
  await column.getByRole('combobox',{name:'Calculation',exact:true}).selectOption('add')
  await column.getByRole('textbox',{name:'Operand 1',exact:true}).fill('score')
  await column.getByRole('textbox',{name:'Operand 2',exact:true}).fill('score')
  await panel.getByRole('button',{name:'Load notes',exact:true}).click()
  await expect(panel.locator('tbody tr')).toHaveCount(2)
  await expect(panel.locator('tbody tr').first()).toContainText('24')
  await panel.getByText('Aggregates for loaded rows',{exact:true}).click()
  await expect(panel.locator('details')).toContainText('sum 30')
  await panel.getByRole('combobox',{name:'Layout',exact:true}).selectOption('list')
  await expect(panel.locator('.database-results-list > li')).toHaveCount(2)
  await panel.getByRole('combobox',{name:'Layout',exact:true}).selectOption('gallery')
  await expect(panel.locator('.database-results-gallery > li')).toHaveCount(2)
})

test('capture extraction is explicit and reviewed metadata saves a new scoped note',async({page})=>{
  await openResearch(page,'Capture reviewer')
  const panel=page.getByRole('region',{name:'Capture reviewer',exact:true})
  expect(await calls(page,'capture_extract_preview')).toHaveLength(0)
  await panel.getByLabel('Article URL',{exact:true}).fill('https://example.org/article')
  await panel.getByRole('button',{name:'Extract preview',exact:true}).click()
  await expect(panel.getByRole('textbox',{name:'Reviewed Markdown',exact:true})).toHaveValue(/useful research/)
  const snapshot=panel.locator('iframe[title="Original source snapshot"]')
  await expect(snapshot).toHaveAttribute('sandbox','')
  await expect(snapshot).toHaveAttribute('referrerpolicy','no-referrer')
  const source=page.frameLocator('iframe[title="Original source snapshot"]')
  await expect(source.getByRole('heading',{name:'Original research finding',exact:true})).toBeVisible()
  await expect(source.locator('script,img,form,input,a,link,style:not(head style)')).toHaveCount(0)
  expect(await page.evaluate(()=>Reflect.get(window,'snapshotExecuted'))).toBeUndefined()
  await panel.getByLabel('Author',{exact:true}).fill('Jane Writer')
  await panel.getByLabel('Tags, separated by commas',{exact:true}).fill('first-article')
  await panel.getByLabel('Article URL',{exact:true}).fill('https://example.org/second')
  await panel.getByRole('button',{name:'Extract preview',exact:true}).click()
  await expect(panel.getByLabel('Author',{exact:true})).toHaveValue('')
  await expect(panel.getByLabel('Tags, separated by commas',{exact:true})).toHaveValue('')
  await panel.getByLabel('Author',{exact:true}).fill('Jane Writer')
  await panel.getByRole('textbox',{name:'Reviewed Markdown',exact:true}).fill('Reviewed excerpt')
  await panel.getByRole('textbox',{name:'Reviewed Markdown',exact:true}).evaluate(element=>(element as HTMLTextAreaElement).setSelectionRange(0,8))
  await panel.getByRole('button',{name:'Highlight selected text',exact:true}).click()
  await expect(panel.getByRole('textbox',{name:'Reviewed Markdown',exact:true})).toHaveValue('==Reviewed== excerpt')
  await panel.getByRole('button',{name:'Save reviewed capture as a new note',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('Saved reviewed capture')
  const saved=(await calls(page,'vault_save_asset'))[0].payload
  expect(saved.requireMissing).toBe(true);expect(saved.expectedVaultId).toBe('screenshot-vault');expect(saved.relativePath).toBe('Inbox/Reviewed article.md')
  const content=new TextDecoder().decode(new Uint8Array(saved.bytes as number[]));expect(content).toContain('author: "Jane Writer"');expect(content).toContain('==Reviewed== excerpt')
})

test('reference desk previews paginated Zotero selections before any bibliography write',async({page})=>{
  await openResearch(page,'Browse bibliography')
  const panel=page.getByRole('dialog',{name:'Bibliography',exact:true})
  await panel.getByRole('button',{name:'Inspect citation usage',exact:true}).click()
  await expect(panel.getByRole('region',{name:'Citation usage'})).toContainText('Missing reference @missing2026')
  await panel.getByRole('button',{name:'Review Zotero import',exact:true}).click()
  await panel.getByLabel('Zotero read API key',{exact:true}).fill('testReadKey')
  await panel.getByRole('button',{name:'Fetch preview',exact:true}).click()
  await expect(panel.getByText('A previewed research paper',{exact:true})).toBeVisible()
  expect(await calls(page,'vault_save_asset')).toHaveLength(0)
  await panel.getByRole('button',{name:'Fetch next page',exact:true}).click()
  await expect(panel.getByText('Second-page paper',{exact:true})).toBeVisible()
  await panel.getByLabel('New vault bibliography path',{exact:true}).fill('Research/reviewed.bib')
  await panel.getByRole('button',{name:'Save selected references as a new bibliography',exact:true}).click()
  await expect(panel.getByRole('region',{name:'Review Zotero import',exact:true})).toHaveCount(0)
  const saved=(await calls(page,'vault_save_asset'))[0].payload
  expect(saved.requireMissing).toBe(true);expect(saved.expectedVaultId).toBe('screenshot-vault')
  const content=new TextDecoder().decode(new Uint8Array(saved.bytes as number[]));expect(content).toContain('@article{ZOTERO1');expect(content).toContain('@book{PAGE2')
  expect(await calls(page,'zotero_import_preview')).toHaveLength(2)
})

test('bibliography file review preserves existing files and literature notes retain citation metadata',async({page})=>{
  await openResearch(page,'Browse bibliography')
  const panel=page.getByRole('dialog',{name:'Bibliography',exact:true})
  await panel.getByLabel('Import a .bib file',{exact:true}).setInputFiles({name:'local.bib',mimeType:'text/plain',buffer:Buffer.from('@article{local2026, title={Local paper}}')})
  await expect(panel.getByRole('region',{name:'Review bibliography file'})).toContainText('Local paper')
  expect(await calls(page,'vault_save_asset')).toHaveLength(0)
  await panel.getByRole('button',{name:'Save reviewed bibliography',exact:true}).click()
  await expect(panel.getByRole('region',{name:'Review bibliography file'})).toHaveCount(0)
  await panel.getByLabel('Import a .bib file',{exact:true}).setInputFiles({name:'new.bib',mimeType:'text/plain',buffer:Buffer.from('@article{different, title={Do not overwrite}}')})
  await panel.getByRole('button',{name:'Save reviewed bibliography',exact:true}).click()
  await expect(panel.getByRole('alert')).toContainText('Destination already exists')
  await panel.getByRole('button',{name:'Cancel file import',exact:true}).click()
  await panel.getByRole('button',{name:'Create literature note',exact:true}).click()
  await expect(panel.getByRole('status')).toContainText('Created a literature note')
  const saved=(await calls(page,'vault_save_note')).find(row=>String(row.payload.path).includes('Literature'))
  expect(saved?.payload.expectedContentHash).toBe('<missing>');expect(saved?.payload.expectedVaultId).toBe('screenshot-vault')
  expect(saved?.payload.markdown).toContain('[@smith2024]');expect(saved?.payload.markdown).toContain('Methods for careful research.')
})

test('capture extraction failures remain actionable without writing a note',async({page})=>{
  await page.addInitScript(()=>sessionStorage.setItem('e2e:capture-failure','1'))
  await openResearch(page,'Capture reviewer')
  await page.getByLabel('Article URL',{exact:true}).fill('https://example.org/article')
  await page.getByRole('button',{name:'Extract preview',exact:true}).click()
  await expect(page.getByRole('region',{name:'Capture reviewer',exact:true}).getByRole('alert')).toContainText('Article extraction unavailable')
  await expect(page.getByRole('button',{name:'Extract preview',exact:true})).toBeEnabled()
  expect(await calls(page,'vault_save_asset')).toHaveLength(0)
})

test('research panels fit narrow viewports and remain reachable at 200 percent zoom',async({page},testInfo)=>{
  await openResearch(page,'Capture reviewer')
  await page.getByLabel('Article URL',{exact:true}).fill('https://example.org/article')
  await page.getByRole('button',{name:'Extract preview',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'Reviewed Markdown',exact:true})).toBeVisible()
  for(const width of [1440,1024,768,375,320]){
    await page.setViewportSize({width,height:900})
    const panel=page.getByRole('region',{name:'Capture reviewer',exact:true})
    expect(await panel.evaluate(element=>getComputedStyle(element).backgroundColor)).not.toMatch(/rgba\([^)]*,\s*0(?:\.|\))/)
    const geometry=await panel.evaluate(element=>({left:element.getBoundingClientRect().left,right:element.getBoundingClientRect().right,scrollWidth:element.scrollWidth,clientWidth:element.clientWidth}))
    expect(geometry.left).toBeGreaterThanOrEqual(0);expect(geometry.right).toBeLessThanOrEqual(width);expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.clientWidth+1)
    await panel.getByRole('button',{name:'Save reviewed capture as a new note',exact:true}).scrollIntoViewIfNeeded()
    await expect(panel.getByRole('button',{name:'Save reviewed capture as a new note',exact:true})).toBeInViewport()
    if(width===1440||width===320)await panel.screenshot({path:testInfo.outputPath(`capture-${width}.png`)})
  }
  await page.setViewportSize({width:768,height:900});await page.locator('html').evaluate(element=>element.style.zoom='2')
  const capturePanel = page.getByRole('region',{name:'Capture reviewer',exact:true})
  await (await workspacePanelCloseButton(page, capturePanel)).scrollIntoViewIfNeeded()
  await closeWorkspacePanel(page, capturePanel)
  await expect(page.getByRole('region',{name:'Capture reviewer',exact:true})).toHaveCount(0)
  await page.locator('html').evaluate(element=>element.style.zoom='1')
  for(const surface of [{command:'Database studio',name:'Database Studio',close:'Close database studio'},{command:'Browse bibliography',name:'Bibliography',close:'Close bibliography'}]){
    await openCommandPalette(page);await runCommand(page,surface.command)
    const panel=page.getByRole(surface.name === 'Bibliography' ? 'dialog' : 'region',{name:surface.name,exact:true})
    expect(await panel.evaluate(element=>getComputedStyle(element).backgroundColor)).not.toMatch(/rgba\([^)]*,\s*0(?:\.|\))/)
    for(const width of [1440,1024,768,375,320]){
      await page.setViewportSize({width,height:900})
      const geometry=await panel.evaluate(element=>({left:element.getBoundingClientRect().left,right:element.getBoundingClientRect().right,scrollWidth:element.scrollWidth,clientWidth:element.clientWidth}))
      expect(geometry.left).toBeGreaterThanOrEqual(0);expect(geometry.right).toBeLessThanOrEqual(width);expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.clientWidth+1)
      await (await workspacePanelCloseButton(page, panel)).scrollIntoViewIfNeeded()
      await expect((await workspacePanelCloseButton(page, panel))).toBeInViewport()
      if(width===1440||width===320)await panel.screenshot({path:testInfo.outputPath(`${surface.name.toLowerCase().replace(/ /g,'-')}-${width}.png`)})
    }
    await page.setViewportSize({width:768,height:900});await page.locator('html').evaluate(element=>element.style.zoom='2')
    await (await workspacePanelCloseButton(page, panel)).scrollIntoViewIfNeeded()
    await (await workspacePanelCloseButton(page, panel)).click()
    await expect(panel).toHaveCount(0)
    await page.locator('html').evaluate(element=>element.style.zoom='1')
  }
})
