import { expect, test } from '@playwright/test'
import { launchApp, openCommandPalette, runCommand, settleLayout, waitForWorkspace } from './helpers'

async function customize(page: import('@playwright/test').Page) {
  await openCommandPalette(page)
  await runCommand(page, 'Customize workspace shortcuts')
  const dialog = page.getByRole('dialog', { name: 'Customize workspace shortcuts', exact: true })
  await expect(dialog).toBeVisible()
  return dialog
}

test('workspace shortcuts keep compact defaults and persist custom names, dimensions, ordering and overflow placement', async ({ page }, testInfo) => {
  await launchApp(page)
  await waitForWorkspace(page)
  const bar = page.locator('.workspace-activity-bar')
  await expect(bar.getByRole('button', { name: 'Database studio', exact: true })).toHaveCount(0)
  const writing = bar.getByRole('button', { name: 'Writing', exact: true })
  await expect(writing).toBeVisible()
  expect((await writing.boundingBox())!.height).toBeLessThanOrEqual(36)

  const dialog = await customize(page)
  const source = dialog.locator('[data-shortcut-id="source"]')
  await source.getByLabel('Button name', { exact: true }).fill('Code')
  await source.getByLabel('Width', { exact: true }).fill('160')
  await source.getByLabel('Text size', { exact: true }).fill('14')
  await source.getByRole('button', { name: 'Move up', exact: true }).click()
  await expect(source.getByLabel('Button name', { exact: true })).toBeFocused()
  const runtime = dialog.locator('[data-shortcut-id="open-runtime-console"]')
  await runtime.getByLabel('Include shortcut', { exact: true }).check()
  await runtime.getByLabel('Pin to row', { exact: true }).uncheck()
  await runtime.getByLabel('Button name', { exact: true }).fill('Run code')
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(bar.getByRole('button').first()).toHaveText('Code')
  const code = bar.getByRole('button', { name: 'Code', exact: true })
  expect((await code.boundingBox())!.width).toBeCloseTo(160, 0)
  expect(await code.evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize))).toBe(14)
  const more = bar.getByRole('button', { name: 'More workspaces', exact: true })
  await more.focus()
  await more.press('ArrowDown')
  const runCode = page.getByRole('menuitem', { name: 'Run code', exact: true })
  await expect(runCode).toBeFocused()
  await runCode.press('Enter')
  await expect(page.getByRole('region', { name: 'Runtime console', exact: true })).toBeVisible()
  await page.reload()
  await waitForWorkspace(page)
  await expect(bar.getByRole('button', { name: 'Code', exact: true })).toBeVisible()
  const removed = await customize(page)
  await removed.locator('[data-shortcut-id="source"]').getByLabel('Include shortcut', { exact: true }).uncheck()
  await removed.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(bar.getByRole('button', { name: 'Code', exact: true })).toHaveCount(0)
  const added = await customize(page)
  const addedSource = added.locator('[data-shortcut-id="source"]')
  await addedSource.getByLabel('Include shortcut', { exact: true }).check()
  await addedSource.getByLabel('Pin to row', { exact: true }).uncheck()
  await added.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(bar.getByRole('button', { name: 'Code', exact: true })).toHaveCount(0)
  await more.click()
  await expect(page.getByRole('menuitem', { name: 'Code', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await settleLayout(page)
  await testInfo.attach('custom-workspace-shortcuts', { body: await page.screenshot({ animations: 'disabled' }), contentType: 'image/png' })
})

test('a hidden workspace shortcut row stays hidden and can be restored through the palette without losing routes', async ({ page }) => {
  await launchApp(page)
  await page.locator('.workspace-activity-bar').getByRole('button', { name: 'Customize workspace shortcuts', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Customize workspace shortcuts', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Show workspace shortcut row', { exact: true }).uncheck()
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('.workspace-activity-bar')).toHaveCount(0)
  await expect(page.locator('button.command-search')).toBeFocused()
  await page.reload()
  await waitForWorkspace(page)
  await expect(page.locator('.workspace-activity-bar')).toHaveCount(0)
  const restored = await customize(page)
  await restored.getByRole('button', { name: 'Reset defaults', exact: true }).click()
  await restored.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('.workspace-activity-bar').getByRole('button', { name: 'Writing', exact: true })).toBeVisible()
})

test('workspace shortcut customization cancels drafts and keeps fields reachable under narrow restored zoom', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 768, height: 900 })
  await page.addInitScript(() => localStorage.setItem('scriptor:ui-zoom', '2'))
  await launchApp(page)
  await waitForWorkspace(page, { allowHiddenVaultList: true })
  const dialog = await customize(page)
  const writing = dialog.locator('[data-shortcut-id="writing"]')
  await writing.getByLabel('Button name', { exact: true }).fill('Discarded name')
  const lastId = await dialog.locator('[data-shortcut-id]').last().getAttribute('data-shortcut-id')
  const lastEntry = dialog.locator(`[data-shortcut-id="${lastId}"]`)
  await lastEntry.getByRole('button', { name: 'Move up', exact: true }).click()
  await lastEntry.getByRole('button', { name: 'Move down', exact: true }).click()
  await expect(lastEntry.getByLabel('Button name', { exact: true })).toBeFocused()
  const last = dialog.locator('[data-shortcut-id]').last().getByLabel('Text size', { exact: true })
  await last.scrollIntoViewIfNeeded()
  await expect(last).toBeInViewport({ ratio: 1 })
  expect(await dialog.evaluate(element => {
    const box = element.getBoundingClientRect()
    return Math.max(0, -box.left, -box.top, box.right - innerWidth, box.bottom - innerHeight)
  })).toBeLessThanOrEqual(1)
  const cancel = dialog.getByRole('button', { name: 'Cancel', exact: true })
  await cancel.scrollIntoViewIfNeeded()
  await expect(cancel).toBeInViewport({ ratio: 1 })
  await testInfo.attach('workspace-shortcuts-zoom', { body: await page.screenshot({ animations: 'disabled' }), contentType: 'image/png' })
  await cancel.click()
  const reopened = await customize(page)
  await expect(reopened.locator('[data-shortcut-id="writing"]').getByLabel('Button name', { exact: true })).toHaveValue('')
  await page.keyboard.press('Escape')
  await expect(reopened).toBeHidden()
})

test('workspace shortcut customization reports failed storage without silently claiming to save', async ({ page }) => {
  await launchApp(page)
  const dialog = await customize(page)
  await dialog.getByLabel('Show workspace shortcut row', { exact: true }).uncheck()
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key: string, value: string) {
      if (key === 'scriptor:workspace-shortcuts:v1') throw new DOMException('Storage denied', 'SecurityError')
      return original.call(this, key, value)
    }
  })
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.locator('.workspace-activity-bar')).toBeVisible()
})
