import { CALCULATION_OPERATORS } from '../../lib/databaseStudio'
import type { CalculationOperator, DatabaseView } from '../../lib/databaseStudio'
interface Props {view:DatabaseView;onChange:(view:DatabaseView)=>void;busy:boolean}
export function DatabaseStudioBuilder({view,onChange,busy}:Props) {
  const update = (patch:Partial<DatabaseView>) => onChange({...view,...patch})
  return <fieldset disabled={busy} className="database-builder"><legend>View definition</legend>
    <label>View name<input value={view.label} maxLength={128} onChange={(event)=>update({label:event.target.value})}/></label>
    <label>Layout<select value={view.mode} onChange={(event)=>update({mode:event.target.value as DatabaseView['mode']})}>{['table','list','gallery'].map(mode=><option key={mode}>{mode}</option>)}</select></label>
    <label>Match<select value={view.combine} onChange={(event)=>update({combine:event.target.value as DatabaseView['combine']})}><option value="all">All filters</option><option value="any">Any filter</option></select></label>
    {view.filters.map((filter,index)=><div className="database-builder-row" key={index}><label>Filter field<select value={filter.field} onChange={(event)=>update({filters:view.filters.map((item,i)=>i===index?{...item,field:event.target.value as typeof filter.field,...(event.target.value==='metadata'?{key:'status'}:{})}:item)})}>{['title','tag','path','days','metadata'].map(field=><option key={field}>{field}</option>)}</select></label>{filter.field==='metadata'?<label>YAML field<input value={filter.key??'status'} placeholder="status or priority" maxLength={64} onChange={event=>update({filters:view.filters.map((item,i)=>i===index?{...item,key:event.target.value}:item)})}/></label>:null}<label>{filter.field==='metadata'?'Equals':'Filter value'}<input value={filter.value} maxLength={256} onChange={(event)=>update({filters:view.filters.map((item,i)=>i===index?{...item,value:event.target.value}:item)})}/></label><button type="button" aria-label={`Remove filter ${index+1}`} onClick={()=>update({filters:view.filters.filter((_,i)=>i!==index)})}>Remove</button></div>)}
    <button type="button" disabled={view.filters.length>=10} onClick={()=>update({filters:[...view.filters,{field:'title',value:''}]})}>Add filter</button>
    <p>Columns project scalar YAML fields. Calculations use field names and never execute code.</p>
    {view.columns.map((column,index)=><div className="database-builder-row" key={index}><label>Field<input value={column.key} maxLength={64} onChange={(event)=>update({columns:view.columns.map((item,i)=>i===index?{...item,key:event.target.value}:item)})}/></label><label>Heading<input value={column.label} maxLength={64} onChange={(event)=>update({columns:view.columns.map((item,i)=>i===index?{...item,label:event.target.value}:item)})}/></label><label>Calculation<select value={column.formula?.op ?? ''} onChange={(event)=>{const op=event.target.value as CalculationOperator;update({columns:view.columns.map((item,i)=>i===index?{key:item.key,label:item.label,...(op?{formula:{op,fields:['lower','upper','length'].includes(op)?[item.key]:[item.key,'score']}}:{})}:item)})}}><option value="">Source field</option>{CALCULATION_OPERATORS.map(op=><option key={op}>{op}</option>)}</select></label>{column.formula?.fields.map((field,fieldIndex)=><label key={fieldIndex}>Operand {fieldIndex+1}<input value={field} onChange={(event)=>update({columns:view.columns.map((item,i)=>i===index&&item.formula?{...item,formula:{...item.formula,fields:item.formula.fields.map((value,j)=>j===fieldIndex?event.target.value:value)}}:item)})}/></label>)}<button type="button" aria-label={`Remove column ${index+1}`} onClick={()=>update({columns:view.columns.filter((_,i)=>i!==index)})}>Remove</button></div>)}
    <button type="button" disabled={view.columns.length>=12} onClick={()=>update({columns:[...view.columns,{key:`field${view.columns.length+1}`,label:'New field'}]})}>Add column</button>
  </fieldset>
}
