// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteSummary = { path: string, title: string, };

export type RpcEvent = { payload: RpcEventPayload, };

export type RpcEventPayload = { "ConfigReloaded": { json: string, generation: bigint, } };

export type RpcPayload = { "Pong": { version: string, } } | { "VaultOpened": { vault_id: string, name: string, root_path: string, } } | { "NoteList": { notes: Array<NoteSummary>, } } | { "SearchHits": { hits: Array<SearchHit>, } } | { "NoteDocument": { path: string, title: string, markdown: string, } } | { "RebuildSummary": { indexed_notes: number, skipped_notes: number, links_written: number, } } | { "HealthReport": { json: string, } } | { "HealthDiagnostics": { json: string, } } | { "GitStatus": { json: string, } } | { "Backlinks": { path: string, json: string, } } | { "GraphSummary": { json: string, } } | { "NoteSaved": { json: string, } } | { "RenameApplied": { json: string, } } | { "ExportResult": { json: string, } } | { "ExportStarted": { job_id: string, } } | { "ExportJobStatus": { json: string, } } | { "IndexRebuildStatus": { json: string, } } | { "ConfigReloaded": { json: string, generation: bigint, } } | "Unit" | { "Json": { json: string, } };

export type RpcResponse = { id: bigint, result: RpcResult, };

export type RpcResult = { "Ok": RpcPayload } | { "Err": string };

export type SearchHit = { path: string, title: string, snippet: string, };

/**
 * Server → client frame: either an RPC response or an unsolicited event.
 */
export type ServerMessage = { "Response": RpcResponse } | { "Event": RpcEvent };
