// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteSummary = { path: string, title: string, };

export type RpcError = { "PluginDisabled": { capability_id: string, } };

export type RpcEvent = { payload: RpcEventPayload, };

export type RpcEventPayload = { "ConfigReloaded": { json: string, generation: bigint, } } | { "ResyncRequired": { reason: string, } };

export type RpcMethod = "Ping" | { "OpenVault": { path: string, } } | "ListNotes" | { "SearchNotes": { query: string, limit: number, } } | { "ReadNote": { path: string, } } | "RebuildIndex" | "HealthReport" | "HealthDiagnostics" | "GitStatus" | { "Backlinks": { path: string, } } | { "GraphSummary": { path: string | null, depth: number, } } | "ReloadConfig" | { "SaveNote": { path: string, markdown: string, expected_content_hash: string | null, dry_run: boolean, } } | { "UpdateNoteIndex": { path: string, } } | { "RenameNoteApply": { from_path: string, to_path: string, update_links: boolean, } } | { "ExportRunNote": { note_path: string, format: string, dry_run: boolean, extra_pandoc_args: Array<string>, output_subdirectory: string | null, } } | { "ExportRunMarkdown": { note_path: string, source_markdown: string, format: string, dry_run: boolean, extra_pandoc_args: Array<string>, output_subdirectory: string | null, } } | { "ExportStartNote": { note_path: string, format: string, dry_run: boolean, extra_pandoc_args: Array<string>, output_subdirectory: string | null, } } | { "ExportStartMarkdown": { note_path: string, source_markdown: string, format: string, dry_run: boolean, extra_pandoc_args: Array<string>, output_subdirectory: string | null, } } | "ExportJobStatus" | { "ExportCancel": { job_id: string | null, } } | "IndexRebuildStatus" | "SubscribeEvents" | { "Invoke": { command: string, payload_json: string, } } | "ListCommands";

export type RpcPayload = { "Pong": { version: string, } } | { "VaultOpened": { vault_id: string, name: string, root_path: string, } } | { "NoteList": { notes: Array<NoteSummary>, } } | { "SearchHits": { hits: Array<SearchHit>, } } | { "NoteDocument": { path: string, title: string, markdown: string, } } | { "RebuildSummary": { indexed_notes: number, skipped_notes: number, links_written: number, } } | { "HealthReport": { json: string, } } | { "HealthDiagnostics": { json: string, } } | { "GitStatus": { json: string, } } | { "Backlinks": { path: string, json: string, } } | { "GraphSummary": { json: string, } } | { "NoteSaved": { json: string, } } | { "RenameApplied": { json: string, } } | { "ExportResult": { json: string, } } | { "ExportStarted": { job_id: string, } } | { "ExportJobStatus": { json: string, } } | { "IndexRebuildStatus": { json: string, } } | { "ConfigReloaded": { json: string, generation: bigint, } } | "Unit" | { "Json": { json: string, } };

export type RpcRequest = { id: bigint, method: RpcMethod, endpoint_nonce?: string, };

export type RpcResponse = { id: bigint, result: RpcResult, };

export type RpcResult = { "Ok": RpcPayload } | { "Error": RpcError } | { "Err": string };

export type SearchHit = { path: string, title: string, snippet: string, };

/**
 * Server → client frame: either an RPC response or an unsolicited event.
 */
export type ServerMessage = { "Response": RpcResponse } | { "Event": RpcEvent };
