// GENERATED from contracts/operations.json. Do not edit by hand.
/// Daemon RPC operation names and their allowed boundary outcomes.
pub const RPC_OPERATION_CATALOG: &[(&str, &[&str])] = &[
    ("Backlinks", &["value", "absent-optional", "degraded", "failed"]),
    ("ExportCancel", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("ExportJobStatus", &["value", "absent-optional", "degraded", "failed"]),
    ("ExportRunMarkdown", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("ExportRunNote", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("ExportStartMarkdown", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("ExportStartNote", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("GitStatus", &["value", "absent-optional", "degraded", "failed"]),
    ("GraphSummary", &["value", "absent-optional", "degraded", "failed"]),
    ("HealthDiagnostics", &["value", "absent-optional", "degraded", "failed"]),
    ("HealthReport", &["value", "absent-optional", "degraded", "failed"]),
    ("IndexRebuildStatus", &["value", "absent-optional", "degraded", "failed"]),
    ("Invoke", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("ListCommands", &["value", "absent-optional", "degraded", "failed"]),
    ("ListNotes", &["value", "absent-optional", "degraded", "failed"]),
    ("OpenVault", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("Ping", &["value", "absent-optional", "degraded", "failed"]),
    ("ReadNote", &["value", "absent-optional", "degraded", "failed"]),
    ("RebuildIndex", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("ReloadConfig", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("RenameNoteApply", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("SaveNote", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("SearchNotes", &["value", "absent-optional", "degraded", "failed"]),
    ("SubscribeEvents", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
    ("UpdateNoteIndex", &["value", "absent-optional", "invalid", "degraded", "failed", "recovered"]),
];
