import type { HelpGuide } from './types.ts'

export const writingGuides: readonly HelpGuide[] = [
  {
    id: 'workspace', title: 'Workspace essentials', category: 'Workspace', policy: 'first-run',
    entry: 'First launch, Help & guides, or F1.', prerequisite: 'No vault or external account is needed to read this introduction.',
    safety: 'Tours explain controls. They never create, send, execute, delete, or publish anything for you.', source: 'src/components/OnboardingTour.tsx', roots: ['.app-shell'],
    steps: [
      ['Your vault', 'Scriptor works with a folder of Markdown notes. Open Vault chooses a folder; an open vault appears in the left sidebar. Keep important work backed up independently.', '.vault-panel'],
      ['Search notes', 'Use the sidebar search to find note content. F focuses search when you are not typing. Searching does not change your files.', '.vault-search'],
      ['Command palette', 'Use the command field, or Ctrl+K on Windows/Linux and Command+K on macOS. Search a command or a note, navigate with arrows, then press Enter.', '.command-search'],
      ['Inspector rail', 'The right rail contains structure, links, references, rendered output, and plugin tools. Collapse it to give the document more room.', '.inspector-panel'],
      ['Editor tools', 'Source exposes Markdown syntax; Split keeps Source and the writable visual preview side by side; Preview is a writable visual Markdown surface. Rendered output in the Inspector remains the final read-only fidelity check. Typography, Insert, and Tools group less-frequent commands.', '.editor-toolbar'],
      ['Saving and recovery', 'Watch save/error status before closing or switching work. Note history, conflicts, snapshots, and external backups solve different recovery problems; do not treat an index as a backup.', '.status-strip'],
      ['Help without extra chrome', 'Press F1 inside a feature for contextual guidance, or Shift+F1 to start its walkthrough directly. Complex optional surfaces can offer one dismissible first-open orientation after onboarding; every tour still starts only when you choose it.', 'header.topbar'],
    ],
    questions: [['Does a tour operate the app for me?', 'No. Next acknowledges a reading step, not a successful operation. Show this control only reveals or focuses an already-visible control.'], ['Can I skip and return?', 'Yes. Skip the initial introduction; use F1 or Help & guides later. Individual tour progress is stored locally and is independent of your notes.']], related: ['vault', 'editor', 'recovery', 'docks'],
  },
  {
    id: 'vault', title: 'Vault navigation and files', category: 'Workspace', policy: 'manual', entry: 'Open Vault in the top bar; vault sidebar.',
    prerequisite: 'Select the intended local folder and wait for indexing.', safety: 'Files on disk are authoritative. Opening a different vault changes the scope of subsequent commands.', source: 'src/components/app/VaultSidebar.tsx', roots: ['.vault-panel'],
    steps: [['Choose the scope', 'Check the vault name and folder before importing or editing. Open Vault is different from opening a note tab.', '.vault-header'], ['Navigate', 'Expand folders, select a Markdown note, and use recent notes or history arrows to return. Collapsing a folder does not remove it.', '.vault-tree'], ['Create intentionally', 'Use New note or New from template. Review the destination and filename; do not assume repeated names create a separate copy.'], ['Maintain the index', 'Use Rebuild index only when search or links are stale. It rebuilds derived knowledge, not lost document content.']],
    questions: [['Where did my note go?', 'Clear search and Inbox filters, expand its folder, and confirm the active vault. Then inspect the actual folder on disk.'], ['Is an empty sidebar a lost vault?', 'Not necessarily. Loading, filters, permission failures, and an empty folder are different states. Inspect status before attempting recovery.']], related: ['search', 'inbox', 'templates', 'recovery'],
  },
  {
    id: 'inbox', title: 'Inbox and organized notes', category: 'Writing', policy: 'manual', entry: 'Inbox in the vault sidebar.', prerequisite: 'Open a vault containing notes.',
    safety: 'Mark organized changes note metadata. It is not deletion, archiving in Gmail, or a backup.', source: 'src/components/inbox/InboxPanel.tsx', roots: ['.inbox-panel'],
    steps: [['Understand the filter', 'Inbox shows notes not yet marked organized. A clear inbox does not mean your vault contains no notes.'], ['Read before triage', 'Open an item and decide where it belongs, which links it needs, and whether its title communicates the subject.'], ['Organize', 'Use Mark organized after reviewing the note. This updates its organized marker; it does not move the file into another folder.'], ['Find it again', 'Switch to All notes or search. Inspect frontmatter when the organized state is unexpected.']],
    questions: [['Why did an item disappear?', 'The Inbox filter excludes organized notes. Find the same file through All notes.'], ['Does organized mean publishable?', 'No. Organization, vault health, export readiness, and publish eligibility are separate checks.']], related: ['vault', 'frontmatter', 'knowledge-repair'],
  },
  {
    id: 'search', title: 'Search and result navigation', category: 'Workspace', policy: 'manual', entry: 'Sidebar Search notes and the search-results dock.', prerequisite: 'Open and index a vault.',
    safety: 'Search is read-only; results are limited to the active vault and the selected search mode.', source: 'src/hooks/useSearchStore.ts', roots: ['.search-results', '.vault-search'],
    steps: [['Choose a query', 'Start with a distinctive word from the title or body. Clear filters when testing whether the index contains a note.'], ['Inspect matches', 'Use the result title and path together; duplicate titles can refer to different files. Open the intended result.'], ['Distinguish modes', 'Keyword search is the default. Semantic search requires separately configured experimental embedding support; it is not automatically available.'], ['Recover stale results', 'Check index status, allow ongoing indexing to finish, and rebuild only when needed. A search error is not a confirmed absence of matching files.']],
    questions: [['Why is a known note missing?', 'Check active vault, indexing state, search text and filters, then compare with the file on disk.'], ['Does Help search my private notes?', 'No. Help search only searches bundled guide text and questions. It does not submit a query to a model or provider.']], related: ['commands', 'status', 'diagnostics'],
  },
  {
    id: 'commands', title: 'Command palette and keyboard navigation', category: 'Workspace', policy: 'manual', entry: 'Top command field; Ctrl+K / Command+K.', prerequisite: 'Some commands require an open note, vault, or enabled capability.',
    safety: 'Opening the palette is read-only. Running a command can launch a separate confirmation or mutation workflow.', source: 'src/components/CommandPalette.tsx', roots: ['.command-palette'],
    steps: [['Find an action', 'Type the action or subject. Read the command category to distinguish an action from a note search result.'], ['Choose with the keyboard', 'Arrow keys move the active result; Enter invokes it; Escape closes the palette. Note-search results may arrive after command matches.'], ['Use contextual availability', 'A missing or disabled command may need a vault, active note, native desktop support, or plugin permission. Do not bypass a capability check.'], ['Find guidance', 'Search Help, guide, FAQ, or tour to open Help & guides. F1 targets the panel currently containing focus.']],
    questions: [['Why does an action open settings instead?', 'An unconfigured capability may route to its setup or permission-review surface instead of failing silently.'], ['Can I change shortcuts?', 'Use Settings > Shortcuts. Resolve conflicts and test the binding outside a text field before relying on it.']], related: ['shortcuts', 'plugins', 'workspace'],
  },
  {
    id: 'tabs', title: 'Document tabs and navigation history', category: 'Workspace', policy: 'manual', entry: 'Document tab row above the editor.', prerequisite: 'Open one or more notes.',
    safety: 'Closing a tab is not deleting a file. Resolve unsaved errors before closing the application.', source: 'src/components/shell/EditorWorkspace.tsx', roots: ['.editor-tabs', '.tab-strip'],
    steps: [['Select the document', 'Check the active tab and path before typing, renaming, exporting, or resolving a conflict.'], ['Keep important notes', 'Use available pin controls to retain frequently used tabs. A pinned tab does not protect the file from external changes.'], ['Move through history', 'Back/forward navigation revisits previously opened notes. Use recent notes when a tab is no longer open.'], ['Close safely', 'Observe dirty/save status. Close tab removes a view; a save error needs retry or an explicit recovery decision.']],
    questions: [['Why do two tabs have the same title?', 'Different folders can contain identical filenames. Use paths to disambiguate.'], ['Will my session return?', 'Workspace session restoration is best-effort. Files and verified backups remain the recovery authority.']], related: ['editor', 'history', 'recovery'],
  },
  {
    id: 'editor', title: 'Write, save, and switch editor views', category: 'Writing', policy: 'manual', entry: 'Central editor; Source / Split / Preview.', prerequisite: 'Open a Markdown note. CodeMirror is the default; Monaco is an advanced option.',
    safety: 'Typing changes the document. Previewing and reading this guide do not authorize execution of embedded code.', source: 'src/components/shell/EditorWorkspace.tsx', roots: ['.editor-panel'],
    steps: [['Start in Source', 'Place the caret where you intend to edit. Use undo/redo for local editing and watch save status after a change.', '.editor-container'], ['Edit visually when useful', 'Choose Split to keep Source and the writable visual preview together, or Preview to edit visually without the source pane. Both edit the same Markdown draft; syntax markers reappear on the active line when you need to correct Markdown.', '.editor-view-modes'], ['Check final rendering', 'Use Inspector > Rendered output when you need the read-only renderer result, including diagrams and renderer extensions.'], ['Insert deliberately', 'Select text for inline formatting; put the caret on a separate line for block content. Check the resulting Markdown after using a snippet.'], ['Handle a failed save', 'Do not assume text is on disk because it is visible. Read the error, keep a safe copy if needed, and use retry/conflict recovery before leaving.']],
    questions: [['Why is the editor dim?', 'Focus/distraction mode can dim supporting chrome. Exit through Tools or the configured shortcut; a genuine modal also temporarily prevents background interaction.'], ['Does changing editor engine change the file format?', 'No. Markdown remains the file format. Engine-specific features may differ; do not expect every extension in Monaco.']], related: ['toolbar', 'preview', 'focus', 'history'],
  },
  {
    id: 'toolbar', title: 'Formatting, Typography, Insert, and Tools', category: 'Writing', policy: 'manual', entry: 'Editor command row.', prerequisite: 'Open a note for editing commands.',
    safety: 'Formatting and insertion act on the current selection/caret. Preferences in Tools affect editing behavior.', source: 'src/components/editor/EditorFormatToolbar.tsx', roots: ['.editor-toolbar', '.toolbar-tools-menu', '.typography-menu-popover', '.insert-menu-popover'],
    steps: [['Use frequent actions', 'Bold, italic, and links stay near the writing surface. Select text first when you want to wrap existing content.'], ['Choose a group', 'Typography transforms writing conventions; Insert adds structures; Tools groups review, view, and advanced editor controls.'], ['Read toggle state', 'Focus, spellcheck, editor theme, and engine settings are preferences, not document formatting. A disabled control can be engine-specific.'], ['Adapt to width', 'Compact controls retain labels for assistive technology. Customize only the actions you frequently need rather than pinning the entire catalog.']],
    questions: [['Why did a command affect the wrong text?', 'It acts on the active document and caret/selection. Undo, restore the selection, and retry.'], ['Does Insert AI summary call a model?', 'The insertion creates a Markdown AI callout template. Actual provider requests belong to the separate opt-in AI workflow.']], related: ['toolbar-customize', 'snippets', 'ai'],
  },
  {
    id: 'toolbar-customize', title: 'Customize the editor toolbar', category: 'Writing', policy: 'manual', entry: 'Editor Tools > Customize toolbar, or its sliders button.', prerequisite: 'No external connection is needed.',
    safety: 'Edits are staged until Apply. Cancel leaves the live toolbar unchanged. Preferences are local, not note content.', source: 'src/components/editor/CustomizableToolbar.tsx', roots: ['.toolbar-customizer'],
    steps: [['Pin by frequency', 'Select only actions you need often; unpinned commands remain in Tools. Start with a small writing-focused set.'], ['Order the controls', 'Use Move earlier/later. The position moves the action, not the current document section.'], ['Choose automatic widths', 'Leave width on Auto for text menus. Set a pixel width only when needed and verify compact-window and translated labels.'], ['Apply or cancel', 'Apply persists your draft preferences. Cancel discards them. Reset inside the customizer is staged until Apply; inspect any storage warning.']],
    questions: [['Will a reset erase my notes?', 'No. Toolbar reset only changes toolbar preferences.'], ['Why did customization not survive restart?', 'Browser/webview storage may be blocked or full. Read the warning and retry after resolving storage access.']], related: ['toolbar', 'appearance', 'shortcuts'],
  },
  {
    id: 'preview', title: 'Rendered output, diagrams, and embedded content', category: 'Writing', policy: 'manual', entry: 'Split/Preview in the editor or Rendered output in the inspector.', prerequisite: 'A Markdown note; some renderers need separately configured capabilities.',
    safety: 'Reading preview does not approve network requests or code execution. External rendering may require explicit setup.', source: 'packages/renderer/src/MarkdownPreview.tsx', roots: ['.markdown-preview', '.preview-pane', '.rendered-preview'],
    steps: [['Check Markdown structure', 'Headings, lists, tables, and callouts depend on source syntax. Fix malformed source instead of treating preview text as another editable copy.'], ['Keep metadata separate', 'A leading frontmatter block describes the note and should not be prose. Inspect delimiters when metadata appears in the document.'], ['Read renderer feedback', 'Diagram placeholders and errors can indicate syntax, dependency, capability, or timeout problems. Basic document content should remain readable.'], ['Compare export separately', 'Preview and exported output may use different engines. Use export preflight and inspect the generated file before sharing.']],
    questions: [['Why is my diagram not rendered?', 'Check fence language and syntax first, then its dependency/capability and visible error. Do not enable external execution merely to dismiss an error.'], ['Why does a callout show raw markers?', 'Check blank lines and block boundaries, particularly after repeated insertion. An adjacent second marker can become literal text.']], related: ['frontmatter', 'code-chunks', 'export'],
  },
  {
    id: 'frontmatter', title: 'Frontmatter and note metadata', category: 'Writing', policy: 'manual', entry: 'Editor Tools > Frontmatter; metadata controls.', prerequisite: 'An active note.',
    safety: 'Metadata can change organization, publishing eligibility, or automation behavior. Review values before saving.', source: 'src/lib/frontmatter.ts', roots: ['.frontmatter-panel', '.frontmatter-editor'],
    steps: [['Locate the block', 'Frontmatter belongs at the beginning of the note between its supported delimiters. Do not insert another block halfway through prose.'], ['Use valid values', 'Check YAML syntax, indentation, quoting, and expected field types. A visible delimiter alone does not prove the metadata is valid.'], ['Review special fields', 'Organization and publish fields drive separate workflows. Setting publish eligibility is not itself an export or deployment.'], ['Confirm and recover', 'Preview the note and check health warnings. Use undo or note history when a metadata edit gives an unexpected result.']],
    questions: [['Should I remove _organized because it is internal?', 'Not automatically. It records organization state. Repair rendering or malformed delimiters rather than deleting useful metadata blindly.'], ['Does publish: true upload my note?', 'No. It makes the note a candidate for a separate reviewed publishing workflow.']], related: ['inbox', 'publish', 'knowledge-repair'],
  },
  {
    id: 'daily', title: 'Daily notes and date navigation', category: 'Writing', policy: 'manual', entry: 'Today and previous/next day controls in the sidebar.', prerequisite: 'Open a vault; review its daily-note folder and filename template.',
    safety: 'Opening a missing day can create a note. Check configured paths and dates before creation.', source: 'src/hooks/useWorkspaceNoteFactory.ts', roots: ['.daily-note-controls', '.daily-note-nav'],
    steps: [['Review the date', 'Today uses the local date. Previous/next day moves the requested daily-note date, not document edit history.'], ['Check configuration', 'Settings controls the daily-note folder, filename pattern, and template. Verify the destination before applying changes.'], ['Open or create', 'Choose the day; existing content should be opened rather than replaced. Resolve filename/path errors instead of retrying blindly.'], ['Link the entry', 'Use ordinary Markdown links or wikilinks to connect daily work to project notes. Daily notes remain portable files.']],
    questions: [['Why did the daily note appear in another folder?', 'The vault daily-note configuration determines its path.'], ['Can a daily template overwrite an existing day?', 'Treat a collision as an open/review situation; never assume a template action is safe replacement.']], related: ['templates', 'vault', 'settings'],
  },
  {
    id: 'templates', title: 'Create notes from templates', category: 'Writing', policy: 'manual', entry: 'New from template or the template picker.', prerequisite: 'Open a vault with available templates.',
    safety: 'Creating a note writes a new file. Inspect destination/name and avoid overwriting an existing note.', source: 'src/components/TemplatePicker.tsx', roots: ['.template-picker', '.template-picker-dialog'],
    steps: [['Choose a starting structure', 'Read the template name and purpose. Use a blank note when no template matches the job.'], ['Review the destination', 'Check title, folder, and generated filename. A template is a starting point, not a separate document format.'], ['Inspect generated content', 'Replace placeholders, check dates and frontmatter, and remove sections that do not apply.'], ['Maintain the template', 'Change the template source for future notes. Existing notes do not automatically inherit later template edits.']],
    questions: [['Why did old notes not change?', 'Templates generate initial content; they are not live linked documents.'], ['Where can I repair missing placeholders?', 'Edit the created Markdown directly, then correct the template for subsequent notes.']], related: ['daily', 'snippets', 'frontmatter'],
  },
  {
    id: 'snippets', title: 'Snippet catalog and reusable blocks', category: 'Writing', policy: 'manual', entry: 'Manage snippets from the palette or vault menu.', prerequisite: 'Open the intended vault and active note for insertion.',
    safety: 'Saving a catalog changes future insertions. Inserting a snippet changes the active note at the caret.', source: 'src/components/SnippetsPanel.tsx', roots: ['.snippets-panel'],
    steps: [['Distinguish catalog and note', 'Editing a saved snippet is different from inserting it. Name snippets by purpose so commands are easy to find.'], ['Preserve syntax', 'Include required block boundaries for tables, callouts, headings, or fences. Inline snippets should not unexpectedly add whole blocks.'], ['Save then insert', 'Save the catalog, return to the correct note, place the caret, and insert. Check source and preview afterward.'], ['Revise safely', 'Changes affect later uses, not previous copies. Deleting a snippet does not remove content already inserted into notes.']],
    questions: [['Why did two snippets run together?', 'The source may lack blank lines between block constructs. Undo and insert on separate lines.'], ['Does a snippet execute its code?', 'Insertion writes text. External execution requires a separate explicit operation and permission.']], related: ['toolbar', 'preview', 'code-chunks'],
  },
  {
    id: 'focus', title: 'Focus, typewriter, spelling, and editor engines', category: 'Writing', policy: 'manual', entry: 'Editor Tools > View or Advanced; editor preferences.', prerequisite: 'An active editor. Some features are CodeMirror-specific.',
    safety: 'These are editing/view preferences, not proofing guarantees. LanguageTool and AI have separate network/setup implications.', source: 'src/hooks/useEditorPreferences.ts', roots: ['.inline-editor-assist'],
    steps: [['Reduce distraction', 'Use Focus to quiet supporting chrome; keep an accessible exit through Tools or your configured shortcut.'], ['Keep a reading position', 'Typewriter mode follows the current line. Turn it off when comparing distant sections or when the movement is distracting.'], ['Use review tools deliberately', 'Spelling and grammar hints need human review. Inspect dictionary/endpoint configuration; unsupported engine features should not be assumed active.'], ['Change engines intentionally', 'CodeMirror is the default. Monaco is advanced and lazy-loaded; Markdown remains the source while available extensions can differ.']],
    questions: [['Why does a toggle have no effect in Monaco?', 'An extension may be implemented only for CodeMirror. Select a supported engine or use an alternative review workflow.'], ['Does a grammar tool keep all text local?', 'That depends on its configured endpoint. Check the integration setting before enabling a network service.']], related: ['editor', 'shortcuts', 'ai'],
  },
  {
    id: 'writing-targets', title: 'Writing targets and document statistics', category: 'Writing', policy: 'manual', entry: 'Writing Targets in Tools or the command palette.', prerequisite: 'Open a note and choose a meaningful target.',
    safety: 'Counts and targets are writing aids, not quality or publication-readiness scores.', source: 'src/components/WritingTargetsPanel.tsx', roots: ['.writing-targets-panel', '.writing-targets'],
    steps: [['Set a useful goal', 'Choose a target appropriate to the document or session rather than accepting an arbitrary number.'], ['Interpret counts', 'Word, character, and reading-time estimates can treat Markdown, code, and metadata differently. Use trends rather than exact cross-tool equivalence.'], ['Review progress', 'Compare actual writing with the target without confusing goal completion with correctness, evidence quality, or successful saving.'], ['Adjust or stop', 'Revise an unrealistic target. Investigate missing history separately from a genuine zero-work session.']],
    questions: [['Why does another editor count differently?', 'Counting rules differ for markup, code, punctuation, and languages.'], ['Does a reached target mean the note is saved?', 'No. Always use the document save state to verify persistence.']], related: ['editor', 'status', 'publish-readiness'],
  },
]
