import type { HelpGuide } from './types.ts'

export const workflowGuides: readonly HelpGuide[] = [
  {
    id: 'export', title: 'Export and Pandoc preflight', category: 'Publishing', policy: 'manual', entry: 'Export / publish or Open publish center.', prerequisite: 'An active note, a suitable export profile, and required external tools such as Pandoc.',
    safety: 'Export writes output files and may run approved external tools. Preflight is not the exported artifact.', source: 'src/components/PublishCenter.tsx', roots: ['.publish-center', '.export-panel'],
    steps: [['Choose the format', 'Select a profile that matches the audience and destination: document, HTML, PDF, or another supported output.'], ['Run preflight', 'Read missing dependencies, citation, resource, and profile errors. Resolve required tools rather than repeatedly pressing Export.'], ['Review output scope', 'Check destination paths and external-tool permission. Confirm only the operation and files you intend.'], ['Inspect the artifact', 'Open the generated output and check layout, figures, citations, headings, and metadata before distributing it.']],
    questions: [['Why does PDF export fail while preview works?', 'PDF generation can depend on Pandoc and additional tools. Preview success does not prove those tools are installed/configured.'], ['Does export publish to the Internet?', 'Local export and deployment are different operations. Review the selected workflow and destination.']], related: ['publish', 'publish-readiness', 'export-jobs', 'citations'],
  },
  {
    id: 'publish', title: 'Local Starlight publishing', category: 'Publishing', policy: 'manual', experimental: true, entry: 'Publish workflow in Export & publish.', prerequisite: 'Eligible notes with publish: true and a configured local output target.',
    safety: 'Planning is read-only; Apply writes managed output. It does not by itself authorize public deployment or unmanaged deletion.', source: 'crates/publish-runner/src/lib.rs', roots: ['.publish-plan', '.publish-review'],
    steps: [['Opt notes in', 'Review publish metadata and content sensitivity. An eligible note is a candidate, not automatically public.'], ['Build a plan', 'Inspect new, changed, and orphaned managed outputs. Confirm the source vault and output directory are separate.'], ['Review before applying', 'Exclude content that should not be copied. Resolve stale-plan or externally modified output warnings rather than forcing them through.'], ['Inspect and deploy separately', 'Check generated local pages, links, and assets. Internet hosting is a separate deliberate workflow.']],
    questions: [['Why was Apply rejected?', 'Source hashes, eligibility, or output state may have changed since planning. Generate and review a fresh plan.'], ['Are all files in the output directory owned by Scriptor?', 'No. Publishing tracks managed outputs and should preserve unrelated files. Do not manually treat the directory as disposable.']], related: ['frontmatter', 'publish-diff', 'export'],
  },
  {
    id: 'publish-diff', title: 'Review publishing changes', category: 'Publishing', policy: 'manual', entry: 'Publishing plan/review and diff view.', prerequisite: 'A current publishing plan.',
    safety: 'Selection and Apply are separate decisions. Reviewing a diff must not silently authorize deletion or overwrite.', source: 'src/components/PublishDiffView.tsx', roots: ['.publish-diff-view', '.publish-diff'],
    steps: [['Understand change categories', 'Separate new output, changed content, missing output, and stale managed output.'], ['Inspect meaningful differences', 'Read content changes, metadata, asset destinations, and links; do not approve solely from a file count.'], ['Choose the scope', 'Select only intended changes. Revisit unexpected removals or externally edited outputs.'], ['Apply a fresh plan', 'After source edits, regenerate the plan. Verify the applied result and retain error context when a partial operation fails.']],
    questions: [['Can I apply a plan from before editing?', 'A stale plan may be rejected for integrity. Replan and review.'], ['Does a clean diff prove the site is correct?', 'No. It only describes differences against the comparison state; inspect the rendered output and content.']], related: ['publish', 'recovery', 'export-jobs'],
  },
  {
    id: 'publish-readiness', title: 'Publish readiness and vault health widgets', category: 'Publishing', policy: 'manual', entry: 'Inspector health/readiness cards.', prerequisite: 'A current index and active note for note-specific checks.',
    safety: 'Ready/Good summarize particular checks, not factual correctness, authorization, or guaranteed export success.', source: 'src/components/shell/InspectorRail.tsx', roots: ['.publish-readiness', '.readiness-card', '.vault-health-card'],
    steps: [['Read the scope', 'Determine whether the widget describes the current note, the vault, or the index cache.'], ['Inspect nonzero findings', 'Open missing citations, broken links, or invalid metadata and repair the actual source.'], ['Check zeroes carefully', 'Zero is meaningful only after a successful read. Loading or failure is not evidence of no problems.'], ['Use export preflight', 'Run the destination-specific checks and inspect the resulting artifact even when readiness is positive.']],
    questions: [['Why does Problems show issues when readiness is good?', 'Different surfaces report different scopes and checks. Inspect the underlying messages.'], ['Does Ready to export include installed tools?', 'Use export preflight for the selected profile; the readiness card alone is not sufficient.']], related: ['diagnostics', 'knowledge-repair', 'export'],
  },
  {
    id: 'export-jobs', title: 'Export jobs, progress, and receipts', category: 'Publishing', policy: 'manual', entry: 'Export jobs/status surface.', prerequisite: 'An export or external-tool job has been started.',
    safety: 'A running job is not a completed artifact. Cancellation and cleanup depend on the job owner and visible outcome.', source: 'src/components/ExportJobsPanel.tsx', roots: ['.export-jobs-panel', '.export-jobs'],
    steps: [['Identify the job', 'Match the note, format, and output destination rather than relying on the most recent status alone.'], ['Observe progress', 'Read queued/running/completed/failed states and available logs. Do not start duplicates while a slow job is still active.'], ['Cancel deliberately', 'Use the supported cancellation action when available and verify the resulting status before retrying.'], ['Keep useful evidence', 'On success inspect output; on failure preserve redacted error/tool information and receipts for diagnosis.']],
    questions: [['Can I close the panel during a job?', 'Closing a view does not necessarily cancel its job. Check the job state explicitly.'], ['Does a process exit code alone prove good output?', 'No. Inspect the produced file and reported verification evidence.']], related: ['export', 'diagnostics', 'recovery'],
  },
  {
    id: 'plugins', title: 'Runtime plugins and capability state', category: 'Integrations', policy: 'manual', experimental: true, entry: 'Inspector > Plugins > Manage installed / Browse plugins.', prerequisite: 'An open vault and a supported first-party catalog entry.',
    safety: 'Installed, enabled, permission-approved, and runtime-ready are separate states. Help never enables a plugin for you.', source: 'src/components/StorePanel.tsx', roots: ['.store-root'],
    steps: [['Inspect the plugin', 'Read its purpose, publisher, maturity, contributions, and required access. The catalog is restricted; a general signed public marketplace is not shipped.'], ['Review permission', 'Understand which data/actions are requested. Permission approval should correspond to the declared operation, not a vague trust score.'], ['Enable and verify', 'Enable the intended capability and check whether its commands/widgets become available. Read persistence/runtime errors.'], ['Recover safely', 'Use safe mode or disable a plugin to isolate problems. Re-enable deliberately; resetting permissions may require a fresh review.']],
    questions: [['Why can\'t an installed plugin run?', 'It may be disabled, missing consent, unavailable in safe mode, or failing its runtime/native capability check.'], ['Can I install arbitrary third-party JavaScript?', 'Do not infer that from the catalog UI. The current platform is first-party/restricted and experimental.']], related: ['permissions', 'modules', 'gmail', 'mcp'],
  },
  {
    id: 'modules', title: 'Built-in modules and installer profiles', category: 'Integrations', policy: 'manual', entry: 'Built-in Modules from settings or commands.', prerequisite: 'Review the active vault and module list.',
    safety: 'A profile can change several capabilities at once. Review its effects before applying it.', source: 'src/components/plugins/PluginManagerCenter.tsx', roots: ['.plugin-manager-modal'],
    steps: [['Separate appearance from capabilities', 'Palettes change appearance; feature modules change what the app can do. Choose the intended tab.'], ['Inspect a module', 'Read required access and its purpose. A missing capability may explain why a panel cannot open.'], ['Review a profile', 'Understand the set of modules affected rather than treating the profile name as a guarantee of suitability.'], ['Check the result', 'Open the expected feature and review errors. Restore previous choices when a bulk profile removed a needed capability.']],
    questions: [['Why does a module look enabled but fail?', 'Runtime, persisted vault state, and permission checks must agree. Inspect the error and retry the supported configuration path.'], ['Will disabling Graph delete notes?', 'Disabling a viewing capability is not deleting source notes. It changes access to the feature.']], related: ['plugins', 'permissions', 'appearance'],
  },
  {
    id: 'permissions', title: 'Plugin consent and native confirmations', category: 'Integrations', policy: 'manual', entry: 'Review required access and confirmation dialogs.', prerequisite: 'Know the plugin, operation, resource, and active vault.',
    safety: 'Never approve merely to silence an error. Grants are scoped and may be one-time; tutorial progress is not consent.', source: 'src/components/chrome/MutationConfirmation.tsx', roots: ['.mutation-confirmation', '.permission-review', '.plugin-permissions'],
    steps: [['Identify the caller', 'Check which feature/plugin requested access and whether you initiated the workflow.'], ['Review scope and consequence', 'Read the file/resource, operation, and whether data will be read, written, sent, executed, or deleted.'], ['Choose explicitly', 'Cancel when scope is unexpected. Approval applies to the named operation, not every future use of the application.'], ['Recover expired consent', 'Restart the intended workflow to obtain a fresh grant. Do not bypass or broaden a failed authorization check.']],
    questions: [['Why am I asked again?', 'A grant can be one-use, expired, reset, or bound to a different resource/vault.'], ['Can the tour approve permissions?', 'No. Help content is read-only and cannot manufacture a native grant.']], related: ['plugins', 'google', 'code-chunks'],
  },
  {
    id: 'feature-flags', title: 'Feature flags and experimental surfaces', category: 'Integrations', policy: 'manual', entry: 'Plugins > Features; advanced preferences.', prerequisite: 'Read the capability maturity before enabling a feature.',
    safety: 'A feature flag is not a support guarantee. Enable one change at a time and keep recovery available.', source: 'src/components/StorePanel.tsx', roots: ['.store-feature-flags', '.feature-flags-panel'],
    steps: [['Read maturity', 'Separate supported, experimental, and design-only capability. A library package does not imply a usable product screen.'], ['Enable for a purpose', 'Choose the smallest capability needed for your task, then open its actual user surface.'], ['Validate behavior', 'Test with disposable data before important work, especially for source-writing integrations.'], ['Disable and report', 'When isolating a regression, record the flag and visible error; return to a known working configuration.']],
    questions: [['Can I enable mobile or a public marketplace here?', 'No. Design-only proposals are not shipped features.'], ['Does disabling a flag undo prior file changes?', 'No. Use note history, Git, or backups for content recovery.']], related: ['plugins', 'recovery', 'diagnostics'],
  },
  {
    id: 'google', title: 'Connect Google Calendar and Tasks', category: 'Integrations', policy: 'manual', experimental: true, entry: 'Settings > Integrations > Google.', prerequisite: 'Desktop app, network access, and a configured Google OAuth Desktop-app client ID.',
    safety: 'OAuth opens the system browser and requests scopes. Tokens use the OS keychain. Help never asks for or stores your credentials.', source: 'src/components/GoogleIntegrationSettingsSection.tsx', roots: ['.google-integration-settings', '.settings-integrations'],
    steps: [['Prepare the correct credential', 'Use a Desktop-app client ID, not a web-app redirect setup or client secret. Check the integration setup instructions and configured account.'], ['Save and connect', 'Review the locally persisted configuration and approve Google consent only for the account/scopes you intend. Cancellation is not a successful connection.'], ['Refresh provider data', 'Connection and synchronization are different states. Sync now and inspect Calendar/Tasks before assuming the account is ready.'], ['Disconnect honestly', 'Use Disconnect and read cleanup failures. A network or keychain error must not be treated as verified credential removal.']],
    questions: [['Why does login fail before browser consent?', 'Read the exact error: native authorization scope, disabled capability, invalid client setup, and browser launch are separate failure points.'], ['Why do Google tasks look duplicated?', 'Inspect the source identifiers and remote tasks before retrying mirroring. Avoid repeated creation while a prior synchronization is unresolved.']], related: ['gmail', 'tasks', 'permissions', 'diagnostics'],
  },
  {
    id: 'gmail', title: 'Gmail account, messages, and compose', category: 'Integrations', policy: 'manual', experimental: true, entry: 'Enable Gmail Manager in Plugins, then open it from the command palette.', prerequisite: 'Desktop support, enabled Gmail capability, Google client setup, network, and approved Gmail-specific scopes.',
    safety: 'Send transmits mail; archive/trash changes the mailbox; Import writes a vault note. These are distinct explicit actions.', source: 'src/components/GmailManagerPanel.tsx', roots: ['.gmail-manager', '.gmail-panel'],
    steps: [['Connect the account', 'Open Account and confirm the Google identity. A token check, offline error, and authentication failure are different states.'], ['Search and read', 'Use Gmail search syntax and inspect sender, subject, and message contents. Results are bounded; the visible list is not a full mailbox export.'], ['Import or manage', 'Import archives selected text to Markdown; Archive/Trash changes Gmail. Verify the intended message before acting.'], ['Compose carefully', 'Review recipient, subject, and plain-text body before Send. This experimental surface is not a full Gmail replacement with every thread/attachment feature.']],
    questions: [['Why did Open Gmail route to Plugins?', 'The capability must be enabled and permission-reviewed first.'], ['Does imported mail become a live mailbox copy?', 'No. A Markdown import is a local copy, not two-way synchronization of the message.']], related: ['google', 'plugins', 'vault'],
  },
  {
    id: 'ai', title: 'Opt-in AI provider and draft proposals', category: 'Integrations', policy: 'manual', experimental: true, entry: 'AI provider settings and supported draft-proposal commands.', prerequisite: 'A configured endpoint/model and any required keychain credential.',
    safety: 'Requests may send selected content to the configured provider. Review draft proposals before applying; generated text is not verified evidence.', source: 'src/components/AiProviderSettings.tsx', roots: ['.ai-provider-settings', '.ai-settings'],
    steps: [['Choose the boundary', 'Check endpoint, model, and which data will leave the device. A local-looking label is not proof that the endpoint is local.'], ['Configure credentials safely', 'Use the supported keychain setting; do not paste secrets into notes, help search, screenshots, or issue reports.'], ['Request a bounded draft', 'Select only needed material and inspect error/timeout state. A Markdown [!ai] callout is a template, not an executed request.'], ['Review before applying', 'Check claims, citations, tone, and changes against your original. Retain an undo/history path.']],
    questions: [['Will AI run automatically while I type?', 'The product workflow is opt-in; reading Help or inserting a callout does not authorize a provider request.'], ['What should I do after a timeout?', 'Check provider/model/network configuration and whether work is still pending before retrying.']], related: ['permissions', 'citations', 'mcp'],
  },
  {
    id: 'mcp', title: 'MCP automation modes and tools', category: 'Integrations', policy: 'manual', entry: 'Open MCP panel.', prerequisite: 'An open vault, configured automation mode, and appropriate permissions.',
    safety: 'Automation tools can read or mutate scoped resources. Prefer read-only exploration before enabling writes.', source: 'src/components/McpPanel.tsx', roots: ['.mcp-panel'],
    steps: [['Choose mode', 'Distinguish disabled, read-only, and write-enabled operation. Mode changes are authority changes, not cosmetic preferences.'], ['Inspect tools', 'Read the tool name, arguments, affected resource, and capability before invoking it.'], ['Review proposals', 'Inspect draft changes and native confirmations. A tool description or model request is not itself authorization.'], ['Audit the outcome', 'Use the audit tab to distinguish started, failed, cancelled, and completed actions. Retain redacted context when reporting a failure.']],
    questions: [['Why is a tool unavailable?', 'It can be blocked by mode, vault scope, capability, permission, or runtime validation.'], ['Can an agent use Help to gain access?', 'No. Guides do not invoke tools, grant permissions, or alter native checks.']], related: ['mcp-audit', 'mcp-drafts', 'permissions'],
  },
  {
    id: 'mcp-audit', title: 'Automation audit records', category: 'Integrations', policy: 'manual', entry: 'MCP > Audit and tool execution details.', prerequisite: 'Relevant automation activity in the active scope.',
    safety: 'Audit records describe operations; they are not a substitute for inspecting the resulting files. Share only redacted evidence.', source: 'src/components/McpPanel.tsx', roots: ['.mcp-audit', '.mcp-audit-panel'],
    steps: [['Find the operation', 'Match timestamp, tool, scope, and outcome. Several retries can belong to one intended task.'], ['Distinguish intent and result', 'A recorded request does not prove a completed mutation. Read result/error and recovery evidence.'], ['Inspect source', 'Verify changed files or output when an operation claims completion.'], ['Preserve diagnostics safely', 'Copy only needed redacted details into a report; exclude keys, tokens, private notes, and unrelated paths.']],
    questions: [['Does an empty log prove nothing happened?', 'Not necessarily. Scope, retention limits, or a loading failure can affect what is visible.'], ['Should I reset the log to repair a task?', 'No. Resetting history does not undo a source mutation and can remove useful evidence.']], related: ['mcp', 'diagnostics', 'recovery'],
  },
  {
    id: 'mcp-drafts', title: 'Automation drafts and applying proposals', category: 'Integrations', policy: 'manual', entry: 'MCP draft/proposal review.', prerequisite: 'A generated proposal for the intended note/vault.',
    safety: 'Reading a proposal is not accepting it. Applying writes content and must preserve the native review/authorization flow.', source: 'src/components/McpPanel.tsx', roots: ['.mcp-drafts', '.mcp-draft-review'],
    steps: [['Verify the target', 'Confirm the note path and source version before inspecting a proposal.'], ['Review the change', 'Compare proposed text with the current document. Check evidence, removals, and formatting.'], ['Apply intentionally', 'Use the explicit apply workflow only after review. A stale target should lead to refresh/review, not forced overwrite.'], ['Verify and recover', 'Inspect the saved note and audit outcome. Use undo/history/Git where appropriate if the result was unwanted.']],
    questions: [['Can I approve all future drafts?', 'Do not treat one reviewed change as unlimited authority. Each workflow keeps its own scope.'], ['Why is a proposal stale?', 'The note may have changed after the proposal was generated. Reconcile against the current source.']], related: ['mcp', 'ai', 'history'],
  },
  {
    id: 'code-chunks', title: 'External code chunks', category: 'Integrations', policy: 'manual', experimental: true, entry: 'Runnable code-chunk controls in a supported preview.', prerequisite: 'Explicit code-execution enablement, approved tool policy, and installed executable.',
    safety: 'Execution can run external processes. Do not run untrusted notes or grant access merely to render a document.', source: 'packages/renderer/src/mpe-client.ts', roots: ['.mpe-code-chunk'],
    steps: [['Inspect the source', 'Read the entire command/code and its inputs before pressing Run. A language fence is not automatically a trusted program.'], ['Review permission and policy', 'Check executable, working scope, network allowance, and visible confirmation.'], ['Observe bounded output', 'Read process output, timeout, cancellation, and exit status. Large output may be truncated intentionally.'], ['Verify side effects', 'Inspect created/changed files and preserve the receipt/error. Reading this tour never executes a chunk.']],
    questions: [['Why is Run unavailable?', 'Execution is opt-in and may be blocked by capability, policy, missing tools, or native desktop availability.'], ['Does a successful run prove the result correct?', 'No. Validate output and side effects independently.']], related: ['permissions', 'preview', 'diagnostics'],
  },
  {
    id: 'resource-sync', title: 'Resource synchronization and sharing plans', category: 'Integrations', policy: 'manual', entry: 'Resource/sync tools in the applicable workflow.', prerequisite: 'Configured source/targets and appropriate resource permissions.',
    safety: 'Plans are read-only until an explicit Apply. Review which data will be copied or exposed before authorizing.', source: 'src/components/ResourceSyncPanel.tsx', roots: ['.resource-sync-panel'],
    steps: [['Choose source and targets', 'Confirm resource identity, allowed scope, and destination. Similar labels can hide different targets.'], ['Build a plan', 'Inspect expected writes, conflicts, and exclusions. Do not equate selecting a target with transferring data.'], ['Review and apply', 'Approve only intended changes and resolve stale-plan failures by replanning.'], ['Verify delivery', 'Check the actual target/output and recorded result. Partial failure requires review rather than blind repeated copying.']],
    questions: [['Does opening this panel share anything?', 'No. Sharing/copying requires the separate configured apply workflow.'], ['Can I assume all targets received the data?', 'No. Inspect per-target outcomes and errors.']], related: ['mcp', 'permissions', 'recovery'],
  },
  {
    id: 'portal', title: 'Portal items and quick actions', category: 'Workspace', policy: 'manual', entry: 'Open Portal from the command palette or configured top-bar action.', prerequisite: 'Review the current workspace/vault scope.',
    safety: 'Portal items can launch actions. Read destination and action type before invoking, especially external links or workflows.', source: 'src/components/portal/PortalPanel.tsx', roots: ['.portal-panel'],
    steps: [['Choose an item type', 'Create an action or reference that has a clear recurring purpose. Avoid duplicating every command already in the palette.'], ['Name and configure', 'Use recognizable labels and verify target paths/URLs. Do not store secrets in labels or notes.'], ['Pin intentionally', 'Pin frequently used items to quick access; keep rare administrative actions out of the writing flow.'], ['Invoke and maintain', 'Check the operation outcome and update stale targets after reorganizing notes. Removing an item does not undo its past actions.']],
    questions: [['Is a Portal item a copy of its target?', 'Usually it is a reference/action definition, not a backup of the target.'], ['Why is an item unavailable?', 'Its target, capability, or active-vault requirement may no longer be satisfied.']], related: ['capture', 'commands', 'permissions'],
  },
  {
    id: 'capture', title: 'Quick Capture', category: 'Writing', policy: 'manual', entry: 'Open Quick Capture from commands or configured top bar.', prerequisite: 'Check the active vault and capture destination.',
    safety: 'Saving capture writes content. Keep the original until the new note is confirmed; capture is not a background backup.', source: 'src/components/portal/QuickCapturePanel.tsx', roots: ['.quick-capture-panel'],
    steps: [['Capture the idea', 'Enter concise text and enough source/context to understand it later.'], ['Review destination', 'Confirm whether this action creates a new note, appends content, or creates a sticky.'], ['Save and verify', 'Check the resulting note/path and any error before closing the capture.'], ['Process later', 'Use Inbox, links, and tags to integrate captured material into your vault rather than leaving permanent fragments.']],
    questions: [['Can two captures use the same title?', 'Filename collisions need explicit handling. Do not assume another save always makes a separate file.'], ['Does closing the capture prove it saved?', 'No. Verify the save outcome and created content.']], related: ['inbox', 'portal', 'stickies'],
  },
  {
    id: 'stickies', title: 'Sticky notes and transient reminders', category: 'Writing', policy: 'manual', entry: 'Show stickies in Tools; Quick Capture sticky action.', prerequisite: 'A workspace with sticky-note support enabled.',
    safety: 'Sticky state is distinct from your Markdown document. Move durable knowledge into a note and back it up appropriately.', source: 'src/components/portal/QuickCapturePanel.tsx', roots: ['.sticky-note', '.stickies-layer'],
    steps: [['Write a reminder', 'Keep a sticky short and actionable so it does not obscure the writing area.'], ['Position or hide', 'Use the available layout/show controls. Hiding stickies is different from deleting them.'], ['Promote durable content', 'Copy or move lasting material into a properly titled Markdown note and verify the result.'], ['Remove obsolete items', 'Delete only after confirming important content is preserved elsewhere.']],
    questions: [['Are stickies part of the open note?', 'Do not assume so. They belong to their own workspace/capture state.'], ['Why are they not visible?', 'Check the show/hide preference and active workspace before concluding they were deleted.']], related: ['capture', 'portal', 'backups'],
  },
]
