import type { HelpGuide } from './types.ts'

export const knowledgeGuides: readonly HelpGuide[] = [
  {
    id: 'inspector', title: 'Inspector rail and contextual widgets', category: 'Knowledge', policy: 'manual', entry: 'Right rail; Inspector / Rendered output / Plugins.', prerequisite: 'Some widgets require an active note or indexed vault.',
    safety: 'A widget reports only its own scope. A healthy index is not proof of saved content, correct citations, or a backup.', source: 'src/components/shell/InspectorRail.tsx', roots: ['.inspector-panel'],
    steps: [['Choose the job', 'Inspector shows contextual information; Rendered output reads the note; Plugins manages extensions. Switching tabs does not rewrite the document.'], ['Select a profile', 'Use a layout/profile suited to research, publishing, or cleanup. Hidden widgets remain available when you change profiles.'], ['Inspect the detail', 'Open the relevant outline, backlink, citation, or health result instead of relying only on its count.'], ['Recover writing space', 'Collapse the rail or resize it. A docked companion can replace the rail temporarily; closing it restores the writing layout.']],
    questions: [['Why is the inspector empty?', 'Check active note, selected tab/profile, loading state, and capability availability.'], ['Do all widgets update instantly?', 'Some depend on indexing or asynchronous reads. A pending/error state is not a confirmed zero.']], related: ['outline', 'backlinks', 'citations', 'docks'],
  },
  {
    id: 'outline', title: 'Document outline', category: 'Knowledge', policy: 'manual', entry: 'Inspector > Outline.', prerequisite: 'An active note containing Markdown headings.',
    safety: 'Outline navigation is read-only; heading edits and section moves change Markdown.', source: 'src/components/shell/InspectorRail.tsx', roots: ['.outline-card', '.outline-panel', '.outline-list'],
    steps: [['Read the hierarchy', 'Heading levels express document structure. A title-like bold sentence is not necessarily a heading.'], ['Jump to a section', 'Select the heading to locate it in the note. Verify the target before applying structure commands.'], ['Repair structure', 'Use meaningful heading levels and unique section names. Avoid skipping levels merely to obtain a different visual size.'], ['Handle missing headings', 'Check source syntax and index/preview readiness. A fenced code sample containing # should not be treated as prose structure.']],
    questions: [['Why is my title not listed?', 'It may not be a Markdown heading, or the current note/index has not refreshed.'], ['Does moving an outline entry move text?', 'Navigation does not. Use the explicit section-move command when you intend to rewrite the document.']], related: ['editor', 'toolbar', 'search'],
  },
  {
    id: 'backlinks', title: 'Backlinks and incoming references', category: 'Knowledge', policy: 'manual', entry: 'Inspector > Backlinks.', prerequisite: 'Open and index the relevant vault.',
    safety: 'Backlinks are derived from source links. Removing a result requires editing the originating note, not deleting an index row.', source: 'src/hooks/useWorkspaceDiagnostics.ts', roots: ['.backlinks-panel', '.backlinks-card', '.backlinks-list'],
    steps: [['Identify the direction', 'Backlinks are other notes pointing to the active note. They differ from outgoing links written inside it.'], ['Read the origin', 'Open the source path and inspect the surrounding sentence before changing a reference.'], ['Resolve ambiguity', 'Similar titles can refer to distinct paths. Use the vault link-resolution rules rather than assuming a title always names one file.'], ['Refresh responsibly', 'After edits, wait for indexing. Diagnose a read error or stale index separately from having no incoming references.']],
    questions: [['Is a note with no backlinks wrong?', 'No. An isolated note may be intentional. Repair should serve your knowledge structure, not maximize counts.'], ['Why did renaming affect a backlink?', 'Links depend on paths/titles and resolution rules. Use the reviewed rename/link-rewrite flow for broad changes.']], related: ['outgoing', 'graph', 'rename'],
  },
  {
    id: 'outgoing', title: 'Outgoing links and unresolved destinations', category: 'Knowledge', policy: 'manual', entry: 'Inspector > Outgoing Links.', prerequisite: 'An active note with Markdown links or wikilinks.',
    safety: 'Opening an external link may leave the app. Creating a missing note writes a file and requires your explicit action.', source: 'src/components/shell/InspectorRail.tsx', roots: ['.outgoing-links', '.outgoing-links-panel', '.outgoing-links-card'],
    steps: [['Inspect the destination', 'Distinguish a vault note, attachment, heading fragment, and external URL. Read the target path before navigating.'], ['Resolve a broken link', 'Check spelling, folder, extension, and whether the target was moved. A missing result can also be an index problem.'], ['Create intentionally', 'Only create a missing note when it represents useful content. Do not create dozens of empty files just to silence health warnings.'], ['Verify after repair', 'Reopen the reference and review the updated source. Bulk rewriting belongs in a preview/confirmation workflow.']],
    questions: [['Why does a link open a confirmation?', 'External or cross-vault navigation has a separate trust boundary. Review the destination.'], ['Are backlinks the same list?', 'No. Outgoing links originate in this note; backlinks originate elsewhere.']], related: ['backlinks', 'knowledge-repair', 'rename'],
  },
  {
    id: 'citations', title: 'Citation references and missing keys', category: 'Knowledge', policy: 'manual', entry: 'Inspector citations and citation insertion tools.', prerequisite: 'Configure local bibliography data and use keys that exist in it.',
    safety: 'Citation formatting is not source verification. Check authors, dates, locators, and the evidence yourself.', source: 'src/components/inspector/citation-plugin-manifest.ts', roots: ['.citations-panel', '.citation-inspector', '.citation-panel'],
    steps: [['Find a bibliography key', 'Use a stable cite key from the configured bibliography. Do not invent a key because a formatted citation looks plausible.'], ['Insert in source', 'Insert the supported citation syntax, including page/section locators when required by the argument.'], ['Check unresolved references', 'Inspect missing-key warnings and bibliography paths. A missing bibliography is different from a malformed entry.'], ['Verify final output', 'Review citation style and bibliography in exported output, not only the preview. Check the factual source behind every citation.']],
    questions: [['Does Scriptor synchronize Zotero?', 'The shipped citation surface uses local bibliography data. Do not infer a composed Zotero synchronization UI from a library package.'], ['Why is a key unresolved?', 'Confirm the exact key, active vault, bibliography configuration, and parser warnings.']], related: ['bibliography', 'export', 'publish-readiness'],
  },
  {
    id: 'bibliography', title: 'Bibliography management', category: 'Knowledge', policy: 'manual', entry: 'Bibliography from the command palette or references controls.', prerequisite: 'A local bibliography file in the configured vault workflow.',
    safety: 'Bibliographic metadata can be incomplete or malformed. Preserve the original source file before broad changes.', source: 'src/components/BibliographyPanel.tsx', roots: ['.bibliography-panel'],
    steps: [['Inspect configuration', 'Confirm which bibliography is being read and whether it belongs to the active vault.'], ['Review entries', 'Match cite keys with titles/authors and identify duplicate or missing keys. Use source paths to distinguish libraries.'], ['Correct data at its source', 'Repair malformed records or fields in the bibliography rather than editing only rendered prose.'], ['Recheck citations', 'Refresh/index as needed, then inspect both the note preview and export preflight for unresolved references.']],
    questions: [['Can one bad entry break everything?', 'Parser failures and per-entry conversion problems can degrade differently. Read warnings rather than assuming all records loaded.'], ['Does an entry prove the reference is correct?', 'No. Verify source accuracy and relevance independently.']], related: ['citations', 'knowledge-repair', 'export'],
  },
  {
    id: 'workbench', title: 'Knowledge Workbench', category: 'Knowledge', policy: 'first-open', entry: 'Open knowledge workbench in the command palette.', prerequisite: 'An indexed vault. Some queues may legitimately be empty.',
    safety: 'The workbench combines navigation and repair planning. Adding links or applying repair actions changes notes only through explicit workflows.', source: 'src/components/KnowledgeWorkbench.tsx', roots: ['.knowledge-workbench-panel'],
    steps: [['Choose a task', 'Repair handles knowledge queues; Views and Collections reuse queries; Tags manages discovery; Discover leads to graph exploration.'], ['Inspect populated results', 'Use title and path together and read incoming/outgoing counts in context. A count is not an automatic instruction to modify the note.'], ['Work through triage', 'Open a queued note, review its meaning, then move to the next item. Keep the workbench context rather than blindly linking everything.'], ['Verify a change', 'Let the index refresh after editing. Re-run the queue to see whether the intended issue was actually resolved.']],
    questions: [['Why is my queue empty?', 'It may genuinely have no matching items; check loading/error and filter state first.'], ['Are orphan notes defects?', 'Not always. Personal logs and intentionally isolated notes may be valid.']], related: ['knowledge-repair', 'saved-views', 'collections', 'tags'],
  },
  {
    id: 'knowledge-repair', title: 'Repair queues and triage', category: 'Knowledge', policy: 'manual', entry: 'Knowledge Workbench > Repair.', prerequisite: 'A current index and the correct filter.',
    safety: 'Repair suggestions need judgment. Do not delete content or fabricate links simply to improve a health count.', source: 'src/components/KnowledgeFiltersPanel.tsx', roots: ['.knowledge-filters-panel'],
    steps: [['Select the queue', 'Orphans, dead ends, and unresolved references describe different relationships. Read the queue label before acting.'], ['Inspect a note', 'Check its path, contents, and relation to surrounding work. A useful missing link needs meaningful context.'], ['Review proposed linking', 'Choose the correct target and inspect the insertion or rewrite scope. Confirm only the changes you intend.'], ['Continue and re-evaluate', 'Use triage navigation, then refresh the queue after edits. Changing filters can change the available sequence.']],
    questions: [['Why did the queue count change?', 'New indexing, filter changes, or source edits can alter results. Do not treat a previous row number as a persistent note identity.'], ['What should I do with an unresolved reference?', 'Repair the target path/title, create a meaningful destination, or remove the reference if it was erroneous.']], related: ['workbench', 'backlinks', 'outgoing'],
  },
  {
    id: 'saved-views', title: 'Saved views and reusable queries', category: 'Knowledge', policy: 'manual', entry: 'Knowledge Workbench > Views; Saved views.', prerequisite: 'An open indexed vault and supported query syntax.',
    safety: 'A view stores a query; it is not a copy or backup of matching notes.', source: 'src/components/SavedViewsPanel.tsx', roots: ['.saved-views-panel'],
    steps: [['Define the intent', 'Start with a clear question: recent notes, a tag, path, or review status. Use supported filters rather than free-form guesses.'], ['Run before saving', 'Inspect results and paths. Confirm that empty results are not a parser or index error.'], ['Name and save', 'Give the view an intention-based name so it remains useful later. Avoid names that imply fixed contents.'], ['Maintain the query', 'Results change as notes evolve. Review stale filters after reorganizing folders or tags.']],
    questions: [['Why did yesterday\'s result disappear?', 'Views are live queries over the current index, not snapshots.'], ['Can I use any SQL here?', 'No. Use the supported query/filter surface and inspect errors; do not assume raw database access.']], related: ['collections', 'search', 'tags'],
  },
  {
    id: 'collections', title: 'Smart collections', category: 'Knowledge', policy: 'manual', entry: 'Knowledge Workbench > Collections.', prerequisite: 'An indexed vault and a valid collection query.',
    safety: 'Collections group query results; deleting a collection definition is distinct from deleting its notes.', source: 'src/components/SmartCollectionsPanel.tsx', roots: ['.smart-collections-panel'],
    steps: [['Choose a useful grouping', 'Define a collection around a project, topic, or review condition instead of duplicating your entire folder tree.'], ['Validate the query', 'Run the supported DQL/filter and inspect several matching notes and known nonmatches.'], ['Save the definition', 'Use a readable label and review where the collection definition is stored.'], ['Revisit after changes', 'Folder renames, tags, and metadata updates can change membership. Update the query rather than moving notes merely to preserve an old result.']],
    questions: [['Does collection membership move files?', 'No. Membership is derived from the query.'], ['How is this different from a folder?', 'A folder is a storage path. A collection can span several folders and changes with the query.']], related: ['saved-views', 'tags', 'frontmatter'],
  },
  {
    id: 'tags', title: 'Tag browsing and tag management', category: 'Knowledge', policy: 'manual', entry: 'Browse tags or Knowledge Workbench > Tags.', prerequisite: 'Indexed notes containing supported tags.',
    safety: 'Browsing is read-only; renaming/removing tags is a source mutation and should be reviewed.', source: 'src/components/TagBrowserPanel.tsx', roots: ['.tag-browser-panel', '.tag-management-panel'],
    steps: [['Browse by meaning', 'Select a tag and inspect matching notes. Similar spellings or nested tags may represent different concepts.'], ['Check the source', 'Open a result and inspect actual tags/frontmatter before deciding a count is incorrect.'], ['Consolidate deliberately', 'Use reviewable rename/cleanup when merging tag variants. Preserve a backup for broad changes.'], ['Refresh downstream views', 'Recheck smart collections and saved views that depended on the old tags.']],
    questions: [['Why do counts disagree?', 'Different views may use different filters or indexing generations. Verify current source and scope.'], ['Should every note have a tag?', 'No. Add tags when they improve retrieval; folders and links also provide structure.']], related: ['collections', 'rename', 'workbench'],
  },
  {
    id: 'graph', title: 'Knowledge graph navigation', category: 'Knowledge', policy: 'first-open', entry: 'Open graph from the command palette or Inspector.', prerequisite: 'An indexed vault and enabled Graph capability.',
    safety: 'Graph navigation is read-only. Enabling its module changes capability settings, not note content.', source: 'src/components/GraphPanel.tsx', roots: ['.graph-overlay'],
    steps: [['Check availability', 'If Graph is disabled, review the recovery action instead of expecting an empty canvas to be an empty vault.'], ['Choose scope', 'Neighborhood follows the current note; Full vault explores more of the vault. Depth limits traversal rather than proving all links are shown.', '.graph-controls'], ['Read the graph', 'Nodes represent notes/references and edges relationships. Use labels and the legend; color alone is not identity.', '.graph-group-legend'], ['Navigate or pause', 'Select a node to open its note. Hibernation pauses graph work; Resume wakes it. Save views only when their settings are useful.']],
    questions: [['Why are some nodes missing?', 'Graph queries are bounded and affected by scope, depth, indexing, and filters.'], ['Does a graph edge prove a meaningful connection?', 'It proves the indexed reference relation, not the truth or strength of an argument.']], related: ['backlinks', 'workbench', 'hibernation'],
  },
  {
    id: 'canvas', title: 'Canvas board and spatial notes', category: 'Knowledge', policy: 'first-open', entry: 'Open canvas from the command palette.', prerequisite: 'Open the intended vault and enable Canvas if required.',
    safety: 'Canvas edits persist board data. Import, attachment, or external-resource operations have their own confirmation boundaries.', source: 'src/components/CanvasPanel.tsx', roots: ['.canvas-overlay'],
    steps: [['Choose the board', 'Check the board/path shown in the footer before adding or moving content. A canvas is not the note editor.', '.canvas-footer'], ['Build relationships', 'Add or select blocks, then arrange them by meaning. Review referenced note/resource destinations.'], ['Navigate spatially', 'Use zoom and viewport controls to inspect crowded boards. Zoom changes the view, not the underlying document content.', '.canvas-viewport-controls'], ['Save and inspect', 'Check operation errors and board persistence. Exported representations can differ from interactive boards; inspect output before sharing.']],
    questions: [['Is moving a card the same as moving its Markdown file?', 'No. Board layout and vault filesystem paths are different concepts.'], ['Why can\'t I use an external attachment?', 'The resource may be unavailable, outside the vault, or require explicit access. Use the supported import/resource flow.']], related: ['resource-sync', 'docks', 'export'],
  },
  {
    id: 'tasks', title: 'Markdown-backed tasks', category: 'Knowledge', policy: 'first-open', experimental: true, entry: 'Open tasks panel in the command palette.', prerequisite: 'An open indexed vault with supported Markdown task syntax.',
    safety: 'Checking or editing a task writes its originating Markdown note. Google synchronization is a separate opt-in integration.', source: 'src/components/TaskPanel.tsx', roots: ['.task-panel'],
    steps: [['Choose a scope', 'Review filters and source paths. A task result is a view of Markdown, not an independent task database.'], ['Open the source', 'Read surrounding text before editing an ambiguous or duplicated task. Source location can change as notes are edited.'], ['Apply a change', 'Use completion/edit actions and wait for the result. Pending/error state means the change is not yet proven saved.'], ['Sync deliberately', 'Enable Google only when configured. Local completion and remote mirroring have separate states and failure paths.']],
    questions: [['Why did my edit fail?', 'Source content may have changed, the note may be unavailable, or the native write failed. Refresh, inspect source, and retry intentionally.'], ['Are Calendar events also Markdown tasks?', 'No. Events and local tasks are separate kinds of information displayed by the integration.']], related: ['google', 'kanban', 'history'],
  },
  {
    id: 'kanban', title: 'Markdown Kanban board', category: 'Knowledge', policy: 'first-open', experimental: true, entry: 'Open kanban for an active note.', prerequisite: 'A suitable Markdown note with supported section headings and cards.',
    safety: 'Moving a card rewrites its source text under the selected heading. It is not merely a visual rearrangement.', source: 'src/components/KanbanPanel.tsx', roots: ['.kanban-panel'],
    steps: [['Inspect source structure', 'Columns derive from supported headings and cards from source content. Start with a simple note and clear column names.'], ['Move intentionally', 'Choose the destination column or drag when supported. Wait while the source mutation is pending.'], ['Handle errors', 'A failed move must not be interpreted as a saved board change. Review the message and source before retrying.'], ['Verify Markdown', 'Return to the note and confirm the card text moved once and retained its contents. Use history for recovery.']],
    questions: [['Why is the board empty?', 'The active note may not contain the required heading/card structure.'], ['Can I move several cards repeatedly during a pending write?', 'Avoid overlapping actions. Wait for completion or resolve the error before issuing another move.']], related: ['tasks', 'editor', 'history'],
  },
  {
    id: 'reader', title: 'Vault PDF and EPUB reader', category: 'Knowledge', policy: 'first-open', experimental: true, entry: 'Open reader from the command palette.', prerequisite: 'Desktop support and a PDF/EPUB stored at a supported vault-relative path.',
    safety: 'Only approved vault documents are opened. Annotation storage is distinct from editing the original PDF/EPUB.', source: 'src/components/reader/ReaderPanel.tsx', roots: ['.reader-panel'],
    steps: [['Select a document', 'Choose the vault-relative document path; external arbitrary filesystem paths are not interchangeable.'], ['Navigate the document', 'Use available page/location and reading controls. Large documents may take time; distinguish loading from failure.'], ['Capture evidence', 'Select a passage for the supported annotation workflow and retain its page/location context.'], ['Recover missing content', 'Check that the document still exists in the vault and that the type is supported. Reopening cannot restore a deleted source file.']],
    questions: [['Does reading change the original document?', 'The viewer reads the file; annotations use a sidecar rather than rewriting the original document.'], ['Can I open a random website as a PDF?', 'No. The reader is a bounded vault-document workflow, not a general web browser.']], related: ['annotations', 'citations', 'vault'],
  },
  {
    id: 'annotations', title: 'Reader annotations and evidence capture', category: 'Knowledge', policy: 'manual', experimental: true, entry: 'Annotation controls within the Reader.', prerequisite: 'A supported document open in the Reader.',
    safety: 'Annotations are stored separately in the vault. Back up the sidecar with the document to preserve context.', source: 'src/components/reader/ReaderPanel.tsx', roots: ['.reader-annotations', '.annotation-panel'],
    steps: [['Select a precise passage', 'Keep enough quotation and location context to identify the source later.'], ['Add interpretation', 'Distinguish the source text from your commentary. Record why the evidence matters to the argument.'], ['Save and verify', 'Check the result and reopen the annotation. Do not infer persistence from a temporary highlight alone.'], ['Use in writing', 'Link or cite the original source with the relevant location. An annotation is not a substitute for verifying the source.']],
    questions: [['Where are annotations kept?', 'The reader uses the vault annotation sidecar; preserve it in backups together with source documents.'], ['Will renaming a document preserve every annotation?', 'Check the reader and source path after changes. Do not assume arbitrary external file moves update sidecar references.']], related: ['reader', 'citations', 'backups'],
  },
]
