import type { HelpGuide } from './types.ts'

export const referenceGuides: readonly HelpGuide[] = [
  {
    id: 'cheatsheet', title: 'Markdown and query cheatsheet', category: 'Writing', policy: 'manual', entry: 'Open Markdown cheatsheet from Tools or the command palette.', prerequisite: 'No provider is needed; query examples require the appropriate indexed vault.',
    safety: 'Examples are reference text. Insertion changes the active note only when you invoke the explicit insertion action.', source: 'src/components/CheatsheetPanel.tsx', roots: ['.cheatsheet-panel'],
    steps: [['Choose the syntax family', 'Distinguish Markdown formatting, wikilinks, citations, supported queries, and insert templates. They are not interchangeable languages.'], ['Read an example', 'Look at delimiters and required whitespace before copying a pattern. Fences and block content need clean boundaries.'], ['Adapt to the current note', 'Replace placeholders and targets deliberately. A sample citation key or note path is not guaranteed to exist in your vault.'], ['Check source and output', 'Inspect both the resulting Markdown and its preview/query output. Resolve errors before reusing the pattern widely.']],
    questions: [['Is the cheatsheet an interactive tutorial?', 'It is a quick syntax reference. Use Help tours for the surrounding workflow and prerequisites.'], ['Will examples run commands?', 'Reading or copying an example does not authorize an external operation. Execution belongs to its own explicit workflow.']], related: ['toolbar', 'snippets', 'preview'],
  },
  {
    id: 'latex', title: 'LaTeX compilation and output', category: 'Publishing', policy: 'manual', entry: 'LaTeX compilation section in Export & publish.', prerequisite: 'A supported source, configured compilation engine, installed tools, and approved process policy.',
    safety: 'Compilation launches an external process and writes output. Do not compile untrusted material without reviewing its scope.', source: 'src/components/PublishCenter.tsx', roots: ['.publish-center-section[aria-labelledby="latex-compile-heading"]'],
    steps: [['Confirm the source and engine', 'Check the active source and selected compilation tool. Markdown preview is not a substitute for a LaTeX toolchain.'], ['Review output settings', 'Choose the intended destination and process options. Avoid overwriting unrelated work.'], ['Run and observe', 'Review the native confirmation, progress, and compiler diagnostics. Wait or use supported cancellation before starting another job.'], ['Inspect the artifact', 'Open the resulting document and check references, figures, fonts, page breaks, and omitted content before sharing.']],
    questions: [['Why does preview work but compilation fail?', 'They use different engines. A missing compiler, unsupported option, or source error may affect only compilation.'], ['Does a zero exit code prove a correct document?', 'No. Inspect the generated artifact and any warnings.']], related: ['export', 'export-jobs', 'permissions'],
  },
  {
    id: 'daemon', title: 'Daemon connection and operational controls', category: 'Integrations', policy: 'manual', entry: 'Advanced settings and daemon operational controls.', prerequisite: 'Native desktop/operational support and a compatible daemon.',
    safety: 'Starting or changing an operational service is different from opening a panel. Endpoint/token details may be sensitive.', source: 'src/components/DaemonOpsPanel.tsx', roots: ['.daemon-ops-panel'],
    steps: [['Inspect connection state', 'Read the daemon version, endpoint status, and error. A missing service differs from an authorization or protocol failure.'], ['Refresh before changing', 'Use a read-only status refresh to determine whether the service has recovered.'], ['Start intentionally', 'Use the supported start/control action when needed and verify the resulting connection. Do not spawn repeated copies to hide a failure.'], ['Report safely', 'Preserve bounded diagnostics and version details, but redact tokens and private paths before sharing.']],
    questions: [['Does an open desktop prove the daemon is connected?', 'No. Check the operational status of the path you are using.'], ['Should I paste endpoint credentials into Help?', 'No. Help search is a local documentation search, not a diagnostic credential collector.']], related: ['advanced', 'mcp', 'diagnostics'],
  },
  {
    id: 'quality', title: 'Performance and release-quality evidence', category: 'Recovery', policy: 'manual', entry: 'Release-quality and measurement sections in Advanced settings.', prerequisite: 'Understand the environment and scope of each measurement.',
    safety: 'Numbers describe a particular run. They are not a certificate that every feature is correct, accessible, or safe.', source: 'src/components/ReleaseQualityPanel.tsx', roots: ['.release-quality-panel'],
    steps: [['Read the metric scope', 'Distinguish startup, first edit, export, memory, and workflow timings. Results depend on data and environment.'], ['Compare like for like', 'Use the same workload and configuration when evaluating a regression.'], ['Preserve failures', 'Record the original failing path and diagnostics. Passing an unrelated benchmark does not resolve it.'], ['Reset only measurements', 'Read the reset scope; clearing journey/measurement records does not repair source content or an integration.']],
    questions: [['Is a fast result proof of usability?', 'No. Interaction, correctness, accessibility, and failure recovery require separate evidence.'], ['Why did a metric change after restart?', 'Cold caches, workload, device state, and measurement lifecycle can differ.']], related: ['hibernation', 'diagnostics', 'status'],
  },
  {
    id: 'support', title: 'Support, feedback, and responsible reporting', category: 'Recovery', policy: 'manual', entry: 'Support Scriptor from the palette or optional top-bar action.', prerequisite: 'A reproducible issue or a clear question about current behavior.',
    safety: 'Support links may open an external browser/mail application. Never include account tokens, passwords, or an unredacted private vault.', source: 'src/components/SupportPanel.tsx', roots: ['.support-panel'],
    steps: [['Check local guidance first', 'Search the feature guide and Q&A for prerequisites and known limitations. Help remains usable offline.'], ['Describe the outcome', 'Write the steps, expected result, actual behavior, version, and environment. Distinguish a feature request from a regression.'], ['Minimize the example', 'Use redacted screenshots and disposable sample notes that reproduce the problem. Remove unrelated personal data.'], ['Choose the destination', 'Review the issue/email destination and send only when ready. Reading this guide does not submit a report.']],
    questions: [['Does Help automatically contact support?', 'No. It is an offline knowledge base. External contact requires your explicit action.'], ['Should I report an experimental limitation?', 'Yes when useful, while identifying the feature maturity and the actual observed behavior.']], related: ['help', 'diagnostics', 'recovery'],
  },
]
