import { body, type GuideTranslations } from './translationTypes.ts'

export const writingTranslations: GuideTranslations = {
  templates: {
    de: body('Notizen aus Vorlagen erstellen', 'Aus Vorlage oder Vorlagenauswahl.', 'Ein geöffneter Tresor mit verfügbaren Vorlagen.', 'Eine neue Notiz schreibt eine Datei. Prüfen Sie Ziel und Namen und vermeiden Sie das Überschreiben vorhandener Notizen.', [
      ['Struktur wählen', 'Lesen Sie Name und Zweck der Vorlage. Passt keine, beginnen Sie mit einer leeren Notiz.'], ['Ziel prüfen', 'Prüfen Sie Titel, Ordner und erzeugten Dateinamen. Eine Vorlage ist ein Ausgangspunkt, kein anderes Dokumentformat.'], ['Inhalt prüfen', 'Ersetzen Sie Platzhalter, kontrollieren Sie Datum und Frontmatter und entfernen Sie unpassende Abschnitte.'], ['Vorlage pflegen', 'Ändern Sie die Vorlage für künftige Notizen. Bestehende Notizen übernehmen spätere Änderungen nicht automatisch.'],
    ], [['Warum änderten sich alte Notizen nicht?', 'Vorlagen erzeugen den Anfangsinhalt; sie sind keine dauerhaft verknüpften Dokumente.'], ['Wie behebe ich fehlende Platzhalter?', 'Bearbeiten Sie die erzeugte Markdown-Datei direkt und korrigieren Sie anschließend die Vorlage für weitere Notizen.']]),
    fa: body('ساخت یادداشت از الگو', 'ساخت از الگو یا انتخابگر الگو.', 'مخزنی با الگوهای قابل‌دسترسی باز باشد.', 'ایجاد یادداشت فایل جدید می‌نویسد. مقصد و نام را بررسی و از بازنویسی یادداشت موجود جلوگیری کنید.', [
      ['انتخاب ساختار اولیه', 'نام و هدف الگو را بخوانید. اگر مناسب نیست، با یادداشت خالی شروع کنید.'], ['بررسی مقصد', 'عنوان، پوشه و نام فایل ساخته‌شده را بررسی کنید. الگو نقطهٔ شروع است، نه قالب فایل متفاوت.'], ['بررسی متن ساخته‌شده', 'جای‌نگهدارها را عوض کنید، تاریخ و frontmatter را ببینید و بخش نامربوط را حذف کنید.'], ['نگهداری الگو', 'منبع الگو را برای یادداشت آینده تغییر دهید. یادداشت موجود تغییر بعدی الگو را خودکار دریافت نمی‌کند.'],
    ], [['چرا یادداشت قدیمی تغییر نکرد؟', 'الگو متن آغازین می‌سازد؛ سند با پیوند زنده نیست.'], ['جای‌نگهدار ناقص را کجا اصلاح کنم؟', 'Markdown ساخته‌شده را مستقیم ویرایش و سپس الگو را برای یادداشت بعدی اصلاح کنید.']]),
  },
  snippets: {
    de: body('Textbausteine und wiederverwendbare Blöcke', 'Textbausteine verwalten in Palette oder Tresormenü.', 'Öffnen Sie den gewünschten Tresor und zum Einfügen die richtige Notiz.', 'Katalog speichern verändert künftige Einfügungen. Einfügen verändert die aktive Notiz am Cursor.', [
      ['Katalog und Notiz unterscheiden', 'Einen gespeicherten Baustein zu bearbeiten ist etwas anderes als ihn einzufügen. Benennen Sie ihn nach seinem Zweck.'], ['Syntax bewahren', 'Tabellen, Callouts, Überschriften und Codeblöcke benötigen passende Blockgrenzen. Inline-Bausteine sollten keine unerwarteten ganzen Blöcke einfügen.'], ['Speichern, dann einfügen', 'Speichern Sie den Katalog, wechseln Sie zur richtigen Notiz, setzen Sie den Cursor und fügen Sie ein. Prüfen Sie Quelltext und Vorschau.'], ['Sicher ändern', 'Änderungen gelten für spätere Nutzungen, nicht für vorhandene Kopien. Löschen entfernt keine bereits eingefügten Notizinhalte.'],
    ], [['Warum laufen zwei Bausteine zusammen?', 'Zwischen Blöcken fehlen möglicherweise Leerzeilen. Machen Sie rückgängig und fügen Sie auf getrennten Zeilen ein.'], ['Führt ein Baustein seinen Code aus?', 'Einfügen schreibt Text. Externe Ausführung benötigt eine eigene ausdrückliche Aktion und Berechtigung.']]),
    fa: body('فهرست قطعه‌ها و بلوک‌های قابل‌استفادهٔ دوباره', 'مدیریت قطعه‌ها در فرمان‌ها یا منوی مخزن.', 'مخزن موردنظر و برای درج، یادداشت درست باز باشد.', 'ذخیرهٔ فهرست درجهای بعدی را تغییر می‌دهد. درج قطعه، یادداشت فعال را در محل نشانگر تغییر می‌دهد.', [
      ['تفاوت فهرست و یادداشت', 'ویرایش قطعهٔ ذخیره‌شده با درج آن فرق دارد. قطعه را بر اساس کاربرد نام‌گذاری کنید.'], ['حفظ نحو', 'جدول، کادر، عنوان و بلوک کد به مرز درست نیاز دارند. قطعهٔ درون‌خطی نباید ناگهان بلوک کامل اضافه کند.'], ['ذخیره سپس درج', 'فهرست را ذخیره کنید، به یادداشت درست برگردید، نشانگر را بگذارید و درج کنید. سپس منبع و پیش‌نمایش را ببینید.'], ['اصلاح ایمن', 'تغییر برای استفادهٔ بعدی است، نه کپی قبلی. حذف قطعه، متن درج‌شده در یادداشت‌ها را حذف نمی‌کند.'],
    ], [['چرا دو قطعه به هم چسبیدند؟', 'ممکن است خط خالی بین بلوک‌ها نباشد. واگرد کنید و روی خط‌های جدا درج کنید.'], ['قطعه کد خود را اجرا می‌کند؟', 'درج فقط متن می‌نویسد. اجرای بیرونی به عمل و مجوز صریح جداگانه نیاز دارد.']]),
  },
  focus: {
    de: body('Fokus, Schreibmaschinenmodus, Rechtschreibung und Engines', 'Editor-Werkzeuge > Ansicht oder Erweitert; Editor-Einstellungen.', 'Ein aktiver Editor; manche Funktionen sind CodeMirror-spezifisch.', 'Dies sind Bearbeitungs- und Ansichtseinstellungen, keine Korrektheitsgarantien. LanguageTool und KI benötigen eigene Netzwerk- und Einrichtungskontrolle.', [
      ['Ablenkung verringern', 'Fokus beruhigt die umgebenden Bedienelemente. Behalten Sie einen zugänglichen Ausweg über Werkzeuge oder Ihr Tastenkürzel.'], ['Position halten', 'Der Schreibmaschinenmodus folgt der aktuellen Zeile. Schalten Sie ihn beim Vergleich entfernter Abschnitte oder störender Bewegung aus.'], ['Prüfwerkzeuge bewusst nutzen', 'Rechtschreib- und Grammatikhinweise brauchen menschliche Prüfung. Kontrollieren Sie Wörterbuch und Endpunkt. Nicht unterstützte Engine-Funktionen gelten nicht automatisch als aktiv.'], ['Engine bewusst wechseln', 'CodeMirror ist Standard; Monaco wird als erweiterte Option bei Bedarf geladen. Markdown bleibt maßgeblich, Erweiterungen können abweichen.'],
    ], [['Warum wirkt ein Schalter in Monaco nicht?', 'Die Erweiterung kann nur für CodeMirror implementiert sein. Wählen Sie eine unterstützte Engine oder einen anderen Prüfvorgang.'], ['Bleibt Grammatikprüfung lokal?', 'Das hängt vom Endpunkt ab. Prüfen Sie die Integration vor dem Einschalten eines Netzwerkdienstes.']]),
    fa: body('تمرکز، حالت ماشین‌تحریر، غلط‌یابی و موتور ویرایش', 'ابزارهای ویرایشگر > نما یا پیشرفته؛ ترجیح‌های ویرایشگر.', 'ویرایشگر فعال؛ بعضی قابلیت‌ها مخصوص CodeMirror هستند.', 'این‌ها ترجیح ویرایش و نما هستند، نه تضمین درست‌نویسی. LanguageTool و هوش مصنوعی تنظیم و پیامد شبکهٔ جدا دارند.', [
      ['کاهش حواس‌پرتی', 'تمرکز کنترل‌های اطراف را آرام می‌کند. راه خروج با ابزارها یا میان‌بر تنظیم‌شده را در دسترس نگه دارید.'], ['حفظ جای خواندن', 'حالت ماشین‌تحریر خط فعلی را دنبال می‌کند. هنگام مقایسهٔ بخش دور یا اگر حرکت آزاردهنده است، خاموشش کنید.'], ['استفادهٔ آگاهانه از بررسی', 'پیشنهاد املا و دستور به بررسی انسانی نیاز دارد. فرهنگ و نشانی سرویس را بررسی کنید؛ قابلیت پشتیبانی‌نشدهٔ موتور را فعال فرض نکنید.'], ['تغییر آگاهانهٔ موتور', 'CodeMirror پیش‌فرض است. Monaco گزینهٔ پیشرفته است که هنگام نیاز بارگذاری می‌شود؛ Markdown منبع باقی می‌ماند و افزونه‌ها ممکن است متفاوت باشند.'],
    ], [['چرا کلید در Monaco اثری ندارد؟', 'ممکن است افزونه فقط برای CodeMirror پیاده‌سازی شده باشد. موتور پشتیبانی‌شده یا راه دیگر بررسی را انتخاب کنید.'], ['ابزار دستور همهٔ متن را محلی نگه می‌دارد؟', 'به سرویس تنظیم‌شده بستگی دارد. پیش از فعال کردن خدمت شبکه‌ای، تنظیم یکپارچه‌سازی را بررسی کنید.']]),
  },
  'writing-targets': {
    de: body('Schreibziele und Dokumentstatistik', 'Schreibziele in Werkzeuge oder Befehlspalette.', 'Öffnen Sie eine Notiz und wählen Sie ein sinnvolles Ziel.', 'Zählwerte und Ziele helfen beim Schreiben; sie bewerten weder Qualität noch Veröffentlichungsreife.', [
      ['Nützliches Ziel setzen', 'Wählen Sie ein zum Dokument oder zur Sitzung passendes Ziel statt einer beliebigen Zahl.'], ['Zählwerte verstehen', 'Wörter, Zeichen und Lesezeit können Markdown, Code und Metadaten unterschiedlich berücksichtigen. Nutzen Sie Trends statt exakter Vergleiche zwischen Werkzeugen.'], ['Fortschritt prüfen', 'Vergleichen Sie tatsächliche Schreibarbeit und Ziel. Zielerreichung beweist weder Richtigkeit noch gute Belege oder erfolgreiches Speichern.'], ['Anpassen oder beenden', 'Ändern Sie unrealistische Ziele. Fehlender Verlauf ist von einer tatsächlich arbeitsfreien Sitzung zu unterscheiden.'],
    ], [['Warum zählt ein anderer Editor anders?', 'Regeln unterscheiden sich für Markup, Code, Satzzeichen und Sprachen.'], ['Bedeutet Ziel erreicht, dass die Notiz gespeichert ist?', 'Nein. Prüfen Sie immer den Speicherzustand des Dokuments.']]),
    fa: body('هدف نوشتن و آمار سند', 'هدف‌های نوشتن در ابزارها یا فهرست فرمان‌ها.', 'یادداشت را باز و هدف معنادار انتخاب کنید.', 'شمارش و هدف ابزار کمک به نوشتن‌اند، نه امتیاز کیفیت یا آمادگی انتشار.', [
      ['هدف مفید', 'هدفی مناسب سند یا نشست تعیین کنید، نه عددی دلخواه.'], ['تفسیر شمارش', 'برآورد واژه، نویسه و زمان خواندن ممکن است Markdown، کد و فراداده را متفاوت بشمارد. روند را بسنجید، نه برابری دقیق با ابزار دیگر.'], ['بررسی پیشرفت', 'نوشتن واقعی را با هدف مقایسه کنید. رسیدن به هدف، درستی، کیفیت شواهد یا موفقیت ذخیره را ثابت نمی‌کند.'], ['اصلاح یا توقف', 'هدف غیرواقعی را عوض کنید. نبودن تاریخچه را جدا از نشست واقعاً بدون نوشتن بررسی کنید.'],
    ], [['چرا ویرایشگر دیگر متفاوت می‌شمارد؟', 'قواعد شمارش نشانه‌گذاری، کد، علائم و زبان‌ها متفاوت‌اند.'], ['رسیدن به هدف یعنی یادداشت ذخیره شده؟', 'خیر. برای اطمینان از ماندگاری، وضعیت ذخیرهٔ سند را بررسی کنید.']]),
  },
  'toolbar-customize': {
    de: body('Editor-Werkzeugleiste anpassen', 'Editor-Werkzeuge > Werkzeugleiste anpassen oder die Schieberegler-Schaltfläche.', 'Keine externe Verbindung nötig.', 'Änderungen werden erst mit Anwenden übernommen. Abbrechen lässt die Werkzeugleiste unverändert. Einstellungen sind lokal und kein Notizinhalt.', [
      ['Nach Häufigkeit anheften', 'Wählen Sie nur oft benötigte Aktionen; andere bleiben in Werkzeuge verfügbar. Beginnen Sie mit einer kleinen Auswahl fürs Schreiben.'], ['Reihenfolge ändern', 'Nutzen Sie Früher/Später verschieben. Das verschiebt die Aktion, keinen Dokumentabschnitt.'], ['Automatische Breiten', 'Lassen Sie Textmenüs auf Auto. Nutzen Sie Pixelbreiten nur bei Bedarf und prüfen Sie kleine Fenster und übersetzte Beschriftungen.'], ['Anwenden oder abbrechen', 'Anwenden speichert den Entwurf, Abbrechen verwirft ihn. Auch Zurücksetzen im Dialog wartet auf Anwenden. Beachten Sie Speicherwarnungen.'],
    ], [['Löscht Zurücksetzen meine Notizen?', 'Nein. Es setzt nur die Werkzeugleisten-Einstellungen zurück.'], ['Warum fehlt die Anpassung nach einem Neustart?', 'Browser-/Webview-Speicher kann blockiert oder voll sein. Beheben Sie die gemeldete Ursache und versuchen Sie erneut zu speichern.']]),
    fa: body('شخصی‌سازی نوار ابزار ویرایشگر', 'ابزارهای ویرایشگر > شخصی‌سازی نوار ابزار یا دکمهٔ لغزنده‌ها.', 'اتصال بیرونی لازم نیست.', 'تغییرها تا اعمال، پیش‌نویس‌اند. انصراف نوار زنده را تغییر نمی‌دهد. ترجیح‌ها محلی‌اند و جزو متن یادداشت نیستند.', [
      ['سنجاق بر اساس کاربرد', 'فقط عمل‌های پرکاربرد را انتخاب کنید؛ بقیه در ابزارها می‌مانند. با مجموعه‌ای کوچک برای نوشتن شروع کنید.'], ['ترتیب کنترل‌ها', 'از جابه‌جایی زودتر یا دیرتر استفاده کنید. جای عمل عوض می‌شود، نه بخش سند.'], ['عرض خودکار', 'عرض منوی متنی را روی خودکار بگذارید. عرض پیکسلی فقط در صورت نیاز و پس از بررسی پنجرهٔ باریک و عنوان ترجمه‌شده مناسب است.'], ['اعمال یا انصراف', 'اعمال پیش‌نویس ترجیح‌ها را ذخیره و انصراف آن را کنار می‌گذارد. بازنشانی داخل پنجره نیز تا اعمال، موقت است. هشدار ذخیره را بررسی کنید.'],
    ], [['بازنشانی یادداشت‌ها را پاک می‌کند؟', 'خیر. فقط ترجیح‌های نوار ابزار بازنشانی می‌شوند.'], ['چرا شخصی‌سازی پس از اجرا باقی نماند؟', 'فضای ذخیرهٔ مرورگر یا وب‌ویو ممکن است مسدود یا پر باشد. هشدار را بخوانید، دسترسی ذخیره را اصلاح و دوباره تلاش کنید.']]),
  },
  preview: {
    de: body('Gerenderte Ausgabe, Diagramme und Einbettungen', 'Geteilt/Vorschau im Editor oder Gerenderte Ausgabe im Inspektor.', 'Eine Markdown-Notiz; manche Renderer benötigen separat konfigurierte Funktionen.', 'Vorschau zu lesen erlaubt weder Netzwerkanfragen noch Codeausführung. Externe Darstellung kann eigene Einrichtung benötigen.', [
      ['Markdown-Struktur prüfen', 'Überschriften, Listen, Tabellen und Callouts hängen von der Syntax ab. Korrigieren Sie fehlerhaften Quelltext; Vorschau ist keine unabhängige zweite Dokumentkopie.'], ['Metadaten trennen', 'Frontmatter am Anfang beschreibt die Notiz und ist kein Fließtext. Prüfen Sie Trennzeichen, wenn Metadaten im Dokument erscheinen.'], ['Renderer-Meldungen lesen', 'Diagramm-Platzhalter und Fehler können Syntax, Abhängigkeiten, Berechtigungen oder Zeitlimits betreffen. Der übrige Text sollte lesbar bleiben.'], ['Export separat vergleichen', 'Vorschau und Export können verschiedene Engines nutzen. Prüfen Sie den Export vorab und lesen Sie die erzeugte Datei vor dem Teilen.'],
    ], [['Warum erscheint mein Diagramm nicht?', 'Prüfen Sie zuerst Sprache und Syntax des Codeblocks, dann Abhängigkeiten, Funktion und Fehlermeldung. Aktivieren Sie keine externe Ausführung nur zum Beseitigen eines Fehlers.'], ['Warum zeigt ein Callout rohe Markierungen?', 'Prüfen Sie Leerzeilen und Blockgrenzen, besonders nach wiederholtem Einfügen. Eine zweite benachbarte Markierung kann als normaler Text erscheinen.']]),
    fa: body('خروجی رندرشده، نمودار و محتوای جاسازی‌شده', 'دوگانه یا پیش‌نمایش در ویرایشگر؛ خروجی رندرشده در نوار بررسی.', 'یادداشت Markdown؛ بعضی رندرگرها به قابلیت تنظیم‌شدهٔ جداگانه نیاز دارند.', 'خواندن پیش‌نمایش مجوز درخواست شبکه یا اجرای کد نیست. رندر بیرونی ممکن است راه‌اندازی صریح بخواهد.', [
      ['بررسی ساختار Markdown', 'عنوان، فهرست، جدول و کادر به نحو منبع وابسته‌اند. منبع نادرست را اصلاح کنید؛ پیش‌نمایش نسخهٔ مستقل دیگری از سند نیست.'], ['جداسازی فراداده', 'frontmatter ابتدای یادداشت، توصیف آن است نه متن اصلی. اگر در سند دیده می‌شود، جداکننده‌ها را بررسی کنید.'], ['خواندن پیام رندرگر', 'جای‌نگهدار و خطای نمودار می‌تواند از نحو، وابستگی، مجوز یا محدودیت زمان باشد. متن پایه باید خوانا بماند.'], ['مقایسهٔ جداگانهٔ خروجی', 'پیش‌نمایش و خروجی ممکن است موتور متفاوت داشته باشند. پیش‌بررسی خروجی را اجرا و فایل حاصل را پیش از اشتراک بررسی کنید.'],
    ], [['چرا نمودار رندر نمی‌شود؟', 'اول زبان بلوک کد و نحو، سپس وابستگی، قابلیت و پیام خطای نمایش‌داده‌شده را بررسی کنید. صرفاً برای پنهان کردن خطا اجرای بیرونی را فعال نکنید.'], ['چرا کادر نشانه‌های خام را نشان می‌دهد؟', 'خط خالی و مرز بلوک را، به‌خصوص پس از درج تکراری، بررسی کنید. نشانهٔ دوم چسبیده ممکن است متن معمولی شود.']]),
  },
  frontmatter: {
    de: body('Frontmatter und Notizmetadaten', 'Editor-Werkzeuge > Frontmatter; Metadaten-Steuerelemente.', 'Eine aktive Notiz.', 'Metadaten können Organisation, Veröffentlichungsfreigabe oder Automatisierung verändern. Prüfen Sie Werte vor dem Speichern.', [
      ['Block finden', 'Frontmatter gehört zwischen unterstützte Trennzeichen am Notizanfang. Fügen Sie keinen zweiten Block mitten im Text ein.'], ['Gültige Werte', 'Prüfen Sie YAML-Syntax, Einrückung, Anführungszeichen und Feldtypen. Sichtbare Trennzeichen allein beweisen keine gültigen Metadaten.'], ['Besondere Felder prüfen', 'Organisations- und Veröffentlichungsfelder steuern getrennte Abläufe. Eine Veröffentlichungsfreigabe führt keinen Export und keine Bereitstellung aus.'], ['Prüfen und wiederherstellen', 'Kontrollieren Sie Vorschau und Zustandswarnungen. Nutzen Sie Rückgängig oder Notizverlauf bei unerwarteten Folgen.'],
    ], [['Soll ich _organized als internes Feld löschen?', 'Nicht automatisch. Das Feld speichert den Organisationszustand. Beheben Sie Darstellungsfehler oder Trennzeichen, statt brauchbare Metadaten ungeprüft zu löschen.'], ['Lädt publish: true meine Notiz hoch?', 'Nein. Die Notiz wird Kandidatin eines gesondert geprüften Veröffentlichungsablaufs.']]),
    fa: body('frontmatter و فرادادهٔ یادداشت', 'ابزارهای ویرایشگر > frontmatter؛ کنترل‌های فراداده.', 'یادداشت فعال باشد.', 'فراداده ممکن است سامان‌دهی، صلاحیت انتشار یا خودکارسازی را تغییر دهد. مقدارها را پیش از ذخیره بررسی کنید.', [
      ['پیدا کردن بلوک', 'frontmatter بین جداکننده‌های پشتیبانی‌شده در آغاز یادداشت است. بلوک دیگری وسط متن درج نکنید.'], ['مقدار معتبر', 'نحو YAML، تورفتگی، نقل‌قول و نوع فیلد را بررسی کنید. دیدن جداکننده به‌تنهایی درستی فراداده را ثابت نمی‌کند.'], ['بررسی فیلدهای ویژه', 'فیلد سامان‌دهی و انتشار روندهای جدا دارند. صلاحیت انتشار، خودِ خروجی گرفتن یا استقرار نیست.'], ['تأیید و بازیابی', 'پیش‌نمایش و هشدار سلامت را بررسی کنید. برای پیامد ناخواسته از واگرد یا تاریخچهٔ یادداشت استفاده کنید.'],
    ], [['فیلد داخلی _organized را حذف کنم؟', 'خودکار نه. این فیلد وضعیت سامان‌دهی را نگه می‌دارد. رندر یا جداکنندهٔ خراب را اصلاح کنید، نه اینکه فرادادهٔ مفید را بی‌بررسی حذف کنید.'], ['publish: true یادداشت را بارگذاری می‌کند؟', 'خیر. فقط آن را نامزد روند جداگانه و بررسی‌شدهٔ انتشار می‌کند.']]),
  },
  daily: {
    de: body('Tagesnotizen und Datumsnavigation', 'Heute sowie vorheriger/nächster Tag in der Seitenleiste.', 'Ein offener Tresor; prüfen Sie Tagesnotiz-Ordner und Dateinamenvorlage.', 'Das Öffnen eines fehlenden Tages kann eine Notiz erstellen. Prüfen Sie Pfade und Datum vorher.', [
      ['Datum prüfen', 'Heute verwendet das lokale Datum. Vorheriger/nächster Tag ändert das angeforderte Tagesdatum, nicht den Bearbeitungsverlauf.'], ['Konfiguration prüfen', 'Einstellungen bestimmen Ordner, Dateinamensmuster und Vorlage. Prüfen Sie das Ziel vor Änderungen.'], ['Öffnen oder erstellen', 'Wählen Sie den Tag. Vorhandene Inhalte werden geöffnet, nicht ersetzt. Beheben Sie Pfad- und Namensfehler vor einer Wiederholung.'], ['Eintrag verknüpfen', 'Verbinden Sie Tagesarbeit mit Projektnotizen durch Markdown-Links oder Wikilinks. Tagesnotizen bleiben portable Dateien.'],
    ], [['Warum liegt die Tagesnotiz in einem anderen Ordner?', 'Die Tagesnotiz-Konfiguration des Tresors bestimmt ihren Pfad.'], ['Kann eine Tagesvorlage einen vorhandenen Tag überschreiben?', 'Behandeln Sie Namenskollisionen als Öffnen und Prüfen; eine Vorlage ist kein automatisch sicherer Ersatz.']]),
    fa: body('یادداشت روزانه و پیمایش تاریخ', 'امروز و کنترل روز قبل یا بعد در نوار کناری.', 'مخزن باز باشد؛ پوشه و الگوی نام یادداشت روزانه را بررسی کنید.', 'باز کردن روزی که هنوز یادداشت ندارد ممکن است فایل جدید بسازد. پیش از ایجاد، مسیر تنظیم‌شده و تاریخ را بررسی کنید.', [
      ['بررسی تاریخ', 'امروز از تاریخ محلی استفاده می‌کند. روز قبل یا بعد، تاریخ یادداشت درخواستی را عوض می‌کند نه تاریخچهٔ ویرایش را.'], ['بررسی تنظیم', 'تنظیمات پوشه، الگوی نام و قالب روزانه را تعیین می‌کند. پیش از تغییر مقصد را بررسی کنید.'], ['باز کردن یا ایجاد', 'روز را انتخاب کنید؛ محتوای موجود باید باز شود، نه جایگزین. خطای نام یا مسیر را پیش از تلاش دوباره حل کنید.'], ['پیوند دادن', 'با پیوند Markdown یا ویکی‌پیوند، کار روزانه را به یادداشت پروژه وصل کنید. یادداشت روزانه فایل قابل‌حمل است.'],
    ], [['چرا یادداشت روزانه در پوشهٔ دیگری است؟', 'تنظیم روزانهٔ مخزن مسیر آن را تعیین می‌کند.'], ['الگوی روزانه می‌تواند روز موجود را بازنویسی کند؟', 'برخورد نام را موقعیت باز کردن و بررسی بدانید؛ فرض نکنید اجرای الگو جایگزینی ایمن است.']]),
  },
  commands: {
    de: body('Befehlspalette und Tastaturnavigation', 'Befehlsfeld oben; Ctrl+K / Command+K.', 'Manche Befehle benötigen eine offene Notiz, einen Tresor oder eine aktivierte Funktion.', 'Die Palette zu öffnen ist schreibgeschützt. Ein Befehl kann einen eigenen Bestätigungs- oder Änderungsablauf starten.', [
      ['Aktion finden', 'Geben Sie Aktion oder Thema ein. Lesen Sie die Kategorie, um einen Befehl von einem Notiztreffer zu unterscheiden.'], ['Mit Tasten auswählen', 'Pfeiltasten wechseln den aktiven Treffer, Enter ruft ihn auf und Escape schließt die Palette. Notiztreffer können später als Befehle eintreffen.'], ['Verfügbarkeit beachten', 'Ein fehlender oder deaktivierter Befehl kann einen Tresor, eine aktive Notiz, Desktop-Unterstützung oder Plugin-Rechte benötigen. Umgehen Sie keine Funktionsprüfung.'], ['Hilfe finden', 'Suchen Sie Hilfe, Anleitung, FAQ oder Tour. F1 bezieht sich auf den Bereich mit dem aktuellen Fokus.'],
    ], [['Warum öffnet eine Aktion stattdessen Einstellungen?', 'Eine noch nicht konfigurierte Funktion kann zur Einrichtung oder Berechtigungsprüfung führen, statt ohne Meldung zu scheitern.'], ['Kann ich Tastenkürzel ändern?', 'Nutzen Sie Einstellungen > Tastenkürzel. Beheben Sie Konflikte und testen Sie die Belegung außerhalb eines Textfelds.']]),
    fa: body('فهرست فرمان‌ها و پیمایش با صفحه‌کلید', 'کادر فرمان بالا؛ Ctrl+K / Command+K.', 'بعضی فرمان‌ها به یادداشت باز، مخزن یا قابلیت فعال نیاز دارند.', 'باز کردن فهرست فقط‌خواندنی است. اجرای فرمان ممکن است روند جداگانهٔ تأیید یا تغییر را باز کند.', [
      ['پیدا کردن عمل', 'نام عمل یا موضوع را بنویسید. دستهٔ فرمان را بخوانید تا آن را از نتیجهٔ جست‌وجوی یادداشت تشخیص دهید.'], ['انتخاب با کلید', 'کلیدهای جهت نتیجهٔ فعال را عوض می‌کنند؛ Enter آن را اجرا می‌کند و Escape فهرست را می‌بندد. نتیجهٔ یادداشت ممکن است بعد از فرمان‌ها برسد.'], ['توجه به دسترسی', 'فرمان غایب یا غیرفعال ممکن است به مخزن، یادداشت فعال، نسخهٔ دسکتاپ یا مجوز افزونه نیاز داشته باشد. بررسی قابلیت را دور نزنید.'], ['پیدا کردن راهنما', 'راهنما، آموزش، FAQ یا تور را جست‌وجو کنید. F1 برای بخشی است که اکنون تمرکز دارد.'],
    ], [['چرا عمل، تنظیمات را باز می‌کند؟', 'قابلیت تنظیم‌نشده ممکن است به راه‌اندازی یا بررسی مجوز هدایت شود تا بی‌پیام شکست نخورد.'], ['می‌توانم میان‌برها را عوض کنم؟', 'به تنظیمات > میان‌برها بروید؛ تداخل‌ها را برطرف کنید و کلید را بیرون کادر متن آزمایش کنید.']]),
  },
  tabs: {
    de: body('Dokumenttabs und Navigationsverlauf', 'Tabzeile über dem Editor.', 'Öffnen Sie eine oder mehrere Notizen.', 'Einen Tab zu schließen löscht keine Datei. Beheben Sie Speicherfehler vor dem Schließen der App.', [
      ['Dokument auswählen', 'Prüfen Sie aktiven Tab und Pfad vor Schreiben, Umbenennen, Export oder Konfliktlösung.'], ['Wichtige Notizen behalten', 'Heften Sie häufig benötigte Tabs über die verfügbaren Steuerelemente an. Das schützt die Datei nicht vor externen Änderungen.'], ['Verlauf nutzen', 'Zurück/Vorwärts besucht frühere Notizen. Nutzen Sie letzte Notizen für bereits geschlossene Tabs.'], ['Sicher schließen', 'Beachten Sie Änderungs- und Speicherstatus. Tab schließen entfernt nur die Ansicht; ein Speicherfehler erfordert Wiederholung oder eine bewusste Wiederherstellung.'],
    ], [['Warum heißen zwei Tabs gleich?', 'Verschiedene Ordner können gleiche Dateinamen enthalten. Unterscheiden Sie sie am Pfad.'], ['Kommt meine Sitzung zurück?', 'Die Wiederherstellung des Arbeitsbereichs erfolgt nach Möglichkeit. Dateien und geprüfte Sicherungen bleiben maßgeblich.']]),
    fa: body('زبانهٔ سند و تاریخچهٔ پیمایش', 'ردیف زبانه‌ها بالای ویرایشگر.', 'یک یا چند یادداشت باز کنید.', 'بستن زبانه فایل را حذف نمی‌کند. پیش از بستن برنامه خطای ذخیره را حل کنید.', [
      ['انتخاب سند', 'پیش از تایپ، تغییر نام، خروجی گرفتن یا حل تعارض، زبانهٔ فعال و مسیر را بررسی کنید.'], ['نگه داشتن یادداشت مهم', 'زبانهٔ پرکاربرد را با کنترل سنجاق نگه دارید. سنجاق کردن جلوی تغییر بیرونی فایل را نمی‌گیرد.'], ['استفاده از تاریخچه', 'قبلی و بعدی یادداشت‌های بازشدهٔ پیشین را نشان می‌دهند. برای زبانهٔ بسته از یادداشت‌های اخیر استفاده کنید.'], ['بستن ایمن', 'وضعیت تغییر و ذخیره را ببینید. بستن زبانه فقط نما را برمی‌دارد؛ خطای ذخیره به تلاش دوباره یا تصمیم روشن برای بازیابی نیاز دارد.'],
    ], [['چرا دو زبانه عنوان یکسان دارند؟', 'پوشه‌های متفاوت ممکن است نام فایل یکسان داشته باشند. با مسیر تشخیص دهید.'], ['نشست من برمی‌گردد؟', 'بازگردانی نشست تا حد امکان انجام می‌شود. فایل‌ها و پشتیبان‌های بررسی‌شده مرجع بازیابی‌اند.']]),
  },
  editor: {
    de: body('Schreiben, speichern und Ansichten wechseln', 'Editor in der Mitte; Quelltext / Geteilt / Vorschau.', 'Öffnen Sie eine Markdown-Notiz. CodeMirror ist Standard, Monaco eine erweiterte Option.', 'Schreiben verändert das Dokument. Vorschau und Anleitung genehmigen keine Ausführung eingebetteten Codes.', [
      ['Im Quelltext beginnen', 'Setzen Sie den Cursor an die gewünschte Stelle. Nutzen Sie Rückgängig/Wiederholen und beobachten Sie nach Änderungen den Speicherstatus.'], ['Bei Bedarf visuell bearbeiten', 'Geteilt zeigt Quelltext und bearbeitbare Vorschau zusammen; Vorschau blendet den Quelltext aus. Beide bearbeiten denselben Markdown-Entwurf. Auf der aktiven Zeile erscheinen Syntaxzeichen für Korrekturen wieder.'], ['Endgültige Darstellung prüfen', 'Inspektor > Gerenderte Ausgabe zeigt das schreibgeschützte Renderer-Ergebnis mit Diagrammen und Erweiterungen.'], ['Bewusst einfügen', 'Markieren Sie Text für Inline-Formatierung; setzen Sie Blockinhalte auf eine eigene Zeile. Prüfen Sie Markdown nach dem Einfügen eines Bausteins.'], ['Speicherfehler behandeln', 'Sichtbarer Text ist nicht zwangsläufig gespeichert. Lesen Sie die Fehlermeldung, sichern Sie bei Bedarf eine Kopie und nutzen Sie Wiederholung oder Konfliktbehebung vor dem Wechsel.'],
    ], [['Warum ist der Editor gedimmt?', 'Fokus- oder ablenkungsfreier Modus kann die Umgebung abdunkeln. Beenden Sie ihn über Werkzeuge oder das Tastenkürzel. Ein echter Dialog blockiert vorübergehend den Hintergrund.'], ['Ändert ein Editorwechsel das Dateiformat?', 'Nein. Markdown bleibt das Format. Funktionen unterscheiden sich je nach Engine; nicht jede Erweiterung ist in Monaco verfügbar.']]),
    fa: body('نوشتن، ذخیره و تغییر نمای ویرایشگر', 'ویرایشگر مرکزی؛ منبع / دوگانه / پیش‌نمایش.', 'یادداشت Markdown باز کنید. CodeMirror پیش‌فرض است و Monaco گزینهٔ پیشرفته.', 'تایپ سند را تغییر می‌دهد. دیدن پیش‌نمایش یا راهنما مجوز اجرای کد درون سند نیست.', [
      ['شروع با منبع', 'نشانگر را در محل موردنظر بگذارید. برای ویرایش محلی از واگرد و انجام دوباره استفاده و بعد از تغییر وضعیت ذخیره را بررسی کنید.'], ['ویرایش دیداری در صورت نیاز', 'دوگانه منبع و پیش‌نمایش قابل‌ویرایش را کنار هم نشان می‌دهد؛ پیش‌نمایش پنل منبع را پنهان می‌کند. هر دو یک پیش‌نویس Markdown را ویرایش می‌کنند. نشانه‌های نحو روی خط فعال برای اصلاح دوباره ظاهر می‌شوند.'], ['کنترل رندر نهایی', 'بررسی > خروجی رندرشده نتیجهٔ فقط‌خواندنی رندرگر، از جمله نمودار و افزونه‌ها را نشان می‌دهد.'], ['درج آگاهانه', 'برای قالب‌بندی درون‌خطی متن را انتخاب کنید و برای بلوک روی خط جدا قرار بگیرید. پس از درج قطعه، Markdown حاصل را بررسی کنید.'], ['رسیدگی به شکست ذخیره', 'دیدن متن، ذخیره روی دیسک را اثبات نمی‌کند. خطا را بخوانید، در صورت نیاز کپی امن نگه دارید و پیش از خروج، تلاش دوباره یا بازیابی تعارض را انجام دهید.'],
    ], [['چرا ویرایشگر کم‌نور است؟', 'حالت تمرکز یا بدون حواس‌پرتی ممکن است کنترل‌های اطراف را کم‌نور کند. از ابزارها یا میان‌بر خارج شوید. پنجرهٔ واقعی نیز موقتاً کار با پشت‌زمینه را می‌بندد.'], ['تغییر موتور، قالب فایل را عوض می‌کند؟', 'خیر. قالب Markdown باقی می‌ماند. قابلیت‌های موتور متفاوت‌اند؛ همهٔ افزونه‌ها در Monaco در دسترس نیستند.']]),
  },
  toolbar: {
    de: body('Formatierung, Typografie, Einfügen und Werkzeuge', 'Befehlszeile des Editors.', 'Für Bearbeitungsbefehle muss eine Notiz geöffnet sein.', 'Formatierung und Einfügen wirken auf Auswahl oder Cursor. Werkzeug-Einstellungen verändern das Bearbeitungsverhalten.', [
      ['Häufige Aktionen', 'Fett, kursiv und Links liegen nahe am Text. Markieren Sie vorhandenen Text, bevor Sie ihn formatieren.'], ['Gruppe wählen', 'Typografie verändert Schreibkonventionen; Einfügen ergänzt Strukturen; Werkzeuge bündelt Prüfung, Ansichten und erweiterte Steuerelemente.'], ['Schalterzustand lesen', 'Fokus, Rechtschreibprüfung, Editor-Theme und Engine sind Einstellungen, keine Textformatierungen. Ein deaktiviertes Element kann enginespezifisch sein.'], ['Breite anpassen', 'Kompakte Bedienelemente behalten zugängliche Namen. Heften Sie nur häufig benötigte Aktionen an.'],
    ], [['Warum wurde der falsche Text geändert?', 'Befehle wirken auf das aktive Dokument und die Auswahl. Machen Sie rückgängig, stellen Sie die Auswahl wieder her und wiederholen Sie.'], ['Ruft KI-Zusammenfassung einfügen ein Modell auf?', 'Es fügt eine Markdown-KI-Callout-Vorlage ein. Anbieteranfragen gehören zum separaten, ausdrücklich aktivierten KI-Ablauf.']]),
    fa: body('قالب‌بندی، تایپوگرافی، درج و ابزارها', 'ردیف فرمان‌های ویرایشگر.', 'برای فرمان ویرایش، یادداشت باز باشد.', 'قالب‌بندی و درج روی انتخاب یا نشانگر فعلی عمل می‌کنند. تنظیم ابزارها رفتار ویرایش را تغییر می‌دهد.', [
      ['عمل‌های پرکاربرد', 'درشت، کج و پیوند نزدیک متن قرار دارند. برای تغییر متن موجود، اول آن را انتخاب کنید.'], ['انتخاب گروه', 'تایپوگرافی رسم نوشتن را اصلاح می‌کند؛ درج ساختار می‌افزاید؛ ابزارها بررسی، نما و کنترل‌های پیشرفته را گروه‌بندی می‌کند.'], ['خواندن وضعیت کلید', 'تمرکز، غلط‌یابی، پوسته و موتور ترجیح ویرایش‌اند، نه قالب‌بندی سند. کنترل غیرفعال ممکن است به موتور خاص وابسته باشد.'], ['سازگاری با عرض', 'کنترل فشرده نام قابل‌دسترسی خود را حفظ می‌کند. فقط عمل‌های پرکاربرد را سنجاق کنید، نه همهٔ فهرست را.'],
    ], [['چرا فرمان متن اشتباه را تغییر داد؟', 'فرمان روی سند فعال و نشانگر یا انتخاب عمل می‌کند. واگرد کنید، انتخاب را اصلاح و دوباره تلاش کنید.'], ['درج خلاصهٔ هوش مصنوعی مدل را فراخوانی می‌کند؟', 'این درج، الگوی کادر Markdown هوش مصنوعی می‌سازد. درخواست واقعی مدل مربوط به روند جداگانهٔ اختیاری هوش مصنوعی است.']]),
  },
  workspace: {
    de: body('Grundlagen des Arbeitsbereichs', 'Beim ersten Start, über Hilfe & Anleitungen oder F1.', 'Diese Einführung benötigt weder einen Tresor noch ein externes Konto.', 'Touren erklären Bedienelemente. Sie erstellen, senden, starten, löschen oder veröffentlichen nichts für Sie.', [
      ['Ihr Tresor', 'Scriptor arbeitet mit einem Ordner voller Markdown-Notizen. Tresor öffnen wählt den Ordner; der geöffnete Tresor erscheint links. Sichern Sie wichtige Arbeit zusätzlich unabhängig.'],
      ['Notizen suchen', 'Die Seitenleiste durchsucht Notiztexte. F fokussiert die Suche, solange Sie nicht schreiben. Die Suche verändert keine Dateien.'],
      ['Befehlspalette', 'Nutzen Sie das Befehlsfeld, Ctrl+K unter Windows/Linux oder Command+K unter macOS. Suchen Sie einen Befehl oder eine Notiz, wählen Sie mit den Pfeiltasten und drücken Sie Enter.'],
      ['Inspektor', 'Rechts finden Sie Struktur, Links, Referenzen, gerenderte Ausgabe und Plugin-Werkzeuge. Klappen Sie die Leiste für mehr Schreibfläche ein.'],
      ['Editor-Werkzeuge', 'Quelltext zeigt Markdown; Geteilt zeigt Quelltext und bearbeitbare Vorschau nebeneinander. Vorschau ist eine bearbeitbare Markdown-Ansicht. Die gerenderte Ausgabe im Inspektor bleibt die abschließende schreibgeschützte Kontrolle. Typografie, Einfügen und Werkzeuge bündeln seltenere Befehle.'],
      ['Speichern und Wiederherstellen', 'Prüfen Sie Speicher- und Fehlerstatus vor dem Schließen oder Wechseln. Notizverlauf, Konflikte, Schnappschüsse und externe Sicherungen lösen unterschiedliche Probleme; ein Index ist keine Sicherung.'],
      ['Kontextbezogene Hilfe', 'F1 öffnet die Hilfe zur aktiven Funktion; Shift+F1 startet deren Tour. Umfangreiche optionale Bereiche können nach der Einführung einmal einen schließbaren Hinweis zeigen. Eine Tour startet nur auf Ihre Auswahl.'],
    ], [['Bedient eine Tour die App für mich?', 'Nein. Weiter bestätigt einen Leseschritt, keinen erfolgreichen Vorgang. Dieses Bedienelement zeigen macht ein bereits sichtbares Element sichtbar oder fokussiert es.'], ['Kann ich überspringen und später zurückkehren?', 'Ja. Überspringen Sie die Einführung und öffnen Sie später F1 oder Hilfe & Anleitungen. Der Tourfortschritt wird lokal und unabhängig von Ihren Notizen gespeichert.']]),
    fa: body('مبانی فضای کار', 'هنگام اولین اجرا، از راهنما و آموزش یا با F1.', 'برای خواندن این مقدمه به مخزن یا حساب بیرونی نیاز ندارید.', 'آموزش فقط کنترل‌ها را توضیح می‌دهد؛ چیزی ایجاد، ارسال، اجرا، حذف یا منتشر نمی‌کند.', [
      ['مخزن شما', 'Scriptor با پوشه‌ای از یادداشت‌های Markdown کار می‌کند. باز کردن مخزن پوشه را انتخاب می‌کند و مخزن بازشده در نوار کناری دیده می‌شود. از کار مهم نسخهٔ پشتیبان مستقل نگه دارید.'],
      ['جست‌وجوی یادداشت', 'جست‌وجوی نوار کناری متن یادداشت‌ها را پیدا می‌کند. وقتی در حال تایپ نیستید، F جست‌وجو را فعال می‌کند. جست‌وجو فایل‌ها را تغییر نمی‌دهد.'],
      ['فهرست فرمان‌ها', 'از کادر فرمان، Ctrl+K در Windows/Linux یا Command+K در macOS استفاده کنید. فرمان یا یادداشت را جست‌وجو کنید، با کلیدهای جهت انتخاب کنید و Enter بزنید.'],
      ['نوار بررسی', 'نوار سمت دیگر ساختار، پیوندها، منابع، خروجی رندرشده و ابزارهای افزونه را نشان می‌دهد. برای فضای نوشتن بیشتر آن را جمع کنید.'],
      ['ابزارهای ویرایشگر', 'حالت منبع نحو Markdown را نشان می‌دهد؛ حالت دوگانه منبع و پیش‌نمایش قابل‌ویرایش را کنار هم قرار می‌دهد. پیش‌نمایش نیز نمای قابل‌ویرایش Markdown است. خروجی رندرشده در نوار بررسی، کنترل نهایی و فقط‌خواندنی است. تایپوگرافی، درج و ابزارها فرمان‌های کم‌کاربردتر را گروه‌بندی می‌کنند.'],
      ['ذخیره و بازیابی', 'پیش از بستن یا تغییر کار، وضعیت ذخیره و خطا را بررسی کنید. تاریخچهٔ یادداشت، تعارض، عکس فوری و پشتیبان بیرونی مسائل متفاوتی را حل می‌کنند؛ نمایه جای پشتیبان نیست.'],
      ['راهنمای همان بخش', 'F1 راهنمای قابلیت فعال و Shift+F1 آموزش آن را باز می‌کند. بخش‌های اختیاری پیچیده ممکن است پس از معرفی اولیه یک پیام قابل‌بستن نشان دهند. آموزش فقط با انتخاب شما شروع می‌شود.'],
    ], [['آموزش به‌جای من با برنامه کار می‌کند؟', 'خیر. بعدی تأیید خواندن یک گام است، نه موفقیت عملیات. نمایش این کنترل فقط کنترل از قبل قابل‌دسترسی را نشان می‌دهد یا روی آن تمرکز می‌کند.'], ['می‌توانم رد کنم و بعد برگردم؟', 'بله. معرفی اولیه را رد کنید و بعد با F1 یا راهنما و آموزش برگردید. پیشرفت آموزش محلی و مستقل از یادداشت‌ها ذخیره می‌شود.']]),
  },
  vault: {
    de: body('Tresor und Dateien', 'Tresor öffnen in der Kopfleiste; Tresor-Seitenleiste.', 'Wählen Sie den gewünschten lokalen Ordner und warten Sie auf die Indexierung.', 'Die Dateien auf dem Datenträger sind maßgeblich. Ein Tresorwechsel verändert den Bereich aller folgenden Befehle.', [
      ['Bereich prüfen', 'Prüfen Sie vor Import oder Bearbeitung Tresorname und Ordner. Einen Tresor zu öffnen ist etwas anderes als einen Notiztab zu öffnen.'], ['Navigieren', 'Klappen Sie Ordner auf, wählen Sie Markdown-Notizen und kehren Sie über letzte Notizen oder Verlaufspfeile zurück. Zuklappen entfernt keinen Ordner.'], ['Bewusst erstellen', 'Nutzen Sie Neue Notiz oder Aus Vorlage. Prüfen Sie Ziel und Dateiname; gleiche Namen erzeugen nicht zwangsläufig eine weitere Kopie.'], ['Index pflegen', 'Erstellen Sie den Index nur bei veralteter Suche oder veralteten Links neu. Das stellt abgeleitete Daten wieder her, keine verlorenen Dokumente.'],
    ], [['Wo ist meine Notiz?', 'Löschen Sie Such- und Posteingangsfilter, öffnen Sie den Ordner und prüfen Sie den aktiven Tresor. Kontrollieren Sie anschließend den tatsächlichen Ordner auf dem Datenträger.'], ['Bedeutet eine leere Seitenleiste Datenverlust?', 'Nicht unbedingt. Laden, Filter, fehlende Berechtigungen und ein leerer Ordner sind unterschiedliche Zustände. Prüfen Sie den Status vor einer Wiederherstellung.']]),
    fa: body('پیمایش مخزن و فایل‌ها', 'باز کردن مخزن در نوار بالا؛ نوار کناری مخزن.', 'پوشهٔ محلی موردنظر را انتخاب کنید و منتظر نمایه‌سازی بمانید.', 'فایل‌های روی دیسک مرجع اصلی‌اند. تغییر مخزن دامنهٔ فرمان‌های بعدی را عوض می‌کند.', [
      ['دامنه را بررسی کنید', 'پیش از وارد کردن یا ویرایش، نام و پوشهٔ مخزن را بررسی کنید. باز کردن مخزن با باز کردن زبانهٔ یادداشت فرق دارد.'], ['پیمایش', 'پوشه‌ها را باز کنید، یادداشت Markdown را انتخاب کنید و با یادداشت‌های اخیر یا پیکان تاریخچه برگردید. جمع کردن پوشه آن را حذف نمی‌کند.'], ['ایجاد آگاهانه', 'از یادداشت جدید یا ساخت از الگو استفاده کنید. مقصد و نام فایل را بررسی کنید؛ نام تکراری لزوماً نسخهٔ جداگانه نمی‌سازد.'], ['نگهداری نمایه', 'فقط وقتی جست‌وجو یا پیوندها قدیمی‌اند نمایه را بازسازی کنید. بازسازی دادهٔ مشتق‌شده را برمی‌گرداند، نه متن ازدست‌رفته را.'],
    ], [['یادداشت من کجاست؟', 'فیلتر جست‌وجو و صندوق ورودی را پاک کنید، پوشه را باز کنید و مخزن فعال را بررسی کنید. سپس پوشهٔ واقعی روی دیسک را ببینید.'], ['نوار کناری خالی یعنی مخزن از دست رفته؟', 'لزوماً خیر. بارگذاری، فیلتر، خطای دسترسی و پوشهٔ خالی حالت‌های متفاوت‌اند. پیش از بازیابی وضعیت را بررسی کنید.']]),
  },
  inbox: {
    de: body('Posteingang und organisierte Notizen', 'Posteingang in der Tresor-Seitenleiste.', 'Ein geöffneter Tresor mit Notizen.', 'Als organisiert markieren ändert Metadaten; es löscht nichts, archiviert keine Gmail-Nachricht und erstellt keine Sicherung.', [
      ['Filter verstehen', 'Der Posteingang zeigt noch nicht organisierte Notizen. Ein leerer Posteingang bedeutet nicht, dass der Tresor leer ist.'], ['Vor der Einordnung lesen', 'Öffnen Sie den Eintrag und prüfen Sie Ablage, benötigte Links und einen verständlichen Titel.'], ['Organisieren', 'Markieren Sie die geprüfte Notiz als organisiert. Das ändert ihre Kennzeichnung, verschiebt aber nicht die Datei.'], ['Wiederfinden', 'Wechseln Sie zu Alle Notizen oder suchen Sie. Prüfen Sie bei unerwartetem Zustand die Frontmatter.'],
    ], [['Warum verschwand ein Eintrag?', 'Der Posteingang blendet organisierte Notizen aus. Die Datei bleibt unter Alle Notizen verfügbar.'], ['Ist eine organisierte Notiz veröffentlichungsreif?', 'Nein. Organisation, Tresorzustand, Exportbereitschaft und Veröffentlichungsfreigabe sind getrennte Prüfungen.']]),
    fa: body('صندوق ورودی و یادداشت‌های سامان‌یافته', 'صندوق ورودی در نوار کناری مخزن.', 'مخزنی دارای یادداشت باز باشد.', 'علامت سامان‌یافته فرادادهٔ یادداشت را تغییر می‌دهد؛ حذف، بایگانی Gmail یا پشتیبان‌گیری نیست.', [
      ['فیلتر را بشناسید', 'صندوق ورودی یادداشت‌های هنوز سامان‌نیافته را نشان می‌دهد. خالی بودن آن به معنی خالی بودن مخزن نیست.'], ['پیش از دسته‌بندی بخوانید', 'یادداشت را باز کنید و محل مناسب، پیوندهای لازم و روشنی عنوانش را بررسی کنید.'], ['سامان‌دهی', 'پس از بررسی، علامت سامان‌یافته را بزنید. این فقط نشانگر یادداشت را به‌روز می‌کند و فایل را به پوشهٔ دیگری نمی‌برد.'], ['دوباره پیدا کنید', 'به همهٔ یادداشت‌ها بروید یا جست‌وجو کنید. اگر وضعیت غیرمنتظره است frontmatter را بررسی کنید.'],
    ], [['چرا موردی ناپدید شد؟', 'فیلتر صندوق ورودی یادداشت سامان‌یافته را پنهان می‌کند. همان فایل را در همهٔ یادداشت‌ها پیدا کنید.'], ['سامان‌یافته یعنی آمادهٔ انتشار؟', 'خیر. سامان‌دهی، سلامت مخزن، آمادگی خروجی و مجوز انتشار بررسی‌های جداگانه‌اند.']]),
  },
  search: {
    de: body('Suche und Ergebnisnavigation', 'Notizsuche in der Seitenleiste und Suchergebnis-Dock.', 'Ein geöffneter, indexierter Tresor.', 'Die Suche ist schreibgeschützt und auf den aktiven Tresor und den gewählten Suchmodus beschränkt.', [
      ['Suchbegriff wählen', 'Beginnen Sie mit einem eindeutigen Wort aus Titel oder Text. Entfernen Sie Filter, wenn Sie prüfen, ob die Notiz im Index steht.'], ['Treffer prüfen', 'Lesen Sie Titel und Pfad zusammen. Gleiche Titel können verschiedene Dateien bezeichnen. Öffnen Sie den gewünschten Treffer.'], ['Modi unterscheiden', 'Standardsuche sucht Schlüsselwörter. Semantische Suche benötigt separat konfigurierte experimentelle Embeddings und ist nicht automatisch verfügbar.'], ['Veraltete Treffer beheben', 'Prüfen Sie den Indexstatus, warten Sie laufende Indexierung ab und bauen Sie nur bei Bedarf neu. Ein Suchfehler beweist nicht, dass Dateien fehlen.'],
    ], [['Warum fehlt eine bekannte Notiz?', 'Prüfen Sie Tresor, Indexstatus, Suchtext und Filter und vergleichen Sie mit der Datei auf dem Datenträger.'], ['Durchsucht die Hilfe meine privaten Notizen?', 'Nein. Die Hilfesuche durchsucht nur mitgelieferte Anleitungen und Fragen. Sie sendet nichts an Modelle oder Anbieter.']]),
    fa: body('جست‌وجو و پیمایش نتیجه‌ها', 'جست‌وجوی یادداشت در نوار کناری و پنل نتیجه‌ها.', 'مخزن باز و نمایه‌شده باشد.', 'جست‌وجو فقط‌خواندنی و محدود به مخزن فعال و حالت انتخابی است.', [
      ['عبارت مناسب', 'با واژه‌ای متمایز از عنوان یا متن شروع کنید. برای بررسی وجود یادداشت در نمایه، فیلترها را پاک کنید.'], ['بررسی نتیجه', 'عنوان و مسیر را با هم بخوانید؛ عنوان یکسان ممکن است به فایل‌های متفاوت اشاره کند. نتیجهٔ موردنظر را باز کنید.'], ['تفاوت حالت‌ها', 'حالت پیش‌فرض واژه‌ای است. جست‌وجوی معنایی به تنظیم جداگانهٔ پشتیبانی آزمایشی بردارهای تعبیه نیاز دارد و خودکار فعال نیست.'], ['رفع نتیجهٔ قدیمی', 'وضعیت نمایه را بررسی کنید، منتظر پایان نمایه‌سازی بمانید و فقط در صورت نیاز بازسازی کنید. خطای جست‌وجو نبودن فایل را اثبات نمی‌کند.'],
    ], [['چرا یادداشت آشنا پیدا نمی‌شود؟', 'مخزن فعال، وضعیت نمایه، عبارت و فیلترها را بررسی و با فایل روی دیسک مقایسه کنید.'], ['راهنما یادداشت خصوصی مرا جست‌وجو می‌کند؟', 'خیر. فقط متن راهنماها و پرسش‌های همراه برنامه جست‌وجو می‌شود؛ چیزی به مدل یا ارائه‌دهنده ارسال نمی‌شود.']]),
  },
}
