import { body, type GuideTranslations } from './translationTypes.ts'

export const inspectionTranslations: GuideTranslations = {
  'layout-presets': {
    de: body('Vorlagen für die Arbeitsbereichsanordnung', 'Einstellungen > Arbeitsbereich > Layoutvorlagen.', 'Öffnen Sie Einstellungen; Vorlagen betreffen Darstellung, keine Notizinhalte.', 'Eine Vorlage ändert sichtbare Layouteinstellungen. Sie bearbeitet kein Markdown, veröffentlicht oder löscht nichts und aktiviert keine Dienste.', [
      ['Zusammenfassung lesen', 'Vergleichen Sie geteilte Vorschau, Haftnotizen, Graphtiefe und Panel-Anordnung vor Anwenden.'], ['Passend zur Aufgabe wählen', 'Nutzen Sie eine Schreibvorlage zum Verfassen oder eine Wissensvorlage für Graph, Inspektor und Beziehungen.'], ['Einmal anwenden', 'Wählen Sie bewusst eine Vorlage, statt beim Bewerten ständig Einzeloptionen umzuschalten.'], ['Danach anpassen', 'Die Vorlage ist ein Ausgangspunkt. Ändern Sie anschließend Einzeloptionen passend zur Aufgabe.'],
    ], [['Ändert eine Vorlage meine Notiz?', 'Nein. Sie ändert die Arbeitsbereichsdarstellung und keinen Markdown-Inhalt.'], ['Kann ich danach anpassen?', 'Ja. Einzelne Arbeitsbereichsoptionen bleiben verfügbar.']]),
    fa: body('الگوهای چیدمان فضای کار', 'تنظیمات > فضای کار > الگوهای چیدمان.', 'تنظیمات را باز کنید. الگو نمایش را تغییر می‌دهد، نه محتوای یادداشت.', 'اعمال الگو تنظیم نمای فضای کار را عوض می‌کند. Markdown را ویرایش، منتشر یا حذف نمی‌کند و خدمت بیرونی را فعال نمی‌کند.', [
      ['خلاصهٔ الگو را بخوانید', 'پیش از اعمال، پیش‌نمایش تقسیم‌شده، نمایش برگهٔ چسبان، عمق گراف و چیدمان پنل را مقایسه کنید.'], ['متناسب کار انتخاب کنید', 'برای تألیف نمای نوشتن و برای روابط و بازرس نمای دانش انتخاب کنید.'], ['یک بار اعمال کنید', 'الگو را آگاهانه انتخاب کنید و هنگام ارزیابی مدام کنترل‌های منفرد را عوض نکنید.'], ['بعداً اصلاح کنید', 'الگو نقطهٔ شروع است. سپس کنترل‌های جدا را متناسب کار تنظیم کنید.'],
    ], [['الگو یادداشت را عوض می‌کند؟', 'خیر. نمایش فضای کار عوض می‌شود، نه محتوای Markdown.'], ['پس از اعمال می‌توانم شخصی‌سازی کنم؟', 'بله. الگو چیدمان اولیه می‌دهد و کنترل‌های مستقل باقی می‌مانند.']]),
  },
  'preview-quality': {
    de: body('Qualitätsleiste der Vorschau', 'Qualitäts- und Statusleiste im Vorschauinspektor.', 'Öffnen Sie eine Notiz mit sichtbarer Vorschau oder Inspektor.', 'Die Leiste berichtet Darstellungs- und Exportbereitschaft. Lesen verändert keine Notiz und startet keinen Export.', [
      ['Darstellungszustand lesen', 'Prüfen Sie den normalen Abschluss der Markdown-Darstellung, bevor Sie die Vorschau als repräsentativ ansehen.'], ['Diagnosen prüfen', 'Warnungen und Fehler können kaputte Diagramme, Metadaten, Verweise oder nicht unterstützte Syntax anzeigen.'], ['Quelle vergleichen', 'Prüfen Sie bei falscher Darstellung den genauen Quellblock. Verlassen Sie sich nicht auf eine vermeintliche stille Reparatur.'], ['Vor Export prüfen', 'Beheben Sie wesentliche Vorschauprobleme. Nachgelagerte Renderer können dieselben oder strengere Fehler melden.'],
    ], [['Garantiert Exportbereit eine korrekte Datei?', 'Nein. Es bestätigt nur klare Vorschauprüfungen. Prüfen Sie das Exportartefakt separat.'], ['Warum unterscheiden sich Vorschau und Export?', 'Renderer, Schriften, externe Werkzeuge und Seitenregeln können verschieden sein.']]),
    fa: body('نوار کیفیت پیش‌نمایش', 'نوار کیفیت و وضعیت بازرس هنگام نمایش یادداشت رندرشده.', 'یادداشت را با پیش‌نمایش یا بازرس نمایان باز کنید.', 'نوار، آمادگی رندر و خروجی را گزارش می‌کند. خواندن آن یادداشت را تغییر نمی‌دهد و خروجی نمی‌سازد.', [
      ['وضعیت رندر را بخوانید', 'پیش از اتکا به نمای دیده‌شده، پایان عادی رندر Markdown را تأیید کنید.'], ['عیب‌ها را ببینید', 'شمار هشدار و خطا، نمودار، فراداده، ارجاع خراب یا ساختار پشتیبانی‌نشده را آشکار می‌کند.'], ['منبع و نما را مقایسه کنید', 'اگر خروجی غلط است بلوک دقیق منبع را ببینید؛ ترمیم خاموش توسط رندر را فرض نکنید.'], ['پیش از خروجی تأیید کنید', 'مشکل مهم پیش‌نمایش را رفع کنید؛ رندر بعدی ممکن است همان خطا یا خطای سخت‌گیرانه‌تر نشان دهد.'],
    ], [['آمادهٔ خروجی یعنی فایل نهایی درست است؟', 'خیر. فقط بررسی پیش‌نمایش پاک است؛ فایل خروجی را جدا تأیید کنید.'], ['چرا پیش‌نمایش و خروجی متفاوت‌اند؟', 'ممکن است رندر، قلم، ابزار بیرونی یا قواعد صفحه‌بندی متفاوت داشته باشند.']]),
  },
  'external-changes': {
    de: body('Externe Dateiänderungen', 'Hinweis, wenn eine geöffnete Notiz außerhalb der App geändert wurde.', 'Eine erkannte externe Änderung der geöffneten Notiz.', 'Neuladen kann den Editorpuffer ersetzen. Beibehalten kann später externe Änderungen überschreiben. Vergleichen Sie vor Speichern.', [
      ['Bearbeitung kurz stoppen', 'Fügen Sie keine Änderungen hinzu, bis die maßgebliche Fassung feststeht.'], ['Externe Quelle bestimmen', 'Prüfen Sie anderen Editor, Synchronisierung, Git oder Dateisystemprozess als Ursache.'], ['Neuladen oder weiterbearbeiten', 'Laden Sie die maßgebliche Datenträgerfassung neu. Weiterbearbeiten bedeutet bewusstes Zusammenführen oder späteres Überschreiben.'], ['Ergebnis prüfen', 'Öffnen oder vergleichen Sie die Notiz und bestätigen Sie den gewünschten Inhalt vor weiteren Änderungen.'],
    ], [['Werden beide Fassungen automatisch zusammengeführt?', 'Nicht durch diesen Hinweis. Nutzen Sie expliziten Vergleich oder Konfliktlösung, wenn beide wertvoll sind.'], ['Warum erscheint der Hinweis ohne Speichern?', 'Die Dateibeobachtung hat eine Änderung außerhalb der aktuellen Editorsitzung erkannt.']]),
    fa: body('تغییر بیرونی فایل', 'هشدار تغییر یادداشت باز روی دیسک، بیرون از Scriptor.', 'تغییر بیرونیِ تشخیص‌داده‌شده برای یادداشت باز.', 'بارگذاری دوباره می‌تواند بافر ویرایشگر را جایگزین کند؛ نگه داشتن ویرایش ممکن است بعداً تغییر بیرونی را بازنویسی کند. پیش از ذخیره مقایسه کنید.', [
      ['کمی ویرایش را متوقف کنید', 'تا تعیین نسخهٔ اصلی تغییر بیشتری اضافه نکنید.'], ['منبع بیرونی را مشخص کنید', 'ببینید ویرایشگر دیگر، ابزار همگام‌سازی، Git یا فرایند فایل یادداشت را تغییر داده است.'], ['بارگذاری یا ادامه را انتخاب کنید', 'اگر نسخهٔ دیسک اصلی است بارگذاری کنید؛ فقط برای ادغام یا بازنویسی آگاهانه ادامه دهید.'], ['نتیجه را بررسی کنید', 'پس از انتخاب دوباره باز یا مقایسه کنید و پیش از ویرایش گسترده، ماندن محتوای مورد انتظار را تأیید کنید.'],
    ], [['هر دو نسخه خودکار ادغام می‌شوند؟', 'از این هشدار خیر. اگر هر دو مفیدند مقایسه یا حل تعارض صریح را به کار ببرید.'], ['چرا بدون ذخیره هشدار آمد؟', 'پایشگر تغییر فایل بیرون از نشست ویرایش فعلی را دیده است.']]),
  },
  'external-links': {
    de: body('Externe Links bestätigen', 'Bestätigung vor Öffnen externer URLs oder App-Links.', 'Ein Link fordert Browser, andere Anwendung oder externes Protokoll an.', 'Das Ziel verlässt Scriptor und kann Daten einem anderen Dienst zeigen. Prüfen Sie die genaue Adresse.', [
      ['Ziel lesen', 'Prüfen Sie vollständigen Host, Schema und Pfad statt nur Linktext aus Notiz oder Plugin.'], ['Auslöser prüfen', 'Die Anfrage sollte zur gerade gewählten Aktion passen und nicht aus unerwartetem gerendertem Inhalt stammen.'], ['Erlauben oder abbrechen', 'Öffnen Sie nur erwartete Ziele und Anwendungen; ansonsten brechen Sie ab.'], ['Verdächtige Links untersuchen', 'Erhalten Sie bei unerwartetem Ziel den Quellkontext aus Notiz oder Plugin und prüfen Sie ihn vor Wiederholung.'],
    ], [['Ändert Abbrechen meine Notiz?', 'Nein. Es lehnt nur externe Navigation ab.'], ['Warum benötigt ein normaler Browserlink Zustimmung?', 'Der Übergang aus dem lokalen Arbeitsbereich bleibt ausdrücklich und gerenderte Inhalte öffnen nichts heimlich.']]),
    fa: body('تأیید پیوند بیرونی', 'تأیید پیش از باز کردن نشانی بیرونی یا پیوند برنامه.', 'پیوندی مرورگر، برنامهٔ دیگر یا پروتکل بیرونی می‌خواهد.', 'باز کردن مقصد از Scriptor خارج می‌شود و ممکن است داده را به برنامه یا وب‌سایت دیگر نشان دهد. مقصد دقیق را بررسی کنید.', [
      ['مقصد را بخوانید', 'میزبان، طرح و مسیر کامل را ببینید و فقط به متن پیوند یادداشت یا افزونه اتکا نکنید.'], ['علت درخواست را ببینید', 'درخواست باید با عمل اخیر شما مطابق باشد و از محتوای رندرشدهٔ غیرمنتظره نیامده باشد.'], ['تأیید یا لغو کنید', 'فقط مقصد و برنامهٔ مورد انتظار را باز کنید؛ در غیر این صورت لغو کنید.'], ['پیوند مشکوک را بررسی کنید', 'اگر یادداشت یا افزونهٔ مورد اعتماد مقصد عجیب ساخت، زمینهٔ منبع را حفظ و پیش از تکرار بررسی کنید.'],
    ], [['لغو یادداشت را تغییر می‌دهد؟', 'خیر. فقط درخواست پیمایش بیرونی رد می‌شود.'], ['چرا پیوند معمولی مرورگر تأیید می‌خواهد؟', 'خروج از فضای محلی صریح می‌ماند و محتوای رندرشده نمی‌تواند مقصد بیرونی را خاموش باز کند.']]),
  },
  'link-rewrite': {
    de: body('Linkumschreibung vorab prüfen', 'Linkumschreibdialog bei Umbenennung oder Refactoring.', 'Ein Vorgang hat möglicherweise zu ändernde Markdown-Verweise gefunden.', 'Anwenden verändert Notizinhalte im gemeldeten Umfang. Prüfen Sie zuerst die Änderungsvorschau.', [
      ['Betroffene Notizen lesen', 'Prüfen Sie Anzahl und Pfade gegen die geplante Umbenennung.'], ['Vorschau ausführen', 'Prüfen Sie alte und neue Ziele, bevor Dateien verändert werden.'], ['Mehrdeutige Links untersuchen', 'Achten Sie auf Aliase, Überschriften, Blockverweise, relative Pfade und doppelte Notiznamen.'], ['Anwenden und verifizieren', 'Wenden Sie eine korrekte Vorschau an und öffnen Sie typische Rückverweise und Ziele.'],
    ], [['Kann ich die Vorschau überspringen?', 'Einige Abläufe erlauben das, doch bei mehreren Notizen empfiehlt sich die Vorschau.'], ['Benennt Umschreiben Dateien um?', 'Der Dialog ändert Verweise des zuständigen Vorgangs. Die Dateiumbenennung ist ein eigener Teil des Ablaufs.']]),
    fa: body('پیش‌نمایش بازنویسی پیوند', 'گفت‌وگوی بازنویسی در تغییر نام یا بازآرایی.', 'عملیات، پیوند Markdown نیازمند تغییر را پیدا کرده است.', 'اعمال، متن یادداشت را در دامنهٔ گزارش‌شده تغییر می‌دهد. ابتدا پیش‌نمایش آزمایشی را ببینید.', [
      ['یادداشت‌های متأثر را ببینید', 'شمار و مسیر را با تغییر نام مورد نظر تطبیق دهید.'], ['پیش‌نمایش آزمایشی را اجرا کنید', 'پیش از تغییر فایل، مقصد قدیم و جدید را بررسی کنید.'], ['پیوند مبهم را بررسی کنید', 'نام مستعار، عنوان، ارجاع بلوک، مسیر نسبی و نام تکراری را با دقت ببینید.'], ['اعمال و تأیید کنید', 'پس از درستی پیش‌نمایش اعمال کنید و نمونهٔ پیوند ورودی و مقصد را باز کنید.'],
    ], [['می‌توانم اجرای آزمایشی را رد کنم؟', 'برخی مسیرها اجازه می‌دهند، ولی برای تغییر چند یادداشت دیدن پیش‌نمایش امن‌تر است.'], ['بازنویسی نام فایل را هم عوض می‌کند؟', 'این گفت‌وگو ارجاع مربوط به عملیات را بازنویسی می‌کند؛ تغییر نام فایل بخش جداگانهٔ همان گردش کار است.']]),
  },
  performance: {
    de: body('Leistungsanzeige', 'Leistungsanzeige über Diagnose oder erweiterte Arbeitsbereichsoptionen aktivieren.', 'Nutzen Sie sie zur Untersuchung von Bedien- oder Darstellungskosten.', 'Die Anzeige liest lokale Messwerte. Sie optimiert oder pausiert keine Subsysteme selbst.', [
      ['Ausgangswert bestimmen', 'Beobachten Sie normale Werte vor Wiederholung der langsamen Aktion.'], ['Eine Aktion reproduzieren', 'Starten Sie eine einzelne Editor-, Graph-, Canvas- oder Navigationsaktion und beobachten Sie passende Werte.'], ['Subsystem zuordnen', 'Nutzen Sie Werte als Hinweis und prüfen Sie die Funktion. Der höchste Wert ist nicht automatisch die Ursache.'], ['Danach deaktivieren', 'Schalten Sie Diagnoseanzeigen nach Abschluss aus, um Schreibraum freizuhalten.'],
    ], [['Beweist ein kurzzeitig hoher Wert einen Fehler?', 'Nein. Suchen Sie wiederholbare Regressionen und einen konkreten wahrnehmbaren Zeitverlust.'], ['Sendet die Anzeige Telemetrie?', 'Diese Anleitung betrifft die lokale Anzeige. Prüfen Sie externe Berichtseinstellungen separat.']]),
    fa: body('نمایش عملکرد', 'نمایش عملکرد را از عیب‌یابی یا کنترل پیشرفتهٔ فضای کار روشن کنید.', 'برای بررسی هزینهٔ تعامل یا رندر مفید است، نه نمایش دائمی هنگام نوشتن.', 'این نما اندازه‌گیری محلی می‌خواند و خودکار زیرسامانه را بهینه یا خواب نمی‌کند.', [
      ['خط پایه بگیرید', 'پیش از بازتولید کندی، مقدار معمول فضای کار را ببینید.'], ['یک عمل را تکرار کنید', 'یک عمل ویرایشگر، گراف، بوم یا پیمایش اجرا کنید و تغییر معیار مربوط را ببینید.'], ['با زیرسامانه تطبیق دهید', 'عدد سرنخ است؛ قابلیت مربوط را بررسی کنید و بیشترین عدد را خودکار علت ندانید.'], ['پس از عیب‌یابی خاموش کنید', 'نما را ببندید تا کنترل تشخیصی با فضای نوشتن رقابت نکند.'],
    ], [['عدد لحظه‌ای بالا خطا را ثابت می‌کند؟', 'خیر. پس‌رفت تکرارپذیر و تأخیر قابل مشاهدهٔ کاربر را پیدا کنید.'], ['این نما دورسنجی می‌فرستد؟', 'این راهنما نمای محلی را پوشش می‌دهد؛ سیاست گزارش بیرونی را در تنظیم دورسنجی جدا ببینید.']]),
  },
  subsystems: {
    de: body('Subsysteme in Ruhezustand versetzen', 'Ruhezustandssteuerung des Arbeitsbereichs.', 'Zur Reduzierung von Hintergrundarbeit oder Diagnose eines belastenden Subsystems.', 'Ruhezustand kann Live-Funktionen ausblenden oder Ansichten veralten lassen. Maßgebliches Markdown sollte dadurch nicht verändert werden.', [
      ['Belastendes Subsystem finden', 'Nutzen Sie Status, Diagnose oder Leistungsanzeige, bevor Sie unbeteiligte Funktionen abschalten.'], ['Einzeln pausieren', 'Ändern Sie jeweils ein Subsystem, um Wirkung auf Reaktion und Ressourcen zu erkennen.'], ['Einschränkungen beobachten', 'Prüfen Sie, welche Panels nicht aktualisieren und ob der Schlafzustand sichtbar ist.'], ['Aufwecken und prüfen', 'Reaktivieren Sie das Subsystem und prüfen Sie Aktualisierung vor Nutzung von Suche, Graph, Vorschau oder anderen abgeleiteten Ansichten.'],
    ], [['Löscht Ruhezustand Indexdaten?', 'Er regelt Laufzeitressourcen. Dauerhafte Löschung und Neuaufbau benötigen eigene Aktionen.'], ['Warum bleibt eine Ansicht nach Aufwecken alt?', 'Sie aktualisiert möglicherweise noch. Warten Sie auf Bereitschaft des zuständigen Dienstes.']]),
    fa: body('کنترل خواب زیرسامانه‌ها', 'کنترل خواب زیرسامانهٔ فضای کار.', 'برای کاهش کار پس‌زمینه یا عیب‌یابی زیرسامانهٔ سنگین استفاده کنید.', 'خواب می‌تواند قابلیت زنده را موقتاً بردارد یا نما را قدیمی کند. نباید به‌تنهایی Markdown اصلی را تغییر دهد.', [
      ['زیرسامانهٔ سنگین را پیدا کنید', 'پیش از خاموش کردن قابلیت نامرتبط، از وضعیت، عیب‌یابی یا نمای عملکرد شاهد بگیرید.'], ['یکی‌یکی بخوابانید', 'هر بار یک زیرسامانه را عوض کنید تا اثر بر پاسخ‌گویی یا منابع معلوم شود.'], ['رفتار محدود را ببینید', 'پنل‌های متوقف‌شده و اعلام خواب در رابط را بررسی کنید.'], ['بیدار و تأیید کنید', 'دوباره فعال کنید و پیش از اتکا به جست‌وجو، گراف، پیش‌نمایش یا نمای مشتق‌شده، تازه شدن را ببینید.'],
    ], [['خواب دادهٔ نمایه را حذف می‌کند؟', 'برای کنترل منابع زمان اجراست، نه حذف؛ پاک‌سازی و بازسازی پایدار عمل صریح جدا می‌خواهند.'], ['چرا نما پس از بیداری قدیمی است؟', 'ممکن است هنوز تازه شود. وضعیت را ببینید و پس از اعلام آمادگی سرویس مسئول دوباره تلاش کنید.']]),
  },
  'status-dock': {
    de: body('Statusbereich und Betriebsregister', 'Unterer Bereich mit Problemen, Ausgabe und Aufgaben.', 'Öffnen Sie einen Tresor für arbeitsbereichsspezifischen Status.', 'Öffnen eines Registers liest Diagnose und Aufgaben. Wiederholen, Abbrechen oder Ändern benötigen eigene Aktionen darin.', [
      ['Zusammenfassung lesen', 'Wählen Sie anhand Statusfußzeile und Abzeichen das passende Register.'], ['Passendes Register öffnen', 'Probleme zeigt bearbeitbare Diagnosen, Ausgabe Vorgangsmeldungen, Aufgaben länger laufende Exporte oder Hintergrundarbeit.'], ['Einen Vorgang verfolgen', 'Ordnen Sie Startaktion und Ergebnis zusammen. Unbeteiligte Warnungen sind nicht automatisch die Ursache.'], ['Nach Klärung schließen', 'Klappen Sie den Bereich ein, damit Betriebsanzeigen nicht dauerhaft Schreibraum verbrauchen.'],
    ], [['Warum drei getrennte Register?', 'Sie zeigen verschiedene Belege: Diagnose, Textausgabe und verfolgte Hintergrundaufgaben.'], ['Behebt Leeren das Problem?', 'Nein. Leeren oder Zurücksetzen betrifft Ansicht oder Datensätze. Reparieren Sie die zuständige Funktion.']]),
    fa: body('پنل وضعیت و زبانهٔ عملیاتی', 'پنل پایین: مشکلات، خروجی و کارها.', 'برای وضعیت مخصوص فضای کار مخزن باز کنید.', 'پنل، عیب و کار پس‌زمینه را گزارش می‌کند. باز کردن زبانه تکرار، لغو یا تغییر کار نمی‌کند مگر عمل صریح داخل آن را بزنید.', [
      ['از خلاصه شروع کنید', 'از نوار وضعیت و نشان‌ها بفهمید شاهد لازم در مشکلات، خروجی یا کارهاست.'], ['زبانهٔ درست را باز کنید', 'مشکلات برای عیب قابل اقدام، خروجی برای پیام عملیات و کارها برای خروجی طولانی یا کار پس‌زمینه است.'], ['یک عملیات را دنبال کنید', 'عمل آغازگر را با نتیجه‌اش مرتبط نگه دارید و هشدار نامرتبط را علت ندانید.'], ['پس از حل جمع کنید', 'پنل را جمع کنید تا نمایش عملیاتی دائماً فضای نوشتن را کم نکند.'],
    ], [['چرا سه زبانه جداست؟', 'سه نوع شاهد دارند: عیب، متن عملیات و کار پس‌زمینهٔ رهگیری‌شده.'], ['پاک کردن نما مشکل را حل می‌کند؟', 'خیر. پاک یا بازنشانی نما یا سابقه را عوض می‌کند؛ قابلیت مسئول را جدا اصلاح کنید.']]),
  },
  'references-preview': {
    de: body('Literaturverweise in der Vorschau', 'Inspektor und Referenzvorschau der aktiven Notiz.', 'Zitierschlüssel in der Notiz und verfügbare Bibliografie mit Index.', 'Formatierte Zitate lesen ist schreibgeschützt. Bibliografiedaten und Quellschlüssel werden separat bearbeitet.', [
      ['Erkannte Schlüssel prüfen', 'Vergleichen Sie angezeigte Zitierschlüssel mit der Notizquelle.'], ['Formatierungsmodus lesen', 'Prüfen Sie citeproc oder Ersatzformatierung vor Vergleich mit Publikationsvorgaben.'], ['Fehlende Literatur ergänzen', 'Öffnen Sie Bibliografiewerkzeuge bei unbekannten Schlüsseln statt gerenderten Text in die Notiz zu kopieren.'], ['Vor Veröffentlichung prüfen', 'Prüfen Sie Zitate und Literaturverzeichnis im endgültigen Export; Stil und Prozessor können abweichen.'],
    ], [['Warum unterscheidet sich ein Schlüssel im Export?', 'Der Export kann einen anderen CSL-Stil, Prozessor oder Publikationsaufbau verwenden.'], ['Soll ich die gerenderte Vorschau bearbeiten?', 'Nein. Bearbeiten Sie Zitierschlüssel oder Bibliografiequelle.']]),
    fa: body('پیش‌نمایش منابع', 'بازرس و پیش‌نمایش ارجاعِ یادداشت فعال.', 'یادداشت باید کلید استناد داشته باشد و کتاب‌نامه و نمایه در دسترس باشد.', 'دیدن استناد قالب‌بندی‌شده فقط‌خواندنی است؛ ویرایش کتاب‌نامه یا کلید منبع عملیات جداست.', [
      ['کلیدهای دیده‌شده را بررسی کنید', 'کلید نمایش‌داده‌شده را با منبع واقعی یادداشت تطبیق دهید.'], ['حالت قالب‌بندی را ببینید', 'پیش از مقایسه با مقصد انتشار، فعال بودن citeproc یا قالب‌بندی جایگزین را تأیید کنید.'], ['منبع مفقود را حل کنید', 'برای کلید بی‌مدخل ابزار کتاب‌نامه را باز کنید؛ متن رندرشده را دستی در یادداشت کپی نکنید.'], ['پیش از انتشار تأیید کنید', 'استناد درون متن و کتاب‌نامه را در خروجی نهایی مقایسه کنید؛ سبک و پردازشگر ممکن است متفاوت باشد.'],
    ], [['چرا کلید در اینجا و خروجی فرق دارد؟', 'خروجی نهایی ممکن است سبک CSL، پردازشگر یا تنظیم انتشار دیگری داشته باشد.'], ['پیش‌نمایش رندرشده را ویرایش کنم؟', 'خیر. کلید استناد یادداشت یا منبع کتاب‌نامه را ویرایش کنید.']]),
  },
  'panel-recovery': {
    de: body('Panel nach Fehler wiederherstellen', 'Fehleransicht bei fehlgeschlagener Darstellung oder Initialisierung.', 'Die Fehlergrenze der Anwendung hat einen Panelfehler erfasst.', 'Wiederholen erzeugt die Ansicht neu. Wiederholtes Zurücksetzen sollte keine dauerhaften Daten-, Rechte- oder Integrationsfehler verdecken.', [
      ['Panel zuordnen', 'Lesen Sie den Funktionsnamen, damit Wiederherstellung auf den betroffenen Bereich begrenzt bleibt.'], ['Kontext erhalten', 'Notieren Sie Fehler und vorausgehende Aktion vor erneutem Versuch, besonders bei wiederholbarem Fehler.'], ['Einmal wiederholen', 'Nutzen Sie Wiederholen nach möglicher Behebung oder schließen Sie die Ansicht zum Schutz übriger Arbeit.'], ['Dauerhafte Fehler melden', 'Nutzen Sie bei erneutem Fehler Diagnose und Support mit Version und Reproduktionsschritten statt einer Wiederholungsschleife.'],
    ], [['Hat der Panelfehler meine Notiz beschädigt?', 'Die Fehleransicht belegt das nicht. Prüfen Sie maßgebliches Markdown und ausstehende Speicherung separat.'], ['Soll ich die ganze App sofort neu laden?', 'Versuchen Sie zuerst gezielte Panel-Wiederherstellung, solange die Anwendung reagiert.']]),
    fa: body('بازیابی خطای پنل', 'نمای جایگزین خطا وقتی پنل رندر یا راه‌اندازی نمی‌شود.', 'مرز خطای برنامه باید شکست پنل را گرفته باشد.', 'تلاش دوباره نمای مربوط را بازسازی می‌کند؛ تکرار نباید خطای پایدار داده، مجوز یا یکپارچه‌سازی را پنهان کند.', [
      ['پنل را مشخص کنید', 'نام قابلیت شکست‌خورده را بخوانید تا بازیابی محدود بماند و وضعیت نامرتبط دوباره شروع نشود.'], ['زمینهٔ مفید را حفظ کنید', 'خطای نمایان و عمل قبلی را پیش از تلاش دوباره ثبت کنید، خصوصاً خطای تکرارپذیر.'], ['یک بار تلاش کنید', 'اگر علت احتمالاً رفع شده تلاش دوباره را بزنید؛ برای حفظ بقیهٔ فضای کار می‌توانید ببندید.'], ['شکست پایدار را پیگیری کنید', 'اگر دوباره شکست خورد با نسخه و مراحل بازتولید از عیب‌یابی یا پشتیبانی استفاده کنید، نه تکرار بی‌پایان.'],
    ], [['خطای پنل یادداشت را خراب کرد؟', 'این نما خرابی را ثابت نمی‌کند. Markdown اصلی و ذخیرهٔ معلق را جدا بررسی کنید.'], ['فوراً کل برنامه را بارگذاری کنم؟', 'ابتدا بازیابی محدود پنل را امتحان کنید مگر خود برنامه پاسخ ندهد.']]),
  },
  'mutation-confirmation': {
    de: body('Zustandsänderung bestätigen', 'Bestätigungsblock vor einem begrenzten Änderungsvorgang.', 'Eine Funktion hat eine ausdrücklich zu bestätigende Änderung vorbereitet.', 'Bestätigen führt die beschriebene Änderung aus. Lesen Sie Umfang, Ziele und Folgen; Abbrechen wendet den Vorschlag nicht an.', [
      ['Aktionsverb lesen', 'Unterscheiden Sie Erstellen, Überschreiben, Löschen, Verschieben, Veröffentlichen, Senden und Rechteänderung.'], ['Umfang prüfen', 'Lesen Sie Datei, Konto, Anzahl, Ziel oder Ressource und gleichen Sie sie mit Ihrer Absicht ab.'], ['Endgültige Folgen prüfen', 'Überschreiben, externes Senden, Löschen oder Rechteänderung besitzen möglicherweise kein Rückgängig in der App.'], ['Bestätigen oder abbrechen', 'Bestätigen Sie korrekten Umfang; sonst brechen Sie ab und korrigieren Sie ursprüngliche Einstellung oder Auswahl.'],
    ], [['Warum wird eine bekannte Aktion bestätigt?', 'Der Vorgang überschreitet eine ausdrücklich geregelte Grenze für Zustandsänderungen.'], ['Verliere ich beim Abbrechen meinen Entwurf?', 'Die Bestätigung bricht den Vorschlag ab, nicht unbeteiligten Editorinhalt. Prüfen Sie eigene Entwurfsregeln des Ablaufs.']]),
    fa: body('تأیید تغییر وضعیت', 'بخش تأیید پیش از عملیات محدودِ تغییردهنده.', 'قابلیت تغییری آماده کرده که تأیید صریح می‌خواهد.', 'تأیید تغییر شرح‌داده‌شده را اجرا می‌کند. دامنه، هدف و پیامد را بخوانید؛ لغو پیشنهاد را اعمال نمی‌کند.', [
      ['فعل عملیات را بخوانید', 'ساخت، بازنویسی، حذف، جابه‌جایی، انتشار، ارسال و تغییر مجوز را جدا کنید.'], ['دامنه را تأیید کنید', 'فایل، حساب، شمار، مقصد یا منبع نام‌برده را با قصد خود تطبیق دهید.'], ['پیامد برگشت‌ناپذیر را ببینید', 'بازنویسی، ارسال بیرونی، حذف یا تغییر مجوز ممکن است واگردانی در برنامه نداشته باشد.'], ['تأیید یا لغو کنید', 'فقط دامنهٔ درست را تأیید کنید؛ در غیر این صورت لغو و تنظیم یا انتخاب آغازگر را اصلاح کنید.'],
    ], [['چرا عمل آشنا تأیید می‌خواهد؟', 'از مرز تغییر وضعیت عبور می‌کند که محصول صریح نگه می‌دارد.'], ['لغو پیش‌نویس را از بین می‌برد؟', 'باید تغییر پیشنهادی را لغو کند، نه متن ویرایشگر نامرتبط؛ اگر گردش کار پیش‌نویس خودش را دارد آن را بررسی کنید.']]),
  },
}
