import { body, type GuideTranslations } from './translationTypes.ts'

export const workflowTranslations: GuideTranslations = {
  'resource-sync': {
    de: body('Ressourcensynchronisation und Freigabepläne', 'Ressourcen-/Synchronisationswerkzeuge im betreffenden Ablauf.', 'Konfigurierte Quelle und Ziele sowie passende Ressourcenrechte.', 'Pläne sind bis zum ausdrücklichen Anwenden schreibgeschützt. Prüfen Sie vor Zustimmung kopierte oder offengelegte Daten.', [
      ['Quelle und Ziele wählen', 'Prüfen Sie Ressourcenidentität, erlaubten Bereich und Ziel. Ähnliche Namen können verschiedene Ziele verbergen.'], ['Plan erstellen', 'Prüfen Sie Schreibvorgänge, Konflikte und Ausschlüsse. Zielauswahl ist noch keine Übertragung.'], ['Prüfen und anwenden', 'Genehmigen Sie nur gewünschte Änderungen. Erstellen Sie bei veralteten Plänen einen neuen Plan.'], ['Lieferung prüfen', 'Prüfen Sie tatsächliches Ziel, Ausgabe und Ergebnis. Teilfehler benötigen Prüfung statt blindes wiederholtes Kopieren.'],
    ], [['Teilt Öffnen dieses Bereichs bereits Daten?', 'Nein. Teilen und Kopieren benötigt einen eigenen konfigurierten Anwendungsablauf.'], ['Erhielten alle Ziele die Daten?', 'Prüfen Sie jedes Zielergebnis und jeden Fehler; nehmen Sie das nicht einfach an.']]),
    fa: body('همگام‌سازی منبع و برنامهٔ اشتراک', 'ابزار منبع و همگام‌سازی در روند مربوط.', 'منبع و مقصد تنظیم‌شده با مجوز مناسب.', 'برنامه تا اعمال صریح فقط‌خواندنی است. پیش از مجوز، دادهٔ کپی‌شونده یا در معرض دسترسی را ببینید.', [
      ['انتخاب منبع و مقصد', 'هویت منبع، دامنهٔ مجاز و مقصد را تأیید کنید. نام مشابه ممکن است مقصد متفاوتی باشد.'], ['ساخت برنامه', 'نوشتن موردانتظار، تعارض و موارد کنارگذاشته را ببینید. انتخاب مقصد انتقال داده نیست.'], ['بررسی و اعمال', 'فقط تغییر موردنظر را تأیید کنید. برای برنامهٔ قدیمی دوباره برنامه بسازید.'], ['تأیید تحویل', 'مقصد واقعی، خروجی و نتیجهٔ ثبت‌شده را بررسی کنید. شکست جزئی نیازمند بررسی است، نه کپی مکرر کورکورانه.'],
    ], [['باز کردن پنل چیزی به اشتراک می‌گذارد؟', 'خیر. اشتراک یا کپی روند اعمال جداگانه و تنظیم‌شده می‌خواهد.'], ['فرض کنم همهٔ مقصدها داده را گرفته‌اند؟', 'خیر. نتیجه و خطای هر مقصد را بررسی کنید.']]),
  },
  portal: {
    de: body('Portal-Einträge und Schnellaktionen', 'Portal über Palette oder konfigurierte Kopfleistenaktion öffnen.', 'Prüfen Sie Arbeitsbereich und Tresor.', 'Portal-Einträge starten Aktionen. Lesen Sie Ziel und Typ vor Aufruf, besonders bei externen Links und Abläufen.', [
      ['Eintragstyp wählen', 'Erstellen Sie eine Aktion oder Referenz mit klarem wiederkehrendem Zweck, statt alle Palettenbefehle zu duplizieren.'], ['Benennen und konfigurieren', 'Nutzen Sie erkennbare Namen und prüfen Sie Pfade/URLs. Keine Geheimnisse in Namen oder Notizen speichern.'], ['Bewusst anheften', 'Heften Sie häufige Einträge an. Seltene Verwaltungsaktionen gehören nicht in den Schreibfluss.'], ['Aufrufen und pflegen', 'Prüfen Sie Ergebnisse und korrigieren Sie Ziele nach Umorganisation. Entfernen macht frühere Aktionen nicht rückgängig.'],
    ], [['Ist ein Portal-Eintrag eine Zielkopie?', 'Meist ist er eine Referenz oder Aktion, keine Sicherung.'], ['Warum fehlt ein Eintrag?', 'Ziel, Funktion oder Anforderung an den aktiven Tresor können nicht mehr erfüllt sein.']]),
    fa: body('موردهای درگاه و عمل سریع', 'باز کردن درگاه از فرمان‌ها یا عمل تنظیم‌شدهٔ نوار بالا.', 'دامنهٔ فضای کار و مخزن را بررسی کنید.', 'مورد درگاه می‌تواند عمل اجرا کند. پیش از فراخوانی نوع و مقصد، به‌ویژه پیوند و روند بیرونی را بخوانید.', [
      ['انتخاب نوع مورد', 'عمل یا مرجعی با هدف تکرارشوندهٔ روشن بسازید، نه نسخهٔ همهٔ فرمان‌ها.'], ['نام و تنظیم', 'نام قابل‌شناسایی و مسیر یا نشانی درست به کار ببرید. راز در عنوان یا یادداشت نگذارید.'], ['سنجاق آگاهانه', 'مورد پرکاربرد را سنجاق کنید و عمل مدیریتی کم‌کاربرد را از جریان نوشتن دور نگه دارید.'], ['اجرا و نگهداری', 'نتیجه را ببینید و پس از سامان‌دهی یادداشت مقصد قدیمی را اصلاح کنید. حذف مورد، عمل قبلی را برنمی‌گرداند.'],
    ], [['مورد درگاه کپی مقصد است؟', 'معمولاً تعریف مرجع یا عمل است، نه پشتیبان مقصد.'], ['چرا مورد در دسترس نیست؟', 'ممکن است مقصد، قابلیت یا نیاز به مخزن فعال دیگر برقرار نباشد.']]),
  },
  capture: {
    de: body('Schnellerfassung', 'Schnellerfassung über Befehle oder konfigurierte Kopfleiste öffnen.', 'Prüfen Sie aktiven Tresor und Erfassungsziel.', 'Speichern schreibt Inhalt. Behalten Sie das Original bis zur bestätigten neuen Notiz; Erfassung ist keine Hintergrundsicherung.', [
      ['Idee erfassen', 'Schreiben Sie kurz und bewahren Sie genügend Quellen- und Kontextangaben für später.'], ['Ziel prüfen', 'Prüfen Sie, ob die Aktion eine Notiz erstellt, Inhalt anhängt oder einen Haftzettel erzeugt.'], ['Speichern und verifizieren', 'Prüfen Sie Notiz, Pfad und Fehler vor Schließen.'], ['Später verarbeiten', 'Nutzen Sie Posteingang, Links und Tags, um Material in den Tresor einzubinden statt dauerhafte Fragmente zu sammeln.'],
    ], [['Können zwei Erfassungen gleich heißen?', 'Dateinamenskollisionen brauchen ausdrückliche Behandlung. Ein weiterer Speichervorgang erzeugt nicht immer eine weitere Datei.'], ['Beweist Schließen die Speicherung?', 'Nein. Prüfen Sie Speicherergebnis und erzeugten Inhalt.']]),
    fa: body('ثبت سریع', 'باز کردن ثبت سریع از فرمان‌ها یا نوار بالای تنظیم‌شده.', 'مخزن فعال و مقصد ثبت را بررسی کنید.', 'ذخیره متن می‌نویسد. اصل را تا تأیید یادداشت جدید نگه دارید؛ ثبت سریع پشتیبان پس‌زمینه نیست.', [
      ['ثبت ایده', 'متن کوتاه با منبع و زمینهٔ کافی برای فهم بعدی بنویسید.'], ['بررسی مقصد', 'تأیید کنید عمل یادداشت جدید می‌سازد، متن می‌افزاید یا یادداشت چسبان ایجاد می‌کند.'], ['ذخیره و تأیید', 'یادداشت، مسیر و خطا را پیش از بستن بررسی کنید.'], ['پردازش بعدی', 'با صندوق ورودی، پیوند و برچسب داده را به مخزن پیوند دهید و قطعهٔ پراکندهٔ دائمی رها نکنید.'],
    ], [['دو ثبت عنوان یکسان می‌توانند داشته باشند؟', 'برخورد نام فایل باید صریح حل شود. ذخیرهٔ دوباره را همیشه ساخت فایل جدا ندانید.'], ['بستن یعنی ذخیره شده؟', 'خیر. نتیجهٔ ذخیره و متن ایجادشده را بررسی کنید.']]),
  },
  stickies: {
    de: body('Haftzettel und vorübergehende Erinnerungen', 'Haftzettel zeigen in Werkzeuge; Haftzettel in Schnellerfassung.', 'Arbeitsbereich mit aktivierter Haftzettel-Unterstützung.', 'Haftzettelzustand ist vom Markdown-Dokument getrennt. Überführen und sichern Sie dauerhaftes Wissen als Notiz.', [
      ['Erinnerung schreiben', 'Halten Sie Haftzettel kurz und handlungsbezogen, damit sie den Schreibbereich nicht verdecken.'], ['Positionieren oder verstecken', 'Nutzen Sie Layout und Anzeige. Verstecken ist nicht Löschen.'], ['Dauerhaften Inhalt übernehmen', 'Kopieren oder verschieben Sie bleibenden Inhalt in eine passend benannte Markdown-Notiz und prüfen Sie das Ergebnis.'], ['Veraltetes entfernen', 'Löschen Sie erst, wenn wichtige Inhalte anderswo erhalten sind.'],
    ], [['Gehören Haftzettel zur offenen Notiz?', 'Nicht automatisch. Sie haben eigenen Arbeitsbereichs-/Erfassungszustand.'], ['Warum sehe ich sie nicht?', 'Prüfen Sie Anzeigeeinstellung und aktiven Arbeitsbereich, bevor Sie Löschung annehmen.']]),
    fa: body('یادداشت چسبان و یادآور موقت', 'نمایش چسبان‌ها در ابزارها؛ عمل چسبان در ثبت سریع.', 'فضای کار دارای پشتیبانی فعال یادداشت چسبان.', 'وضعیت چسبان از سند Markdown جداست. دانش ماندگار را به یادداشت ببرید و مناسب پشتیبان بگیرید.', [
      ['نوشتن یادآور', 'چسبان را کوتاه و عملی نگه دارید تا فضای نوشتن را نپوشاند.'], ['جابه‌جایی یا پنهان کردن', 'از چیدمان و کنترل نمایش استفاده کنید. پنهان کردن حذف نیست.'], ['تبدیل محتوای ماندگار', 'محتوای پایدار را به یادداشت Markdown با عنوان مناسب کپی یا منتقل و نتیجه را تأیید کنید.'], ['حذف مورد قدیمی', 'فقط پس از تأیید حفظ متن مهم در جای دیگر حذف کنید.'],
    ], [['چسبان جزو یادداشت باز است؟', 'چنین فرض نکنید؛ وضعیت مستقل فضای کار و ثبت دارد.'], ['چرا دیده نمی‌شوند؟', 'ترجیح نمایش و فضای کار فعال را پیش از نتیجه گرفتن دربارهٔ حذف بررسی کنید.']]),
  },
  mcp: {
    de: body('MCP-Automatisierungsmodi und Werkzeuge', 'MCP-Bereich öffnen.', 'Offener Tresor, konfigurierter Automatisierungsmodus und passende Rechte.', 'Werkzeuge lesen oder verändern begrenzte Ressourcen. Beginnen Sie schreibgeschützt, bevor Sie Schreiben aktivieren.', [
      ['Modus wählen', 'Unterscheiden Sie deaktiviert, schreibgeschützt und schreibberechtigt. Ein Moduswechsel verändert Befugnisse, nicht nur das Aussehen.'], ['Werkzeuge prüfen', 'Lesen Sie Namen, Argumente, betroffene Ressource und Funktion vor Aufruf.'], ['Vorschläge prüfen', 'Prüfen Sie Entwürfe und native Bestätigungen. Werkzeugbeschreibung oder Modellanfrage ist keine Freigabe.'], ['Ergebnis prüfen', 'Unterscheiden Sie im Audit gestartet, fehlgeschlagen, abgebrochen und abgeschlossen. Behalten Sie bereinigten Fehlerkontext.'],
    ], [['Warum fehlt ein Werkzeug?', 'Modus, Tresorbereich, Funktion, Berechtigung oder Laufzeitprüfung können es blockieren.'], ['Kann ein Agent durch Hilfe Zugriff erhalten?', 'Nein. Anleitungen rufen keine Werkzeuge auf, erteilen keine Rechte und verändern keine nativen Prüfungen.']]),
    fa: body('حالت و ابزار خودکارسازی MCP', 'پنل MCP را باز کنید.', 'مخزن باز، حالت خودکارسازی تنظیم‌شده و مجوز مناسب.', 'ابزار منابع محدود را می‌خواند یا تغییر می‌دهد. پیش از فعال کردن نوشتن، فقط‌خواندنی بررسی کنید.', [
      ['انتخاب حالت', 'خاموش، فقط‌خواندنی و مجاز به نوشتن را جدا کنید. تغییر حالت تغییر اختیار است، نه ظاهر.'], ['بررسی ابزار', 'نام، ورودی، منبع متاثر و قابلیت را پیش از فراخوانی بخوانید.'], ['بررسی پیشنهاد', 'پیش‌نویس و تأیید بومی را ببینید. توضیح ابزار یا درخواست مدل خودِ مجوز نیست.'], ['ممیزی نتیجه', 'در ممیزی شروع، شکست، لغو و تکمیل را تشخیص دهید. زمینهٔ خطای پالایش‌شده را برای گزارش نگه دارید.'],
    ], [['چرا ابزار در دسترس نیست؟', 'حالت، دامنهٔ مخزن، قابلیت، مجوز یا اعتبارسنجی اجرا ممکن است آن را ببندد.'], ['عامل با راهنما می‌تواند دسترسی بگیرد؟', 'خیر. راهنما ابزار اجرا نمی‌کند، مجوز نمی‌دهد و بررسی بومی را تغییر نمی‌دهد.']]),
  },
  'mcp-audit': {
    de: body('Automatisierungs-Audit', 'MCP > Audit und Ausführungsdetails.', 'Relevante Automatisierungsaktivität im aktiven Bereich.', 'Audit beschreibt Vorgänge, ersetzt aber keine Dateiprüfung. Teilen Sie nur bereinigte Belege.', [
      ['Vorgang finden', 'Vergleichen Sie Zeit, Werkzeug, Bereich und Ergebnis. Mehrere Versuche können zu derselben beabsichtigten Aufgabe gehören.'], ['Absicht und Ergebnis trennen', 'Eine Anfrage beweist keine abgeschlossene Änderung. Lesen Sie Ergebnis, Fehler und Wiederherstellungsbelege.'], ['Quelle prüfen', 'Prüfen Sie geänderte Dateien oder Ausgabe bei gemeldetem Abschluss.'], ['Diagnose sicher bewahren', 'Kopieren Sie nur nötige bereinigte Details; keine Schlüssel, Tokens, privaten Notizen oder fremden Pfade.'],
    ], [['Beweist ein leeres Protokoll, dass nichts geschah?', 'Nicht unbedingt. Bereich, Aufbewahrungsgrenzen oder Ladefehler beeinflussen die Anzeige.'], ['Soll ich zum Reparieren das Protokoll zurücksetzen?', 'Nein. Zurücksetzen macht keine Quellenänderung rückgängig und entfernt möglicherweise nützliche Belege.']]),
    fa: body('سوابق ممیزی خودکارسازی', 'MCP > ممیزی و جزئیات اجرای ابزار.', 'فعالیت مرتبط خودکارسازی در دامنهٔ فعال.', 'ممیزی عملیات را توصیف می‌کند، جای بررسی فایل حاصل نیست. فقط شاهد پالایش‌شده را به اشتراک بگذارید.', [
      ['پیدا کردن عملیات', 'زمان، ابزار، دامنه و نتیجه را تطبیق دهید. چند تلاش ممکن است برای یک کار موردنظر باشند.'], ['جداسازی قصد و نتیجه', 'درخواست ثبت‌شده تکمیل تغییر را ثابت نمی‌کند. نتیجه، خطا و شاهد بازیابی را بخوانید.'], ['بررسی منبع', 'وقتی عملیات تکمیل گزارش می‌کند، فایل تغییرکرده یا خروجی را تأیید کنید.'], ['حفظ ایمن تشخیص', 'فقط جزئیات لازم پالایش‌شده را گزارش کنید؛ کلید، توکن، یادداشت خصوصی و مسیر نامربوط را کنار بگذارید.'],
    ], [['گزارش خالی یعنی هیچ کاری نشده؟', 'لزوماً نه. دامنه، حد نگهداری یا شکست بارگذاری روی نمایش اثر دارد.'], ['برای اصلاح کار گزارش را بازنشانی کنم؟', 'خیر. بازنشانی، تغییر منبع را برنمی‌گرداند و ممکن است شاهد مفید را حذف کند.']]),
  },
  'mcp-drafts': {
    de: body('Automatisierungsentwürfe anwenden', 'MCP-Entwurfs- und Vorschlagsprüfung.', 'Ein Vorschlag für die richtige Notiz und den richtigen Tresor.', 'Lesen ist keine Annahme. Anwenden schreibt Inhalt und benötigt den nativen Prüf- und Freigabeablauf.', [
      ['Ziel verifizieren', 'Prüfen Sie Notizpfad und Quellversion vor dem Vorschlag.'], ['Änderung lesen', 'Vergleichen Sie mit dem aktuellen Dokument. Prüfen Sie Belege, Löschungen und Formatierung.'], ['Bewusst anwenden', 'Nutzen Sie ausdrückliches Anwenden nach Prüfung. Veraltete Ziele benötigen Aktualisierung und Prüfung, kein erzwungenes Überschreiben.'], ['Prüfen und wiederherstellen', 'Kontrollieren Sie gespeicherte Notiz und Audit. Nutzen Sie bei unerwünschten Folgen Rückgängig, Verlauf oder Git.'],
    ], [['Kann ich alle künftigen Entwürfe genehmigen?', 'Eine geprüfte Änderung bedeutet keine unbegrenzte Befugnis. Jeder Ablauf hat seinen eigenen Bereich.'], ['Warum ist der Vorschlag veraltet?', 'Die Notiz kann sich nach Erstellung verändert haben. Vergleichen Sie mit der aktuellen Quelle.']]),
    fa: body('پیش‌نویس خودکارسازی و اعمال پیشنهاد', 'بررسی پیش‌نویس یا پیشنهاد MCP.', 'پیشنهاد ساخته‌شده برای یادداشت و مخزن موردنظر.', 'خواندن پذیرش نیست. اعمال متن می‌نویسد و باید روند بومی بررسی و مجوز را حفظ کند.', [
      ['تأیید مقصد', 'مسیر یادداشت و نسخهٔ منبع را پیش از بررسی پیشنهاد تأیید کنید.'], ['خواندن تغییر', 'متن پیشنهادی را با سند فعلی مقایسه کنید. شاهد، حذف و قالب‌بندی را ببینید.'], ['اعمال آگاهانه', 'فقط پس از بررسی از اعمال صریح استفاده کنید. مقصد قدیمی تازه‌سازی و بررسی می‌خواهد، نه بازنویسی اجباری.'], ['تأیید و بازیابی', 'یادداشت ذخیره‌شده و نتیجهٔ ممیزی را ببینید. برای پیامد ناخواسته از واگرد، تاریخچه یا Git مناسب استفاده کنید.'],
    ], [['همهٔ پیش‌نویس‌های آینده را تأیید کنم؟', 'یک تغییر بررسی‌شده اختیار نامحدود نیست. هر روند دامنهٔ خودش را دارد.'], ['چرا پیشنهاد قدیمی است؟', 'ممکن است پس از ساخت پیشنهاد یادداشت عوض شده باشد. با منبع فعلی تطبیق دهید.']]),
  },
  'code-chunks': {
    de: body('Externe Codeblöcke ausführen', 'Ausführbare Codeblock-Steuerung in unterstützter Vorschau.', 'Ausdrücklich aktivierte Ausführung, freigegebene Werkzeugrichtlinie und installiertes Programm.', 'Ausführung startet möglicherweise externe Prozesse. Führen Sie keine unvertrauenswürdigen Notizen aus und erteilen Sie keine Rechte nur zur Darstellung.', [
      ['Quelle prüfen', 'Lesen Sie gesamten Befehl, Code und Eingaben vor Start. Eine Sprachmarkierung macht Code nicht vertrauenswürdig.'], ['Rechte und Richtlinie prüfen', 'Prüfen Sie Programm, Arbeitsbereich, Netzwerkfreigabe und Bestätigung.'], ['Begrenzte Ausgabe lesen', 'Prüfen Sie Ausgabe, Zeitlimit, Abbruch und Prozessstatus. Große Ausgabe kann bewusst gekürzt sein.'], ['Nebenwirkungen prüfen', 'Prüfen Sie neue oder geänderte Dateien und behalten Sie Beleg und Fehler. Eine Tour führt niemals Code aus.'],
    ], [['Warum fehlt Ausführen?', 'Ausführung ist freiwillig und kann durch Funktion, Richtlinie, fehlende Programme oder fehlenden Desktop blockiert sein.'], ['Beweist erfolgreiche Ausführung Richtigkeit?', 'Nein. Prüfen Sie Ausgabe und Nebenwirkungen unabhängig.']]),
    fa: body('اجرای قطعهٔ کد بیرونی', 'کنترل کد قابل‌اجرا در پیش‌نمایش پشتیبانی‌شده.', 'فعال‌سازی صریح اجرا، سیاست ابزار مجاز و برنامهٔ نصب‌شده.', 'اجرا ممکن است پردازهٔ بیرونی راه بیندازد. یادداشت نامطمئن را اجرا نکنید و صرفاً برای نمایش سند دسترسی ندهید.', [
      ['بررسی منبع', 'پیش از اجرا تمام فرمان، کد و ورودی را بخوانید. برچسب زبان، برنامه را خودکار قابل‌اعتماد نمی‌کند.'], ['بررسی مجوز و سیاست', 'برنامه، دامنهٔ کار، دسترسی شبکه و تأیید را ببینید.'], ['خواندن خروجی محدود', 'خروجی، مهلت، لغو و وضعیت خروج را بخوانید. خروجی بزرگ ممکن است عمداً کوتاه شود.'], ['بررسی اثر جانبی', 'فایل ایجادشده یا تغییرکرده و رسید یا خطا را نگه دارید. خواندن آموزش هیچ کدی اجرا نمی‌کند.'],
    ], [['چرا اجرا در دسترس نیست؟', 'اجرا اختیاری است و شاید قابلیت، سیاست، نبود ابزار یا نبود دسکتاپ بومی مانع باشد.'], ['اجرای موفق درستی نتیجه را ثابت می‌کند؟', 'خیر. خروجی و اثر جانبی را مستقل بررسی کنید.']]),
  },
  'feature-flags': {
    de: body('Funktionsschalter und experimentelle Bereiche', 'Plugins > Funktionen; erweiterte Einstellungen.', 'Lesen Sie vor dem Aktivieren die Funktionsreife.', 'Ein Schalter garantiert keine Unterstützung. Ändern Sie jeweils nur eine Funktion und halten Sie Wiederherstellung bereit.', [
      ['Reife lesen', 'Unterscheiden Sie unterstützt, experimentell und nur geplant. Eine Bibliothek bedeutet nicht, dass eine Produktoberfläche existiert.'], ['Gezielt aktivieren', 'Wählen Sie die kleinste benötigte Funktion und öffnen Sie ihre tatsächliche Oberfläche.'], ['Verhalten prüfen', 'Testen Sie mit entbehrlichen Daten vor wichtiger Arbeit, besonders bei Integrationen, die Quellen schreiben.'], ['Deaktivieren und melden', 'Notieren Sie bei Fehlern Schalter und Meldung und kehren Sie zur bekannten funktionierenden Konfiguration zurück.'],
    ], [['Kann ich hier Mobilgeräte oder einen öffentlichen Marktplatz aktivieren?', 'Nein. Reine Entwürfe sind keine ausgelieferten Funktionen.'], ['Macht Deaktivieren frühere Dateiänderungen rückgängig?', 'Nein. Nutzen Sie Notizverlauf, Git oder Sicherungen.']]),
    fa: body('کلید قابلیت و بخش آزمایشی', 'افزونه‌ها > قابلیت‌ها؛ ترجیح‌های پیشرفته.', 'پیش از فعال کردن، بلوغ قابلیت را بخوانید.', 'کلید قابلیت تضمین پشتیبانی نیست. هر بار یک تغییر بدهید و راه بازیابی داشته باشید.', [
      ['خواندن بلوغ', 'پشتیبانی‌شده، آزمایشی و صرفاً طراحی‌شده را جدا کنید. بستهٔ کتابخانه وجود صفحهٔ قابل‌استفاده را ثابت نمی‌کند.'], ['فعال کردن برای هدف', 'کوچک‌ترین قابلیت لازم را انتخاب و رابط واقعی آن را باز کنید.'], ['بررسی رفتار', 'پیش از کار مهم با دادهٔ دورریختنی آزمایش کنید، به‌ویژه یکپارچه‌سازی‌ای که منبع را می‌نویسد.'], ['خاموش کردن و گزارش', 'برای یافتن خطا، نام کلید و پیام را ثبت و به تنظیم سالم شناخته‌شده برگردید.'],
    ], [['موبایل یا بازار عمومی را اینجا فعال کنم؟', 'خیر. پیشنهاد صرفاً طراحی‌شده قابلیت عرضه‌شده نیست.'], ['خاموش کردن، تغییر قبلی فایل را برمی‌گرداند؟', 'خیر. از تاریخچهٔ یادداشت، Git یا پشتیبان استفاده کنید.']]),
  },
  google: {
    de: body('Google Calendar und Tasks verbinden', 'Einstellungen > Integrationen > Google.', 'Desktop-App, Netzwerk und Google-OAuth-Client-ID für Desktop-Apps.', 'OAuth öffnet den Systembrowser und fragt Zugriffsbereiche ab. Tokens liegen im Betriebssystem-Schlüsselbund. Hilfe fragt keine Zugangsdaten ab und speichert sie nicht.', [
      ['Passende Kennung vorbereiten', 'Nutzen Sie eine Desktop-Client-ID, keine Web-Weiterleitung und kein Client-Geheimnis. Prüfen Sie Einrichtungshinweise und Konto.'], ['Speichern und verbinden', 'Prüfen Sie lokale Einstellungen. Genehmigen Sie nur gewünschtes Konto und Zugriffsbereiche. Abbruch ist keine erfolgreiche Verbindung.'], ['Anbieterdaten aktualisieren', 'Verbindung und Synchronisation sind getrennt. Synchronisieren Sie und prüfen Sie Calendar/Tasks vor Annahme der Bereitschaft.'], ['Trennen prüfen', 'Nutzen Sie Trennen und lesen Sie Bereinigungsfehler. Netzwerk- oder Schlüsselbundfehler beweisen keine entfernten Zugangsdaten.'],
    ], [['Warum scheitert Anmeldung vor der Browserzustimmung?', 'Lesen Sie den genauen Fehler: native Freigabe, deaktivierte Funktion, ungültiger Client und Browserstart sind verschiedene Ursachen.'], ['Warum sind Google-Aufgaben doppelt?', 'Prüfen Sie Quell-IDs und entfernte Aufgaben vor erneuter Spiegelung. Erstellen Sie keine Doppelaufträge bei ungeklärter Synchronisation.']]),
    fa: body('اتصال Google Calendar و Tasks', 'تنظیمات > یکپارچه‌سازی > Google.', 'برنامهٔ دسکتاپ، شبکه و شناسهٔ OAuth مخصوص برنامهٔ دسکتاپ Google.', 'OAuth مرورگر سیستم را باز و دامنهٔ دسترسی را درخواست می‌کند. توکن در کلیددان سیستم است. راهنما اطلاعات ورود را نمی‌گیرد یا ذخیره نمی‌کند.', [
      ['آماده کردن شناسهٔ درست', 'شناسهٔ برنامهٔ دسکتاپ را استفاده کنید، نه بازگردانی وب یا راز کلاینت. راه‌اندازی و حساب تنظیم‌شده را بررسی کنید.'], ['ذخیره و اتصال', 'تنظیم محلی را ببینید و فقط حساب و دسترسی موردنظر را تأیید کنید. انصراف اتصال موفق نیست.'], ['تازه کردن دادهٔ سرویس', 'اتصال و همگام‌سازی جدا هستند. همگام کنید و Calendar/Tasks را پیش از آماده دانستن حساب بررسی کنید.'], ['قطع اتصال با تأیید', 'قطع را بزنید و خطای پاک‌سازی را بخوانید. خطای شبکه یا کلیددان، حذف تأییدشدهٔ اطلاعات ورود نیست.'],
    ], [['چرا ورود پیش از رضایت مرورگر شکست می‌خورد؟', 'خطای دقیق را بخوانید؛ دامنهٔ مجوز بومی، قابلیت خاموش، تنظیم کلاینت و باز شدن مرورگر نقاط شکست جدا هستند.'], ['چرا کارهای Google تکراری‌اند؟', 'شناسهٔ منبع و کار دوردست را پیش از تکرار بازتاب بررسی کنید. تا همگام‌سازی قبلی روشن نشده، دوباره ایجاد نکنید.']]),
  },
  gmail: {
    de: body('Gmail-Konto, Nachrichten und Schreiben', 'Gmail Manager in Plugins aktivieren, dann über die Palette öffnen.', 'Desktop, aktivierte Gmail-Funktion, Google-Client, Netzwerk und Gmail-spezifische Zustimmung.', 'Senden überträgt E-Mail; Archiv/Papierkorb verändert das Postfach; Import schreibt eine Tresornotiz. Das sind getrennte ausdrückliche Aktionen.', [
      ['Konto verbinden', 'Öffnen Sie Konto und prüfen Sie die Google-Identität. Tokenprüfung, Offline-Fehler und Authentifizierungsfehler sind getrennt.'], ['Suchen und lesen', 'Nutzen Sie Gmail-Syntax und prüfen Sie Absender, Betreff und Inhalt. Die begrenzte Liste ist kein vollständiger Postfachexport.'], ['Importieren oder verwalten', 'Import speichert ausgewählten Text in Markdown. Archiv/Papierkorb verändert Gmail. Prüfen Sie vorher die richtige Nachricht.'], ['Sorgfältig schreiben', 'Prüfen Sie Empfänger, Betreff und Klartext vor Senden. Die experimentelle Oberfläche ersetzt nicht sämtliche Gmail-Thread- und Anhangsfunktionen.'],
    ], [['Warum öffnet Gmail stattdessen Plugins?', 'Die Funktion muss zuerst aktiviert und ihre Berechtigung geprüft sein.'], ['Wird importierte Mail zur laufenden Postfachkopie?', 'Nein. Markdown-Import ist eine lokale Kopie, keine beidseitige Nachrichtensynchronisation.']]),
    fa: body('حساب Gmail، پیام و نوشتن نامه', 'مدیر Gmail را در افزونه‌ها فعال و از فرمان‌ها باز کنید.', 'دسکتاپ، قابلیت Gmail فعال، کلاینت Google، شبکه و رضایت دامنهٔ Gmail.', 'ارسال نامه را می‌فرستد؛ بایگانی یا زباله‌دان صندوق را تغییر می‌دهد؛ وارد کردن یادداشت مخزن می‌نویسد. این عمل‌ها صریح و جدا هستند.', [
      ['اتصال حساب', 'حساب را باز و هویت Google را تأیید کنید. بررسی توکن، خطای آفلاین و خطای احراز هویت جدا هستند.'], ['جست‌وجو و خواندن', 'نحو جست‌وجوی Gmail را به کار ببرید و فرستنده، موضوع و متن را ببینید. نتیجه محدود است و کل صندوق را صادر نمی‌کند.'], ['وارد کردن یا مدیریت', 'وارد کردن متن انتخابی را به Markdown می‌برد؛ بایگانی و زباله‌دان Gmail را تغییر می‌دهد. اول پیام درست را تأیید کنید.'], ['نوشتن دقیق', 'پیش از ارسال، گیرنده، موضوع و متن ساده را بررسی کنید. این بخش آزمایشی جایگزین همهٔ قابلیت‌های رشته و پیوست Gmail نیست.'],
    ], [['چرا باز کردن Gmail به افزونه‌ها می‌رود؟', 'قابلیت باید ابتدا فعال و مجوزش بررسی شود.'], ['نامهٔ واردشده کپی زندهٔ صندوق است؟', 'خیر. وارد کردن Markdown کپی محلی است، نه همگام‌سازی دوطرفهٔ پیام.']]),
  },
  ai: {
    de: body('Freiwillige KI-Anfragen und Entwurfsvorschläge', 'KI-Anbietereinstellungen und unterstützte Entwurfsbefehle.', 'Konfigurierter Endpunkt und Modell sowie nötige Schlüsselbund-Zugangsdaten.', 'Anfragen können ausgewählten Inhalt senden. Prüfen Sie Vorschläge vor Anwendung; erzeugter Text ist kein verifizierter Beleg.', [
      ['Grenze wählen', 'Prüfen Sie Endpunkt, Modell und abfließende Daten. Ein lokal klingender Name beweist keinen lokalen Endpunkt.'], ['Zugangsdaten sicher konfigurieren', 'Nutzen Sie den Schlüsselbund. Keine Geheimnisse in Notizen, Hilfesuche, Bildschirmfotos oder Fehlermeldungen einfügen.'], ['Begrenzten Entwurf anfordern', 'Wählen Sie nur benötigtes Material und prüfen Sie Fehler und Zeitlimit. Ein Markdown-[!ai]-Callout ist eine Vorlage, keine ausgeführte Anfrage.'], ['Vor Anwendung prüfen', 'Vergleichen Sie Aussagen, Zitate, Ton und Änderungen mit dem Original. Halten Sie Rückgängig und Verlauf bereit.'],
    ], [['Läuft KI automatisch beim Schreiben?', 'Der Ablauf ist freiwillig. Hilfe lesen oder Callout einfügen genehmigt keine Anbieteranfrage.'], ['Was tun nach Zeitüberschreitung?', 'Prüfen Sie Anbieter, Modell, Netzwerk und eventuell noch laufende Arbeit vor Wiederholung.']]),
    fa: body('ارائه‌دهندهٔ اختیاری هوش مصنوعی و پیش‌نویس', 'تنظیم ارائه‌دهنده و فرمان پیشنهاد پیش‌نویس.', 'نشانی و مدل تنظیم‌شده و اطلاعات لازم در کلیددان.', 'درخواست ممکن است متن انتخابی را ارسال کند. پیشنهاد را پیش از اعمال بررسی کنید؛ متن تولیدشده شاهد تأییدشده نیست.', [
      ['انتخاب مرز', 'نشانی، مدل و دادهٔ خروجی از دستگاه را بررسی کنید. نام ظاهراً محلی، محلی بودن سرویس را ثابت نمی‌کند.'], ['تنظیم ایمن اطلاعات ورود', 'از کلیددان پشتیبانی‌شده استفاده کنید. راز را در یادداشت، جست‌وجوی راهنما، تصویر یا گزارش مشکل نگذارید.'], ['درخواست پیش‌نویس محدود', 'فقط دادهٔ لازم را انتخاب و خطا و مهلت را بررسی کنید. کادر Markdown با [!ai] الگو است، نه درخواست اجراشده.'], ['بررسی پیش از اعمال', 'ادعا، ارجاع، لحن و تغییر را با اصل مقایسه کنید. راه واگرد و تاریخچه را نگه دارید.'],
    ], [['هوش مصنوعی هنگام تایپ خودکار اجرا می‌شود؟', 'روند اختیاری است. خواندن راهنما یا درج کادر مجوز درخواست سرویس نیست.'], ['پس از پایان مهلت چه کنم؟', 'تنظیم سرویس، مدل، شبکه و احتمال ادامهٔ کار را پیش از تلاش دوباره بررسی کنید.']]),
  },
  'export-jobs': {
    de: body('Exportaufträge, Fortschritt und Belege', 'Exportaufträge und Statusbereich.', 'Ein Export- oder Werkzeugauftrag wurde gestartet.', 'Ein laufender Auftrag ist keine fertige Datei. Abbruch und Bereinigung hängen vom Auftragseigner und sichtbaren Ergebnis ab.', [
      ['Auftrag erkennen', 'Prüfen Sie Notiz, Format und Ausgabeziel; verlassen Sie sich nicht nur auf den letzten Status.'], ['Fortschritt beobachten', 'Lesen Sie wartend, laufend, abgeschlossen oder fehlgeschlagen und verfügbare Protokolle. Starten Sie keine Doppelaufträge während langsamer Arbeit.'], ['Bewusst abbrechen', 'Nutzen Sie vorhandene Abbruchaktionen und prüfen Sie den Folgestatus vor einem neuen Versuch.'], ['Belege behalten', 'Prüfen Sie erfolgreiche Ausgabe; bewahren Sie bei Fehlern bereinigte Werkzeugmeldungen und Belege für die Diagnose auf.'],
    ], [['Darf ich den Bereich während eines Auftrags schließen?', 'Die Ansicht zu schließen bricht den Auftrag nicht zwangsläufig ab. Prüfen Sie seinen Zustand ausdrücklich.'], ['Beweist der Prozesscode gute Ausgabe?', 'Nein. Prüfen Sie die erzeugte Datei und gemeldete Verifikationsbelege.']]),
    fa: body('کارهای خروجی، پیشرفت و رسید', 'بخش کارهای خروجی و وضعیت.', 'کار خروجی یا ابزار بیرونی شروع شده باشد.', 'کار در حال اجرا فایل کامل نیست. لغو و پاک‌سازی به مالک کار و نتیجهٔ قابل‌مشاهده وابسته است.', [
      ['تشخیص کار', 'یادداشت، قالب و مقصد را تطبیق دهید؛ فقط به آخرین وضعیت تکیه نکنید.'], ['دیدن پیشرفت', 'صف، اجرا، تکمیل، شکست و گزارش موجود را بخوانید. وقتی کار کند هنوز فعال است، نسخهٔ تکراری شروع نکنید.'], ['لغو آگاهانه', 'از عمل لغو پشتیبانی‌شده استفاده و پیش از تلاش دوباره وضعیت حاصل را بررسی کنید.'], ['حفظ شاهد مفید', 'در موفقیت خروجی را ببینید؛ در شکست خطای پالایش‌شده، اطلاعات ابزار و رسید را برای تشخیص نگه دارید.'],
    ], [['هنگام کار می‌توانم پنل را ببندم؟', 'بستن نما لزوماً کار را لغو نمی‌کند. وضعیت کار را صریح بررسی کنید.'], ['کد خروج پردازه به‌تنهایی کیفیت خروجی را ثابت می‌کند؟', 'خیر. فایل ساخته‌شده و شواهد تأیید گزارش‌شده را بررسی کنید.']]),
  },
  plugins: {
    de: body('Laufzeit-Plugins und Funktionszustand', 'Inspektor > Plugins > Installierte verwalten / Plugins durchsuchen.', 'Ein offener Tresor und ein unterstützter Eintrag des Herstellerkatalogs.', 'Installiert, aktiviert, genehmigt und laufzeitbereit sind getrennte Zustände. Hilfe aktiviert kein Plugin für Sie.', [
      ['Plugin prüfen', 'Lesen Sie Zweck, Herausgeber, Reife, Beiträge und Zugriff. Der Katalog ist beschränkt; ein allgemeiner signierter öffentlicher Marktplatz ist nicht verfügbar.'], ['Berechtigung prüfen', 'Verstehen Sie angeforderte Daten und Aktionen. Zustimmung gehört zur angegebenen Operation, nicht zu einem vagen Vertrauenswert.'], ['Aktivieren und prüfen', 'Aktivieren Sie die gewünschte Funktion und prüfen Sie Befehle und Widgets sowie Speicher- und Laufzeitfehler.'], ['Sicher wiederherstellen', 'Nutzen Sie sicheren Modus oder deaktivieren Sie das Plugin zur Fehlereingrenzung. Aktivieren Sie bewusst erneut; zurückgesetzte Rechte benötigen möglicherweise neue Prüfung.'],
    ], [['Warum läuft ein installiertes Plugin nicht?', 'Es kann deaktiviert sein, Zustimmung fehlen, im sicheren Modus gesperrt sein oder an nativer Laufzeitprüfung scheitern.'], ['Kann ich beliebiges JavaScript von Dritten installieren?', 'Der Katalog beweist das nicht. Die aktuelle Plattform ist eingeschränkt, herstellergeführt und experimentell.']]),
    fa: body('افزونهٔ اجرا و وضعیت قابلیت', 'بررسی > افزونه‌ها > مدیریت نصب‌شده یا مرور افزونه.', 'مخزن باز و ورودی پشتیبانی‌شدهٔ فهرست سازنده.', 'نصب، فعال بودن، تأیید مجوز و آمادگی اجرا وضعیت جدا دارند. راهنما افزونه را برای شما فعال نمی‌کند.', [
      ['بررسی افزونه', 'هدف، ناشر، بلوغ، قابلیت افزوده و دسترسی لازم را بخوانید. فهرست محدود است؛ بازار عمومی امضاشدهٔ جامع در دسترس نیست.'], ['بررسی مجوز', 'داده و عمل درخواستی را بشناسید. تأیید باید به عملیات اعلام‌شده مربوط باشد، نه امتیاز مبهم اعتماد.'], ['فعال‌سازی و تأیید', 'قابلیت موردنظر را فعال و دسترسی فرمان و ابزارک را بررسی کنید. خطای ماندگاری و اجرا را بخوانید.'], ['بازیابی ایمن', 'برای جداسازی مشکل از حالت امن یا غیرفعال کردن افزونه استفاده کنید. دوباره آگاهانه فعال کنید؛ بازنشانی مجوز ممکن است بررسی تازه بخواهد.'],
    ], [['چرا افزونهٔ نصب‌شده اجرا نمی‌شود؟', 'ممکن است غیرفعال، فاقد رضایت، مسدود در حالت امن یا ناموفق در بررسی قابلیت بومی باشد.'], ['JavaScript دلخواه دیگران را می‌توانم نصب کنم؟', 'از رابط فهرست چنین نتیجه نگیرید. سکوی فعلی محدود، وابسته به سازنده و آزمایشی است.']]),
  },
  modules: {
    de: body('Eingebaute Module und Installationsprofile', 'Eingebaute Module über Einstellungen oder Befehle.', 'Prüfen Sie aktiven Tresor und Modulliste.', 'Ein Profil kann mehrere Funktionen zugleich verändern. Prüfen Sie seine Folgen vor dem Anwenden.', [
      ['Aussehen und Funktionen trennen', 'Paletten verändern Darstellung, Module verändern Möglichkeiten. Wählen Sie den passenden Tab.'], ['Modul prüfen', 'Lesen Sie Zugriff und Zweck. Eine fehlende Funktion kann erklären, warum ein Bereich nicht öffnet.'], ['Profil prüfen', 'Prüfen Sie betroffene Module; der Profilname allein garantiert keine Eignung.'], ['Ergebnis kontrollieren', 'Öffnen Sie die erwartete Funktion und lesen Sie Fehler. Stellen Sie frühere Einstellungen wieder her, wenn ein Profil benötigte Funktionen entfernt hat.'],
    ], [['Warum scheitert ein scheinbar aktives Modul?', 'Laufzeit, gespeicherter Tresorzustand und Rechte müssen übereinstimmen. Prüfen Sie den Fehler und nutzen Sie den vorgesehenen Konfigurationsweg.'], ['Löscht Graph deaktivieren Notizen?', 'Nein. Eine Ansichtsfunktion zu deaktivieren verändert ihren Zugang, nicht die Quelldateien.']]),
    fa: body('ماژول داخلی و نمایهٔ نصب', 'ماژول‌های داخلی از تنظیمات یا فرمان‌ها.', 'مخزن فعال و فهرست ماژول را بررسی کنید.', 'نمایه می‌تواند چند قابلیت را همزمان تغییر دهد. پیش از اعمال پیامد را بررسی کنید.', [
      ['جداسازی ظاهر و قابلیت', 'پالت ظاهر را تغییر می‌دهد؛ ماژول کار قابل‌انجام را. زبانهٔ موردنظر را انتخاب کنید.'], ['بررسی ماژول', 'دسترسی و هدف را بخوانید. نبودن قابلیت ممکن است علت باز نشدن پنل باشد.'], ['بررسی نمایه', 'مجموعهٔ ماژول‌های متاثر را بشناسید؛ نام نمایه تضمین مناسب بودن نیست.'], ['کنترل نتیجه', 'قابلیت موردانتظار را باز و خطا را ببینید. اگر نمایهٔ گروهی قابلیت لازم را برداشته، انتخاب قبلی را برگردانید.'],
    ], [['چرا ماژول ظاهراً فعال شکست می‌خورد؟', 'اجرا، وضعیت ذخیره‌شدهٔ مخزن و مجوز باید هماهنگ باشند. خطا را بررسی و مسیر تنظیم پشتیبانی‌شده را دوباره طی کنید.'], ['غیرفعال کردن گراف یادداشت را حذف می‌کند؟', 'خیر. خاموش کردن قابلیت نمایش، دسترسی به قابلیت را تغییر می‌دهد نه یادداشت منبع را.']]),
  },
  permissions: {
    de: body('Plugin-Zustimmung und native Bestätigungen', 'Angeforderten Zugriff und Bestätigungsdialoge prüfen.', 'Kennen Sie Plugin, Aktion, Ressource und aktiven Tresor.', 'Genehmigen Sie nichts nur zum Verbergen eines Fehlers. Rechte sind begrenzt und können einmalig sein; Tourfortschritt ist keine Zustimmung.', [
      ['Aufrufer erkennen', 'Prüfen Sie anfragende Funktion oder Plugin und ob Sie den Ablauf selbst gestartet haben.'], ['Bereich und Folgen prüfen', 'Lesen Sie Datei/Ressource, Aktion und ob Daten gelesen, geschrieben, gesendet, ausgeführt oder gelöscht werden.'], ['Ausdrücklich entscheiden', 'Brechen Sie bei unerwartetem Bereich ab. Zustimmung gilt für die benannte Aktion, nicht jede künftige App-Nutzung.'], ['Abgelaufene Zustimmung erneuern', 'Starten Sie den gewünschten Ablauf für eine neue Freigabe erneut. Umgehen oder erweitern Sie keine fehlgeschlagene Prüfung.'],
    ], [['Warum werde ich erneut gefragt?', 'Eine Freigabe kann verbraucht, abgelaufen, zurückgesetzt oder an eine andere Ressource/einen anderen Tresor gebunden sein.'], ['Kann eine Tour Berechtigungen genehmigen?', 'Nein. Hilfe ist schreibgeschützt und kann keine native Freigabe erzeugen.']]),
    fa: body('رضایت افزونه و تأیید بومی', 'بررسی دسترسی لازم و پنجرهٔ تأیید.', 'افزونه، عملیات، منبع و مخزن فعال را بشناسید.', 'صرفاً برای خاموش کردن خطا تأیید نکنید. مجوز محدود و گاه یک‌بارمصرف است؛ پیشرفت آموزش رضایت نیست.', [
      ['شناخت درخواست‌کننده', 'بررسی کنید کدام قابلیت یا افزونه دسترسی می‌خواهد و آیا خودتان روند را شروع کرده‌اید.'], ['بررسی دامنه و پیامد', 'فایل یا منبع و عملیات را بخوانید و بدانید داده خوانده، نوشته، ارسال، اجرا یا حذف می‌شود.'], ['انتخاب صریح', 'اگر دامنه غیرمنتظره است انصراف دهید. تأیید برای عملیات نام‌برده است، نه هر استفادهٔ آینده از برنامه.'], ['تازه کردن مجوز منقضی', 'روند موردنظر را برای مجوز تازه دوباره شروع کنید. بررسی ناموفق را دور نزنید یا دامنه‌اش را گسترده نکنید.'],
    ], [['چرا دوباره سؤال می‌شود؟', 'مجوز ممکن است مصرف‌شده، منقضی، بازنشانی‌شده یا وابسته به منبع یا مخزن دیگر باشد.'], ['آموزش می‌تواند مجوز بدهد؟', 'خیر. راهنما فقط‌خواندنی است و نمی‌تواند مجوز بومی بسازد.']]),
  },
  export: {
    de: body('Export und Pandoc-Vorabprüfung', 'Exportieren / Veröffentlichen oder Veröffentlichungszentrum öffnen.', 'Eine aktive Notiz, ein passendes Exportprofil und benötigte externe Werkzeuge wie Pandoc.', 'Export schreibt Ausgabedateien und kann freigegebene externe Werkzeuge ausführen. Vorabprüfung ist noch kein Exportergebnis.', [
      ['Format wählen', 'Wählen Sie ein Profil passend zu Publikum und Ziel: Dokument, HTML, PDF oder andere unterstützte Ausgabe.'], ['Vorabprüfung ausführen', 'Lesen Sie fehlende Abhängigkeiten, Zitat-, Ressourcen- und Profilfehler. Beheben Sie Werkzeuganforderungen statt wiederholt Export zu drücken.'], ['Ausgabebereich prüfen', 'Prüfen Sie Zielpfade und Werkzeugberechtigung. Bestätigen Sie nur gewünschte Aktionen und Dateien.'], ['Ergebnis prüfen', 'Öffnen Sie die erzeugte Datei und prüfen Sie Layout, Abbildungen, Zitate, Überschriften und Metadaten vor der Weitergabe.'],
    ], [['Warum scheitert PDF trotz funktionierender Vorschau?', 'PDF kann Pandoc und zusätzliche Werkzeuge benötigen. Vorschau beweist nicht deren Installation oder Konfiguration.'], ['Veröffentlicht Export im Internet?', 'Lokaler Export und Bereitstellung sind unterschiedliche Aktionen. Prüfen Sie Ablauf und Ziel.']]),
    fa: body('خروجی گرفتن و پیش‌بررسی Pandoc', 'خروجی و انتشار یا باز کردن مرکز انتشار.', 'یادداشت فعال، نمایهٔ خروجی مناسب و ابزار بیرونی لازم مانند Pandoc.', 'خروجی فایل می‌نویسد و ممکن است ابزار بیرونی مجاز اجرا کند. پیش‌بررسی خودِ فایل خروجی نیست.', [
      ['انتخاب قالب', 'نمایه را مناسب مخاطب و مقصد انتخاب کنید: سند، HTML، PDF یا خروجی پشتیبانی‌شدهٔ دیگر.'], ['اجرای پیش‌بررسی', 'وابستگی غایب و خطای ارجاع، منبع و نمایه را بخوانید. ابزار لازم را آماده کنید، نه اینکه مکرر خروجی بزنید.'], ['بررسی دامنهٔ خروجی', 'مسیر مقصد و مجوز ابزار بیرونی را ببینید. فقط عملیات و فایل موردنظر را تأیید کنید.'], ['بررسی نتیجه', 'فایل ساخته‌شده را باز و پیش از توزیع چیدمان، شکل، ارجاع، عنوان و فراداده را بررسی کنید.'],
    ], [['چرا PDF شکست می‌خورد اما پیش‌نمایش کار می‌کند؟', 'ساخت PDF ممکن است Pandoc و ابزار اضافی بخواهد. موفقیت پیش‌نمایش نصب یا تنظیم آن‌ها را ثابت نمی‌کند.'], ['خروجی در اینترنت منتشر می‌شود؟', 'خروجی محلی و استقرار عمل متفاوت‌اند. روند و مقصد انتخابی را بررسی کنید.']]),
  },
  publish: {
    de: body('Lokale Starlight-Veröffentlichung', 'Veröffentlichungsablauf in Export & Veröffentlichung.', 'Freigegebene Notizen mit publish: true und ein konfiguriertes lokales Ausgabeziel.', 'Planung ist schreibgeschützt; Anwenden schreibt verwaltete Ausgaben. Das erlaubt weder öffentliche Bereitstellung noch Löschung fremder Dateien.', [
      ['Notizen freigeben', 'Prüfen Sie Veröffentlichungsmetadaten und sensible Inhalte. Eine freigegebene Notiz ist Kandidatin, nicht automatisch öffentlich.'], ['Plan erstellen', 'Prüfen Sie neue, geänderte und verwaiste verwaltete Ausgaben. Quelltresor und Ausgabeordner müssen getrennt sein.'], ['Vor Anwendung prüfen', 'Schließen Sie nicht zu kopierende Inhalte aus. Beheben Sie veraltete Pläne und extern veränderte Ausgaben, statt Warnungen zu erzwingen.'], ['Prüfen und separat bereitstellen', 'Prüfen Sie lokale Seiten, Links und Assets. Internet-Hosting ist ein eigener bewusster Ablauf.'],
    ], [['Warum wurde Anwenden abgelehnt?', 'Quellhashes, Freigabe oder Ausgabezustand können sich seit der Planung verändert haben. Erstellen und prüfen Sie einen neuen Plan.'], ['Gehören alle Ausgabedateien Scriptor?', 'Nein. Veröffentlichung verfolgt verwaltete Ausgaben und bewahrt andere Dateien. Behandeln Sie den Ordner nicht als beliebig löschbar.']]),
    fa: body('انتشار محلی Starlight', 'روند انتشار در خروجی و انتشار.', 'یادداشت واجد شرایط با publish: true و مقصد خروجی محلی تنظیم‌شده.', 'برنامه‌ریزی فقط‌خواندنی است؛ اعمال خروجی مدیریت‌شده را می‌نویسد. این به‌تنهایی مجوز استقرار عمومی یا حذف فایل خارج از مدیریت نیست.', [
      ['انتخاب یادداشت برای انتشار', 'فراداده و حساسیت متن را بررسی کنید. واجد شرایط بودن فقط نامزد شدن است، نه عمومی بودن خودکار.'], ['ساخت برنامه', 'خروجی جدید، تغییرکرده و یتیم مدیریت‌شده را بررسی کنید. مخزن منبع و پوشهٔ خروجی باید جدا باشند.'], ['بررسی پیش از اعمال', 'محتوای نامناسب برای کپی را کنار بگذارید. خطای برنامهٔ قدیمی یا خروجی تغییرکردهٔ بیرونی را حل کنید، نه اینکه تحمیل کنید.'], ['بررسی و استقرار جدا', 'صفحهٔ محلی، پیوند و دارایی را بررسی کنید. میزبانی اینترنت روند آگاهانهٔ جداست.'],
    ], [['چرا اعمال رد شد؟', 'هش منبع، صلاحیت یا وضعیت خروجی شاید از زمان برنامه‌ریزی تغییر کرده باشد. برنامهٔ تازه بسازید و بررسی کنید.'], ['همهٔ فایل‌های پوشهٔ خروجی متعلق به Scriptor هستند؟', 'خیر. انتشار خروجی مدیریت‌شده را دنبال و فایل نامربوط را حفظ می‌کند. پوشه را دورریختنی ندانید.']]),
  },
  'publish-diff': {
    de: body('Veröffentlichungsänderungen prüfen', 'Veröffentlichungsplan, Prüfung und Differenzansicht.', 'Ein aktueller Veröffentlichungsplan.', 'Auswahl und Anwenden sind getrennte Entscheidungen. Eine Differenz zu lesen darf keine stille Lösch- oder Überschreibfreigabe sein.', [
      ['Änderungsarten verstehen', 'Unterscheiden Sie neue Ausgabe, geänderten Inhalt, fehlende Ausgabe und veraltete verwaltete Dateien.'], ['Sinnvolle Unterschiede lesen', 'Prüfen Sie Inhalte, Metadaten, Asset-Ziele und Links. Genehmigen Sie nicht allein aufgrund der Dateianzahl.'], ['Bereich wählen', 'Wählen Sie nur gewünschte Änderungen. Prüfen Sie unerwartete Löschungen oder extern bearbeitete Ausgaben erneut.'], ['Frischen Plan anwenden', 'Erzeugen Sie nach Quellenänderung einen neuen Plan. Prüfen Sie das Ergebnis und bewahren Sie Fehlerkontext bei Teilfehlern.'],
    ], [['Kann ich einen Plan von vor einer Bearbeitung anwenden?', 'Ein veralteter Plan kann aus Integritätsgründen abgelehnt werden. Planen und prüfen Sie neu.'], ['Beweist eine saubere Differenz eine richtige Website?', 'Nein. Sie beschreibt nur Unterschiede zum Vergleichszustand. Prüfen Sie Darstellung und Inhalte.']]),
    fa: body('بررسی تغییرهای انتشار', 'برنامه و بررسی انتشار و نمای تفاوت.', 'برنامهٔ انتشار تازه.', 'انتخاب و اعمال تصمیم‌های جدا هستند. خواندن تفاوت نباید بی‌صدا مجوز حذف یا بازنویسی بدهد.', [
      ['شناخت نوع تغییر', 'خروجی جدید، محتوای تغییرکرده، خروجی غایب و خروجی مدیریت‌شدهٔ قدیمی را جدا کنید.'], ['خواندن تفاوت مهم', 'تغییر متن، فراداده، مقصد دارایی و پیوند را بخوانید؛ صرفاً با تعداد فایل تأیید نکنید.'], ['انتخاب دامنه', 'فقط تغییر موردنظر را انتخاب کنید. حذف غیرمنتظره و خروجی ویرایش‌شدهٔ بیرونی را دوباره ببینید.'], ['اعمال برنامهٔ تازه', 'بعد از ویرایش منبع، برنامه را دوباره بسازید. نتیجهٔ اعمال را تأیید و در شکست جزئی زمینهٔ خطا را نگه دارید.'],
    ], [['برنامهٔ پیش از ویرایش را می‌توانم اعمال کنم؟', 'برنامهٔ قدیمی ممکن است برای حفظ یکپارچگی رد شود. دوباره برنامه‌ریزی و بررسی کنید.'], ['تفاوت پاک، درستی سایت را ثابت می‌کند؟', 'خیر. فقط تفاوت با وضعیت مقایسه را بیان می‌کند. خروجی رندرشده و محتوا را بررسی کنید.']]),
  },
  'publish-readiness': {
    de: body('Veröffentlichungsbereitschaft und Tresorzustand', 'Zustands- und Bereitschaftskarten im Inspektor.', 'Aktueller Index und aktive Notiz für notizbezogene Prüfungen.', 'Bereit/Gut fasst bestimmte Prüfungen zusammen, nicht Wahrheit, Berechtigung oder garantierten Exporterfolg.', [
      ['Bereich lesen', 'Bestimmen Sie, ob die Karte aktive Notiz, Tresor oder Indexcache beschreibt.'], ['Befunde prüfen', 'Öffnen Sie fehlende Zitate, defekte Links oder ungültige Metadaten und korrigieren Sie die tatsächliche Quelle.'], ['Nullen sorgfältig prüfen', 'Null ist nur nach erfolgreichem Lesen aussagekräftig. Laden oder Fehler beweist keine Problemfreiheit.'], ['Export vorab prüfen', 'Führen Sie zielabhängige Prüfungen aus und kontrollieren Sie die erzeugte Datei auch bei positiver Bereitschaft.'],
    ], [['Warum meldet Probleme Fehler trotz guter Bereitschaft?', 'Bereiche und Prüfungen unterscheiden sich. Lesen Sie die zugrunde liegenden Meldungen.'], ['Prüft Exportbereit auch installierte Werkzeuge?', 'Nutzen Sie die Vorabprüfung des gewählten Profils. Die Karte allein genügt nicht.']]),
    fa: body('آمادگی انتشار و ابزارک سلامت مخزن', 'کارت سلامت و آمادگی در نوار بررسی.', 'نمایهٔ تازه و یادداشت فعال برای بررسی مختص یادداشت.', 'آماده یا خوب خلاصهٔ بررسی مشخص است، نه صحت واقعیت، مجوز یا تضمین موفقیت خروجی.', [
      ['خواندن دامنه', 'مشخص کنید ابزارک یادداشت فعلی، مخزن یا حافظهٔ نمایه را توصیف می‌کند.'], ['بررسی یافته', 'ارجاع غایب، پیوند شکسته یا فرادادهٔ نادرست را باز و منبع واقعی را اصلاح کنید.'], ['بررسی دقیق صفر', 'صفر فقط پس از خواندن موفق معنا دارد. بارگذاری یا شکست نبودن مشکل را ثابت نمی‌کند.'], ['پیش‌بررسی خروجی', 'بررسی مختص مقصد را اجرا و حتی با آمادگی مثبت، فایل نتیجه را ببینید.'],
    ], [['چرا با آمادگی خوب، مشکلات خطا دارند؟', 'بخش‌ها دامنه و بررسی متفاوت گزارش می‌کنند. پیام اصلی را بخوانید.'], ['آمادهٔ خروجی ابزار نصب‌شده را هم بررسی می‌کند؟', 'از پیش‌بررسی نمایهٔ انتخابی استفاده کنید؛ کارت آمادگی کافی نیست.']]),
  },
}
