import { body, type GuideTranslations } from './translationTypes.ts'

export const knowledgeTranslations: GuideTranslations = {
  canvas: {
    de: body('Canvas und räumliche Notizen', 'Canvas öffnen in der Befehlspalette.', 'Öffnen Sie den richtigen Tresor und aktivieren Sie Canvas bei Bedarf.', 'Canvas-Bearbeitung speichert Boarddaten. Import, Anhänge und externe Ressourcen haben eigene Bestätigungsgrenzen.', [
      ['Board wählen', 'Prüfen Sie Board und Pfad in der Fußzeile vor dem Einfügen oder Verschieben. Canvas ist nicht der Notizeditor.'], ['Beziehungen aufbauen', 'Fügen Sie Blöcke hinzu oder wählen Sie sie aus und ordnen Sie nach Bedeutung. Prüfen Sie referenzierte Notiz- und Ressourcenziele.'], ['Räumlich navigieren', 'Nutzen Sie Zoom und Ansichtssteuerung für volle Boards. Zoom verändert die Ansicht, nicht den Dokumentinhalt.'], ['Speichern und prüfen', 'Prüfen Sie Fehler und gespeicherten Zustand. Export kann anders als das interaktive Board aussehen; prüfen Sie ihn vor dem Teilen.'],
    ], [['Verschiebt eine Karte ihre Markdown-Datei?', 'Nein. Boardanordnung und Dateipfade im Tresor sind unterschiedliche Dinge.'], ['Warum funktioniert ein externer Anhang nicht?', 'Er kann fehlen, außerhalb des Tresors liegen oder ausdrücklichen Zugriff benötigen. Nutzen Sie den unterstützten Import-/Ressourcenablauf.']]),
    fa: body('بوم و یادداشت‌های فضایی', 'باز کردن بوم از فهرست فرمان‌ها.', 'مخزن موردنظر را باز و در صورت نیاز بوم را فعال کنید.', 'ویرایش بوم دادهٔ تخته را ذخیره می‌کند. وارد کردن، پیوست و منبع بیرونی مرز تأیید جدا دارند.', [
      ['انتخاب تخته', 'پیش از افزودن یا جابه‌جایی، نام و مسیر تخته در پایین را بررسی کنید. بوم ویرایشگر یادداشت نیست.'], ['ساخت رابطه', 'بلوک را بیفزایید یا انتخاب و بر اساس معنا مرتب کنید. مقصد یادداشت و منبع ارجاع‌شده را بررسی کنید.'], ['پیمایش فضایی', 'برای تختهٔ شلوغ از بزرگ‌نمایی و کنترل دید استفاده کنید. بزرگ‌نمایی نما را عوض می‌کند، نه محتوای سند را.'], ['ذخیره و بررسی', 'خطای عملیات و ماندگاری تخته را بررسی کنید. خروجی ممکن است با تختهٔ تعاملی فرق کند؛ پیش از اشتراک آن را ببینید.'],
    ], [['جابه‌جایی کارت یعنی جابه‌جایی فایل Markdown؟', 'خیر. چیدمان تخته و مسیر فایل مخزن متفاوت‌اند.'], ['چرا پیوست بیرونی کار نمی‌کند؟', 'منبع ممکن است غایب، بیرون مخزن یا نیازمند دسترسی صریح باشد. از روند پشتیبانی‌شدهٔ وارد کردن یا منبع استفاده کنید.']]),
  },
  tasks: {
    de: body('Aufgaben aus Markdown', 'Aufgabenbereich öffnen in der Befehlspalette.', 'Ein offener indexierter Tresor mit unterstützter Markdown-Aufgabensyntax.', 'Abhaken und Bearbeiten schreibt die Ursprungsnotiz. Google-Synchronisierung ist eine separate, freiwillige Integration.', [
      ['Bereich wählen', 'Prüfen Sie Filter und Quellpfade. Treffer zeigen Markdown, keine unabhängige Aufgabendatenbank.'], ['Quelle öffnen', 'Lesen Sie umgebenden Text vor dem Bearbeiten mehrdeutiger oder doppelter Aufgaben. Die Quellposition kann sich ändern.'], ['Änderung anwenden', 'Nutzen Sie Abschluss-/Bearbeitungsaktionen und warten Sie auf das Ergebnis. Warten oder Fehler beweist keine gespeicherte Änderung.'], ['Bewusst synchronisieren', 'Aktivieren Sie Google nur nach Einrichtung. Lokaler Abschluss und entfernte Spiegelung haben getrennte Zustände und Fehlerwege.'],
    ], [['Warum schlug die Änderung fehl?', 'Quelle oder Verfügbarkeit können sich geändert haben oder das native Schreiben ist gescheitert. Aktualisieren, prüfen und bewusst wiederholen.'], ['Sind Kalenderereignisse Markdown-Aufgaben?', 'Nein. Ereignisse und lokale Aufgaben sind verschiedene Informationsarten der Integration.']]),
    fa: body('کارهای مبتنی بر Markdown', 'باز کردن پنل کارها در فرمان‌ها.', 'مخزن باز و نمایه‌شده با نحو کار Markdown پشتیبانی‌شده.', 'تیک زدن و ویرایش کار یادداشت مبدأ را می‌نویسد. همگام‌سازی Google یکپارچه‌سازی اختیاری جداست.', [
      ['انتخاب دامنه', 'فیلتر و مسیر منبع را بررسی کنید. نتیجه نمای Markdown است، نه پایگاه مستقل کار.'], ['باز کردن منبع', 'پیش از تغییر کار مبهم یا تکراری متن پیرامون را بخوانید. محل منبع با ویرایش یادداشت تغییر می‌کند.'], ['اعمال تغییر', 'از عمل تکمیل یا ویرایش استفاده و منتظر نتیجه بمانید. انتظار یا خطا ذخیره شدن را ثابت نمی‌کند.'], ['همگام‌سازی آگاهانه', 'Google را فقط پس از تنظیم فعال کنید. تکمیل محلی و بازتاب دوردست وضعیت و مسیر خطای جدا دارند.'],
    ], [['چرا ویرایش شکست خورد؟', 'متن منبع ممکن است تغییر کرده، یادداشت ناموجود یا نوشتن بومی ناموفق باشد. تازه‌سازی کنید، منبع را ببینید و آگاهانه دوباره تلاش کنید.'], ['رویداد تقویم هم کار Markdown است؟', 'خیر. رویداد و کار محلی دو نوع دادهٔ متفاوت در این یکپارچه‌سازی‌اند.']]),
  },
  kanban: {
    de: body('Markdown-Kanban', 'Kanban für die aktive Notiz öffnen.', 'Eine passende Markdown-Notiz mit unterstützten Überschriften und Karten.', 'Eine Karte zu verschieben schreibt ihren Quelltext unter der Zielüberschrift um; es ist keine bloße Ansichtsänderung.', [
      ['Quellstruktur prüfen', 'Spalten entstehen aus unterstützten Überschriften, Karten aus Quellinhalten. Beginnen Sie mit einer einfachen Notiz und klaren Spaltennamen.'], ['Bewusst verschieben', 'Wählen Sie die Zielspalte oder ziehen Sie die Karte, wenn unterstützt. Warten Sie auf den Schreibvorgang.'], ['Fehler behandeln', 'Eine fehlgeschlagene Bewegung ist keine gespeicherte Boardänderung. Prüfen Sie Meldung und Quelle vor Wiederholung.'], ['Markdown verifizieren', 'Kehren Sie zur Notiz zurück und prüfen Sie, dass die Karte genau einmal verschoben wurde und ihren Inhalt behielt. Nutzen Sie Verlauf zur Wiederherstellung.'],
    ], [['Warum ist das Board leer?', 'Die aktive Notiz enthält möglicherweise nicht die benötigte Überschriften-/Kartenstruktur.'], ['Kann ich während des Schreibens weitere Karten verschieben?', 'Vermeiden Sie überlappende Aktionen. Warten Sie auf Abschluss oder beheben Sie den Fehler vor der nächsten Bewegung.']]),
    fa: body('تختهٔ کانبان Markdown', 'کانبان را برای یادداشت فعال باز کنید.', 'یادداشت Markdown مناسب با عنوان بخش و کارت پشتیبانی‌شده.', 'جابه‌جایی کارت متن منبع را زیر عنوان مقصد بازنویسی می‌کند؛ صرفاً تغییر ظاهری نیست.', [
      ['بررسی ساختار', 'ستون از عنوان پشتیبانی‌شده و کارت از متن منبع می‌آید. با یادداشت ساده و نام ستون روشن شروع کنید.'], ['جابه‌جایی آگاهانه', 'ستون مقصد را انتخاب کنید یا در صورت پشتیبانی بکشید. هنگام نوشتن منبع منتظر بمانید.'], ['رسیدگی به خطا', 'جابه‌جایی ناموفق را تغییر ذخیره‌شده ندانید. پیام و منبع را پیش از تلاش دوباره ببینید.'], ['تأیید Markdown', 'به یادداشت برگردید و مطمئن شوید کارت یک بار جابه‌جا شده و متنش حفظ شده است. برای بازیابی از تاریخچه استفاده کنید.'],
    ], [['چرا تخته خالی است؟', 'ممکن است یادداشت فعال ساختار لازم عنوان و کارت را نداشته باشد.'], ['هنگام نوشتن می‌توانم چند کارت را پشت سر هم جابه‌جا کنم؟', 'از عمل هم‌پوشان پرهیز کنید. پیش از حرکت دیگر منتظر تکمیل بمانید یا خطا را حل کنید.']]),
  },
  reader: {
    de: body('PDF und EPUB im Tresor lesen', 'Leser öffnen in der Befehlspalette.', 'Desktop-Unterstützung und eine PDF/EPUB-Datei an einem unterstützten tresorrelativen Pfad.', 'Nur freigegebene Tresordokumente werden geöffnet. Annotationen speichern ist vom Bearbeiten des Originaldokuments getrennt.', [
      ['Dokument wählen', 'Wählen Sie den tresorrelativen Pfad. Beliebige externe Dateipfade sind nicht austauschbar.'], ['Im Dokument navigieren', 'Nutzen Sie Seiten-/Positions- und Lesesteuerung. Große Dokumente können länger laden; unterscheiden Sie Laden von Fehler.'], ['Belege erfassen', 'Wählen Sie eine Passage für den unterstützten Annotationsablauf und behalten Sie Seiten-/Positionskontext.'], ['Fehlenden Inhalt prüfen', 'Prüfen Sie Existenz im Tresor und unterstützten Typ. Erneut öffnen stellt keine gelöschte Quelldatei wieder her.'],
    ], [['Ändert Lesen das Original?', 'Der Betrachter liest die Datei; Annotationen nutzen eine Begleitdatei und schreiben das Original nicht um.'], ['Kann ich jede Website als PDF öffnen?', 'Nein. Der Leser ist auf Tresordokumente begrenzt und kein allgemeiner Browser.']]),
    fa: body('خواندن PDF و EPUB مخزن', 'باز کردن خوانشگر در فرمان‌ها.', 'نسخهٔ دسکتاپ و PDF یا EPUB در مسیر نسبی پشتیبانی‌شدهٔ مخزن.', 'فقط سند مجاز مخزن باز می‌شود. ذخیرهٔ حاشیه‌نویسی با ویرایش PDF یا EPUB اصلی فرق دارد.', [
      ['انتخاب سند', 'مسیر نسبی سند در مخزن را انتخاب کنید؛ مسیر دلخواه بیرون قابل‌جایگزینی نیست.'], ['پیمایش سند', 'از صفحه، موقعیت و کنترل خواندن استفاده کنید. سند بزرگ زمان می‌برد؛ بارگذاری را از خطا تشخیص دهید.'], ['ثبت شاهد', 'قطعه را برای روند حاشیه‌نویسی انتخاب و زمینهٔ صفحه یا موقعیت را حفظ کنید.'], ['بررسی محتوای غایب', 'وجود سند در مخزن و پشتیبانی نوع را تأیید کنید. باز کردن دوباره فایل منبع حذف‌شده را برنمی‌گرداند.'],
    ], [['خواندن اصل سند را تغییر می‌دهد؟', 'نمایشگر فایل را می‌خواند؛ حاشیه‌نویسی در فایل همراه است، نه بازنویسی اصل سند.'], ['هر وب‌سایتی را می‌توانم به‌صورت PDF باز کنم؟', 'خیر. خوانشگر روند محدود سند مخزن است، نه مرورگر عمومی.']]),
  },
  annotations: {
    de: body('Annotationen und Belegerfassung', 'Annotationswerkzeuge im Leser.', 'Ein unterstütztes Dokument ist im Leser geöffnet.', 'Annotationen liegen separat im Tresor. Sichern Sie Begleitdatei und Dokument gemeinsam, damit der Kontext erhalten bleibt.', [
      ['Präzise Passage wählen', 'Bewahren Sie genügend Zitat und Positionskontext, um die Quelle später zu identifizieren.'], ['Interpretation ergänzen', 'Trennen Sie Quelltext und eigene Kommentare. Halten Sie fest, warum der Beleg für die Argumentation wichtig ist.'], ['Speichern und prüfen', 'Prüfen Sie das Ergebnis und öffnen Sie die Annotation erneut. Eine vorübergehende Markierung beweist keine Speicherung.'], ['Im Schreiben verwenden', 'Verlinken oder zitieren Sie das Original mit der passenden Fundstelle. Annotationen ersetzen keine Quellenprüfung.'],
    ], [['Wo liegen Annotationen?', 'In der Annotations-Begleitdatei des Tresors. Sichern Sie sie zusammen mit den Quelldokumenten.'], ['Bleiben beim Umbenennen alle Annotationen erhalten?', 'Prüfen Sie Leser und Quellpfad nach Änderungen. Beliebige externe Verschiebungen aktualisieren Begleitverweise nicht zwangsläufig.']]),
    fa: body('حاشیه‌نویسی خوانشگر و ثبت شاهد', 'کنترل حاشیه‌نویسی داخل خوانشگر.', 'سند پشتیبانی‌شده در خوانشگر باز باشد.', 'حاشیه‌نویسی جدا در مخزن ذخیره می‌شود. برای حفظ زمینه، فایل همراه و سند را با هم پشتیبان بگیرید.', [
      ['انتخاب قطعهٔ دقیق', 'نقل‌قول و زمینهٔ موقعیت را به‌اندازه‌ای نگه دارید که بعداً منبع شناخته شود.'], ['افزودن تفسیر', 'متن منبع را از نظر خود جدا کنید. بنویسید چرا شاهد برای استدلال مهم است.'], ['ذخیره و تأیید', 'نتیجه را بررسی و حاشیه را دوباره باز کنید. برجسته‌سازی موقت به‌تنهایی ذخیره را اثبات نمی‌کند.'], ['استفاده در نوشتن', 'اصل منبع را با محل مربوط پیوند یا ارجاع دهید. حاشیه‌نویسی جای بررسی منبع نیست.'],
    ], [['حاشیه‌ها کجا نگه داشته می‌شوند؟', 'در فایل همراه حاشیه‌نویسی مخزن؛ آن را همراه سند منبع پشتیبان بگیرید.'], ['تغییر نام همهٔ حاشیه‌ها را حفظ می‌کند؟', 'بعد از تغییر، خوانشگر و مسیر را بررسی کنید. فرض نکنید جابه‌جایی بیرونی خودکار ارجاع فایل همراه را اصلاح می‌کند.']]),
  },
  'saved-views': {
    de: body('Gespeicherte Ansichten und Abfragen', 'Wissenswerkbank > Ansichten; Gespeicherte Ansichten.', 'Ein offener indexierter Tresor und unterstützte Abfragesyntax.', 'Eine Ansicht speichert eine Abfrage, keine Kopie oder Sicherung der Treffer.', [
      ['Absicht bestimmen', 'Beginnen Sie mit einer klaren Frage: letzte Notizen, Tag, Pfad oder Prüfstatus. Nutzen Sie unterstützte Filter statt freier Vermutungen.'], ['Vor Speichern ausführen', 'Prüfen Sie Treffer und Pfade. Schließen Sie Parser- oder Indexfehler als Ursache leerer Ergebnisse aus.'], ['Benennen und speichern', 'Benennen Sie die Ansicht nach ihrem Zweck, nicht nach vermeintlich festen Inhalten.'], ['Abfrage pflegen', 'Treffer verändern sich mit den Notizen. Prüfen Sie alte Filter nach Änderungen an Ordnern oder Tags.'],
    ], [['Warum verschwand der gestrige Treffer?', 'Ansichten sind aktuelle Indexabfragen, keine Schnappschüsse.'], ['Kann ich beliebiges SQL verwenden?', 'Nein. Nutzen Sie die unterstützten Abfragen und Filter; roher Datenbankzugriff ist nicht vorausgesetzt.']]),
    fa: body('نماهای ذخیره‌شده و جستارهای قابل‌استفادهٔ دوباره', 'میزکار دانش > نماها؛ نماهای ذخیره‌شده.', 'مخزن باز و نمایه‌شده با نحو جستار پشتیبانی‌شده.', 'نما جستار را ذخیره می‌کند، نه کپی یا پشتیبان یادداشت‌های مطابق را.', [
      ['تعیین هدف', 'با پرسشی روشن شروع کنید: یادداشت اخیر، برچسب، مسیر یا وضعیت بررسی. فیلتر پشتیبانی‌شده به کار ببرید، نه حدس آزاد.'], ['اجرا پیش از ذخیره', 'نتیجه و مسیر را ببینید. مطمئن شوید خالی بودن از خطای تجزیه یا نمایه نیست.'], ['نام و ذخیره', 'نام را بر اساس هدف بگذارید تا بعداً مفید بماند؛ نامی که محتوای ثابت القا می‌کند مناسب نیست.'], ['نگهداری جستار', 'نتیجه با تغییر یادداشت عوض می‌شود. پس از سامان‌دهی پوشه و برچسب، فیلتر قدیمی را بررسی کنید.'],
    ], [['چرا نتیجهٔ دیروز ناپدید شد؟', 'نما جستار زندهٔ نمایهٔ فعلی است، نه عکس فوری.'], ['هر SQL را می‌توانم استفاده کنم؟', 'خیر. از جستار و فیلتر پشتیبانی‌شده استفاده و خطا را بررسی کنید؛ دسترسی خام پایگاه داده را فرض نکنید.']]),
  },
  collections: {
    de: body('Intelligente Sammlungen', 'Wissenswerkbank > Sammlungen.', 'Ein indexierter Tresor und eine gültige Sammlungsabfrage.', 'Sammlungen gruppieren Treffer. Eine Definition zu löschen ist nicht dasselbe wie ihre Notizen zu löschen.', [
      ['Sinnvoll gruppieren', 'Gruppieren Sie nach Projekt, Thema oder Prüfbedingung, statt den gesamten Ordnerbaum zu duplizieren.'], ['Abfrage prüfen', 'Führen Sie unterstützte DQL/Filter aus und prüfen Sie mehrere Treffer sowie bekannte Nichttreffer.'], ['Definition speichern', 'Wählen Sie einen lesbaren Namen und prüfen Sie den Speicherort der Definition.'], ['Nach Änderungen prüfen', 'Ordnernamen, Tags und Metadaten verändern die Mitgliedschaft. Korrigieren Sie die Abfrage statt Dateien nur für alte Treffer zu verschieben.'],
    ], [['Verschiebt Mitgliedschaft Dateien?', 'Nein. Sie ergibt sich aus der Abfrage.'], ['Was unterscheidet eine Sammlung vom Ordner?', 'Ein Ordner ist ein Speicherpfad. Eine Sammlung kann mehrere Ordner umfassen und verändert sich mit der Abfrage.']]),
    fa: body('مجموعه‌های هوشمند', 'میزکار دانش > مجموعه‌ها.', 'مخزن نمایه‌شده و جستار معتبر مجموعه.', 'مجموعه نتیجه‌های جستار را گروه‌بندی می‌کند. حذف تعریف مجموعه با حذف یادداشت‌هایش فرق دارد.', [
      ['گروه‌بندی مفید', 'مجموعه را برای پروژه، موضوع یا شرط بررسی تعریف کنید، نه تکرار کل درخت پوشه.'], ['اعتبار جستار', 'DQL یا فیلتر پشتیبانی‌شده را اجرا و چند مورد مطابق و نامطابقِ شناخته‌شده را بررسی کنید.'], ['ذخیرهٔ تعریف', 'نام خوانا انتخاب کنید و محل نگهداری تعریف مجموعه را ببینید.'], ['بررسی پس از تغییر', 'تغییر نام پوشه، برچسب و فراداده عضویت را عوض می‌کند. جستار را اصلاح کنید، نه اینکه برای حفظ نتیجهٔ قدیمی یادداشت را جابه‌جا کنید.'],
    ], [['عضویت مجموعه فایل را می‌برد؟', 'خیر. عضویت از جستار مشتق می‌شود.'], ['تفاوتش با پوشه چیست؟', 'پوشه مسیر ذخیره است. مجموعه می‌تواند چند پوشه را پوشش دهد و با جستار تغییر کند.']]),
  },
  tags: {
    de: body('Tags durchsuchen und verwalten', 'Tags durchsuchen oder Wissenswerkbank > Tags.', 'Indexierte Notizen mit unterstützten Tags.', 'Durchsuchen ist schreibgeschützt; Umbenennen oder Entfernen ändert den Quelltext und benötigt Prüfung.', [
      ['Nach Bedeutung durchsuchen', 'Wählen Sie einen Tag und prüfen Sie Notizen. Ähnliche Schreibweisen oder verschachtelte Tags können unterschiedliche Begriffe sein.'], ['Quelle prüfen', 'Öffnen Sie einen Treffer und lesen Sie Tags und Frontmatter, bevor Sie einen Zählwert als falsch einstufen.'], ['Bewusst zusammenführen', 'Prüfen Sie Umbenennungs- oder Bereinigungsänderungen beim Zusammenführen von Varianten. Sichern Sie vor größeren Änderungen.'], ['Abhängige Ansichten prüfen', 'Prüfen Sie Sammlungen und gespeicherte Ansichten, die alte Tags verwendeten.'],
    ], [['Warum unterscheiden sich Zählwerte?', 'Ansichten können verschiedene Filter oder Indexgenerationen nutzen. Prüfen Sie aktuelle Quelle und Bereich.'], ['Braucht jede Notiz einen Tag?', 'Nein. Tags sollen das Wiederfinden verbessern; Ordner und Links strukturieren ebenfalls.']]),
    fa: body('مرور و مدیریت برچسب', 'مرور برچسب‌ها یا میزکار دانش > برچسب‌ها.', 'یادداشت نمایه‌شده دارای برچسب پشتیبانی‌شده.', 'مرور فقط‌خواندنی است؛ تغییر نام یا حذف برچسب منبع را تغییر می‌دهد و باید بررسی شود.', [
      ['مرور بر اساس معنا', 'برچسب را انتخاب و یادداشت مطابق را بررسی کنید. املای مشابه یا برچسب تو‌در‌تو ممکن است مفهوم متفاوتی باشد.'], ['بررسی منبع', 'نتیجه را باز و برچسب واقعی یا frontmatter را پیش از نادرست دانستن شمارش بخوانید.'], ['یکپارچه‌سازی آگاهانه', 'برای ادغام شکل‌های برچسب از تغییر نام یا پاک‌سازی قابل‌بررسی استفاده کنید. پیش از تغییر گسترده پشتیبان نگه دارید.'], ['تازه‌سازی نماهای وابسته', 'مجموعهٔ هوشمند و نمای ذخیره‌شدهٔ وابسته به برچسب قدیمی را دوباره بررسی کنید.'],
    ], [['چرا شمارش‌ها فرق دارند؟', 'نماها ممکن است فیلتر یا نسل نمایهٔ متفاوت داشته باشند. منبع فعلی و دامنه را بررسی کنید.'], ['هر یادداشت باید برچسب داشته باشد؟', 'خیر. وقتی بازیابی بهتر می‌شود برچسب بگذارید؛ پوشه و پیوند نیز ساختار می‌دهند.']]),
  },
  graph: {
    de: body('Im Wissensgraph navigieren', 'Graph öffnen über Palette oder Inspektor.', 'Ein indexierter Tresor und aktivierte Graph-Funktion.', 'Graph-Navigation ist schreibgeschützt. Das Modul zu aktivieren verändert Funktionseinstellungen, keine Notizinhalte.', [
      ['Verfügbarkeit prüfen', 'Ist Graph deaktiviert, prüfen Sie die Wiederherstellungsaktion. Ein leerer Zeichenbereich bedeutet nicht automatisch einen leeren Tresor.'], ['Bereich wählen', 'Nachbarschaft folgt der aktiven Notiz; Gesamter Tresor untersucht mehr Inhalte. Tiefe begrenzt die Traversierung und beweist keine vollständige Darstellung.'], ['Graph lesen', 'Knoten stehen für Notizen und Referenzen, Kanten für Beziehungen. Nutzen Sie Beschriftungen und Legende; Farbe allein identifiziert nichts.'], ['Navigieren oder pausieren', 'Ein Knoten öffnet seine Notiz. Ruhezustand pausiert die Arbeit; Fortsetzen weckt sie. Speichern Sie Ansichten nur mit nützlichen Einstellungen.'],
    ], [['Warum fehlen Knoten?', 'Graph-Abfragen sind begrenzt und hängen von Bereich, Tiefe, Index und Filtern ab.'], ['Beweist eine Kante einen sinnvollen Zusammenhang?', 'Sie beweist die indexierte Referenzbeziehung, nicht Wahrheit oder Stärke einer Argumentation.']]),
    fa: body('پیمایش گراف دانش', 'باز کردن گراف از فرمان‌ها یا نوار بررسی.', 'مخزن نمایه‌شده و قابلیت گراف فعال باشد.', 'پیمایش گراف فقط‌خواندنی است. فعال کردن ماژول، تنظیم قابلیت را تغییر می‌دهد نه متن یادداشت را.', [
      ['بررسی دسترسی', 'اگر گراف غیرفعال است، عمل بازیابی را بررسی کنید. صفحهٔ خالی را نشانهٔ مخزن خالی ندانید.'], ['انتخاب دامنه', 'همسایگی یادداشت فعلی را دنبال می‌کند؛ کل مخزن بخش بیشتری را می‌کاود. عمق پیمایش را محدود می‌کند و نمایش همهٔ پیوندها را اثبات نمی‌کند.'], ['خواندن گراف', 'گره یادداشت یا ارجاع و یال رابطه را نشان می‌دهد. از عنوان و راهنمای نمودار استفاده کنید؛ رنگ به‌تنهایی هویت نیست.'], ['پیمایش یا توقف', 'گره را برای باز کردن یادداشت انتخاب کنید. خواب کار گراف را متوقف و ادامه آن را بیدار می‌کند. فقط نمای دارای تنظیم مفید را ذخیره کنید.'],
    ], [['چرا بعضی گره‌ها نیستند؟', 'جستار گراف محدود است و از دامنه، عمق، نمایه و فیلتر تأثیر می‌گیرد.'], ['یال، ارتباط معنادار را ثابت می‌کند؟', 'فقط رابطهٔ ارجاع نمایه‌شده را ثابت می‌کند، نه حقیقت یا قوت استدلال را.']]),
  },
  citations: {
    de: body('Zitate und fehlende Schlüssel', 'Zitate im Inspektor und Werkzeuge zum Einfügen von Zitaten.', 'Konfigurieren Sie lokale Literaturdaten und verwenden Sie dort vorhandene Schlüssel.', 'Zitierformatierung verifiziert keine Quellen. Prüfen Sie Autoren, Daten, Fundstellen und Belege selbst.', [
      ['Literaturschlüssel finden', 'Verwenden Sie einen stabilen Schlüssel aus der konfigurierten Literaturdatei. Erfinden Sie keinen Schlüssel wegen einer plausibel aussehenden Darstellung.'], ['Im Quelltext einfügen', 'Nutzen Sie die unterstützte Zitiersyntax einschließlich Seiten- oder Abschnittsangaben, wenn die Argumentation sie benötigt.'], ['Offene Referenzen prüfen', 'Lesen Sie Warnungen zu fehlenden Schlüsseln und prüfen Sie Literaturpfade. Eine fehlende Datei ist nicht dasselbe wie ein fehlerhafter Eintrag.'], ['Endausgabe prüfen', 'Prüfen Sie Zitierstil und Literaturverzeichnis im Export, nicht nur in der Vorschau. Kontrollieren Sie die tatsächliche Quelle jedes Zitats.'],
    ], [['Synchronisiert Scriptor Zotero?', 'Der bestehende Zitatbereich nutzt lokale Literaturdaten. Ein Bibliothekspaket allein beweist keine integrierte Oberfläche für laufende Zotero-Synchronisation.'], ['Warum bleibt ein Schlüssel unaufgelöst?', 'Prüfen Sie den genauen Schlüssel, aktiven Tresor, Literaturkonfiguration und Parserwarnungen.']]),
    fa: body('ارجاع‌ها و کلیدهای پیدا‌نشده', 'ارجاع‌های نوار بررسی و ابزار درج ارجاع.', 'دادهٔ کتاب‌شناختی محلی را تنظیم و از کلید موجود در آن استفاده کنید.', 'قالب‌بندی ارجاع، اعتبارسنجی منبع نیست. نویسنده، تاریخ، محل و شواهد را خودتان بررسی کنید.', [
      ['پیدا کردن کلید منبع', 'کلید پایدار فایل منابع تنظیم‌شده را به کار ببرید. چون ارجاع ظاهراً معتبر است، کلید نسازید.'], ['درج در منبع', 'نحو پشتیبانی‌شدهٔ ارجاع را همراه صفحه یا بخش موردنیاز استدلال درج کنید.'], ['بررسی ارجاع حل‌نشده', 'هشدار کلید غایب و مسیر منابع را ببینید. نبودن فایل منابع با ورودی نادرست فرق دارد.'], ['بررسی خروجی نهایی', 'سبک ارجاع و فهرست منابع را در خروجی، نه فقط پیش‌نمایش، بررسی کنید. منبع واقعی هر ارجاع را کنترل کنید.'],
    ], [['Scriptor با Zotero همگام می‌شود؟', 'بخش فعلی ارجاع از دادهٔ محلی منابع استفاده می‌کند. وجود بستهٔ کتابخانه به‌تنهایی رابط یکپارچهٔ همگام‌سازی پیوسته با Zotero را اثبات نمی‌کند.'], ['چرا کلید حل نمی‌شود؟', 'کلید دقیق، مخزن فعال، تنظیم منابع و هشدار تجزیه‌گر را بررسی کنید.']]),
  },
  bibliography: {
    de: body('Literaturverwaltung', 'Literaturverzeichnis in der Befehlspalette oder Referenzwerkzeugen.', 'Eine lokale Literaturdatei im konfigurierten Tresorablauf.', 'Literaturmetadaten können fehlen oder fehlerhaft sein. Bewahren Sie die Originaldatei vor größeren Änderungen auf.', [
      ['Konfiguration prüfen', 'Prüfen Sie, welche Literaturdatei gelesen wird und ob sie zum aktiven Tresor gehört.'], ['Einträge prüfen', 'Vergleichen Sie Schlüssel mit Titeln und Autoren. Finden Sie doppelte oder fehlende Schlüssel; unterscheiden Sie Bibliotheken anhand der Quellpfade.'], ['Quelle korrigieren', 'Beheben Sie fehlerhafte Datensätze und Felder in der Literaturdatei, nicht nur im gerenderten Text.'], ['Zitate erneut prüfen', 'Aktualisieren oder indexieren Sie bei Bedarf und kontrollieren Sie Vorschau und Export-Vorabprüfung auf offene Referenzen.'],
    ], [['Kann ein fehlerhafter Eintrag alles blockieren?', 'Parserfehler und einzelne Konvertierungsprobleme können unterschiedlich wirken. Lesen Sie Warnungen; nicht alle Datensätze müssen geladen sein.'], ['Beweist ein Eintrag, dass die Referenz stimmt?', 'Nein. Prüfen Sie Genauigkeit und Relevanz der Quelle unabhängig.']]),
    fa: body('مدیریت فهرست منابع', 'فهرست منابع از فرمان‌ها یا کنترل منابع.', 'فایل منابع محلی در روند تنظیم‌شدهٔ مخزن.', 'فرادادهٔ منابع ممکن است ناقص یا نادرست باشد. پیش از تغییر گسترده فایل اصلی را نگه دارید.', [
      ['بررسی تنظیم', 'تأیید کنید کدام فایل منابع خوانده می‌شود و متعلق به مخزن فعال است.'], ['بررسی ورودی', 'کلید را با عنوان و نویسنده تطبیق دهید و کلید تکراری یا غایب را پیدا کنید. کتابخانه‌ها را با مسیر منبع تشخیص دهید.'], ['اصلاح در مبدأ', 'رکورد یا فیلد نادرست را در فایل منابع اصلاح کنید، نه فقط متن رندرشده.'], ['بررسی دوبارهٔ ارجاع', 'در صورت نیاز تازه‌سازی یا نمایه‌سازی کنید؛ سپس پیش‌نمایش و پیش‌بررسی خروجی را برای ارجاع حل‌نشده ببینید.'],
    ], [['یک ورودی خراب همه چیز را می‌شکند؟', 'خطای تجزیه و تبدیل یک ورودی می‌تواند اثر متفاوت داشته باشد. هشدار را بخوانید و فرض نکنید همهٔ رکوردها بارگذاری شده‌اند.'], ['وجود ورودی درستی منبع را ثابت می‌کند؟', 'خیر. دقت و ارتباط منبع را مستقل بررسی کنید.']]),
  },
  workbench: {
    de: body('Wissenswerkbank', 'Wissenswerkbank öffnen in der Befehlspalette.', 'Ein indexierter Tresor; leere Warteschlangen können korrekt sein.', 'Die Werkbank kombiniert Navigation und Reparaturplanung. Links und Reparaturen ändern Notizen nur über ausdrückliche Abläufe.', [
      ['Aufgabe wählen', 'Reparatur bearbeitet Wissenslisten; Ansichten und Sammlungen verwenden Abfragen erneut; Tags unterstützen Entdeckung; Entdecken öffnet Graph-Erkundung.'], ['Treffer prüfen', 'Lesen Sie Titel und Pfad zusammen sowie eingehende und ausgehende Zählwerte im Kontext. Eine Zahl ist kein automatischer Änderungsauftrag.'], ['Einträge beurteilen', 'Öffnen Sie eine Notiz, prüfen Sie ihre Bedeutung und gehen Sie zur nächsten. Behalten Sie den Kontext, statt alles blind zu verknüpfen.'], ['Änderung überprüfen', 'Warten Sie nach Bearbeitung auf die Indexierung. Führen Sie die Abfrage erneut aus und prüfen Sie, ob das Problem wirklich behoben wurde.'],
    ], [['Warum ist die Liste leer?', 'Es kann wirklich keine Treffer geben. Prüfen Sie zuerst Laden, Fehler und Filter.'], ['Sind verwaiste Notizen Fehler?', 'Nicht immer. Persönliche Aufzeichnungen und bewusst isolierte Notizen können sinnvoll sein.']]),
    fa: body('میزکار دانش', 'باز کردن میزکار دانش در فرمان‌ها.', 'مخزن نمایه‌شده؛ برخی صف‌ها به‌درستی خالی‌اند.', 'میزکار پیمایش و برنامه‌ریزی اصلاح را ترکیب می‌کند. افزودن پیوند و اعمال اصلاح فقط از روند صریح یادداشت را تغییر می‌دهد.', [
      ['انتخاب کار', 'اصلاح صف‌های دانش را بررسی می‌کند؛ نما و مجموعه جستار را دوباره به کار می‌برند؛ برچسب به کشف کمک می‌کند؛ کشف به گراف می‌رود.'], ['بررسی نتیجه', 'عنوان و مسیر را با هم بخوانید و شمارش ورودی و خروجی را در زمینه بسنجید. عدد دستور خودکار تغییر نیست.'], ['ارزیابی نوبتی', 'یادداشت صف را باز کنید، معنایش را بررسی و به بعدی بروید. زمینهٔ میزکار را نگه دارید و همه چیز را کورکورانه پیوند ندهید.'], ['تأیید تغییر', 'پس از ویرایش منتظر تازه‌سازی نمایه بمانید. صف را دوباره اجرا کنید تا رفع واقعی مسئله مشخص شود.'],
    ], [['چرا صف خالی است؟', 'ممکن است واقعاً مورد مطابقی نباشد. ابتدا بارگذاری، خطا و فیلتر را بررسی کنید.'], ['یادداشت یتیم نقص است؟', 'همیشه نه. گزارش شخصی یا یادداشت عمداً جدا می‌تواند درست باشد.']]),
  },
  'knowledge-repair': {
    de: body('Reparaturlisten und Einordnung', 'Wissenswerkbank > Reparatur.', 'Ein aktueller Index und der richtige Filter.', 'Reparaturvorschläge benötigen Urteil. Löschen Sie keine Inhalte und erfinden Sie keine Links nur für bessere Kennzahlen.', [
      ['Liste wählen', 'Verwaiste Notizen, Sackgassen und offene Referenzen beschreiben verschiedene Beziehungen. Lesen Sie die Bezeichnung vor einer Aktion.'], ['Notiz prüfen', 'Prüfen Sie Pfad, Inhalt und Bezug zur übrigen Arbeit. Ein fehlender Link braucht sinnvollen Kontext.'], ['Linkvorschlag prüfen', 'Wählen Sie das richtige Ziel und prüfen Sie Einfüge- oder Änderungsbereich. Bestätigen Sie nur gewünschte Änderungen.'], ['Fortsetzen und neu beurteilen', 'Navigieren Sie durch die Einträge und aktualisieren Sie nach Änderungen. Andere Filter können die Reihenfolge verändern.'],
    ], [['Warum änderte sich die Anzahl?', 'Neue Indexierung, Filter und Quellenänderungen verändern Treffer. Eine alte Zeilennummer ist keine dauerhafte Notiz-ID.'], ['Was tun mit einer offenen Referenz?', 'Korrigieren Sie Zielpfad oder Titel, erstellen Sie ein sinnvolles Ziel oder entfernen Sie eine irrtümliche Referenz.']]),
    fa: body('صف اصلاح و بررسی نوبتی', 'میزکار دانش > اصلاح.', 'نمایهٔ تازه و فیلتر درست.', 'پیشنهاد اصلاح به قضاوت نیاز دارد. برای بهتر شدن شمارش، متن را حذف یا پیوند ساختگی ایجاد نکنید.', [
      ['انتخاب صف', 'یادداشت یتیم، بن‌بست و ارجاع حل‌نشده رابطه‌های متفاوتی‌اند. پیش از عمل عنوان صف را بخوانید.'], ['بررسی یادداشت', 'مسیر، محتوا و ارتباط با کار پیرامون را ببینید. پیوند مفید زمینهٔ معنادار می‌خواهد.'], ['بررسی پیوند پیشنهادی', 'مقصد درست را انتخاب و دامنهٔ درج یا بازنویسی را بررسی کنید. فقط تغییر موردنظر را تأیید کنید.'], ['ادامه و ارزیابی دوباره', 'در صف پیمایش و پس از ویرایش تازه‌سازی کنید. تغییر فیلتر می‌تواند ترتیب موجود را عوض کند.'],
    ], [['چرا تعداد صف تغییر کرد؟', 'نمایه‌سازی تازه، تغییر فیلتر یا منبع نتیجه را عوض می‌کند. شمارهٔ قبلی ردیف هویت پایدار یادداشت نیست.'], ['با ارجاع حل‌نشده چه کنم؟', 'مسیر یا عنوان مقصد را اصلاح کنید، مقصد معنادار بسازید یا ارجاع اشتباه را بردارید.']]),
  },
  inspector: {
    de: body('Inspektor und kontextbezogene Widgets', 'Rechte Leiste; Inspektor / Gerenderte Ausgabe / Plugins.', 'Manche Widgets benötigen eine aktive Notiz oder einen indexierten Tresor.', 'Jedes Widget beschreibt nur seinen Bereich. Ein gesunder Index beweist weder gespeicherte Inhalte noch richtige Zitate oder eine Sicherung.', [
      ['Aufgabe wählen', 'Inspektor zeigt Kontext, Gerenderte Ausgabe liest die Notiz, Plugins verwaltet Erweiterungen. Ein Tabwechsel schreibt das Dokument nicht um.'], ['Profil wählen', 'Wählen Sie ein Layout für Recherche, Veröffentlichung oder Aufräumen. Ausgeblendete Widgets bleiben über andere Profile verfügbar.'], ['Details prüfen', 'Öffnen Sie Gliederung, Rückverweis, Zitat oder Zustandsbefund statt nur die Anzahl zu lesen.'], ['Schreibfläche zurückgewinnen', 'Klappen Sie die Leiste ein oder ändern Sie ihre Größe. Ein angedockter Begleitbereich kann sie vorübergehend ersetzen; Schließen stellt das Schreiblayout wieder her.'],
    ], [['Warum ist der Inspektor leer?', 'Prüfen Sie aktive Notiz, Tab/Profil, Ladezustand und Funktionsverfügbarkeit.'], ['Aktualisieren alle Widgets sofort?', 'Einige warten auf Indexierung oder asynchrones Lesen. Warten oder Fehler ist keine bestätigte Null.']]),
    fa: body('نوار بررسی و ابزارک‌های وابسته به زمینه', 'نوار کناری بررسی؛ بررسی / خروجی رندرشده / افزونه‌ها.', 'بعضی ابزارک‌ها یادداشت فعال یا مخزن نمایه‌شده می‌خواهند.', 'ابزارک فقط دامنهٔ خودش را گزارش می‌کند. سلامت نمایه، ذخیرهٔ متن، درستی ارجاع یا وجود پشتیبان را اثبات نمی‌کند.', [
      ['انتخاب کار', 'بررسی اطلاعات زمینه را نشان می‌دهد؛ خروجی رندرشده یادداشت را نمایش می‌دهد؛ افزونه‌ها توسعه‌ها را مدیریت می‌کند. تغییر زبانه سند را بازنویسی نمی‌کند.'], ['انتخاب چیدمان', 'چیدمانی مناسب پژوهش، انتشار یا پاک‌سازی انتخاب کنید. ابزارک پنهان با تغییر چیدمان دوباره در دسترس است.'], ['بررسی جزئیات', 'ساختار، پیوند ورودی، ارجاع یا نتیجهٔ سلامت را باز کنید و فقط به شمارش تکیه نکنید.'], ['بازگرداندن فضای نوشتن', 'نوار را جمع کنید یا اندازه‌اش را عوض کنید. پنل همراه ممکن است موقتاً جای آن را بگیرد؛ بستن پنل چیدمان نوشتن را برمی‌گرداند.'],
    ], [['چرا نوار بررسی خالی است؟', 'یادداشت فعال، زبانه و چیدمان، وضعیت بارگذاری و دسترسی قابلیت را بررسی کنید.'], ['همهٔ ابزارک‌ها فوری به‌روز می‌شوند؟', 'برخی به نمایه‌سازی یا خواندن غیرهمزمان وابسته‌اند. حالت انتظار یا خطا، صفر تأییدشده نیست.']]),
  },
  outline: {
    de: body('Dokumentgliederung', 'Inspektor > Gliederung.', 'Eine aktive Notiz mit Markdown-Überschriften.', 'Gliederungsnavigation ist schreibgeschützt; Überschriften bearbeiten oder Abschnitte verschieben verändert Markdown.', [
      ['Hierarchie lesen', 'Überschriftenebenen beschreiben die Struktur. Ein fett gedruckter titelähnlicher Satz ist nicht zwangsläufig eine Überschrift.'], ['Abschnitt aufrufen', 'Wählen Sie eine Überschrift, um sie in der Notiz zu finden. Prüfen Sie das Ziel vor Strukturänderungen.'], ['Struktur verbessern', 'Verwenden Sie sinnvolle Ebenen und eindeutige Abschnittsnamen. Überspringen Sie keine Ebenen nur für eine andere Schriftgröße.'], ['Fehlende Überschriften prüfen', 'Prüfen Sie Quellsyntax und Index-/Vorschauzustand. Ein # in einem Codebeispiel ist keine Dokumentüberschrift.'],
    ], [['Warum fehlt mein Titel?', 'Er ist möglicherweise keine Markdown-Überschrift oder Notiz/Index wurden noch nicht aktualisiert.'], ['Verschiebt ein Gliederungseintrag den Text?', 'Navigation tut das nicht. Nutzen Sie ausdrücklich Abschnitt verschieben zum Umschreiben.']]),
    fa: body('ساختار سند', 'بررسی > ساختار.', 'یادداشت فعال دارای عنوان‌های Markdown باشد.', 'پیمایش ساختار فقط‌خواندنی است؛ ویرایش عنوان و جابه‌جایی بخش، Markdown را تغییر می‌دهد.', [
      ['خواندن سلسله‌مراتب', 'سطح عنوان ساختار سند را بیان می‌کند. جملهٔ درشت شبیه عنوان لزوماً عنوان نیست.'], ['رفتن به بخش', 'عنوان را انتخاب کنید تا در یادداشت پیدا شود. پیش از فرمان ساختاری مقصد را بررسی کنید.'], ['اصلاح ساختار', 'سطح معنادار و نام بخش یکتا به کار ببرید. صرفاً برای اندازهٔ دیداری، سطح عنوان را نپرید.'], ['عنوان غایب', 'نحو منبع و آمادگی نمایه یا پیش‌نمایش را بررسی کنید. # داخل نمونهٔ کد نباید ساختار متن شمرده شود.'],
    ], [['چرا عنوانم فهرست نشده؟', 'ممکن است عنوان Markdown نباشد یا یادداشت و نمایه هنوز تازه نشده باشند.'], ['جابه‌جایی در ساختار متن را می‌برد؟', 'پیمایش چنین کاری نمی‌کند. برای بازنویسی سند از فرمان صریح جابه‌جایی بخش استفاده کنید.']]),
  },
  backlinks: {
    de: body('Rückverweise und eingehende Referenzen', 'Inspektor > Rückverweise.', 'Öffnen und indexieren Sie den betreffenden Tresor.', 'Rückverweise entstehen aus Quelllinks. Entfernen Sie einen Treffer durch Bearbeitung der Ursprungsnotiz, nicht durch Löschen einer Indexzeile.', [
      ['Richtung erkennen', 'Rückverweise sind andere Notizen, die auf die aktive Notiz zeigen. Ausgehende Links stehen dagegen in dieser Notiz.'], ['Ursprung lesen', 'Öffnen Sie den Quellpfad und lesen Sie den umgebenden Satz vor einer Änderung.'], ['Mehrdeutigkeit klären', 'Ähnliche Titel können verschiedene Pfade bezeichnen. Beachten Sie die Linkauflösungsregeln des Tresors.'], ['Verantwortlich aktualisieren', 'Warten Sie nach Änderungen auf die Indexierung. Unterscheiden Sie Lesefehler und veralteten Index von tatsächlich fehlenden Referenzen.'],
    ], [['Ist eine Notiz ohne Rückverweise falsch?', 'Nein. Isolation kann beabsichtigt sein. Reparaturen sollen Ihrer Wissensstruktur dienen, nicht Zahlen maximieren.'], ['Warum änderte Umbenennen einen Rückverweis?', 'Links hängen von Pfaden, Titeln und Auflösung ab. Nutzen Sie den geprüften Umbenennungs- und Linkänderungsablauf für größere Änderungen.']]),
    fa: body('پیوندهای ورودی و ارجاع‌های برگشتی', 'بررسی > پیوندهای ورودی.', 'مخزن مربوط باز و نمایه‌شده باشد.', 'پیوند ورودی از پیوند منبع مشتق می‌شود. برای حذف نتیجه، یادداشت مبدأ را ویرایش کنید، نه ردیف نمایه را.', [
      ['تشخیص جهت', 'پیوند ورودی از یادداشت دیگری به یادداشت فعال می‌آید. پیوند خروجی در خود این یادداشت نوشته شده است.'], ['خواندن مبدأ', 'مسیر منبع را باز و جملهٔ اطراف را پیش از تغییر ارجاع بخوانید.'], ['رفع ابهام', 'عنوان مشابه ممکن است مسیر متفاوت داشته باشد. قواعد حل پیوند مخزن را به کار ببرید و فرض نکنید هر عنوان فقط یک فایل است.'], ['تازه‌سازی مسئولانه', 'بعد از ویرایش منتظر نمایه‌سازی بمانید. خطای خواندن و نمایهٔ قدیمی را از نبودن واقعی ارجاع جدا کنید.'],
    ], [['یادداشت بدون پیوند ورودی اشتباه است؟', 'خیر. جدا بودن ممکن است عمدی باشد. اصلاح باید به ساختار دانش کمک کند، نه شمارش را زیاد کند.'], ['چرا تغییر نام روی پیوند ورودی اثر گذاشت؟', 'پیوند به مسیر، عنوان و قواعد حل وابسته است. برای تغییر گسترده از روند بررسی‌شدهٔ تغییر نام و بازنویسی پیوند استفاده کنید.']]),
  },
  outgoing: {
    de: body('Ausgehende Links und unaufgelöste Ziele', 'Inspektor > Ausgehende Links.', 'Eine aktive Notiz mit Markdown-Links oder Wikilinks.', 'Ein externer Link kann die App verlassen. Ein fehlendes Ziel zu erstellen schreibt eine Datei und benötigt Ihre ausdrückliche Aktion.', [
      ['Ziel prüfen', 'Unterscheiden Sie Tresornotiz, Anhang, Überschriftenfragment und externe URL. Lesen Sie vor der Navigation den Zielpfad.'], ['Defekten Link klären', 'Prüfen Sie Schreibweise, Ordner, Endung und mögliche Verschiebung. Ein fehlender Treffer kann auch am Index liegen.'], ['Bewusst erstellen', 'Erstellen Sie fehlende Notizen nur für sinnvolle Inhalte. Erzeugen Sie keine leeren Dateien nur zum Verbergen von Warnungen.'], ['Reparatur verifizieren', 'Öffnen Sie die Referenz erneut und prüfen Sie den Quelltext. Massenänderungen benötigen Vorschau und Bestätigung.'],
    ], [['Warum verlangt ein Link eine Bestätigung?', 'Externe oder tresorübergreifende Navigation überschreitet eine eigene Vertrauensgrenze. Prüfen Sie das Ziel.'], ['Sind Rückverweise dieselbe Liste?', 'Nein. Ausgehende Links beginnen in dieser Notiz, Rückverweise in anderen.']]),
    fa: body('پیوندهای خروجی و مقصدهای حل‌نشده', 'بررسی > پیوندهای خروجی.', 'یادداشت فعال با پیوند Markdown یا ویکی‌پیوند.', 'باز کردن پیوند بیرونی ممکن است از برنامه خارج شود. ساخت یادداشت گمشده فایل می‌نویسد و عمل صریح شما را می‌خواهد.', [
      ['بررسی مقصد', 'یادداشت مخزن، پیوست، بخش عنوان و نشانی بیرونی را تشخیص دهید. پیش از رفتن، مسیر مقصد را بخوانید.'], ['حل پیوند شکسته', 'املاء، پوشه، پسوند و جابه‌جایی مقصد را بررسی کنید. نتیجهٔ غایب ممکن است مشکل نمایه هم باشد.'], ['ایجاد آگاهانه', 'یادداشت غایب را فقط برای محتوای مفید بسازید؛ برای خاموش کردن هشدار ده‌ها فایل خالی نسازید.'], ['بررسی پس از اصلاح', 'ارجاع را دوباره باز و منبع تازه را بررسی کنید. بازنویسی گروهی باید پیش‌نمایش و تأیید داشته باشد.'],
    ], [['چرا پیوند تأیید می‌خواهد؟', 'پیمایش بیرونی یا بین مخزن‌ها مرز اعتماد جدا دارد. مقصد را بررسی کنید.'], ['پیوند ورودی همین فهرست است؟', 'خیر. خروجی از این یادداشت شروع می‌شود؛ ورودی از یادداشت دیگر.']]),
  },
}
