import { body, type GuideTranslations } from './translationTypes.ts'

export const navigationTranslations: GuideTranslations = {
  'knowledge-discover': {
    de: body('Wissensentdeckung', 'Wissenswerkbank > Entdecken.', 'Öffnen Sie einen Tresor. Eine aktive Notiz gibt dem Graph einen Ausgangspunkt.', 'Entdecken öffnet Wissenswerkzeuge zur Navigation. Es repariert keine Links und verändert selbst keine Notizen.', [
      ['Untersuchungsweg wählen', 'Öffnen Sie Graph für Beziehungen, Reparatur für ungelöste Struktur, Sammlungen für abgeleitete Gruppen oder Tags für Taxonomie.'], ['Aktive Notiz als Kontext nutzen', 'Graph kann von der aktiven Notiz ausgehen. Prüfen Sie den Pfad vor Interpretation der Beziehungen.'], ['Zuständiges Werkzeug öffnen', 'Filter, Änderungen, Rechte und Diagnose gehören zum Zielpanel. Entdecken dupliziert diese Funktionen nicht.'], ['Mit gleichem Umfang zurückkehren', 'Öffnen Sie Entdecken erneut für eine andere Untersuchung. Schließen der Werkbank verändert den Tresor nicht.'],
    ], [['Warum ist hier kein Graph?', 'Entdecken ist der Einstieg. Der vollständige Graph übernimmt Darstellung, Filter, Navigation und Fehlerbehebung.'], ['Repariert Öffnen von Reparatur automatisch?', 'Nein. Die Warteschlange erfordert Prüfung und Quelländerungen benötigen ausdrückliche Aktionen.']]),
    fa: body('مرکز کشف دانش', 'میزکار دانش > کشف.', 'مخزن باز کنید؛ یادداشت فعال به گراف هدف تمرکز می‌دهد.', 'کشف مرکز پیمایش است. دکمه‌ها ابزار دانش را باز می‌کنند و خودشان پیوند را اصلاح یا یادداشت را تغییر نمی‌دهند.', [
      ['مسیر بررسی را انتخاب کنید', 'گراف برای روابط، ترمیم برای ساختار حل‌نشده، مجموعه برای گروه مشتق‌شده و برچسب برای رده‌بندی است.'], ['از یادداشت فعال زمینه بگیرید', 'گراف می‌تواند از سند فعال شروع شود. پیش از تفسیر روابط مسیر را تأیید کنید.'], ['به ابزار مسئول بروید', 'فیلتر، تغییر، مجوز و عیب‌یابی دقیق در پنل مقصد است؛ کشف قابلیت را تکرار نمی‌کند.'], ['با حفظ دامنه برگردید', 'برای عوض کردن نوع بررسی دوباره کشف را باز کنید. بستن میزکار مخزن را تغییر نمی‌دهد.'],
    ], [['چرا اینجا گراف نیست؟', 'کشف محل ورود است؛ گراف کامل مسئول رندر، فیلتر، پیمایش و بازیابی خودش است.'], ['باز کردن ترمیم چیزی را خودکار اصلاح می‌کند؟', 'خیر. صف ترمیم نیازمند بازبینی است و تغییر منبع عمل صریح می‌خواهد.']]),
  },
  'gmail-messages': {
    de: body('Gmail-Nachrichten suchen und lesen', 'Gmail-Verwaltung > Nachrichten.', 'Aktivierte Gmail-Funktion, angemeldetes Konto, native Desktop-App und Netzwerk.', 'Suche und Lesen sind begrenzter Anbieterzugriff. Archivieren, Papierkorb und Import sind getrennte Änderungen mit bewusster Auswahl.', [
      ['Gezielt suchen', 'Nutzen Sie Gmail-Suchsyntax oder den Posteingang. Begrenzte Ergebnisse sind kein vollständiger Mailboxexport.'], ['Richtige Nachricht öffnen', 'Prüfen Sie Absender, Datum, Betreff und Ausschnitt vor Laden oder Bearbeiten.'], ['Lokale und externe Aktionen trennen', 'Import schreibt eine Markdown-Kopie in den Tresor. Archiv und Papierkorb ändern Gmail.'], ['Nach Änderung aktualisieren', 'Prüfen Sie Anbieterzustand nach Archivieren oder Papierkorb und die lokale Notiz nach Import. Die Zeile allein belegt keinen Erfolg.'],
    ], [['Warum fehlen Nachrichten?', 'Die Abfragen sind absichtlich begrenzt. Verfeinern Sie die Suche; die Liste ist nicht das ganze Postfach.'], ['Synchronisiert Import weiter mit Gmail?', 'Nein. Er erstellt eine lokale Markdown-Kopie ohne laufende beidseitige Spiegelung.']]),
    fa: body('جست‌وجو و خواندن نامهٔ Gmail', 'مدیر Gmail > پیام‌ها.', 'قابلیت Gmail فعال، حساب واردشده، دسکتاپ بومی و شبکه.', 'خواندن و جست‌وجو دسترسی محدود ارائه‌دهنده است. بایگانی، زباله و ورود عملیات تغییردهندهٔ جدا با انتخاب آگاهانه‌اند.', [
      ['هدفمند جست‌وجو کنید', 'نحو جست‌وجوی Gmail یا محدودهٔ پیش‌فرض صندوق را به کار ببرید. فهرست محدود خروجی کامل صندوق نیست.'], ['پیام درست را باز کنید', 'پیش از بارگذاری محتوا یا عمل روی پیام، فرستنده، تاریخ، موضوع و خلاصه را ببینید.'], ['عمل محلی و بیرونی را جدا کنید', 'ورود، کپی Markdown در مخزن می‌نویسد؛ بایگانی و زباله Gmail را تغییر می‌دهند.'], ['پس از تغییر تازه کنید', 'وضعیت ارائه‌دهنده بعد از بایگانی یا زباله و یادداشت محلی بعد از ورود را ببینید؛ ردیف نمایان به‌تنهایی موفقیت نیست.'],
    ], [['چرا همهٔ پیام‌ها دیده نمی‌شوند؟', 'مدیر عمداً پرس‌وجوی محدود دارد. جست‌وجوی Gmail را دقیق‌تر کنید؛ فهرست فعلی تمام صندوق نیست.'], ['ورود با Gmail همگام می‌ماند؟', 'خیر. کپی محلی Markdown می‌سازد و آینهٔ زندهٔ دوسویه نیست.']]),
  },
  'gmail-compose': {
    de: body('Gmail verfassen und senden', 'Gmail-Verwaltung > Verfassen.', 'Verbundenes Konto und geprüfte Empfänger, Betreff und Nachricht.', 'Senden überträgt externe Mail. Prüfen Sie Adresse und Inhalt; Hilfe sendet nicht und erteilt keine Berechtigung.', [
      ['Konto bestätigen', 'Prüfen Sie die Google-Identität vor dem Entwurf, damit das richtige Konto sendet.'], ['Empfänger lesen', 'Prüfen Sie die gesamte Adresse, besonders nach Einfügen oder bei ähnlichen Kontakten.'], ['Betreff und Inhalt prüfen', 'Der experimentelle Editor ist begrenzt und auf Klartext ausgelegt. Prüfen Sie Formatierung und erwartete Anhänge.'], ['Einmal senden und prüfen', 'Warten Sie vor Wiederholung auf das Ergebnis. Zeitüberschreitung oder Fehler beweisen nicht, dass der Anbieter nichts angenommen hat.'],
    ], [['Kann ich Dateien anhängen?', 'Der experimentelle Editor ist kein vollständiger Gmail-Client. Nutzen Sie die tatsächlich angebotenen Felder.'], ['Soll ich nach Zeitüberschreitung sofort wieder senden?', 'Prüfen Sie zuerst Rückmeldung und Anbieterergebnis, um doppelte Mail zu vermeiden.']]),
    fa: body('نوشتن و ارسال نامه در Gmail', 'مدیر Gmail > نوشتن.', 'حساب متصل و گیرنده، موضوع و بدنهٔ بررسی‌شده.', 'ارسال نامهٔ بیرونی می‌فرستد. گیرنده و محتوا را ببینید؛ راهنما ارسال را نمی‌زند و اختیار نمی‌دهد.', [
      ['حساب را تأیید کنید', 'پیش از پیش‌نویس هویت Google متصل را ببینید تا نامه از حساب درست برود.'], ['گیرنده را بررسی کنید', 'نشانی کامل را مخصوصاً پس از چسباندن یا در مخاطبان مشابه ببینید.'], ['موضوع و متن را بخوانید', 'ویرایشگر فعلی محدود و متن‌ساده‌محور است؛ قالب و انتظار پیوست مفقود را پیش از ارسال بررسی کنید.'], ['یک بار ارسال و تأیید کنید', 'پیش از تلاش دوباره منتظر نتیجه بمانید. وقفه یا خطای ارائه‌دهنده ثابت نمی‌کند نامه پذیرفته نشده است.'],
    ], [['می‌توانم فایل پیوست کنم؟', 'نویسندهٔ آزمایشی فعلی جای کارخواه کامل Gmail نیست؛ فقط فیلدهای پشتیبانی‌شدهٔ موجود را به کار ببرید.'], ['پس از وقفه فوراً تکرار کنم؟', 'ابتدا وضعیت برگشتی و تا حد ممکن نتیجهٔ ارائه‌دهنده را ببینید تا ارسال تکراری نشود.']]),
  },
  'gmail-account': {
    de: body('Gmail-Konto verbinden', 'Gmail-Verwaltung > Konto.', 'Aktivierte Gmail-Funktion, Desktop-App, Netzwerk und gültige Google-OAuth-Client-ID für Desktop-Apps.', 'Verbinden öffnet Google-Zustimmung und speichert Token im Betriebssystem-Schlüsselbund. Trennen entfernt keine importierten Markdown-Notizen.', [
      ['Funktionsfreigabe prüfen', 'Führt Gmail zu Plugins, prüfen und aktivieren Sie zuerst die Gmail-Funktion vor OAuth-Diagnose.'], ['Richtige Client-ID nutzen', 'Verwenden Sie die konfigurierte Desktop-App-ID. Web-App-Zugangsdaten benötigen einen anderen Weiterleitungsablauf.'], ['Gewünschtes Konto erlauben', 'Lesen Sie Konto und Rechte im Google-Dialog. Kehren Sie danach zur Verbindungsanzeige in Scriptor zurück.'], ['Trennen und prüfen', 'Nutzen Sie Trennen bei Bedarf. Behandeln Sie Fehler bei Bereinigung oder Schlüsselbund als ungelöst.'],
    ], [['Warum scheitert Verbindung vor Öffnen von Google?', 'Funktionsfreigabe oder native Autorisierung können zuerst scheitern. Lesen Sie die genaue lokale Meldung.'], ['Löscht Trennen importierte Mailnotizen?', 'Nein. Importiertes Markdown ist lokaler Tresorinhalt mit eigenem Lebenszyklus.']]),
    fa: body('اتصال حساب Gmail', 'مدیر Gmail > حساب.', 'قابلیت Gmail فعال، دسکتاپ، شبکه و شناسهٔ معتبر OAuth برنامهٔ دسکتاپ Google.', 'اتصال رضایت Google را باز و توکن را در کلیددان سیستم ذخیره می‌کند. قطع اتصال یادداشت Markdown واردشده را حذف نمی‌کند.', [
      ['قابلیت را اول ببینید', 'اگر Gmail به افزونه‌ها می‌رود، پیش از عیب‌یابی OAuth قابلیت Gmail را بررسی و فعال کنید.'], ['شناسهٔ درست بدهید', 'شناسهٔ OAuth تنظیم‌شدهٔ برنامهٔ دسکتاپ استفاده کنید. شناسهٔ برنامهٔ وب مسیر بازگشت مرورگر متفاوت دارد.'], ['حساب مورد نظر را تأیید کنید', 'رضایت و دامنهٔ Google را پیش از پایان مرورگر بخوانید و برای وضعیت اتصال به Scriptor برگردید.'], ['قطع و تأیید کنید', 'در صورت نیاز قطع اتصال بزنید؛ خطای پاک‌سازی یا کلیددان را رفع‌نشده بدانید و حذف اطلاعات ورود را فرض نکنید.'],
    ], [['چرا پیش از باز شدن Google اتصال شکست می‌خورد؟', 'قابلیت یا مجوز بومی ممکن است پیش از رضایت مرورگر رد شود. ابتدا خطای محلی دقیق را بخوانید.'], ['قطع اتصال یادداشت نامه را حذف می‌کند؟', 'خیر. Markdown واردشده محتوای محلی مخزن با چرخهٔ مستقل است.']]),
  },
  'vault-config': {
    de: body('Arbeitsabläufe des Tresors konfigurieren', 'Einstellungen > Allgemein > Tresorkonfiguration.', 'Öffnen Sie den Tresor, dessen Standardwerte und Regeln Sie ändern möchten.', 'Einstellungen können Notizziele, automatischen Export, Graphgruppen und Zusammenarbeit verändern. Prüfen Sie Vorschau und speichern Sie bewusst.', [
      ['Tresorumfang bestätigen', 'Prüfen Sie den aktiven Tresor vor Änderung von Ordnern, Vorlagen, Posteingang, Schreibzielen, Graphgruppen und Suchwurzeln.'], ['Pfadoptionen vorab ansehen', 'Prüfen Sie Tagesnotizvorschau sowie Vorlagen-, Notiztyp-, Bibliografie- und Verlaufspfade, damit relative Ziele stimmen.'], ['Subsysteme unterscheiden', 'Posteingang, Export beim Speichern, Graphgruppen, Canvas-Zusammenarbeit und zusätzliche Suchwurzeln haben getrennte Zuständigkeiten. Ändern Sie nur die benötigte.'], ['Speichern und praktisch prüfen', 'Speichern Sie die Konfiguration und testen Sie die geänderte Funktion. Ein gespeichertes Formular beweist keinen funktionierenden Ablauf.'],
    ], [['Sind das globale App-Präferenzen?', 'Überwiegend betreffen sie den aktiven Tresor. Darstellung, Tastenkürzel und weitere App-Präferenzen werden getrennt verwaltet.'], ['Löscht ein falscher Pfad bestehende Notizen?', 'Normale Konfiguration ist keine Löschung, kann aber künftige Dateien oder Ausgaben umleiten. Sichern und prüfen Sie Ziele vor Automatisierung.']]),
    fa: body('پیکربندی گردش کار مخزن', 'تنظیمات > عمومی > پیکربندی مخزن.', 'مخزنی را باز کنید که پیش‌فرض و قواعدش را می‌خواهید تغییر دهید.', 'این تنظیم محل یادداشت جدید، خروجی خودکار، گروه گراف و فرادادهٔ همکاری را تغییر می‌دهد. پیش‌نمایش را ببینید و آگاهانه ذخیره کنید.', [
      ['دامنهٔ مخزن را تأیید کنید', 'پیش از تغییر پوشه، الگو، صندوق، هدف نوشتن، گروه گراف یا ریشهٔ پیمایش مخزن فعال را ببینید؛ تنظیم مخصوص همان مخزن است.'], ['تنظیم مسیر را پیش‌نمایش کنید', 'پیش‌نمایش روزانه و مسیر الگو، نوع یادداشت، کتاب‌نامه و تاریخچه را ببینید تا مسیر نسبی به مقصد درست برسد.'], ['گردش کار و اثر بیرونی را جدا کنید', 'صندوق، خروجی هنگام ذخیره، گروه گراف، همکاری بوم و ریشهٔ اضافی زیرسامانه‌های متفاوت دارند؛ فقط مسئول کار فعلی را تغییر دهید.'], ['ذخیره و آزمایش کنید', 'پیکربندی را نگه دارید و همان قابلیت را اجرا کنید. فرم ذخیره‌شده کار کردن الگو، خروجی، پیمایش یا همکاری را ثابت نمی‌کند.'],
    ], [['این ترجیح کل برنامه است؟', 'خیر. این بخش عمدتاً مخزن فعال را تنظیم می‌کند؛ ظاهر، میان‌بر و ترجیح برنامه مسئول جدا دارند.'], ['مسیر بد یادداشت موجود را حذف می‌کند؟', 'تنظیم معمول حذف نیست، اما می‌تواند فایل آینده یا خروجی مشتق‌شده را هدایت کند. پشتیبان و مقصد را پیش از اتکا به خودکارسازی بررسی کنید.']]),
  },
  'rename-block': {
    de: body('Blockanker umbenennen', 'Blockanker-Dialog im Verweis- oder Refactoringablauf.', 'Ein vorhandener Blockanker und seine Notiz.', 'Anwenden kann Anker und Verweise in mehreren Notizen ändern. Prüfen Sie die Vorschau bei häufig verwendeten Ankern.', [
      ['Notiz und Anker bestätigen', 'Lesen Sie Pfad und bestehende Block-ID, damit ähnliche Anker anderer Notizen nicht verwechselt werden.'], ['Stabilen Namen wählen', 'Nutzen Sie eine kurze passende ID ohne Kollision mit einem anderen Block derselben Notiz.'], ['Verweise prüfen', 'Lassen Sie Verweise aktualisieren aktiv, wenn Rückverweise folgen sollen. Führen Sie Vorschau aus und prüfen Sie jede betroffene Datei.'], ['Anwenden und Navigation testen', 'Bestätigen Sie die korrekte Vorschau und öffnen Sie typische Blocklinks und Rückverweise.'],
    ], [['Was passiert ohne Verweisaktualisierung?', 'Der Anker ändert sich, vorhandene Wikilinks können am alten Ziel bleiben und müssen separat repariert werden.'], ['Ändert Vorschau Markdown?', 'Nein. Sie berechnet geplanten Umfang. Erst Anwenden verändert Dateien.']]),
    fa: body('تغییر نام لنگر بلوک', 'گفت‌وگوی نام لنگر از گردش کار ارجاع یا بازآرایی.', 'لنگر موجود و یادداشت صاحب آن.', 'اعمال ممکن است لنگر منبع و ارجاع چند یادداشت را تغییر دهد. برای لنگر پرتکرار ابتدا اجرای آزمایشی را ببینید.', [
      ['یادداشت و لنگر را تأیید کنید', 'مسیر و شناسهٔ موجود را بخوانید تا لنگر مشابه در یادداشت دیگر اشتباه نشود.'], ['لنگر پایدار انتخاب کنید', 'شناسهٔ کوتاه و مناسب بدون برخورد با لنگر دیگر همان مقصد بدهید.'], ['بازنویسی ارجاع را ببینید', 'اگر پیوند ورودی باید همراه نام عوض شود گزینهٔ به‌روزرسانی ارجاع را روشن بگذارید و همهٔ فایل‌های پیش‌نمایش را بررسی کنید.'], ['اعمال و پیمایش را تأیید کنید', 'پس از درستی پیش‌نمایش اعمال و پیوند بلوک و ورودی نمونه را باز کنید.'],
    ], [['اگر به‌روزرسانی ارجاع را خاموش کنم چه می‌شود؟', 'لنگر عوض می‌شود ولی ویکی‌پیوند ممکن است مقصد قدیم را نگه دارد و جدا اصلاح شود.'], ['اجرای آزمایشی Markdown را عوض می‌کند؟', 'خیر. فقط دامنهٔ پیشنهادی را حساب می‌کند؛ عمل جداگانهٔ اعمال تغییر می‌دهد.']]),
  },
  'rename-section': {
    de: body('Abschnitt und Verweise umbenennen', 'Abschnittsumbenennung aus Gliederungs- oder Linkbearbeitung.', 'Eine vorhandene Überschrift in der richtigen Notiz.', 'Anwenden kann Überschrift und tresorweite Verweise ändern und Navigation oder Gliederung beeinflussen.', [
      ['Quellüberschrift bestätigen', 'Prüfen Sie Pfad und Abschnitt. Gleicher Überschrifttext in verschiedenen Notizen ist nicht dasselbe Ziel.'], ['Überschriftänderung wählen', 'Lassen Sie Überschrift aktualisieren aktiv, wenn sichtbarer Text und Rückverweise gemeinsam wechseln sollen. Deaktivieren Sie nur bei verstandenem Verweismodell.'], ['Vorschauumfang prüfen', 'Lesen Sie Dateien und Warnungen, besonders doppelte Überschriften, Aliase, kodierte Fragmente und entfernte Quellordner.'], ['Anwenden und Links testen', 'Öffnen Sie danach die Überschrift aus Gliederung und mindestens einem eingehenden Verweis.'],
    ], [['Kann ich nur Verweise umbenennen?', 'Der Dialog steuert die Quellüberschrift. Prüfen Sie Vorschau, weil reine Verweisänderung überraschende Folgen haben kann.'], ['Warum betrifft das mehrere Dateien?', 'Überschriftlinks können im gesamten Tresor liegen und müssen für korrekte Navigation mitgeändert werden.']]),
    fa: body('تغییر نام بخش و ارجاع‌های آن', 'گفت‌وگوی تغییر بخش از نمای ساختار یا بازآرایی پیوند.', 'عنوان موجود در یادداشت مورد نظر.', 'اعمال می‌تواند متن عنوان و ارجاع سراسر مخزن را عوض کند و بر پیوند، ساختار و پیمایش تولیدی اثر بگذارد.', [
      ['عنوان منبع را تأیید کنید', 'مسیر و برچسب فعلی را ببینید؛ عنوان یکسان در یادداشت دیگر هدف یکسان نیست.'], ['تغییر عنوان را انتخاب کنید', 'اگر عنوان و پیوند ورودی باید با هم عوض شوند گزینهٔ به‌روزرسانی عنوان را روشن بگذارید؛ فقط با درک مدل ارجاع خاموش کنید.'], ['دامنهٔ آزمایشی را ببینید', 'فایل و هشدار، عنوان تکراری، نام مستعار، قطعهٔ کدگذاری‌شده و پیوند از پوشهٔ دیگر را بررسی کنید.'], ['اعمال و پیوند را آزمایش کنید', 'عنوان جدید را از ساختار و دست‌کم یک ارجاع ورودی باز کنید تا حل درست قطعه تأیید شود.'],
    ], [['می‌توانم فقط ارجاع را عوض و عنوان را نگه دارم؟', 'گفت‌وگو تغییر عنوان منبع را انتخاب‌پذیر می‌کند. نتیجهٔ آزمایشی را ببینید چون تغییر فقط ارجاع ممکن است غافلگیرکننده باشد.'], ['چرا تغییر بخش چند فایل را لمس می‌کند؟', 'پیوند عنوان می‌تواند از هر جای مخزن باشد؛ حفظ پیمایش بازنویسی همهٔ ارجاع‌های مطابق را می‌خواهد.']]),
  },
  'rename-tag': {
    de: body('Tag-Hierarchie umbenennen', 'Tag-Umbenennung aus Tagbrowser oder Wissensrefactoring.', 'Ein vorhandenes Tag im aktiven Tresor.', 'Anwenden ändert passende Tags im Notiztext einschließlich untergeordneter Tags. Prüfen Sie breite Elternbereiche vorab.', [
      ['Elterntag bestätigen', 'Lesen Sie Tag und Anzahl abhängiger Notizen und Kinder vor Namenswahl.'], ['Ersatz wählen', 'Nutzen Sie den kanonischen Namen; Großschreibung oder Satzzeichen allein sollten keine fremden Konzepte unterscheiden.'], ['Hierarchie prüfen', 'Prüfen Sie in der Vorschau Kinder wie eltern/kind, die mit dem Elternnamensraum wechseln.'], ['Taxonomie verifizieren', 'Prüfen Sie Tags, Beispielnotizen und Automatisierung oder gespeicherte Ansichten mit dem alten Namen.'],
    ], [['Werden Kinder ebenfalls umbenannt?', 'Ja. Untergeordnete Tags sind enthalten; deshalb ist die Vorschau wichtig.'], ['Verstehen gespeicherte Ansichten den neuen Namen automatisch?', 'Nicht unbedingt. Prüfen Sie Abfragen, Sammlungen, Vorlagen und Regeln mit altem Tagtext.']]),
    fa: body('تغییر نام سلسله‌مراتب برچسب', 'گفت‌وگوی نام برچسب از مرورگر برچسب یا بازآرایی دانش.', 'برچسب موجود در مخزن فعال.', 'اعمال برچسب مطابق را در متن یادداشت، همراه فرزندهای سلسله‌مراتبی بازنویسی می‌کند. دامنهٔ والد گسترده را پیش از تغییر ببینید.', [
      ['والد را تأیید کنید', 'برچسب فعلی و شمار تقریبی یادداشت و فرزند وابسته را پیش از نام جدید بخوانید.'], ['جایگزین را انتخاب کنید', 'نام اصلی بدهید و برای جداسازی مفهوم نامرتبط فقط به بزرگی حروف یا نشانه اتکا نکنید.'], ['اثر سلسله‌مراتبی را ببینید', 'در پیش‌نمایش فرزندی مانند والد/فرزند را ببینید؛ با فضای نام والد تغییر می‌کند.'], ['اعمال و رده‌بندی را تأیید کنید', 'برچسب، یادداشت نمونه، خودکارسازی و نمای ذخیره‌شدهٔ وابسته را پس از اعمال بررسی کنید.'],
    ], [['فرزند هم تغییر نام می‌دهد؟', 'بله. فرزند زیر والد شامل می‌شود؛ به همین دلیل دامنهٔ آزمایشی مهم است.'], ['نمای ذخیره‌شده نام جدید را خودکار می‌فهمد؟', 'الزاماً خیر. پرس‌وجو، مجموعه، الگو و قواعد حاوی متن قدیم را بازبینی کنید.']]),
  },
  'workspace-modes': {
    de: body('Arbeitsbereichsmodi', 'Moduswahl in der Kopfleiste: Schreiben, Wissen, Veröffentlichen, Prüfen oder Automatisierung.', 'Ein Modus betont Werkzeuge für Ihre Aufgabe und konvertiert kein Markdown.', 'Moduswechsel ordnet Bereiche neu. Er veröffentlicht nicht, startet keine Automation und ändert weder Funktionsrechte noch Notizen.', [
      ['Aufgabe wählen', 'Schreiben betont Text, Wissen Beziehungen, Veröffentlichen Export, Prüfen Qualität und Automatisierung MCP sowie Betrieb. Wählen Sie Ihre aktuelle Aufgabe.'], ['Schwerpunkte erkennen', 'Panels und Aktionen können hervortreten, ohne maßgebliche Inhalte oder Rechte zu ändern.'], ['Zuständige Funktion öffnen', 'Öffnen Sie Werkbank, Veröffentlichung, Prüfung oder MCP über Modusaktion oder Befehlspalette. Der Modus selbst führt den Vorgang nicht aus.'], ['Ohne Inhaltsverlust wechseln', 'Wechseln Sie bei neuer Aufgabe. Prüfen Sie Speicherung unabhängig vom Darstellungsmodus.'],
    ], [['Führt Automatisierungsmodus Werkzeuge automatisch aus?', 'Nein. Er macht Werkzeuge erreichbar; MCP-Modi, Rechte, Entwürfe und Änderungen behalten eigene ausdrückliche Steuerung.'], ['Warum änderte sich die Anordnung?', 'Modi sind Aufgabenvorlagen. Markdown bleibt erhalten; dauerhafte eigene Anordnung steuern Layouteinstellungen.']]),
    fa: body('حالت‌های فضای کار', 'انتخاب حالت در نوار بالا: نوشتن، دانش، انتشار، بازبینی یا خودکارسازی.', 'حالت ابزار مناسب کار را برجسته می‌کند و Markdown اصلی را تبدیل نمی‌کند.', 'تغییر حالت، چیدمان و تأکید نما را عوض می‌کند. خودکار منتشر یا اجرا نمی‌کند و قابلیت یا یادداشت را تغییر نمی‌دهد.', [
      ['کار را انتخاب کنید', 'نوشتن برای تألیف، دانش برای روابط، انتشار برای خروجی، بازبینی برای کیفیت و خودکارسازی برای MCP و عملیات است. مطابق قصد فعلی انتخاب کنید.'], ['تأکید چیدمان را ببینید', 'پنل یا عمل برجسته می‌شود بدون تغییر متن اصلی یا دادن مجوز بیشتر.'], ['قابلیت مسئول را باز کنید', 'از عمل مخصوص حالت یا پالت فرمان وارد میزکار، مرکز انتشار، سلامت یا MCP شوید؛ خود حالت عملیات نیست.'], ['بدون از دست دادن محتوا برگردید', 'با تغییر کار، حالت را عوض کنید. ذخیره را جدا تأیید کنید چون نمایش و نگهداری سند مستقل‌اند.'],
    ], [['حالت خودکارسازی خودکار ابزار اجرا می‌کند؟', 'خیر. دسترسی به نما را آسان می‌کند؛ حالت MCP، مجوز، پیش‌نویس و تغییر کنترل صریح خود را دارند.'], ['چرا انتخاب حالت چیدمان را عوض کرد؟', 'حالت الگوی فضای کار برای کار متفاوت است. Markdown همان است؛ برای چیدمان شخصی ماندگار از تنظیم چیدمان استفاده کنید.']]),
  },
  'topbar-customize': {
    de: body('Kopfleistenaktionen anpassen', 'Schieberegler rechts in der Kopfleiste oder deren Kontextmenü.', 'Kein Tresor und kein externer Dienst zur Sichtbarkeitsänderung nötig.', 'Anpassung versteckt oder zeigt Starter. Sie deaktiviert keine Funktion, entzieht keine Rechte und löscht keine Daten.', [
      ['Schreibweg freihalten', 'Zeigen Sie häufige Navigation und Schreibaktionen; verbergen Sie seltene Starter, die Breite beanspruchen.'], ['Versteckt und deaktiviert trennen', 'Abgewählte Aktionen bleiben im zuständigen Panel, in Einstellungen oder Befehlspalette verfügbar, soweit unterstützt.'], ['Enge Fenster testen', 'Prüfen Sie nach Änderungen kleine Fenster oder geteilte Arbeitsbereiche auf verständliche verbleibende Steuerung.'], ['Standards wiederherstellen', 'Nutzen Sie Standardwerte statt zu raten, welche Aktionen ursprünglich dauerhaft sichtbar waren.'],
    ], [['Schaltet Verbergen Git oder MCP aus?', 'Nein. Sichtbarkeit ist Darstellung; Funktion und Laufzeitkonfiguration werden andernorts gesteuert.'], ['Warum ist Support standardmäßig verborgen?', 'Die Kopfleiste priorisiert wiederkehrendes Schreiben und Navigation. Seltene Ziele bleiben erreichbar, ohne dauerhaft Platz zu belegen.']]),
    fa: body('شخصی‌سازی دکمهٔ نوار بالا', 'کنترل لغزندهٔ سمت راست نوار بالا یا منوی زمینه‌ای آن.', 'برای تغییر نمایش، مخزن یا خدمت بیرونی لازم نیست.', 'شخصی‌سازی فقط میان‌بر را پنهان یا برمی‌گرداند؛ قابلیت را خاموش، مجوز را لغو یا داده را حذف نمی‌کند.', [
      ['مسیر نوشتن را باز نگه دارید', 'پیمایش و کار نوشتن پرتکرار را نمایان و دکمهٔ فرعیِ اشغال‌کنندهٔ عرض را پنهان کنید.'], ['پنهان و غیرفعال را جدا کنید', 'عمل بی‌علامت از نوار حذف می‌شود ولی در صورت پشتیبانی از پنل اصلی، تنظیمات یا پالت قابل دسترسی است.'], ['عرض محدود را بیازمایید', 'پس از تغییر، پنجره را کوچک یا فضای تقسیم‌شده را امتحان کنید تا کنترل باقی‌مانده قابل فهم بماند.'], ['در صورت نیاز پیش‌فرض را برگردانید', 'بازیابی پیش‌فرض را بزنید، نه حدس دستی دربارهٔ دکمه‌های اولیه.'],
    ], [['پنهان کردن Git یا MCP خاموشش می‌کند؟', 'خیر. نمایش نوار فقط نماست؛ وضعیت قابلیت و تنظیم اجرا جای دیگر است.'], ['چرا پشتیبانی پیش‌فرض پنهان است؟', 'نمای پیش‌فرض نوشتن و پیمایش پرتکرار را مقدم می‌دارد. مقصد کم‌استفاده بدون اشغال دائمی سرصفحه قابل کشف است.']]),
  },
  'mobile-navigation': {
    de: body('Navigation in mobilen und schmalen Ansichten', 'Untere Navigation bei schmaler oder mobiler Anordnung.', 'Nutzen Sie ein schmales Fenster oder eine unterstützte mobile Größe mit eingeklappter Dreispaltenansicht.', 'Bereichswechsel ändert nur Sichtbarkeit, keine Notiz, keinen Tresor und keine Funktionsfreigabe. Modusaktionen öffnen normale geprüfte Abläufe.', [
      ['Aktiven Bereich wählen', 'Tresor zeigt Dateien, Schreiben den Editor, Linse Inspektorkontext und Befehl die Palette, ohne alle Desktopspalten einzublenden.'], ['Modusaktion nutzen', 'Wissen, Veröffentlichen, Prüfen und Automatisierung können einen kontextbezogenen Starter über der Navigation zeigen. Er öffnet dieselbe Desktopfunktion.'], ['Zum Schreiben zurückkehren', 'Wählen Sie Schreiben nach Navigation oder Prüfung, damit der Editor den verfügbaren Platz nutzt.'], ['Verborgenen Zustand beachten', 'Bereichswechsel beweist weder Schließen, Speichern noch Aufgabenabschluss. Prüfen Sie den zuständigen Status.'],
    ], [['Warum sind Tresor und Inspektor nicht gleichzeitig sichtbar?', 'Schmale Ansichten erhalten mit einem Hauptbereich nutzbare Editorbreite. Breitere Ansichten zeigen mehrere Regionen.'], ['Ändert Befehl den Arbeitsmodus?', 'Nein. Es öffnet Befehlssuche. Modus und mobile Bereichswahl sind unabhängig.']]),
    fa: body('پیمایش موبایل و فضای باریک', 'پیمایش پایین در چیدمان باریک یا موبایل.', 'پنجرهٔ باریک یا اندازهٔ موبایل پشتیبانی‌شده با چیدمان سه‌ستونی جمع‌شده به کار ببرید.', 'تغییر صفحه فقط نمایش را عوض می‌کند، نه یادداشت، مخزن یا قابلیت. دکمهٔ حالت همان گردش کار بررسی‌شده را باز می‌کند.', [
      ['صفحهٔ فعال را انتخاب کنید', 'مخزن فایل، نوشتن ویرایشگر، لنز زمینهٔ بازرس و فرمان پالت را نشان می‌دهد؛ همهٔ ستون دسکتاپ هم‌زمان لازم نیست.'], ['عمل حالت را به کار ببرید', 'دانش، انتشار، بازبینی و خودکارسازی می‌توانند دکمهٔ زمینه‌ای بالای پیمایش داشته باشند؛ همان قابلیت مسئول دسکتاپ را باز می‌کند.'], ['سریع به نوشتن برگردید', 'پس از پیمایش یا بررسی، نوشتن را انتخاب کنید تا ویرایشگر فضای موجود را بگیرد.'], ['وضعیت پنهان را موجود بدانید', 'عوض کردن صفحه یعنی قابلیت بسته، یادداشت ذخیره یا عملیات تمام نشده است؛ وضعیت مسئول را جدا بررسی کنید.'],
    ], [['چرا مخزن و بازرس هم‌زمان دیده نمی‌شوند؟', 'چیدمان باریک یک صفحهٔ اصلی نگه می‌دارد تا ویرایشگر عرض قابل استفاده داشته باشد؛ عرض بیشتر چند ناحیه را برمی‌گرداند.'], ['فرمان حالت فضای کار را عوض می‌کند؟', 'خیر. جست‌وجوی فرمان را باز می‌کند؛ حالت و صفحهٔ موبایل مستقل‌اند.']]),
  },
  typography: {
    de: body('Typografie bereinigen und Text umformen', 'Typografiemenü in der Editorwerkzeugleiste.', 'Eine bearbeitbare Markdown-Notiz mit richtigem Cursor oder Textauswahl.', 'Typografiebefehle ändern Markdown. Prüfen Sie Auswahl und machen Sie unerwartet breite Änderungen sofort rückgängig.', [
      ['Umfang auswählen', 'Markieren Sie Text für lokale Änderungen. Klären Sie ohne Auswahl den Aktionsumfang vor großflächiger Bereinigung.'], ['Eine Umformung wählen', 'Leerraum, Anführungszeichen, Gedankenstrichabstand, Großschreibung und Kursivumwandlung lösen verschiedene Probleme. Stapeln Sie sie nicht ungeprüft.'], ['Strukturierte Syntax prüfen', 'Prüfen Sie Links, Code, Metadaten, Zitate und absichtliche Abstände nach breiter Textnormalisierung.'], ['Rückgängig oder bewusst weiter', 'Vergleichen Sie Quelle und Vorschau. Machen Sie Unerwartetes vor der nächsten Umformung rückgängig.'],
    ], [['Warum änderten sich gewünschte Satzzeichen?', 'Die Befehle wenden feste Regeln an. Wählen Sie kleiner oder machen Sie rückgängig und bearbeiten Sie Ausnahmen manuell.'], ['Soll ich Code und Metadaten bereinigen?', 'Vermeiden Sie breite Prosaumformung auf strukturierter Syntax, sofern der Befehl diese nicht ausdrücklich unterstützt.']]),
    fa: body('پاک‌سازی نگارشی و تبدیل متن', 'منوی نگارش در نوار ابزار ویرایشگر.', 'یادداشت Markdown قابل ویرایش با مکان‌نما یا انتخاب متن درست.', 'فرمان نگارش متن Markdown را تغییر می‌دهد. انتخاب را ببینید و تغییر بیش از قصد را فوراً واگردانی کنید.', [
      ['دامنه را انتخاب کنید', 'برای تغییر محلی متن انتخاب کنید. بدون انتخاب، دامنهٔ عمل ویرایشگر را پیش از پاک‌سازی بزرگ بفهمید.'], ['یک تبدیل انتخاب کنید', 'پاک‌سازی فاصله، نقل‌قول، خط تیره، حالت حروف و تبدیل نقل‌قول یا کج مسئلهٔ متفاوت دارند؛ کورکورانه پشت هم اجرا نکنید.'], ['نحو حساس را ببینید', 'پس از پاک‌سازی گسترده، پیوند، کد، فراداده، استناد و فاصلهٔ عمدی را بررسی کنید؛ عادی‌سازی نثر ممکن است اینجا نامناسب باشد.'], ['واگردانی یا ادامهٔ آگاهانه', 'منبع و پیش‌نمایش را مقایسه کنید. پیش از تبدیل دیگر تغییر غیرمنتظره را واگردانی کنید تا مرز اصلی قابل بازیابی بماند.'],
    ], [['چرا تبدیل نقل‌قول نشانهٔ دلخواه را عوض کرد؟', 'فرمان تبدیل قطعی متن انجام می‌دهد؛ محدوده را کوچک یا واگردانی کنید و استثنا را دستی اصلاح کنید.'], ['روی کد یا فراداده پاک‌سازی کنم؟', 'تبدیل گستردهٔ نثر روی نحو ساختاری را انجام ندهید مگر همان فرمان صریحاً آن را پشتیبانی کند.']]),
  },
  insert: {
    de: body('Markdown-Strukturen einfügen', 'Einfügen in der Editorwerkzeugleiste.', 'Eine bearbeitbare Notiz mit Cursor am gewünschten Ort.', 'Einfügen ändert die aktive Notiz. Blockvorlagen brauchen Leerzeilen; einige Strukturen benötigen spätere Konfiguration oder externe Renderer.', [
      ['Cursor setzen', 'Wählen Sie den genauen Ort vor Menüöffnung. Nutzen Sie für Blöcke möglichst eine leere Zeile, damit sie nicht mit Text verschmelzen.'], ['Struktur wählen', 'Tabellen, Diagramme, Mathematik, Hinweisblöcke und Trennlinien sind Quellvorlagen. Ersetzen Sie Platzhalter und prüfen Sie Syntax.'], ['Felder ausfüllen', 'Ersetzen Sie Bezeichnungen, Knoten, Formeln, Tabellenzellen und Hinweistext sofort.'], ['Quelle und Darstellung prüfen', 'Prüfen Sie Markdown und Vorschau. Korrigieren Sie Blockgrenzen oder Rendereranforderungen statt erneut einzufügen.'],
    ], [['Warum erscheint ein Block als Klartext?', 'Nachbarblöcke oder unvollständige Syntax können die Darstellung verhindern. Prüfen Sie Leerzeilen und Quelle vor erneutem Einfügen.'], ['Führt Diagrammeinfügen externen Code aus?', 'Einfügen schreibt nur Markdown oder Codeblöcke. Darstellung und Ausführung besitzen eigene Funktions- und Sicherheitsgrenzen.']]),
    fa: body('درج ساختار Markdown', 'منوی درج در نوار ابزار ویرایشگر.', 'یادداشت قابل ویرایش با مکان‌نما در محل ساختار جدید.', 'درج یادداشت فعال را تغییر می‌دهد. بلوک خط خالی اطراف می‌خواهد و بعضی ساختارها تنظیم بعدی یا رندر بیرونی می‌خواهند.', [
      ['ابتدا مکان‌نما را بگذارید', 'پیش از باز کردن منو محل دقیق را انتخاب کنید؛ برای بلوک خط خالی بهتر است تا به نثر مجاور نچسبد.'], ['ساختار را انتخاب کنید', 'جدول، نمودار، ریاضی، کادر، خط افقی و موارد دیگر الگوی منبع‌اند؛ تا جای‌نگهدار عوض و نحو تأیید نشود محتوای نهایی نیستند.'], ['فیلد لازم را پر کنید', 'برچسب، گره، فرمول، خانهٔ جدول یا متن کادر را فوراً جایگزین کنید تا نشان الگو نماند.'], ['منبع و رندر را ببینید', 'Markdown درج‌شده و پیش‌نمایش را بررسی کنید؛ مرز بلوک یا پیش‌نیاز رندر را اصلاح کنید، نه درج کپی دوم.'],
    ], [['چرا بلوک درج‌شده متن خام شد؟', 'مکان‌نما ممکن است کنار بلوک دیگر بوده یا نحو ناقص باشد. پیش از درج دوباره خط خالی و منبع دقیق را ببینید.'], ['درج نمودار کد بیرونی اجرا می‌کند؟', 'درج فقط Markdown یا منبع حصاردار می‌نویسد؛ رندر و اجرا مرز قابلیت و ایمنی جدا دارند.']]),
  },
}
