import { body, type GuideTranslations } from './translationTypes.ts'

export const workflowTranslations: GuideTranslations = {
  'export-jobs': {
    de: body('Exportaufträge, Fortschritt und Belege', 'Exportaufträge und Statusbereich.', 'Ein Export- oder Werkzeugauftrag wurde gestartet.', 'Ein laufender Auftrag ist keine fertige Datei. Abbruch und Bereinigung hängen vom Auftragseigner und sichtbaren Ergebnis ab.', [
      ['Auftrag erkennen', 'Prüfen Sie Notiz, Format und Ausgabeziel; verlassen Sie sich nicht nur auf den letzten Status.'], ['Fortschritt beobachten', 'Lesen Sie wartend, laufend, abgeschlossen oder fehlgeschlagen und verfügbare Protokolle. Starten Sie keine Doppelaufträge während langsamer Arbeit.'], ['Bewusst abbrechen', 'Nutzen Sie vorhandene Abbruchaktionen und prüfen Sie den Folgestatus vor einem neuen Versuch.'], ['Belege behalten', 'Prüfen Sie erfolgreiche Ausgabe; bewahren Sie bei Fehlern bereinigte Werkzeugmeldungen und Belege für die Diagnose auf.'],
    ], [['Darf ich den Bereich während eines Auftrags schließen?', 'Die Ansicht zu schließen bricht den Auftrag nicht zwangsläufig ab. Prüfen Sie seinen Zustand ausdrücklich.'], ['Beweist der Prozesscode gute Ausgabe?', 'Nein. Prüfen Sie die erzeugte Datei und gemeldete Verifikationsbelege.']]),
    fa: body('کارهای خروجی، پیشرفت و رسید', 'بخش کارهای خروجی و وضعیت.', 'کار خروجی یا ابزار بیرونی شروع شده باشد.', 'کار در حال اجرا فایل کامل نیست. لغو و پاک‌سازی به مالک کار و نتیجهٔ قابل‌مشاهده وابسته است.', [
      ['تشخیص کار', 'یادداشت، قالب و مقصد را تطبیق دهید؛ فقط به آخرین وضعیت تکیه نکنید.'], ['دیدن پیشرفت', 'صف، اجرا، تکمیل، شکست و گزارش موجود را بخوانید. وقتی کار کند هنوز فعال است، نسخهٔ تکراری شروع نکنید.'], ['لغو آگاهانه', 'از عمل لغو پشتیبانی‌شده استفاده و پیش از تلاش دوباره وضعیت حاصل را بررسی کنید.'], ['حفظ شاهد مفید', 'در موفقیت خروجی را ببینید؛ در شکست خطای پالایش‌شده، اطلاعات ابزار و رسید را برای تشخیص نگه دارید.'],
    ], [['هنگام کار می‌توانم پنل را ببندم؟', 'بستن نما لزوماً کار را لغو نمی‌کند. وضعیت کار را صریح بررسی کنید.'], ['کد خروج پردازه به‌تنهایی کیفیت خروجی را ثابت می‌کند؟', 'خیر. فایل ساخته‌شده و شواهد تأیید گزارش‌شده را بررسی کنید.']]),
  },
  plugins: {
    de: body('Laufzeit-Plugins und Funktionszustand', 'Inspektor > Plugins > Installierte verwalten / Plugins durchsuchen.', 'Ein offener Tresor und ein unterstützter Eintrag des Herstellerkatalogs.', 'Installiert, aktiviert, genehmigt und laufzeitbereit sind getrennte Zustände. Hilfe aktiviert kein Plugin für Sie.', [
      ['Plugin prüfen', 'Lesen Sie Zweck, Herausgeber, Reife, Beiträge und Zugriff. Der Katalog ist beschränkt; ein allgemeiner signierter öffentlicher Marktplatz ist nicht verfügbar.'], ['Berechtigung prüfen', 'Verstehen Sie angeforderte Daten und Aktionen. Zustimmung gehört zur angegebenen Operation, nicht zu einem vagen Vertrauenswert.'], ['Aktivieren und prüfen', 'Aktivieren Sie die gewünschte Funktion und prüfen Sie Befehle und Widgets sowie Speicher- und Laufzeitfehler.'], ['Sicher wiederherstellen', 'Nutzen Sie sicheren Modus oder deaktivieren Sie das Plugin zur Fehlereingrenzung. Aktivieren Sie bewusst erneut; zurückgesetzte Rechte benötigen möglicherweise neue Prüfung.'],
    ], [['Warum läuft ein installiertes Plugin nicht?', 'Es kann deaktiviert sein, Zustimmung fehlen, im sicheren Modus gesperrt sein oder an nativer Laufzeitprüfung scheitern.'], ['Kann ich beliebiges JavaScript von Dritten installieren?', 'Der Katalog beweist das nicht. Die aktuelle Plattform ist eingeschränkt, herstellergeführt und experimentell.']]),
    fa: body('افزونهٔ اجرا و وضعیت قابلیت', 'بررسی > افزونه‌ها > مدیریت نصب‌شده یا مرور افزونه.', 'مخزن باز و ورودی پشتیبانی‌شدهٔ فهرست سازنده.', 'نصب، فعال بودن، تأیید مجوز و آمادگی اجرا وضعیت جدا دارند. راهنما افزونه را برای شما فعال نمی‌کند.', [
      ['بررسی افزونه', 'هدف، ناشر، بلوغ، قابلیت افزوده و دسترسی لازم را بخوانید. فهرست محدود است؛ بازار عمومی امضاشدهٔ جامع در دسترس نیست.'], ['بررسی مجوز', 'داده و عمل درخواستی را بشناسید. تأیید باید به عملیات اعلام‌شده مربوط باشد، نه امتیاز مبهم اعتماد.'], ['فعال‌سازی و تأیید', 'قابلیت موردنظر را فعال و دسترسی فرمان و ابزارک را بررسی کنید. خطای ماندگاری و اجرا را بخوانید.'], ['بازیابی ایمن', 'برای جداسازی مشکل از حالت امن یا غیرفعال کردن افزونه استفاده کنید. دوباره آگاهانه فعال کنید؛ بازنشانی مجوز ممکن است بررسی تازه بخواهد.'],
    ], [['چرا افزونهٔ نصب‌شده اجرا نمی‌شود؟', 'ممکن است غیرفعال، فاقد رضایت، مسدود در حالت امن یا ناموفق در بررسی قابلیت بومی باشد.'], ['JavaScript دلخواه دیگران را می‌توانم نصب کنم؟', 'از رابط فهرست چنین نتیجه نگیرید. سکوی فعلی محدود، وابسته به سازنده و آزمایشی است.']]),
  },
  modules: {
    de: body('Eingebaute Module und Installationsprofile', 'Eingebaute Module über Einstellungen oder Befehle.', 'Prüfen Sie aktiven Tresor und Modulliste.', 'Ein Profil kann mehrere Funktionen zugleich verändern. Prüfen Sie seine Folgen vor dem Anwenden.', [
      ['Aussehen und Funktionen trennen', 'Paletten verändern Darstellung, Module verändern Möglichkeiten. Wählen Sie den passenden Tab.'], ['Modul prüfen', 'Lesen Sie Zugriff und Zweck. Eine fehlende Funktion kann erklären, warum ein Bereich nicht öffnet.'], ['Profil prüfen', 'Prüfen Sie betroffene Module; der Profilname allein garantiert keine Eignung.'], ['Ergebnis kontrollieren', 'Öffnen Sie die erwartete Funktion und lesen Sie Fehler. Stellen Sie frühere Einstellungen wieder her, wenn ein Profil benötigte Funktionen entfernt hat.'],
    ], [['Warum scheitert ein scheinbar aktives Modul?', 'Laufzeit, gespeicherter Tresorzustand und Rechte müssen übereinstimmen. Prüfen Sie den Fehler und nutzen Sie den vorgesehenen Konfigurationsweg.'], ['Löscht Graph deaktivieren Notizen?', 'Nein. Eine Ansichtsfunktion zu deaktivieren verändert ihren Zugang, nicht die Quelldateien.']]),
    fa: body('ماژول داخلی و نمایهٔ نصب', 'ماژول‌های داخلی از تنظیمات یا فرمان‌ها.', 'مخزن فعال و فهرست ماژول را بررسی کنید.', 'نمایه می‌تواند چند قابلیت را همزمان تغییر دهد. پیش از اعمال پیامد را بررسی کنید.', [
      ['جداسازی ظاهر و قابلیت', 'پالت ظاهر را تغییر می‌دهد؛ ماژول کار قابل‌انجام را. زبانهٔ موردنظر را انتخاب کنید.'], ['بررسی ماژول', 'دسترسی و هدف را بخوانید. نبودن قابلیت ممکن است علت باز نشدن پنل باشد.'], ['بررسی نمایه', 'مجموعهٔ ماژول‌های متاثر را بشناسید؛ نام نمایه تضمین مناسب بودن نیست.'], ['کنترل نتیجه', 'قابلیت موردانتظار را باز و خطا را ببینید. اگر نمایهٔ گروهی قابلیت لازم را برداشته، انتخاب قبلی را برگردانید.'],
    ], [['چرا ماژول ظاهراً فعال شکست می‌خورد؟', 'اجرا، وضعیت ذخیره‌شدهٔ مخزن و مجوز باید هماهنگ باشند. خطا را بررسی و مسیر تنظیم پشتیبانی‌شده را دوباره طی کنید.'], ['غیرفعال کردن گراف یادداشت را حذف می‌کند؟', 'خیر. خاموش کردن قابلیت نمایش، دسترسی به قابلیت را تغییر می‌دهد نه یادداشت منبع را.']]),
  },
  permissions: {
    de: body('Plugin-Zustimmung und native Bestätigungen', 'Angeforderten Zugriff und Bestätigungsdialoge prüfen.', 'Kennen Sie Plugin, Aktion, Ressource und aktiven Tresor.', 'Genehmigen Sie nichts nur zum Verbergen eines Fehlers. Rechte sind begrenzt und können einmalig sein; Tourfortschritt ist keine Zustimmung.', [
      ['Aufrufer erkennen', 'Prüfen Sie anfragende Funktion oder Plugin und ob Sie den Ablauf selbst gestartet haben.'], ['Bereich und Folgen prüfen', 'Lesen Sie Datei/Ressource, Aktion und ob Daten gelesen, geschrieben, gesendet, ausgeführt oder gelöscht werden.'], ['Ausdrücklich entscheiden', 'Brechen Sie bei unerwartetem Bereich ab. Zustimmung gilt für die benannte Aktion, nicht jede künftige App-Nutzung.'], ['Abgelaufene Zustimmung erneuern', 'Starten Sie den gewünschten Ablauf für eine neue Freigabe erneut. Umgehen oder erweitern Sie keine fehlgeschlagene Prüfung.'],
    ], [['Warum werde ich erneut gefragt?', 'Eine Freigabe kann verbraucht, abgelaufen, zurückgesetzt oder an eine andere Ressource/einen anderen Tresor gebunden sein.'], ['Kann eine Tour Berechtigungen genehmigen?', 'Nein. Hilfe ist schreibgeschützt und kann keine native Freigabe erzeugen.']]),
    fa: body('رضایت افزونه و تأیید بومی', 'بررسی دسترسی لازم و پنجرهٔ تأیید.', 'افزونه، عملیات، منبع و مخزن فعال را بشناسید.', 'صرفاً برای خاموش کردن خطا تأیید نکنید. مجوز محدود و گاه یک‌بارمصرف است؛ پیشرفت آموزش رضایت نیست.', [
      ['شناخت درخواست‌کننده', 'بررسی کنید کدام قابلیت یا افزونه دسترسی می‌خواهد و آیا خودتان روند را شروع کرده‌اید.'], ['بررسی دامنه و پیامد', 'فایل یا منبع و عملیات را بخوانید و بدانید داده خوانده، نوشته، ارسال، اجرا یا حذف می‌شود.'], ['انتخاب صریح', 'اگر دامنه غیرمنتظره است انصراف دهید. تأیید برای عملیات نام‌برده است، نه هر استفادهٔ آینده از برنامه.'], ['تازه کردن مجوز منقضی', 'روند موردنظر را برای مجوز تازه دوباره شروع کنید. بررسی ناموفق را دور نزنید یا دامنه‌اش را گسترده نکنید.'],
    ], [['چرا دوباره سؤال می‌شود؟', 'مجوز ممکن است مصرف‌شده، منقضی، بازنشانی‌شده یا وابسته به منبع یا مخزن دیگر باشد.'], ['آموزش می‌تواند مجوز بدهد؟', 'خیر. راهنما فقط‌خواندنی است و نمی‌تواند مجوز بومی بسازد.']]),
  },
  export: {
    de: body('Export und Pandoc-Vorabprüfung', 'Exportieren / Veröffentlichen oder Veröffentlichungszentrum öffnen.', 'Eine aktive Notiz, ein passendes Exportprofil und benötigte externe Werkzeuge wie Pandoc.', 'Export schreibt Ausgabedateien und kann freigegebene externe Werkzeuge ausführen. Vorabprüfung ist noch kein Exportergebnis.', [
      ['Format wählen', 'Wählen Sie ein Profil passend zu Publikum und Ziel: Dokument, HTML, PDF oder andere unterstützte Ausgabe.'], ['Vorabprüfung ausführen', 'Lesen Sie fehlende Abhängigkeiten, Zitat-, Ressourcen- und Profilfehler. Beheben Sie Werkzeuganforderungen statt wiederholt Export zu drücken.'], ['Ausgabebereich prüfen', 'Prüfen Sie Zielpfade und Werkzeugberechtigung. Bestätigen Sie nur gewünschte Aktionen und Dateien.'], ['Ergebnis prüfen', 'Öffnen Sie die erzeugte Datei und prüfen Sie Layout, Abbildungen, Zitate, Überschriften und Metadaten vor der Weitergabe.'],
    ], [['Warum scheitert PDF trotz funktionierender Vorschau?', 'PDF kann Pandoc und zusätzliche Werkzeuge benötigen. Vorschau beweist nicht deren Installation oder Konfiguration.'], ['Veröffentlicht Export im Internet?', 'Lokaler Export und Bereitstellung sind unterschiedliche Aktionen. Prüfen Sie Ablauf und Ziel.']]),
    fa: body('خروجی گرفتن و پیش‌بررسی Pandoc', 'خروجی و انتشار یا باز کردن مرکز انتشار.', 'یادداشت فعال، نمایهٔ خروجی مناسب و ابزار بیرونی لازم مانند Pandoc.', 'خروجی فایل می‌نویسد و ممکن است ابزار بیرونی مجاز اجرا کند. پیش‌بررسی خودِ فایل خروجی نیست.', [
      ['انتخاب قالب', 'نمایه را مناسب مخاطب و مقصد انتخاب کنید: سند، HTML، PDF یا خروجی پشتیبانی‌شدهٔ دیگر.'], ['اجرای پیش‌بررسی', 'وابستگی غایب و خطای ارجاع، منبع و نمایه را بخوانید. ابزار لازم را آماده کنید، نه اینکه مکرر خروجی بزنید.'], ['بررسی دامنهٔ خروجی', 'مسیر مقصد و مجوز ابزار بیرونی را ببینید. فقط عملیات و فایل موردنظر را تأیید کنید.'], ['بررسی نتیجه', 'فایل ساخته‌شده را باز و پیش از توزیع چیدمان، شکل، ارجاع، عنوان و فراداده را بررسی کنید.'],
    ], [['چرا PDF شکست می‌خورد اما پیش‌نمایش کار می‌کند؟', 'ساخت PDF ممکن است Pandoc و ابزار اضافی بخواهد. موفقیت پیش‌نمایش نصب یا تنظیم آن‌ها را ثابت نمی‌کند.'], ['خروجی در اینترنت منتشر می‌شود؟', 'خروجی محلی و استقرار عمل متفاوت‌اند. روند و مقصد انتخابی را بررسی کنید.']]),
  },
  publish: {
    de: body('Lokale Starlight-Veröffentlichung', 'Veröffentlichungsablauf in Export & Veröffentlichung.', 'Freigegebene Notizen mit publish: true und ein konfiguriertes lokales Ausgabeziel.', 'Planung ist schreibgeschützt; Anwenden schreibt verwaltete Ausgaben. Das erlaubt weder öffentliche Bereitstellung noch Löschung fremder Dateien.', [
      ['Notizen freigeben', 'Prüfen Sie Veröffentlichungsmetadaten und sensible Inhalte. Eine freigegebene Notiz ist Kandidatin, nicht automatisch öffentlich.'], ['Plan erstellen', 'Prüfen Sie neue, geänderte und verwaiste verwaltete Ausgaben. Quelltresor und Ausgabeordner müssen getrennt sein.'], ['Vor Anwendung prüfen', 'Schließen Sie nicht zu kopierende Inhalte aus. Beheben Sie veraltete Pläne und extern veränderte Ausgaben, statt Warnungen zu erzwingen.'], ['Prüfen und separat bereitstellen', 'Prüfen Sie lokale Seiten, Links und Assets. Internet-Hosting ist ein eigener bewusster Ablauf.'],
    ], [['Warum wurde Anwenden abgelehnt?', 'Quellhashes, Freigabe oder Ausgabezustand können sich seit der Planung verändert haben. Erstellen und prüfen Sie einen neuen Plan.'], ['Gehören alle Ausgabedateien Scriptor?', 'Nein. Veröffentlichung verfolgt verwaltete Ausgaben und bewahrt andere Dateien. Behandeln Sie den Ordner nicht als beliebig löschbar.']]),
    fa: body('انتشار محلی Starlight', 'روند انتشار در خروجی و انتشار.', 'یادداشت واجد شرایط با publish: true و مقصد خروجی محلی تنظیم‌شده.', 'برنامه‌ریزی فقط‌خواندنی است؛ اعمال خروجی مدیریت‌شده را می‌نویسد. این به‌تنهایی مجوز استقرار عمومی یا حذف فایل خارج از مدیریت نیست.', [
      ['انتخاب یادداشت برای انتشار', 'فراداده و حساسیت متن را بررسی کنید. واجد شرایط بودن فقط نامزد شدن است، نه عمومی بودن خودکار.'], ['ساخت برنامه', 'خروجی جدید، تغییرکرده و یتیم مدیریت‌شده را بررسی کنید. مخزن منبع و پوشهٔ خروجی باید جدا باشند.'], ['بررسی پیش از اعمال', 'محتوای نامناسب برای کپی را کنار بگذارید. خطای برنامهٔ قدیمی یا خروجی تغییرکردهٔ بیرونی را حل کنید، نه اینکه تحمیل کنید.'], ['بررسی و استقرار جدا', 'صفحهٔ محلی، پیوند و دارایی را بررسی کنید. میزبانی اینترنت روند آگاهانهٔ جداست.'],
    ], [['چرا اعمال رد شد؟', 'هش منبع، صلاحیت یا وضعیت خروجی شاید از زمان برنامه‌ریزی تغییر کرده باشد. برنامهٔ تازه بسازید و بررسی کنید.'], ['همهٔ فایل‌های پوشهٔ خروجی متعلق به Scriptor هستند؟', 'خیر. انتشار خروجی مدیریت‌شده را دنبال و فایل نامربوط را حفظ می‌کند. پوشه را دورریختنی ندانید.']]),
  },
  'publish-diff': {
    de: body('Veröffentlichungsänderungen prüfen', 'Veröffentlichungsplan, Prüfung und Differenzansicht.', 'Ein aktueller Veröffentlichungsplan.', 'Auswahl und Anwenden sind getrennte Entscheidungen. Eine Differenz zu lesen darf keine stille Lösch- oder Überschreibfreigabe sein.', [
      ['Änderungsarten verstehen', 'Unterscheiden Sie neue Ausgabe, geänderten Inhalt, fehlende Ausgabe und veraltete verwaltete Dateien.'], ['Sinnvolle Unterschiede lesen', 'Prüfen Sie Inhalte, Metadaten, Asset-Ziele und Links. Genehmigen Sie nicht allein aufgrund der Dateianzahl.'], ['Bereich wählen', 'Wählen Sie nur gewünschte Änderungen. Prüfen Sie unerwartete Löschungen oder extern bearbeitete Ausgaben erneut.'], ['Frischen Plan anwenden', 'Erzeugen Sie nach Quellenänderung einen neuen Plan. Prüfen Sie das Ergebnis und bewahren Sie Fehlerkontext bei Teilfehlern.'],
    ], [['Kann ich einen Plan von vor einer Bearbeitung anwenden?', 'Ein veralteter Plan kann aus Integritätsgründen abgelehnt werden. Planen und prüfen Sie neu.'], ['Beweist eine saubere Differenz eine richtige Website?', 'Nein. Sie beschreibt nur Unterschiede zum Vergleichszustand. Prüfen Sie Darstellung und Inhalte.']]),
    fa: body('بررسی تغییرهای انتشار', 'برنامه و بررسی انتشار و نمای تفاوت.', 'برنامهٔ انتشار تازه.', 'انتخاب و اعمال تصمیم‌های جدا هستند. خواندن تفاوت نباید بی‌صدا مجوز حذف یا بازنویسی بدهد.', [
      ['شناخت نوع تغییر', 'خروجی جدید، محتوای تغییرکرده، خروجی غایب و خروجی مدیریت‌شدهٔ قدیمی را جدا کنید.'], ['خواندن تفاوت مهم', 'تغییر متن، فراداده، مقصد دارایی و پیوند را بخوانید؛ صرفاً با تعداد فایل تأیید نکنید.'], ['انتخاب دامنه', 'فقط تغییر موردنظر را انتخاب کنید. حذف غیرمنتظره و خروجی ویرایش‌شدهٔ بیرونی را دوباره ببینید.'], ['اعمال برنامهٔ تازه', 'بعد از ویرایش منبع، برنامه را دوباره بسازید. نتیجهٔ اعمال را تأیید و در شکست جزئی زمینهٔ خطا را نگه دارید.'],
    ], [['برنامهٔ پیش از ویرایش را می‌توانم اعمال کنم؟', 'برنامهٔ قدیمی ممکن است برای حفظ یکپارچگی رد شود. دوباره برنامه‌ریزی و بررسی کنید.'], ['تفاوت پاک، درستی سایت را ثابت می‌کند؟', 'خیر. فقط تفاوت با وضعیت مقایسه را بیان می‌کند. خروجی رندرشده و محتوا را بررسی کنید.']]),
  },
  'publish-readiness': {
    de: body('Veröffentlichungsbereitschaft und Tresorzustand', 'Zustands- und Bereitschaftskarten im Inspektor.', 'Aktueller Index und aktive Notiz für notizbezogene Prüfungen.', 'Bereit/Gut fasst bestimmte Prüfungen zusammen, nicht Wahrheit, Berechtigung oder garantierten Exporterfolg.', [
      ['Bereich lesen', 'Bestimmen Sie, ob die Karte aktive Notiz, Tresor oder Indexcache beschreibt.'], ['Befunde prüfen', 'Öffnen Sie fehlende Zitate, defekte Links oder ungültige Metadaten und korrigieren Sie die tatsächliche Quelle.'], ['Nullen sorgfältig prüfen', 'Null ist nur nach erfolgreichem Lesen aussagekräftig. Laden oder Fehler beweist keine Problemfreiheit.'], ['Export vorab prüfen', 'Führen Sie zielabhängige Prüfungen aus und kontrollieren Sie die erzeugte Datei auch bei positiver Bereitschaft.'],
    ], [['Warum meldet Probleme Fehler trotz guter Bereitschaft?', 'Bereiche und Prüfungen unterscheiden sich. Lesen Sie die zugrunde liegenden Meldungen.'], ['Prüft Exportbereit auch installierte Werkzeuge?', 'Nutzen Sie die Vorabprüfung des gewählten Profils. Die Karte allein genügt nicht.']]),
    fa: body('آمادگی انتشار و ابزارک سلامت مخزن', 'کارت سلامت و آمادگی در نوار بررسی.', 'نمایهٔ تازه و یادداشت فعال برای بررسی مختص یادداشت.', 'آماده یا خوب خلاصهٔ بررسی مشخص است، نه صحت واقعیت، مجوز یا تضمین موفقیت خروجی.', [
      ['خواندن دامنه', 'مشخص کنید ابزارک یادداشت فعلی، مخزن یا حافظهٔ نمایه را توصیف می‌کند.'], ['بررسی یافته', 'ارجاع غایب، پیوند شکسته یا فرادادهٔ نادرست را باز و منبع واقعی را اصلاح کنید.'], ['بررسی دقیق صفر', 'صفر فقط پس از خواندن موفق معنا دارد. بارگذاری یا شکست نبودن مشکل را ثابت نمی‌کند.'], ['پیش‌بررسی خروجی', 'بررسی مختص مقصد را اجرا و حتی با آمادگی مثبت، فایل نتیجه را ببینید.'],
    ], [['چرا با آمادگی خوب، مشکلات خطا دارند؟', 'بخش‌ها دامنه و بررسی متفاوت گزارش می‌کنند. پیام اصلی را بخوانید.'], ['آمادهٔ خروجی ابزار نصب‌شده را هم بررسی می‌کند؟', 'از پیش‌بررسی نمایهٔ انتخابی استفاده کنید؛ کارت آمادگی کافی نیست.']]),
  },
}
