import { body, type GuideTranslations } from './translationTypes.ts'

export const settingsTranslations: GuideTranslations = {
  settings: {
    de: body('Einstellungen und ihr Geltungsbereich', 'Einstellungen in der Kopfleiste.', 'Manche Einstellungen benötigen Tresor oder native Desktop-App.', 'App-Einstellungen, Tresorkonfiguration und externe Konten haben unterschiedliche Speicher- und Berechtigungsgrenzen.', [
      ['Kategorie wählen', 'Wählen Sie Allgemein, Darstellung, Arbeitsbereich, Integrationen, Tastenkürzel oder Erweitert passend zur Aufgabe statt ein langes Formular zu durchsuchen.'], ['Bereich prüfen', 'Unterscheiden Sie Tresoreinstellungen und lokale UI-Präferenzen. Tresorkonfiguration kann andere Nutzer desselben Ordners betreffen.'], ['Bewusst speichern', 'Lesen Sie Speicherhinweise und Speichern/Anwenden. Nicht jedes Feld wird sofort gespeichert.'], ['Wirkung prüfen', 'Testen Sie ein kleines Beispiel in der Funktion. Fehler nach Speichern können eine weitere Integrations- oder Abhängigkeitsreparatur benötigen.'],
    ], [['Warum fehlen Bedienelemente?', 'Sie können einen Tresor, Desktop oder eine aktivierte Funktion benötigen.'], ['Löscht Einstellungen zurücksetzen Dateien?', 'Lesen Sie den genauen Umfang. Hilfe zurücksetzen betrifft nur Hilfe; andere Aktionen haben eigene Regeln.']]),
    fa: body('تنظیمات و دامنهٔ ترجیح', 'تنظیمات در نوار بالا.', 'بعضی تنظیم‌ها مخزن باز یا دسکتاپ بومی می‌خواهند.', 'ترجیح برنامه، تنظیم مخزن و حساب بیرونی مرز نگهداری و مجوز متفاوت دارند.', [
      ['انتخاب دسته', 'متناسب کار، عمومی، ظاهر، فضای کار، یکپارچه‌سازی، میان‌بر یا پیشرفته را انتخاب کنید، نه جست‌وجو در فرم بلند.'], ['بررسی دامنه', 'تنظیم مخزن را از ترجیح محلی رابط جدا کنید. تغییر مخزن می‌تواند روی کاربران همان پوشه اثر بگذارد.'], ['ذخیرهٔ آگاهانه', 'توضیح ماندگاری و عمل ذخیره یا اعمال را ببینید. همهٔ فیلدها فوری ذخیره نمی‌شوند.'], ['تأیید اثر', 'به قابلیت برگردید و نمونهٔ کوچک را آزمایش کنید. خطای پس از ذخیره ممکن است اصلاح جداگانهٔ یکپارچه‌سازی یا وابستگی بخواهد.'],
    ], [['چرا بعضی کنترل‌ها در دسترس نیستند؟', 'ممکن است مخزن، دسکتاپ بومی یا قابلیت فعال بخواهند.'], ['بازنشانی تنظیم فایل را پاک می‌کند؟', 'دامنهٔ دقیق را بخوانید. بازنشانی پیشرفت راهنما فقط راهنماست؛ عمل دیگر قرارداد جدا دارد.']]),
  },
  appearance: {
    de: body('Palette, Tag/Nacht und Anzeige', 'Einstellungen > Darstellung; Tag/Nacht in der Kopfleiste.', 'Kein externer Dienst erforderlich.', 'Darstellung verändert Anzeige, nicht Markdown. Hoher Kontrast unterstützt Zugänglichkeit und ist keine Qualitätsnote.', [
      ['Palette wählen', 'Wählen Sie Farbfamilie unabhängig von Tag/Nacht. Prüfen Sie Text, Bedienelemente und Code, nicht nur Farbfelder.'], ['Hell, Dunkel oder System', 'Tag/Nacht verändert Helligkeit ohne Palettenwechsel. System folgt bei Unterstützung der Betriebssystemeinstellung.'], ['Lesbarkeit anpassen', 'Stellen Sie UI-Schrift und Dichte bequem ein. Prüfen Sie schmale Fenster und Zoom, nicht nur große Bildschirme.'], ['Editorabgleich prüfen', 'Der Editor folgt der App bis zu einer ausdrücklichen Überschreibung. Prüfen Sie bei Abweichung sein eigenes Theme.'],
    ], [['Warum sollte Nachtmodus nicht Dracula oder Nord wählen?', 'Palettenidentität und Hell/Dunkel sind unabhängige Einstellungen.'], ['Warum blieb der Editor dunkel?', 'Eine eigene Editor-Theme-Einstellung kann den Abgleich überschreiben. Stellen Sie Synchronisation wieder her.']]),
    fa: body('پالت، روز و شب و تنظیم نمایش', 'تنظیمات > ظاهر؛ کنترل روز و شب در نوار بالا.', 'خدمت بیرونی لازم نیست.', 'ظاهر ترجیح نمایش را عوض می‌کند، نه Markdown را. تضاد بالا انتخاب دسترسی‌پذیری است، نه امتیاز کیفیت.', [
      ['انتخاب پالت', 'خانوادهٔ رنگ را مستقل از روز و شب انتخاب کنید. متن، کنترل و کد را ببینید، نه فقط نمونهٔ رنگ.'], ['روشن، تیره یا سیستم', 'روز و شب ظاهر را بدون چرخش خانوادهٔ پالت عوض می‌کند. سیستم در صورت پشتیبانی ترجیح سیستم‌عامل را دنبال می‌کند.'], ['تنظیم خوانایی', 'قلم رابط و تراکم را برای راحتی تنظیم کنید. پنجرهٔ باریک و بزرگ‌نمایی را هم بررسی کنید.'], ['بررسی هماهنگی ویرایشگر', 'ویرایشگر تا تعیین ترجیح مستقل از ظاهر برنامه پیروی می‌کند. در ناهماهنگی پوستهٔ خودش را ببینید.'],
    ], [['چرا شب نباید Dracula یا Nord را انتخاب کند؟', 'هویت پالت و روشن یا تیره تنظیم مستقل‌اند.'], ['چرا ویرایشگر تیره ماند؟', 'ممکن است پوستهٔ مستقل ویرایشگر هماهنگی را کنار زده باشد. همگامی را در ترجیح ویرایشگر برگردانید.']]),
  },
  'custom-theme': {
    de: body('Eigene Palette erstellen', 'Palettenkatalog > Eigene Palette erstellen.', 'Eine passende Basispalette und lesbare Vorder-/Hintergrundfarben.', 'Vorschau ist vorübergehend; Speichern behält eine lokale Palette. Löschen darf Notizinhalte nicht verändern.', [
      ['Mit Basis beginnen', 'Nutzen Sie eine stimmige Basis statt unzusammenhängender Einzeländerungen. Wählen Sie einen eindeutigen beschreibenden Namen.'], ['Anpassen und prüfen', 'Prüfen Sie Hintergrund, Flächen, Text, Akzent, Rahmen und Auswahl. Farbfelder zeigen nicht jede betroffene Komponente.'], ['Validierung beachten', 'Beheben Sie ungültige Farben und Kontrastfehler vor Speichern. Prüfen Sie auch Tastaturfokus und deaktivierten Text.'], ['Speichern oder abbrechen', 'Speichern Sie nach Prüfung; Abbrechen stellt die aktive Palette wieder her. Prüfen Sie nach Löschen die gültige Ersatzpalette.'],
    ], [['Warum kann ich Farben nicht speichern?', 'Sie können ungültig sein oder Kontrastprüfungen verletzen. Ändern Sie Werte statt Prüfung zu unterdrücken.'], ['Werden eigene Paletten auf allen Geräten geteilt?', 'Sie liegen lokal, solange Sie Einstellungen nicht ausdrücklich über einen unterstützten Weg übertragen.']]),
    fa: body('ساخت پالت شخصی', 'فهرست پالت > ساخت پالت شخصی.', 'پالت پایهٔ مناسب و رنگ متن و زمینهٔ خوانا.', 'پیش‌نمایش موقت است؛ ذخیره پالت محلی را نگه می‌دارد. حذف پالت نباید متن یادداشت را تغییر دهد.', [
      ['شروع از پایه', 'از پایهٔ هماهنگ استفاده کنید، نه تغییر مستقل رنگ‌های نامربوط. نام متمایز و توصیفی بدهید.'], ['اصلاح و بررسی', 'زمینه، سطح، متن، تأکید، مرز و انتخاب را ببینید. نمونهٔ رنگ همهٔ اجزای متاثر را نشان نمی‌دهد.'], ['رعایت اعتبارسنجی', 'پیش از ذخیره مقدار رنگ نادرست و خطای تضاد را اصلاح کنید. تمرکز صفحه‌کلید و متن غیرفعال را هم بررسی کنید.'], ['ذخیره یا انصراف', 'پس از بررسی ذخیره کنید؛ انصراف پالت فعال را برمی‌گرداند. پس از حذف پالت شخصی، جایگزین معتبر را تأیید کنید.'],
    ], [['چرا این رنگ‌ها ذخیره نمی‌شوند؟', 'ممکن است نامعتبر یا فاقد تضاد لازم باشند. مقدار را اصلاح کنید، نه اعتبارسنجی را خاموش.'], ['پالت شخصی بین همهٔ دستگاه‌ها مشترک است؟', 'محلی ذخیره می‌شود مگر تنظیم مرتبط را صریح از راه پشتیبانی‌شده منتقل کنید.']]),
  },
  shortcuts: {
    de: body('Tastenkürzel und Konflikte', 'Einstellungen > Tastenkürzel.', 'Kennen Sie Control oder Command als Mod-Taste Ihrer Plattform.', 'Tastenkürzel verändern Aufruf, nicht native Befugnis. Zerstörerische Befehle behalten ihre Bestätigungen.', [
      ['Aktion finden', 'Suchen Sie nach Befehl, statt eine Taste einer mehrdeutigen Beschriftung zuzuweisen.'], ['Belegung wählen', 'Nutzen Sie unterstützte Modifikatoren und prüfen Sie Konflikte und ungültige Kombinationen. Überschreiben Sie gängige Bearbeitungstasten nicht versehentlich.'], ['Im Kontext testen', 'Beim Schreiben oder fehlender Funktion können Kürzel unterdrückt sein. Testen Sie den Befehl bei Bedarf außerhalb von Eingabefeldern.'], ['Gezielt zurücksetzen', 'Stellen Sie eine Belegung oder dokumentierte Standards wieder her. Prüfen Sie nach Neuladen.'],
    ], [['Warum verhält F1 sich im Editor anders?', 'F1 öffnet kontextbezogene Hilfe. Hilfe fängt keinen gewöhnlichen Text ab und sendet keine Notizen.'], ['Warum tut ein Kürzel nichts?', 'Prüfen Sie Konflikt, Fokus, Tresor/Notiz, Funktionszustand und übernommene Belegung.']]),
    fa: body('میان‌بر صفحه‌کلید و تداخل', 'تنظیمات > میان‌برها.', 'بدانید کلید Mod روی سکوی شما Control است یا Command.', 'میان‌بر فراخوانی را تغییر می‌دهد، نه اختیار بومی را. فرمان مخرب تأیید خود را نگه می‌دارد.', [
      ['پیدا کردن عمل', 'بر اساس فرمان جست‌وجو کنید، نه تخصیص کلید به عنوان مبهم.'], ['انتخاب کلید', 'نحو کلید کمکی پشتیبانی‌شده را به کار ببرید و تداخل یا ترکیب نامعتبر را ببینید. تصادفی کلید رایج ویرایش را جایگزین نکنید.'], ['آزمایش در زمینه', 'بعضی میان‌برها هنگام تایپ یا نبود قابلیت خاموش‌اند. فرمان واقعی را در صورت نیاز بیرون ورودی آزمایش کنید.'], ['بازنشانی محدود', 'کلید منفرد یا پیش‌فرض مستند را برگردانید و پس از بارگذاری دوباره تأیید کنید.'],
    ], [['چرا F1 در ویرایشگر فرق دارد؟', 'F1 راهنمای زمینه را باز می‌کند. راهنما متن معمولی را نمی‌گیرد یا یادداشت ارسال نمی‌کند.'], ['چرا میان‌بر کاری نمی‌کند؟', 'تداخل، تمرکز، پیش‌نیاز مخزن یا یادداشت، وضعیت قابلیت و اعمال شدن کلید را ببینید.']]),
  },
}
