import { body, type GuideTranslations } from './translationTypes.ts'

export const operationTranslations: GuideTranslations = {
  backups: {
    de: body('Lokale Schnappschüsse und externe Sicherungen', 'Sicherungssteuerung in Einstellungen und erweiterten Abläufen.', 'Öffnen Sie den richtigen Tresor und wählen Sie ein geeignetes Speicherziel.', 'Lokale Schnappschüsse und externe Katastrophensicherungen schützen vor unterschiedlichen Ausfällen. Prüfen Sie Manifeste und testen Sie Wiederherstellung.', [
      ['Ziel wählen', 'Lokale Schnappschüsse helfen innerhalb des Tresors. Ein unabhängiges externes Ziel schützt beim Verlust des Ursprungs.'], ['Umfang prüfen', 'Prüfen Sie enthaltene Dateien, Zielbindung, freien Speicher und kopierte sensible Daten.'], ['Erstellen und prüfen', 'Warten Sie auf Abschluss und lesen Sie Manifest und Ergebnis. Ein aktivierter Zeitplan beweist keinen kürzlich erfolgreichen Lauf.'], ['Wiederherstellung üben', 'Führen Sie einen kontrollierten sicheren Test durch und erhalten Sie das Original. Prüfen Sie Dokumente, Anhänge und benötigte Begleitdateien.'],
    ], [['Reicht ein Schnappschuss neben den Notizen?', 'Nicht bei Geräte- oder Tresorverlust. Nutzen Sie eine unabhängige geprüfte Sicherung.'], ['Warum verlangt automatische Sicherung Zustimmung?', 'Native Sicherungsschreibzugriffe haben eigene Berechtigungsgrenzen. Prüfen Sie den angefragten Umfang.']]),
    fa: body('نسخهٔ محلی و پشتیبان بیرونی', 'کنترل پشتیبان در تنظیمات و گردش کار پیشرفته.', 'مخزن مورد نظر را باز و مقصد ذخیرهٔ مناسب را انتخاب کنید.', 'نسخهٔ محلی و پشتیبان بازیابی فاجعهٔ بیرونی در برابر خرابی‌های متفاوت محافظت می‌کنند. فهرست صحت را بررسی و بازیابی را آزمایش کنید.', [
      ['مقصد را انتخاب کنید', 'نسخهٔ محلی برای بازیابی سریع داخل مخزن است؛ مقصد بیرونی مستقل از دست رفتن محل اصلی را پوشش می‌دهد.'], ['دامنه را بررسی کنید', 'فایل‌های شامل‌شده، وابستگی مقصد، فضای دیسک و کپی شدن اطلاعات حساس را ببینید.'], ['بسازید و تأیید کنید', 'منتظر پایان بمانید و فهرست صحت و نتیجه را بررسی کنید. فعال بودن زمان‌بندی موفقیت پشتیبان اخیر را ثابت نمی‌کند.'], ['بازیابی را تمرین کنید', 'آزمایش کنترل‌شده و امن انجام دهید و اصل را حفظ کنید. متن، پیوست و فایل جانبی لازم را تأیید کنید.'],
    ], [['نسخهٔ کنار یادداشت کافی است؟', 'برای از دست رفتن دستگاه یا مخزن خیر. پشتیبان مستقل و تأییدشده لازم است.'], ['چرا پشتیبان خودکار تأیید می‌خواهد؟', 'نوشتن بومی پشتیبان مرز اختیار صریح دارد؛ دامنهٔ درخواست را بررسی کنید.']]),
  },
  restore: {
    de: body('Geprüfte Sicherung wiederherstellen', 'Wiederherstellen im Sicherungsablauf.', 'Eine geprüfte Sicherung des richtigen Tresors und ein sicherer Plan für aktuelle Inhalte.', 'Wiederherstellung kann aktuelle Dateien ersetzen. Sie bleibt ausdrücklich manuell und gehört nicht zur automatischen Einführung.', [
      ['Aktuelle Arbeit sichern', 'Erstellen Sie vorab eine separate sichere Kopie, besonders bei nützlichen aktuellen Änderungen.'], ['Sicherung überprüfen', 'Prüfen Sie Tresorbindung, Pfade, Hashwerte, Größen und Zeitpunkt. Nutzen Sie keine fremde oder beschädigte Sicherung.'], ['Genaue Wiederherstellung bestätigen', 'Lesen Sie Umfang und Folgen im nativen Dialog. Brechen Sie bei einem falschen Ziel ab.'], ['Ergebnis prüfen', 'Prüfen Sie Dokumente, Anhänge und Ergebnisbericht. Untersuchen Sie Teilfehler oder Journalhinweise vor weiteren Änderungen.'],
    ], [['Kann Hilfe Wiederherstellung an meinen Dateien vorführen?', 'Nein. Touren führen keine Wiederherstellung oder destruktiven Vorgänge aus.'], ['Warum wird die Sicherung abgelehnt?', 'Manifestintegrität, Pfadsicherheit, Tresorbindung oder fehlende Daten können die Prüfung verhindern. Bewahren und untersuchen Sie sie, ohne Prüfungen zu umgehen.']]),
    fa: body('بازیابی پشتیبان تأییدشده', 'بازیابی در گردش کار پشتیبان.', 'پشتیبان تأییدشدهٔ مخزن مورد نظر و برنامهٔ امن برای محتوای فعلی.', 'بازیابی می‌تواند فایل فعلی را جایگزین کند. عمداً دستی است و جزئی از آموزش خودکارِ بار اول نیست.', [
      ['کار فعلی را حفظ کنید', 'پیش از بازیابی نسخهٔ امن جدا بسازید، به‌خصوص اگر فایل فعلی تغییر مفید دارد.'], ['پشتیبان را بررسی کنید', 'وابستگی مخزن، مسیر، هش، اندازه و زمان را ببینید. نسخهٔ آسیب‌دیده یا نامرتبط را به کار نبرید.'], ['بازیابی دقیق را تأیید کنید', 'دامنه و پیامد را در تأیید بومی بخوانید و اگر مقصد اشتباه است لغو کنید.'], ['بازیابی را اعتبارسنجی کنید', 'سند، پیوست و نتیجه را بررسی کنید. پیش از ویرایش معمول، شکست جزئی یا شواهد دفتر عملیات را پیگیری کنید.'],
    ], [['راهنما می‌تواند بازیابی را روی فایل من اجرا کند؟', 'خیر. آموزش عملیات بازیابی یا مخرب اجرا نمی‌کند.'], ['چرا پشتیبان رد می‌شود؟', 'ممکن است صحت فهرست، ایمنی مسیر، وابستگی مخزن یا دادهٔ موجود تأیید نشود. آن را حفظ و عیب‌یابی کنید، نه دور زدن بررسی.']]),
  },
  git: {
    de: body('Git-Status, Unterschiede und ausgewählte Commits', 'Git-Panel über Befehlspalette oder konfigurierte Kopfleiste.', 'Ein unterstütztes Git-Repository und bei Bedarf eine eingerichtete Identität.', 'Commit, Pull, Push, Verwerfen und Konfliktlösung sind verschiedene Änderungen. Prüfen Sie die genaue Dateiauswahl.', [
      ['Repository-Zustand lesen', 'Unterscheiden Sie Laden, fehlendes Repository, sauber, geändert und Fehler. Fehlgeschlagene Statusabfrage bedeutet nicht sauber.'], ['Unterschiede prüfen', 'Lesen Sie Quellenänderungen und unversionierte Pfade. Schließen Sie private oder generierte Inhalte aus, die nicht versioniert werden sollen.'], ['Ausgewählte Änderungen committen', 'Wählen Sie gewünschte Dateien und eine hilfreiche Nachricht. Prüfen Sie den erzeugten Commit nach der Aktion.'], ['Remote-Aktionen getrennt behandeln', 'Push und Pull benötigen eigene Autorisierung, Netzwerk und Konfliktbehandlung. Ein lokaler Commit wird nicht automatisch hochgeladen.'],
    ], [['Werden alle vorgemerkten Änderungen übernommen?', 'Prüfen Sie den Vertrag der expliziten Dateiauswahl und den Commit. Eine allgemeine Beschriftung belegt keinen Umfang.'], ['Ist Git eine vollständige Sicherung?', 'Es schützt nur versionierte und committete Inhalte in verfügbaren Repository-Kopien. Sichern Sie alle wichtigen Daten unabhängig.']]),
    fa: body('وضعیت Git، تفاوت‌ها و ثبت تغییر منتخب', 'پنل Git از پالت فرمان یا نوار بالای تنظیم‌شده.', 'مخزن Git پشتیبانی‌شده و هویت تنظیم‌شده در صورت نیاز.', 'ثبت، دریافت، ارسال، دور ریختن و حل تعارض عملیات متفاوت‌اند. فایل‌های منتخب را دقیق ببینید.', [
      ['وضعیت مخزن را بخوانید', 'بارگذاری، نبود مخزن، پاک، تغییرکرده و خطا را تفکیک کنید. شکست خواندن وضعیت یعنی مخزن پاک نیست که ثابت شده باشد.'], ['تفاوت‌ها را بررسی کنید', 'تغییر منبع و مسیرهای رهگیری‌نشده را ببینید؛ محتوای خصوصی یا تولیدی نامناسب را وارد ثبت نکنید.'], ['تغییر منتخب را ثبت کنید', 'فایل مورد نظر و پیام مفید انتخاب کنید و نتیجهٔ ثبت را بررسی کنید. فشار دکمه موفقیت را ثابت نمی‌کند.'], ['کار بیرونی را جدا انجام دهید', 'ارسال و دریافت مجوز، شبکه و حل تعارض جدا می‌خواهند. ثبت محلی خودکار بارگذاری نمی‌شود.'],
    ], [['همهٔ تغییر آمادهٔ ثبت، ثبت می‌شود؟', 'قرارداد انتخاب صریح فایل و نتیجهٔ ثبت را ببینید؛ از برچسب کلی دکمه دامنه را حدس نزنید.'], ['Git پشتیبان کامل است؟', 'فقط محتوای رهگیری و ثبت‌شده در نسخه‌های موجود مخزن را محافظت می‌کند. دادهٔ مهم را مستقل پشتیبان بگیرید.']]),
  },
  conflicts: {
    de: body('Konflikte und Änderungen auf dem Datenträger', 'Konfliktlösung oder Speicherintegritätswarnung.', 'Verstehen Sie lokale, gespeicherte und vorgeschlagene Fassung.', 'Die Wahl einer Fassung kann eine andere verwerfen. Akzeptieren Sie nicht ungeprüft eine Seite, um Speichern freizugeben.', [
      ['Fassungen zuordnen', 'Lesen Sie, welcher Text lokal, auf dem Datenträger oder aus einer anderen Revision stammt. Prüfen Sie den Notizpfad.'], ['Bewusst vergleichen', 'Erhalten Sie nützliche Änderungen beider Seiten und prüfen Sie jeden Konfliktabschnitt.'], ['Zusammenführung lesen', 'Prüfen Sie das gesamte vorgeschlagene Markdown einschließlich Metadaten und Verweise vor Anwenden.'], ['Speicherung bestätigen', 'Prüfen Sie gespeicherten Text, Git und Index. Bewahren Sie Diagnosebelege bei einem Anwendungsfehler auf.'],
    ], [['Überschreibt Weiterbearbeiten sofort die Datei?', 'Lesen Sie den konkreten Aktionsvertrag. Weiterbearbeiten und Zustimmung zum Überschreiben sind verschiedene Aktionen.'], ['Kann ich später lösen?', 'Sichern Sie ungespeicherten Text und klären Sie, was Schließen oder Abbrechen erhält.']]),
    fa: body('تعارض و بازیابی تغییر روی دیسک', 'حل‌کنندهٔ تعارض یا هشدار صحت ذخیره.', 'پیش از حل، نسخهٔ محلی، دیسک و پیشنهادی را بشناسید.', 'انتخاب نسخه ممکن است دیگری را دور بریزد. فقط برای باز شدن راه ذخیره یک طرف را خودکار نپذیرید.', [
      ['نسخه‌ها را مشخص کنید', 'متن محلی، روی دیسک و نسخهٔ دیگر را شناسایی و مسیر یادداشت را تأیید کنید.'], ['آگاهانه مقایسه کنید', 'تغییر مفید هر دو طرف را حفظ و همهٔ بخش‌های تعارض را بررسی کنید.'], ['نتیجهٔ ادغام را بخوانید', 'کل Markdown پیشنهادی، فراداده و ارجاع را پیش از اعمال بررسی کنید.'], ['نگهداری را تأیید کنید', 'نتیجهٔ ذخیره و وضعیت Git و نمایه را ببینید. اگر اعمال شکست خورد شواهد عیب‌یابی را نگه دارید.'],
    ], [['ادامهٔ ویرایش فوراً نسخهٔ دیسک را بازنویسی می‌کند؟', 'قرارداد همان هشدار را بخوانید؛ ادامهٔ ویرایش و پذیرفتن بازنویسی یک عمل نیستند.'], ['می‌توانم گفت‌وگو را ببندم و بعد حل کنم؟', 'ابتدا متن ذخیره‌نشده را حفظ کنید و بدانید بستن یا لغو چه چیزی را نگه می‌دارد.']]),
  },
  rename: {
    de: body('Notizen umbenennen und Verweise ändern', 'Aktive Notiz umbenennen und Linkumschreibdialoge.', 'Die richtige aktive Notiz und ein gültiger Zielpfad.', 'Umbenennen und Umschreiben können mehrere Dateien betreffen. Prüfen Sie Umfang und erhalten Sie einen Wiederherstellungsweg.', [
      ['Ziel wählen', 'Verwenden Sie einen gültigen tresorrelativen Pfad und prüfen Sie Kollisionen. Ähnliche Namen können verschiedene Notizen bezeichnen.'], ['Verweise vorab prüfen', 'Lesen Sie Vorschau und geplante Ziele. Externe oder unverwaltete Links benötigen gegebenenfalls eigene Prüfung.'], ['Bewusst anwenden', 'Bestätigen Sie nur die geplante Änderung. Bei veralteter Quelle oder Zielfehlern aktualisieren Sie den Plan.'], ['Navigation prüfen', 'Öffnen Sie den neuen Pfad, Rückverweise und ausgehende Links. Prüfen Sie Git und Verlauf auf unerwartete Änderungen.'],
    ], [['Warum nicht im Dateimanager umbenennen?', 'Externe Umbenennung führt möglicherweise keine geprüften Linkänderungen aus. Prüfen Sie danach Verweise.'], ['Kann die Anleitung umbenennen?', 'Nein. Sie erklärt den Ablauf, ohne Pfade oder Dokumente zu verändern.']]),
    fa: body('تغییر نام یادداشت و بازنویسی پیوند', 'تغییر نام یادداشت فعال و گفت‌وگوی بازنویسی پیوند.', 'یادداشت فعال درست و مسیر مقصد معتبر.', 'تغییر نام و بازنویسی می‌تواند چند فایل را تغییر دهد. دامنه را پیش‌نمایش و راه بازیابی را حفظ کنید.', [
      ['مقصد را انتخاب کنید', 'مسیر معتبر نسبی به مخزن بدهید و برخورد نام را ببینید. نام مشابه الزاماً یادداشت یکسان نیست.'], ['پیوندهای متأثر را ببینید', 'نتیجهٔ اجرای آزمایشی و ارجاع جدید را بخوانید. پیوند بیرونی یا مدیریت‌نشده بررسی جدا می‌خواهد.'], ['آگاهانه اعمال کنید', 'فقط تغییر مورد نظر را تأیید کنید. برای منبع قدیمی یا خطای مقصد، طرح را تازه کنید.'], ['پیمایش را تأیید کنید', 'مسیر جدید، پیوند ورودی و خروجی را باز و Git و تاریخچه را برای تغییر غیرمنتظره بررسی کنید.'],
    ], [['چرا در مدیر فایل تغییر نام ندهم؟', 'تغییر بیرونی ممکن است پیوندها را مانند گردش کار بررسی‌شده اصلاح نکند. بعداً ارجاع‌ها را ببینید.'], ['راهنما می‌تواند تغییر نام دهد؟', 'خیر. فقط گردش کار را توضیح می‌دهد و مسیر یا سند را تغییر نمی‌دهد.']]),
  },
  import: {
    de: body('Obsidian-Tresor importieren', 'Obsidian-Tresor importieren in Befehlspalette oder Tresormenü.', 'Lesbare Quelle, sicheres Ziel und genügend Speicher.', 'Import schreibt lokale Dateien. Sichern Sie Quelle und Ziel und prüfen Sie Kollisionen und Konvertierungen.', [
      ['Quelle wählen', 'Bestätigen und erhalten Sie den ursprünglichen Ordner. Wählen Sie keinen unbeabsichtigten übergeordneten Ordner.'], ['Optionen lesen', 'Prüfen Sie Ziel, Anhänge, unterstützte Konvertierung und Kollisionen. App-spezifisches Verhalten wird möglicherweise nicht übertragen.'], ['Importergebnis lesen', 'Warten Sie auf den begrenzten Vorgang und prüfen Sie Anzahl und Fehler; nicht jede Quelldatei muss importiert worden sein.'], ['Beispiele prüfen', 'Öffnen Sie typische Notizen, Links, Anhänge, Metadaten und Diagramme vor Verlass auf die Migration.'],
    ], [['Funktioniert jedes Obsidian-Plugin?', 'Nein. Portables Markdown garantiert keine Kompatibilität mit beliebiger Plugin-Syntax oder Funktion.'], ['Darf ich das Original sofort löschen?', 'Erhalten Sie es, bis Inhalt und unabhängige Sicherung geprüft sind.']]),
    fa: body('ورود مخزن Obsidian', 'فرمان ورود مخزن Obsidian از پالت فرمان یا منوی مخزن.', 'منبع خواندنی، مقصد امن و فضای کافی.', 'ورود فایل محلی می‌نویسد. ابتدا منبع و مقصد را پشتیبان بگیرید و برخورد نام و تبدیل را بررسی کنید.', [
      ['منبع را انتخاب کنید', 'پوشهٔ اصلی را تأیید و حفظ کنید. پوشهٔ والد نامقصود را انتخاب نکنید.'], ['گزینه‌ها را ببینید', 'مقصد، پیوست، تبدیل پشتیبانی‌شده و برخورد را بررسی کنید. رفتار خاص برنامه ممکن است منتقل نشود.'], ['اجرا و نتیجه را بخوانید', 'منتظر عملیات محدود بمانید و شمار و خطا را ببینید؛ ورود همهٔ فایل‌ها را فرض نکنید.'], ['نمونه‌ها را تأیید کنید', 'یادداشت، پیوند، پیوست، فراداده و نمودار نمونه را پیش از اتکا به مخزن منتقل‌شده باز کنید.'],
    ], [['همهٔ افزونه‌های Obsidian کار می‌کنند؟', 'خیر. قابل حمل بودن Markdown سازگاری با هر نحو یا رفتار افزونه را تضمین نمی‌کند.'], ['می‌توانم اصل را فوراً حذف کنم؟', 'تا تأیید محتوا و پشتیبان مستقل، اصل را نگه دارید.']]),
  },
  advanced: {
    de: body('Erweiterte Einstellungen und Betriebswerkzeuge', 'Einstellungen > Erweitert und Betriebsbefehle.', 'Klären Sie Subsystem, Reifegrad und Abhängigkeiten.', 'Erweiterte Optionen behalten ausdrückliche Grenzen für Prozesse, Netzwerk, Schlüsselbund, Sicherung und native Schreibzugriffe.', [
      ['Verantwortlichen Bereich wählen', 'Ändern Sie die Einstellung des fehlerhaften Subsystems statt unbeteiligte Experimente einzuschalten.'], ['Abhängigkeiten prüfen', 'Prüfen Sie Programme, Endpunkte, Ressourcen und Grenzen. Fehlende Werkzeuge sollten verständliche Fehler melden.'], ['Eine Variable ändern', 'Notieren Sie den ursprünglichen Wert und testen Sie mit sicheren Daten, damit Regressionen zugeordnet werden können.'], ['Bekannten Zustand herstellen', 'Deaktivieren Sie unnötige Experimente und prüfen Sie Bearbeiten und Suche. Bewahren Sie Protokolle ohne Weitergabe von Geheimnissen auf.'],
    ], [['Sind Verschlüsselung, Mobil und öffentlicher Marktplatz vollständig verfügbar?', 'Lesen Sie das Reifegradverzeichnis. Entwürfe und inkubierende Module garantieren keinen Produktablauf.'], ['Erlaubt eine Werkzeugeinstellung alle späteren Zugriffe?', 'Nein. Native Vorgänge prüfen Umfang und Berechtigung unabhängig.']]),
    fa: body('تنظیمات پیشرفته و ابزار عملیاتی', 'تنظیمات > پیشرفته و فرمان‌های عملیاتی.', 'زیرسامانه، بلوغ قابلیت و وابستگی لازم را بشناسید.', 'پیشرفته به معنی دسترسی نامحدود نیست. فرایند، شبکه، کلیددان، پشتیبان و نوشتن بومی مرز صریح دارند.', [
      ['مسئول را مشخص کنید', 'تنظیم زیرسامانهٔ خراب را انتخاب کنید و قابلیت آزمایشی نامرتبط را روشن نکنید.'], ['وابستگی را ببینید', 'برنامهٔ اجرایی، نشانی، منابع و محدودیت را بررسی کنید. نبود ابزار باید خطای قابل اقدام بدهد.'], ['یک متغیر را تغییر دهید', 'مقدار قبلی را ثبت و با دادهٔ امن آزمایش کنید تا علت پس‌رفت مشخص شود.'], ['به وضعیت شناخته‌شده برگردید', 'آزمایش غیرلازم را خاموش و کار ویرایش و جست‌وجو را تأیید کنید. گزارش را بدون افشای راز حفظ کنید.'],
    ], [['رمزنگاری، موبایل و بازار عمومی کاملاً عرضه شده‌اند؟', 'دفتر بلوغ قابلیت را ببینید. طرح یا ماژول در حال رشد ضمانت گردش کار موجود نیست.'], ['تنظیم ابزار همهٔ دسترسی‌های بعدی را می‌دهد؟', 'خیر. عملیات بومی دامنه و مجوز را مستقل بررسی می‌کند.']]),
  },
  help: {
    de: body('Hilfe, Fragen und wiederholbare Touren nutzen', 'F1 für kontextbezogene Hilfe oder globaler Hilfeeintrag in Kopfleiste und Befehlspalette.', 'Die Hilfe funktioniert offline und ohne Tresor.', 'Dies ist redaktionelle Produkthilfe. Sie bedient keine Funktionen automatisch und sendet Suchtext an keinen Dienst.', [
      ['Im Kontext öffnen', 'Drücken Sie F1 innerhalb einer Funktion; Umschalt+F1 startet oder setzt deren Tour fort. Der globale Eintrag öffnet die durchsuchbare Übersicht.'], ['Mit Suche fragen', 'Geben Sie Funktionsnamen oder Fragen ein. Gebündelte Antworten erscheinen lokal; weder Notiztext, Zugangsdaten noch Anfrage verlassen die App.'], ['Einladungen verstehen', 'Nach der Einführung können komplexe oder experimentelle Bereiche einmalig unverbindlich einladen. Schließen, lesen oder Tour starten sind Ihre Wahl; einfache und Wiederherstellungsabläufe bleiben manuell.'], ['Wiederholen oder zurücksetzen', 'Touren bleiben nach Abschluss und Schließen verfügbar. Steuerung zeigen markiert nur ein vorhandenes Ziel. Fortschritt zurücksetzen ändert allein Hilfestatus, keine Notizen, Einstellungen, Rechte oder Konten.'],
    ], [['In welchen Sprachen sind die ausführlichen Anleitungen verfügbar?', 'Alle gebündelten Anleitungen, Schritte und Antworten sind auf Englisch, Deutsch und Persisch verfügbar und folgen der Spracheinstellung.'], ['Was tun bei fehlender Steuerung?', 'Die Funktion kann geschlossen, deaktiviert, nicht verfügbar oder anders angeordnet sein. Lesen Sie Einstieg und Voraussetzungen; Hilfe aktiviert keine riskanten Abläufe automatisch.']]),
    fa: body('استفاده از راهنما، پرسش‌ها و آموزش تکرارپذیر', 'F1 برای راهنمای زمینه‌ای یا ورودی سراسری راهنما در نوار بالا و پالت فرمان.', 'راهنما آفلاین و بدون مخزن کار می‌کند.', 'این راهنمای تدوین‌شدهٔ محصول است، نه گفت‌وگوی هوش مصنوعی یا مجری خودکار. متن جست‌وجو به خدمتی فرستاده نمی‌شود.', [
      ['در زمینه باز کنید', 'در قابلیت مورد نظر F1 را بزنید. Shift+F1 آموزش آن را شروع یا ادامه می‌دهد. ورودی سراسری مرورگر قابل جست‌وجوی راهنما را باز می‌کند.'], ['با جست‌وجو بپرسید', 'نام قابلیت یا پرسش طبیعی بنویسید. پاسخ همراه برنامه محلی نمایش داده می‌شود؛ متن یادداشت، اطلاعات ورود و پرسش از برنامه خارج نمی‌شود.'], ['دعوت را بشناسید', 'پس از شروع اولیه، بعضی بخش‌های پیچیده یا آزمایشی دعوت غیرمسدودکنندهٔ بار اول دارند. می‌توانید ببندید، بخوانید یا آموزش را صریحاً شروع کنید. کار ساده و بازیابی فقط دستی است.'], ['تکرار یا بازنشانی کنید', 'آموزش پس از بستن و پایان قابل تکرار است. نمایش کنترل فقط هدف موجود را نشان می‌دهد. بازنشانی پیشرفت فقط وضعیت راهنما را عوض می‌کند، نه یادداشت، تنظیم، مجوز یا حساب.'],
    ], [['راهنمای تفصیلی چه زبان‌هایی دارد؟', 'همهٔ راهنماها، گام‌ها و پاسخ‌های همراه برنامه به انگلیسی، آلمانی و فارسی موجودند و از زبان انتخابی پیروی می‌کنند.'], ['اگر کنترل نبود چه کنم؟', 'قابلیت ممکن است بسته، غیرفعال، ناموجود یا متفاوت چیده شده باشد. مسیر و پیش‌نیاز را بخوانید؛ راهنما گردش کار خطرناک را خودکار فعال نمی‌کند.']]),
  },
  cheatsheet: {
    de: body('Markdown- und Abfragereferenz', 'Markdown-Kurzreferenz über Werkzeuge oder Befehlspalette.', 'Kein Anbieter nötig; Abfragebeispiele benötigen den passenden indizierten Tresor.', 'Beispiele sind Referenztext. Nur eine ausdrücklich gewählte Einfügeaktion verändert die aktive Notiz.', [
      ['Syntaxfamilie wählen', 'Unterscheiden Sie Markdown, Wikilinks, Zitate, unterstützte Abfragen und Vorlagen. Diese Sprachen sind nicht austauschbar.'], ['Beispiel lesen', 'Prüfen Sie Trennzeichen und Leerraum. Codeblöcke und andere Blöcke benötigen korrekte Grenzen.'], ['An Notiz anpassen', 'Ersetzen Sie Platzhalter und Ziele. Beispiel-Zitierschlüssel oder Pfade existieren möglicherweise nicht im Tresor.'], ['Quelle und Ergebnis prüfen', 'Lesen Sie Markdown und Vorschau oder Abfrageausgabe. Beheben Sie Fehler vor breiter Wiederverwendung.'],
    ], [['Ist die Kurzreferenz eine interaktive Einführung?', 'Sie ist eine schnelle Syntaxreferenz. Touren erklären Ablauf und Voraussetzungen.'], ['Führen Beispiele Befehle aus?', 'Lesen und Kopieren autorisieren keine externen Vorgänge. Ausführung hat einen eigenen ausdrücklichen Ablauf.']]),
    fa: body('برگهٔ مرجع Markdown و پرس‌وجو', 'مرجع Markdown از ابزارها یا پالت فرمان.', 'ارائه‌دهنده لازم نیست؛ مثال پرس‌وجو مخزن نمایه‌شدهٔ مناسب می‌خواهد.', 'مثال متن مرجع است. درج فقط با عمل صریح، یادداشت فعال را تغییر می‌دهد.', [
      ['خانوادهٔ نحو را انتخاب کنید', 'قالب Markdown، پیوند ویکی، استناد، پرس‌وجوی پشتیبانی‌شده و الگوی درج زبان‌های قابل جایگزینی نیستند.'], ['مثال را بخوانید', 'جداکننده و فاصلهٔ لازم را بررسی کنید. حصار کد و بلوک مرز درست می‌خواهند.'], ['با یادداشت تطبیق دهید', 'جای‌نگهدار و مقصد را آگاهانه عوض کنید. کلید استناد یا مسیر نمونه ممکن است در مخزن نباشد.'], ['منبع و خروجی را ببینید', 'Markdown و پیش‌نمایش یا نتیجهٔ پرس‌وجو را بررسی و پیش از استفادهٔ گسترده خطا را رفع کنید.'],
    ], [['این برگه آموزش تعاملی است؟', 'مرجع سریع نحو است. برای گردش کار و پیش‌نیاز از آموزش راهنما استفاده کنید.'], ['مثال فرمان اجرا می‌کند؟', 'خواندن یا کپی مثال مجوز عملیات بیرونی نیست. اجرا گردش کار صریح جدا دارد.']]),
  },
  latex: {
    de: body('LaTeX kompilieren und Ausgabe prüfen', 'LaTeX-Kompilierung in Export und Veröffentlichung.', 'Unterstützte Quelle, konfigurierte Engine, installierte Werkzeuge und genehmigte Prozessrichtlinie.', 'Kompilierung startet einen externen Prozess und schreibt Ausgabe. Prüfen Sie den Umfang vor Ausführung unvertrauenswürdiger Quellen.', [
      ['Quelle und Engine prüfen', 'Prüfen Sie aktive Quelle und Compiler. Markdown-Vorschau ersetzt keine LaTeX-Werkzeugkette.'], ['Ausgabeeinstellungen lesen', 'Wählen Sie Ziel und Prozessoptionen und vermeiden Sie Überschreiben fremder Arbeit.'], ['Ausführen und beobachten', 'Lesen Sie native Zustimmung, Fortschritt und Compilerdiagnose. Warten Sie oder nutzen Sie unterstützten Abbruch vor einer weiteren Aufgabe.'], ['Dokument prüfen', 'Prüfen Sie Verweise, Bilder, Schriften, Seitenumbrüche und fehlende Inhalte vor Weitergabe.'],
    ], [['Warum funktioniert Vorschau, aber nicht Kompilierung?', 'Die Engines sind verschieden. Fehlender Compiler, nicht unterstützte Optionen oder Quellenfehler können nur die Kompilierung betreffen.'], ['Belegt Rückgabecode null ein korrektes Dokument?', 'Nein. Prüfen Sie Datei und Warnungen.']]),
    fa: body('کامپایل LaTeX و بررسی خروجی', 'بخش کامپایل LaTeX در خروجی و انتشار.', 'منبع پشتیبانی‌شده، موتور تنظیم‌شده، ابزار نصب‌شده و سیاست فرایند تأییدشده.', 'کامپایل فرایند بیرونی اجرا و خروجی می‌نویسد. پیش از کامپایل منبع نامطمئن دامنه را بررسی کنید.', [
      ['منبع و موتور را تأیید کنید', 'منبع فعال و ابزار کامپایل را ببینید. پیش‌نمایش Markdown جای زنجیرهٔ ابزار LaTeX نیست.'], ['تنظیم خروجی را بخوانید', 'مقصد و گزینهٔ فرایند را انتخاب کنید و کار نامرتبط را بازنویسی نکنید.'], ['اجرا و مشاهده کنید', 'تأیید بومی، پیشرفت و عیب کامپایل را بخوانید. پیش از کار دوم منتظر بمانید یا لغو پشتیبانی‌شده را انجام دهید.'], ['فایل نتیجه را ببینید', 'پیش از اشتراک، ارجاع، شکل، قلم، شکست صفحه و محتوای جاافتاده را بررسی کنید.'],
    ], [['چرا پیش‌نمایش کار می‌کند ولی کامپایل شکست می‌خورد؟', 'موتور متفاوت است. نبود کامپایلر، گزینهٔ نامعتبر یا خطای منبع ممکن است فقط کامپایل را متأثر کند.'], ['کد خروج صفر درستی سند را ثابت می‌کند؟', 'خیر. فایل تولیدی و هشدار را بررسی کنید.']]),
  },
  daemon: {
    de: body('Daemon-Verbindung und Betriebssteuerung', 'Erweiterte Einstellungen und Daemon-Steuerung.', 'Native Desktop- oder Betriebsunterstützung und kompatibler Daemon.', 'Dienststart oder Betriebsänderung ist eine eigene Aktion. Endpunkte und Token können sensible Daten enthalten.', [
      ['Verbindung lesen', 'Prüfen Sie Version, Endpunktstatus und Fehler. Ein fehlender Dienst unterscheidet sich von Berechtigungs- oder Protokollfehlern.'], ['Vor Änderung aktualisieren', 'Nutzen Sie eine lesende Statusaktualisierung, um mögliche Wiederherstellung zu erkennen.'], ['Bewusst starten', 'Nutzen Sie den unterstützten Start und prüfen Sie die Verbindung. Wiederholte Dienstkopien beheben keinen Fehler.'], ['Sicher berichten', 'Erhalten Sie begrenzte Diagnose und Version. Entfernen Sie Token und private Pfade vor Weitergabe.'],
    ], [['Belegt die geöffnete Desktop-App eine Daemon-Verbindung?', 'Nein. Prüfen Sie den Betriebsstatus des verwendeten Zugriffswegs.'], ['Soll ich Zugangsdaten in die Hilfe eingeben?', 'Nein. Hilfesuche durchsucht lokale Dokumentation und sammelt keine Diagnose-Zugangsdaten.']]),
    fa: body('اتصال سرویس پس‌زمینه و کنترل عملیات', 'تنظیمات پیشرفته و کنترل سرویس پس‌زمینه.', 'پشتیبانی بومی دسکتاپ یا عملیاتی و سرویس سازگار.', 'شروع یا تغییر سرویس عملیاتی با باز کردن پنل فرق دارد. نشانی و توکن ممکن است حساس باشند.', [
      ['وضعیت اتصال را ببینید', 'نسخه، وضعیت نشانی و خطا را بخوانید. نبود سرویس با خطای مجوز یا پروتکل متفاوت است.'], ['پیش از تغییر تازه کنید', 'با تازه‌سازی فقط‌خواندنی وضعیت، بازگشت احتمالی سرویس را مشخص کنید.'], ['آگاهانه شروع کنید', 'کنترل شروع پشتیبانی‌شده را به کار ببرید و اتصال نتیجه را تأیید کنید. برای پنهان کردن خطا نمونه‌های مکرر نسازید.'], ['امن گزارش کنید', 'عیب‌یابی محدود و نسخه را حفظ کنید؛ توکن و مسیر خصوصی را پیش از اشتراک حذف کنید.'],
    ], [['باز بودن دسکتاپ یعنی سرویس وصل است؟', 'خیر. وضعیت عملیاتی مسیر مورد استفاده را بررسی کنید.'], ['اطلاعات ورود نشانی را در راهنما بنویسم؟', 'خیر. جست‌وجوی راهنما فقط مستند محلی را می‌گردد و جمع‌کنندهٔ اطلاعات ورود نیست.']]),
  },
  quality: {
    de: body('Leistungs- und Freigabequalität prüfen', 'Qualitäts- und Messbereiche in erweiterten Einstellungen.', 'Klären Sie Umgebung und Umfang jeder Messung.', 'Zahlen beschreiben einen bestimmten Lauf und zertifizieren nicht jede Funktion, Zugänglichkeit oder Sicherheit.', [
      ['Messumfang lesen', 'Unterscheiden Sie Start, erste Bearbeitung, Export, Speicher und Ablaufzeiten. Daten und Umgebung beeinflussen Ergebnisse.'], ['Gleiches vergleichen', 'Nutzen Sie dieselbe Last und Konfiguration zur Regressionsbewertung.'], ['Fehler erhalten', 'Notieren Sie ursprünglichen Fehlerpfad und Diagnose. Ein erfolgreicher fremder Benchmark löst ihn nicht.'], ['Nur Messungen zurücksetzen', 'Lesen Sie den Umfang. Das Leeren von Ablauf- und Messdaten repariert weder Quelle noch Integration.'],
    ], [['Belegt Geschwindigkeit Nutzbarkeit?', 'Nein. Bedienung, Korrektheit, Zugänglichkeit und Fehlerbehebung benötigen eigene Belege.'], ['Warum ändert sich ein Wert nach Neustart?', 'Caches, Last, Gerätezustand und Messlebenszyklus können abweichen.']]),
    fa: body('شواهد عملکرد و کیفیت انتشار', 'بخش کیفیت انتشار و اندازه‌گیری در تنظیمات پیشرفته.', 'محیط و دامنهٔ هر اندازه‌گیری را بشناسید.', 'عدد یک اجرای مشخص را توصیف می‌کند و گواه درستی، دسترسی‌پذیری یا ایمنی همهٔ قابلیت‌ها نیست.', [
      ['دامنهٔ عدد را بخوانید', 'شروع، اولین ویرایش، خروجی، حافظه و زمان گردش کار را جدا کنید. داده و محیط بر نتیجه اثر دارند.'], ['موارد همسان را مقایسه کنید', 'برای بررسی پس‌رفت بار و تنظیم یکسان به کار ببرید.'], ['شکست را حفظ کنید', 'مسیر شکست اصلی و عیب را ثبت کنید. موفقیت آزمون نامرتبط مشکل را حل نمی‌کند.'], ['فقط اندازه‌گیری را بازنشانی کنید', 'دامنه را بخوانید؛ پاک کردن سابقهٔ سفر یا اندازه‌گیری منبع یا یکپارچه‌سازی را اصلاح نمی‌کند.'],
    ], [['سرعت، کاربردپذیری را ثابت می‌کند؟', 'خیر. تعامل، درستی، دسترسی‌پذیری و بازیابی خطا شواهد مستقل می‌خواهند.'], ['چرا عدد پس از شروع دوباره عوض شد؟', 'حافظهٔ سرد، بار، وضعیت دستگاه و چرخهٔ اندازه‌گیری ممکن است متفاوت باشند.']]),
  },
  support: {
    de: body('Support, Rückmeldung und verantwortliches Melden', 'Scriptor unterstützen über Befehlspalette oder optionale Kopfleiste.', 'Ein reproduzierbares Problem oder eine klare Frage zum aktuellen Verhalten.', 'Supportlinks können Browser oder Mail öffnen. Teilen Sie keine Token, Passwörter oder unbereinigten privaten Tresore.', [
      ['Lokale Hilfe prüfen', 'Lesen Sie Anleitung und Antworten zu Voraussetzungen und Grenzen. Hilfe ist offline verfügbar.'], ['Ergebnis beschreiben', 'Notieren Sie Schritte, Erwartung, tatsächliches Verhalten, Version und Umgebung. Trennen Sie Funktionswunsch und Regression.'], ['Beispiel verkleinern', 'Nutzen Sie bereinigte Bilder und entbehrliche Beispielnotizen. Entfernen Sie unbeteiligte persönliche Daten.'], ['Ziel wählen', 'Prüfen Sie Berichts- oder Mailziel und senden Sie erst bewusst. Lesen der Hilfe reicht keinen Bericht ein.'],
    ], [['Kontaktiert Hilfe den Support automatisch?', 'Nein. Sie ist eine Offline-Wissensbasis. Externer Kontakt erfordert Ihre ausdrückliche Aktion.'], ['Soll ich experimentelle Grenzen melden?', 'Wenn hilfreich, mit Reifegrad und tatsächlich beobachtetem Verhalten.']]),
    fa: body('پشتیبانی، بازخورد و گزارش مسئولانه', 'پشتیبانی Scriptor از پالت یا دکمهٔ اختیاری نوار بالا.', 'مشکل قابل تکرار یا پرسش روشن دربارهٔ رفتار فعلی.', 'پیوند پشتیبانی ممکن است مرورگر یا برنامهٔ نامه باز کند. توکن، رمز و مخزن خصوصیِ پاک‌سازی‌نشده نفرستید.', [
      ['ابتدا راهنمای محلی را بخوانید', 'پیش‌نیاز و محدودیت شناخته‌شده را در راهنما و پاسخ‌ها بجویید. راهنما آفلاین کار می‌کند.'], ['نتیجه را شرح دهید', 'گام، انتظار، رفتار واقعی، نسخه و محیط را بنویسید و درخواست قابلیت را از پس‌رفت جدا کنید.'], ['نمونه را کوچک کنید', 'تصویر پاک‌سازی‌شده و یادداشت آزمایشی دورریختنی استفاده و دادهٔ شخصی نامرتبط را حذف کنید.'], ['مقصد را انتخاب کنید', 'مقصد مسئله یا نامه را بررسی و هنگام آمادگی ارسال کنید. خواندن راهنما گزارش ارسال نمی‌کند.'],
    ], [['راهنما خودکار به پشتیبانی پیام می‌دهد؟', 'خیر. پایگاه دانش آفلاین است و ارتباط بیرونی عمل صریح شما را می‌خواهد.'], ['محدودیت آزمایشی را گزارش کنم؟', 'اگر مفید است بله؛ بلوغ قابلیت و رفتار واقعاً دیده‌شده را مشخص کنید.']]),
  },
}
